### ISSUE TITLE
[Bug]: TypeError: this.getOptions is not a function + SPFx

### ISSUE THREAD

**Issue by vchauhan1994** [babel/babel-loader#1004]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

I am using Docx npm module in SharePoint Framework(React)

import { Document, Packer, Paragraph, TextRun } from "docx";

For that I want to use babel-loader.

### Configuration

{
        test: /\.(?:js|mjs|cjs)$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: [
              ['@babel/preset-env', { targets: "defaults" }]
            ]
          }
        }
      }

### Current and expected behavior

There should be no error while after using gulp bundle command but currently facing below error:

Error - [webpack] 'dist':
./lib/webparts/docxWebpart/DocxWebpartWebPart.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: this.getOptions is not a function
    at Object.loader (D:/Practice/DocxCreatorPOC/DocxReactPOC/node_modules/babel-loader/lib/index.js:44:28)
    at Object.<anonymous> (D:/Practice/DocxCreatorPOC/DocxReactPOC/node_modules/babel-loader/lib/index.js:39:12)

### Environment

babel-loader-9.1
Node: 16.20.1
NPM: 9.8.1
OS: Windows 10

**Comment by vchauhan1994** [comment]
@JLHwung As I am using SPFx it has no direct index file so i have used webpack in gulpfile.js according to below article.

https://learn.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/extending-webpack-in-build-pipeline

and finally i am running gulp bundle command to check for any errors in my package but getting this error.

**Comment by JLHwung** [comment]
`this.loadOptions` is a webpack API available on webpack 5 only. My guess is that your toolchain is using webpack 4 or older versions. Even if you have installed the latest webpack 5, it is still depending on an older version. You can either try to upgrade your build tool, or downgrade `babel-loader` to v8.0.

**Comment by shaotianchi** [comment]
i have this error when i use happypack. and ererything get ok when not use happypack.

**Comment by JLHwung** [comment]
> i have this error when i use happypack. and ererything get ok when not use happypack.

babel-loader 9 does not support happypack because happypack provides `loader-utils@1` to babel-loader. Please downgrade to babel-loader 8.
