### ISSUE TITLE
Issue while creating build for React JS Application

### ISSUE THREAD

**Issue by codal-mitalt** [babel/babel-loader#1012]
Creating an optimized production build...
Failed to compile.

./node_modules/ml-matrix/src/symmetricMatrix.js 7:2
Module parse failed: Unexpected character '#' (7:2)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| export class SymmetricMatrix extends AbstractMatrix {
|   /** @type {Matrix} */
>   #matrix;
|   get size() {
|     return this.#matrix.size;

Versions

  "babel-loader": "8.1.0",

**Comment by codal-mitalt** [comment]
here is webpack config
`const CompressionPlugin = require('compression-webpack-plugin'); // gzip
const BrotliPlugin = require('brotli-webpack-plugin'); // brotli
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  optimization: {
    splitChunks: {
      chunks: 'all',
      name: false,
    },
    // Keep the runtime chunk separated to enable long term caching
    // https://twitter.com/wSokra/status/969679223278505985
    // https://github.com/facebook/create-react-app/issues/5358
    runtimeChunk: {
      name: entrypoint => `runtime-${entrypoint.name}`,
    },
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: `public/index.html`,
      favicon: `public/favicon.ico`,
    }),
    new CompressionPlugin({
      // gzip plugin
      filename: '[path].gz[query]',
      algorithm: 'gzip',
      test: /\.(js|css|html)$/,
      threshold: 8192,
      minRatio: 0.8,
    }),
    new BrotliPlugin({
      // brotli plugin
      asset: '[path].br[query]',
      test: /\.(js|css|html)$/,
      threshold: 10240,
      minRatio: 0.8,
    }),
    new BundleAnalyzerPlugin(),
    new webpack.optimize.ModuleConcatenationPlugin(),
    new webpack.optimize.UglifyJsPlugin({
      /* options here */
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'manifest',
      minChunks: Infinity,
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      minChunks: Infinity,
    }),
  ],
  module: {
    rules: [
      {
        test: /\.js$/,
        use: 'babel-loader',
        exclude: /node_modules/,
      },
    ],
  },
  entry: {
    app: './app.js',
    vendor: ['react', 'react-dom', 'react-router', 'styled-components'],
  },
};
`

**Comment by JLHwung** [comment]
Can you post your Babel config?

**Comment by codal-mitalt** [comment]
`{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-optional-chaining"
  ]
}
`

**Comment by JLHwung** [comment]
Thanks. The error comes from your node_modules, specifically the [`ml-matrix`](https://github.com/mljs/matrix/blob/4b632bb701d35ab69094a0249b1719c51aa6807f/src/symmetricMatrix.js#L8) library. As `node_modules` has been excluded from the `babel-loader`, Babel can not transform that code for your. Please enable Babel for the `ml-matrix` library. 

```js
// webpack.config.js
{
  rules: [
  {
    test: /\.(?:js|mjs|cjs)$/,
    exclude: {
      and: [/node_modules/], // Exclude libraries in node_modules ...
      not: [
        // Except for a few of them that needs to be transpiled because they use modern syntax
        /ml-matrix/,
      ]
    },
    use: {
      loader: 'babel-loader',
      options: {
        presets: [
          ['@babel/preset-env', '@babel/preset-react']
        ]
      }
    }
  }
]}
```

See also https://github.com/babel/babel-loader#some-files-in-my-node_modules-are-not-transpiled-for-ie-11

Please consider upgrade `@babel/core` and `@babel/preset-env` to the latest version, then these three plugins can be safely removed as they have been included in the `preset-env`.
```
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-optional-chaining"
```

**Comment by mamedbekovruslan** [comment]
Can  you help me, i have same issue, but my project on CRA. And i don`t uderstand, how to use your solution. Can you help me ?
