### ISSUE TITLE
unknow option .default 

### ISSUE THREAD

**Issue by luoriwusheng-xia** [babel/babel-loader#1014]
## **BEFORE YOU SUBMIT** please read the following:

*Delete what isn't applicable below*
**I'm submitting a bug report**
**I'm submitting a feature request**
**I'm submitting a support request** => Please do not submit support request here, see note at the top of this template.

**Webpack Version:**
   "webpack": "^5.89.0",

**Babel Core Version**:
  "@babel/cli": "^7.23.4",
    "@babel/core": "^7.23.6",
    "@babel/preset-env": "^7.23.6",

**Babel Loader Version**:
9.1.3

**Please tell us about your environment:**
Windows 10

**Current behavior:**
An error occurred during compilation

![image](https://github.com/babel/babel-loader/assets/152823466/aafe13b8-5679-4c73-b796-a7e1df6e87ac)

**Expected/desired behavior:**

build sucess

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

```js
module: {
    rules: [
      {
        test: /\.(?:js|mjs|cjs)$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: [
              ['@babel/preset-env', { targets: "defaults" }]
            ]
          }
        }
      },
}
```

copy from webpack5 website 

[webpack-babel-loader](https://webpack.js.org/loaders/babel-loader)

full  error log

```

ERROR in ./src/main.js
Module build failed (from ./node_modules/.pnpm/babel-loader@9.1.3_@babel+core@7.23.6_webpack@5.89.0/node_modules/babel-loader/lib/index.js):
Error: Unknown option: .default. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
    at D:\owner\vue2-webpack5-template\babel.config.js
    at Object.loadPartialConfigAsync (D:\owner\vue2-webpack5-template\node_modules\.pnpm\@babel+core@7.23.6\node_modules\@babel\core\lib\config\index.js:34:85)
    at Object.loader (D:\owner\vue2-webpack5-template\node_modules\.pnpm\babel-loader@9.1.3_@babel+core@7.23.6_webpack@5.89.0\node_modules\babel-loader\lib\index.js:109:30)
    at Object.<anonymous> (D:\owner\vue2-webpack5-template\node_modules\.pnpm\babel-loader@9.1.3_@babel+core@7.23.6_webpack@5.89.0\node_modules\babel-loader\lib\index.js:39:12)

```

The prompt says there is an issue with main.js, but the content of main.js is very clean

main.js

```js
import Vue from 'vue'
import App from './App.vue'

new Vue({
  render: h => h(App)
}).$mount('#app')
```

full package.json

```json
{
  "name": "vue2-webpack5-template",
  "main": "index.js",
  "scripts": {
    "serve": "cross-env NODE_ENV=development webpack-dev-server --config build/webpack.dev.js",
    "build": "cross-env NODE_ENV=production webpack  --config build/webpack.prod.js"
  },
  "devDependencies": {
    "@babel/cli": "^7.23.4",
    "@babel/core": "^7.23.6",
    "@babel/preset-env": "^7.23.6",
    "autoprefixer": "^10.4.16",
    "babel-loader": "^9.1.3",
    "babel-plugin-component": "^1.1.1",
    "cross-env": "^7.0.3",
    "css-loader": "^6.8.1",
    "html-webpack-plugin": "^5.5.4",
    "husky": "^8.0.3",
    "lint-staged": "^15.2.0",
    "mini-css-extract-plugin": "^2.7.6",
    "postcss-loader": "^7.3.3",
    "prettier": "^3.1.1",
    "sass": "^1.69.5",
    "sass-loader": "^13.3.2",
    "style-loader": "^3.3.3",
    "vue-loader": "^15.11.1",
    "webpack": "^5.89.0",
    "webpack-cli": "^5.1.4",
    "webpack-dev-server": "^4.15.1",
    "webpack-merge": "^5.10.0"
  },
  "dependencies": {
    "axios": "^1.6.2",
    "core-js": "^3.34.0",
    "element-ui": "^2.15.14",
    "vue": "^2.7.15",
    "vue-router": "~3.6.5",
    "vuex": "~3.6.2"
  }
}

```

```bash
pnpm 8.10.2
node: v20.10.0
```

**Comment by nicolo-ribaudo** [comment]
Can you share the contents of `D:\owner\vue2-webpack5-template\babel.config.js`?

**Comment by luoriwusheng-xia** [comment]
> Can you share the contents of `D:\owner\vue2-webpack5-template\babel.config.js`?

yes, this is all the content


```js
/**
 * @type {import('@babel/core').TransformOptions}
 */
exports.default = {
  root: true,
  "presets": [
    [
      "@babel/preset-env"
    ]
  ],

  plugins: [
    [
      // element-ui 懒加载
      // babel-plugin-component
      "component",
      {
        libraryName: "element-ui",
        styleLibraryName: "theme-chalk"
      }
    ]
  ]
}
```

**Comment by luoriwusheng-xia** [comment]
> Can you share the contents of `D:\owner\vue2-webpack5-template\babel.config.js`?

I haven't set any configuration related to. browserslistrc. Is this related to the current error?

**Comment by JLHwung** [comment]
Please change `exports.default` to `module.exports`, as `babel.config.js` expects the the config object to be the only commonjs module export.

**Comment by luoriwusheng-xia** [comment]
> Please change `exports.default` to `module.exports`, as `babel.config.js` expects the the config object to be the only commonjs module export.

Yes, you are right. Thank you for your guidance

I will close the current issue
