### ISSUE TITLE
Feature request: const enum support by webpack dependencies

### ISSUE THREAD

**Issue by JSerFeng** [babel/babel-loader#1047]
I can implement this if I checked this is doable and of course after your approval

**Current behavior:**

There are 2 issues I encountered.

1. const enum is supported in a way that's not optimized enough, although babel cannot get info about other modules, but webpack can, and babel can know if a module has exported const enum
2. re-export type without type modifier is not allowed, because babel cannot know is this exported member is type or not, so babel has to stay it as is, but the exported type from exported module is erased already.

**Solution**

Webpack has one thing called dependency, it's helpful for finding imported member, exported member, we can implement a new type of dependencies called, I don't know, maybe ConstEnumDependency and TypeExportedDependency, and provide these dependencies through `loaderContext._module.addDependency`

Giving 2 modules:

lib.ts
```typescript
export const enum Foo { A, B };
export type Bar = number;
```

reexports.ts
```typescript
export { Bar, Foo } from './lib'

Foo.A
```

`lib.ts` has dependencies: `ConstEnumDependency` and `TypeExportedDependency`

`reexports.ts` has dependencies `ExportImportedSpecifierDependency { Bar }` and ``ExportImportedSpecifierDependency { Foo }``

When webpack dependencies from a module, it will try to get exports info from them, we can make those 2 dependencies provide info about typescript types to webpack. By doing this, webpack can know that module `lib.ts` have export member `Foo` and `Bar`, this way we solve the problem 2, which is `cannot find export Foo from module lib.ts`. And since this dependency is unused, it won't appear in the final output

At codegen phase, webpack can use export info to get export content, you can try JSON module in webpack, if you import something from a JSON module, you will find the final output is optimized, for example, you import `a.b` from a JSON module, and the JSON module is like: {a: {b: 1} }, you will find `a.b` in final output turns into literal `1`, `ConstEnumDependency` can do the same

I can implement this if your think it's alright to have this kind of features

**Comment by JSerFeng** [comment]
Thanks for the reply, I'll try

> which should be bubdler-agnostic

isn't babel-loader for webpack bundler only ?

**Comment by JSerFeng** [comment]
Do I have way to access webpack loader context in a normal plugin ? If so I can implement a separate plugin for this feature

**Comment by nicolo-ribaudo** [comment]
babel-loader is for webapck only, but it does no code transformations. It's only used to call Babel from Webapck.

**Comment by nicolo-ribaudo** [comment]
> and normal babel-plugin cannot have ways to access webpack loader context

Maybe we could expose it in the caller object
