### ISSUE TITLE
Previous loaders are included in the filepath passed to Babel plugins

### ISSUE THREAD

**Issue by dallonf** [babel/babel-loader#106]
This issue is described in more detail over here, where I noticed the symptoms: https://github.com/yahoo/babel-plugin-react-intl/issues/5

Basically, I have [ts-loader](https://github.com/TypeStrong/ts-loader) set to run before babel-loader, and a plugin ([babel-plugin-react-intl](https://github.com/yahoo/babel-plugin-react-intl)) that depends on file options being passed to it. When `babel-plugin-react-intl` receives the file information, the `filename` value is `'<project directory>/node_modules/ts-loader/index.js!<project directory>/src/pages/asset/Page.tsx'` - which it can't parse.

**Comment by johanneslumpe** [comment]
Just came across this issue today too - hope this can be fixed soon :)

**Comment by Couto** [comment]
This is now on v6.2.0
I'm closing this. Please re-open if something comes up
