### ISSUE TITLE
.babelrc location not configurable

### ISSUE THREAD

**Issue by jonathanewerner** [babel/babel-loader#107]
Is it true that the babelrc location can not be specified in the loader options? (I guess so because of `delete options.babelrc;` in `index.js`). Why is that the case?

**Comment by idolize** [comment]
Yeah, it looks like it searches for it in the [`process.cwd()`](https://github.com/babel/babel-loader/blob/master/index.js#L9) and [every directory above that point](https://github.com/babel/babel-loader/blob/master/lib/resolve-rc.js) for the `.babelrc` file.

I want to use a `.babelrc` file that is a child of the current working directory, but as of right now I can't :disappointed:

**Comment by rolftimmermans** [comment]
This is unfortunate, especially since ".babelrc" is also used when using babel with node source code. It would be nice to have an alternative rc file for the browser code.

**Comment by michaelBenin** [comment]
What about having it configured in the package.json?

**Comment by michaelBenin** [comment]
@rolftimmermans - I was able to get multiple configs by setting different environments. I am not happy with this but it currently works.

Example:

```
{
  "stage": 0,
  "env": {
    "client-dev": {
      "plugins": ["react-transform"],
      "extra": {
        "react-transform": {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals": ["module"]
          }, {
            "transform": "react-transform-catch-errors",
            "imports": ["react", "redbox-react"]
          }]
        }
      }
    },
    "development": {}
  }
}
```

**Comment by mdreizin** [comment]
IMHO `babelrc` property should not be ignored by `babel-loader`. Using of `. babelrc` would be very useful. Please review #121.

**Comment by Couto** [comment]
For the adventurous ones, you can try to specify `.babelrc` by using the develop branch:

in your package.json
```
devDependencies: {
  "babel-loader": "babel/babel-loader#develop"
}
```

Like before, babel-loader only uses the babelrc for cache purposes, it won't interpret any option inside the .babelrc file

**Comment by lijunle** [comment]
> Yeah, it looks like it searches for it in the process.cwd() and every directory above that point for the .babelrc file.

This logic is **WRONG**. It should search starting from the directory of the file being transpiled instead of `process.cwd()`, 

[Babelrc document](http://babeljs.io/docs/usage/babelrc/#lookup-behavior):

> Babel will look for a .babelrc in **the current directory of the file being transpiled**. If one does not exist, it will travel up the directory tree until it finds either a .babelrc, or a package.json with a "babel": {} hash within.

**Comment by nilssolanki** [comment]
I'm also all for there being `.babelrc` location option. With vue.js 2, we're forced to use the `.babelrc` file, which we cannot place in a directory below our assets, since our package.json is in a parallel directory…

**Comment by ORESoftware** [comment]
+1, would like to have option to manually configure location of .babelrc (and name of file too)

**Comment by jjaburke91** [comment]
+1. Would like to move .babelrc our of the root folder and into my conf/ directory.

**Comment by huangyingjie** [comment]
Have to +1.

**Comment by pret-a-porter** [comment]
+1

**Comment by myuseringithub** [comment]
+1 for an option to choose .babelrc path and change it. 
I need to use during source code build, the separate .babelrc & node_modules of gulp directory, not the source code's directory (which has other .babelrc file). As the node_modules are not installed in the source code's directory, only until gulp-babel finishes compiling the code. 
The current behavior forces me to install source code's local node modules.

**Comment by daniele-orlando** [comment]
+1
