### ISSUE TITLE
Babel-loader looses correct error stack when Promise and react-router is used

### ISSUE THREAD

**Issue by gryzzly** [babel/babel-loader#114]
When initial rendering kicks off in a Promise callback the error stack and location are lost. The stack and location are correct when using transform-loader?babelify with exact same code.

Here's babel-loader:
<img width="525" alt="screen shot 2015-10-06 at 14 42 33" src="https://cloud.githubusercontent.com/assets/26131/10303924/4d7d51a6-6c30-11e5-83ec-17dac129baa2.png">

Here `babelify` via webpack’s `transform-loader` yields correct code location:
<img width="493" alt="screen shot 2015-10-06 at 14 38 52" src="https://cloud.githubusercontent.com/assets/26131/10303934/5f5d46a6-6c30-11e5-9d28-e639ea9311c0.png">

I've tried to compile the minimal code to reproduce, removing routing from the code solves the problem, but with `babelify` it works without removing routing: https://github.com/gryzzly/babel-loader-issue

**Comment by zloirock** [comment]
https://github.com/zloirock/core-js/issues/107

**Comment by zloirock** [comment]
https://github.com/zloirock/core-js/issues/107

**Comment by gryzzly** [comment]
@zloirock thanks for the reply! this doesn't only happen with core-js Promise, I tried `bluebird` as well, stack is lost only with `babel-loader` and again is not lost with `transform?babelify`

**Comment by zloirock** [comment]
You tried bluebird with [`Promise.longStackTraces()`](https://github.com/petkaantonov/bluebird/blob/master/API.md#promiselongstacktraces---void)?

**Comment by gryzzly** [comment]
@zloirock I tried previously with less "reduced" setup (more of my app code was in the example).

Retried again and now I can see that actually `bluebird` will provide stack trace with `longStackTraces()` with both `babel-loader` and `transform?babelify`, but it will point at compiled bundle rather than original code via source map. In entry point file at the top: 

```js
import Promise from 'bluebird';
Promise.longStackTraces();
require('babel-runtime/core-js/promise').default = Promise;
```
I put that above other requires and I could definitely see that bluebird was picked up. The trace it prints is different as it’s using `console.warn`.  So with `bluebird` I get this with both loaders:
<img width="524" alt="screen shot 2015-10-06 at 23 51 04" src="https://cloud.githubusercontent.com/assets/26131/10317222/d5f76e12-6c7c-11e5-8f51-a77d4db260bd.png">

**Comment by gryzzly** [comment]
I found that in my case just using `window.Promise` solves the issue as I need this to work only in Chrome. That proves the issue lies in `es6.promise.js` indeed as you suggested and so can be closed. Thanks for looking into it!

**Comment by benjamingr** [comment]
> zloirock/core-js#107. Unhandled rejection tracking is not a part of spec. Stack - also. If you wanna help implement long stack trace - welcome.

Actually, it's a part of the spec - https://github.com/tc39/ecma262/pull/76

**Comment by zloirock** [comment]
@benjamingr I mean ES6 :) Anyway, unhandled rejection tracking available.
