### ISSUE TITLE
option getModuleId does not work

### ISSUE THREAD

**Issue by jonnybcz** [babel/babel-loader#118]
option getModuleId does not work

**Comment by Couto** [comment]
err... more info please?

**Comment by jonnybcz** [comment]
Try add option getModuleId. The option does not work. Specify a custom callback to generate a module id with. Called as getModuleId(moduleName). If falsy value is returned then the generated module id is used. http://babeljs.io/docs/usage/options/

**Comment by igoratron** [comment]
@jonnybcz Came across the same issue today and it took me a while to realise that `moduleIds` needs to be set to `true` for `getModuleId` or `moduleRoot` to work. 

So something similar to
```javascript
babel.transform(fileContents, {
  moduleIds: true,
  getModuleId: moduleName => 'someOtherName'
  ...
}
```
Hope this helps next time!

**Comment by loganfsmyth** [comment]
The `getModuleId` option only really works for AMD/UMD transforms, which don't really make sense in a Webpack context. Since it's been ages, I assume this is safe to close.
