### ISSUE TITLE
Please help - "You may need an appropriate loader"

### ISSUE THREAD

**Issue by niftylettuce** [babel/babel-loader#119]
```log
ERROR in ./~/react-native-button/Button.js
Module parse failed: /Users/myuser/Public/myproject/react-native/node_modules/react-native-button/Button.js Line 18: Unexpected token ...
You may need an appropriate loader to handle this file type.
| var Button = React.createClass({
|   propTypes: {
|     ...TouchableOpacity.propTypes,
|     disabled: PropTypes.bool,
|     style: Text.propTypes.style,
 @ ./src/main.ios.js 8:13-43
```

The code is `...` as you can see from `propTypes`.  Here's my webpack config:

```js
  module: {
    loaders: [
      {
        test: /\.(js|jsx|es6)$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        query: {
          optional: [ 'runtime' ],
          stage: 0
        }
      }
    ]
  },]
```

**Comment by DLMR** [comment]
I think you need to remove `exclude: /node_modules/`since you are using a npm package that needs to be transpiled with Babel.

**Comment by niftylettuce** [comment]
I tried that already

**Comment by DLMR** [comment]
Can you publish a repo with this error so it is possible to look at it?

**Comment by niftylettuce** [comment]
Steps to reproduce:

1. Clone this repo, run npm install, https://github.com/jhabdas/react-native-webpack-starter-kit#installation
2. Install react native button, `npm install --save react-native-button`.  Then in the cloned folder/repo open `./src/main.ios.js` and add to top of the file `var Button = require('react-native-button');`.  Save the file.
3. Run `npm start` (you'll get this error, but note that `exclude: /node_modules/` is in the webpack config

**Comment by niftylettuce** [comment]
Ah, I see.. keyword was "remove" not "add"... Let me try now without exclude node modules!

**Comment by creamidea** [comment]
I have met the same error message. But my reason is that I wrote the wrong module.loader.include. [Here ](https://github.com/creamidea/creamidea.github.com/issues/19) is the detail.
**Key: it is a good idea to use `path.solve` to concat the string of path, not `+`**
