### ISSUE TITLE
Babel 6 is out.

### ISSUE THREAD

**Issue by ritz078** [babel/babel-loader#123]
An upgrade will be great.

**Comment by ryancbarry** [comment]
+1

**Comment by rosko** [comment]
+1

**Comment by eelkeh** [comment]
+1

**Comment by schovi** [comment]
+1

**Comment by shanecav** [comment]
+1

**Comment by eelkeh** [comment]
+1

**Comment by Couto** [comment]
Please stop with the +1 :)
It's the first thing I'll do in the morning tomorrow (aprox 8h from now)

**Comment by Couto** [comment]
Also any PR in the meantime is appreciated

**Comment by afc163** [comment]
+1

**Comment by shinnn** [comment]
@afc163 https://github.com/babel/babel-loader/issues/123#issuecomment-152368201

**Comment by Couto** [comment]
For the adventurous ones, you can test the develop branch:

```
devDependencies: {
  babel-loader: 'babel/babel-loader#develop'
}
```

Don't forget to install peerDependencies and plugins:

```
npm install babel-loader babel-core babel-preset-es2015
````

If people say that it's good, I'll make a release to master!

**Comment by malyw** [comment]
Hey @Couto 
Just tried "babel/babel-loader#develop"- works good for me!

JS build: 2.6s -> 2.1s (~20% profit)
Thanks!

**Comment by msokk** [comment]
I wonder how will custom polyfilling look like in v6?
https://github.com/babel/babel-loader#custom-polyfills-eg-promise-library

**Comment by schovi** [comment]
Works fine too in https://github.com/schovi/webpack-chrome-extension

**Comment by MarianArlt** [comment]
Specified `'babel?optional[]=runtime&stage=0'` in config, 6.0.0 throws me an error about loader options being unknown (worked fine before).

    ERROR in ./app/index.jsx
    Module build failed: ReferenceError: [BABEL] /Library/WebServer/Documents/yarsk.test/app/index.jsx: Unknown option: base.optional
        at Logger.error (/Library/WebServer/Documents/yarsk.test/node_modules/babel-core/lib/transformation/file/logger.js:43:11)
        at OptionManager.mergeOptions (/Library/WebServer/Documents/yarsk.test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:18)
        at OptionManager.init (/Library/WebServer/Documents/yarsk.test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:395:10)
        at File.initOptions (/Library/WebServer/Documents/yarsk.test/node_modules/babel-core/lib/transformation/file/index.js:191:75)
        at new File (/Library/WebServer/Documents/yarsk.test/node_modules/babel-core/lib/transformation/file/index.js:122:22)
        at Pipeline.transform (/Library/WebServer/Documents/yarsk.test/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
        at transpile (/Library/WebServer/Documents/yarsk.test/node_modules/babel-loader/index.js:12:22)
        at Object.module.exports (/Library/WebServer/Documents/yarsk.test/node_modules/babel-loader/index.js:69:12)
     @ multi main

**Comment by malyw** [comment]
@MarianArlt `runtime` and `stage`params are supposed to be removed.
Check e.g.: [Quick guide: how to update Babel 5.x -> 6.x](https://medium.com/@malyw/how-to-update-babel-5-x-6-x-d828c230ec53)

**Comment by MarianArlt** [comment]
@malyw Thanks for the pointer, changed to `'babel?presets[]=es2015'` and now compiles fine but throws a syntax error about react static propTypes.

    ERROR in ./app/components/form/index.jsx
    Module build failed: SyntaxError: /Library/WebServer/Documents/yarsk.test/app/components/form/index.jsx: Unexpected token (19:19)
      17 | // ES6 React Component:
      18 | export default class SurveyForm extends Component {
    > 19 |   static propTypes = {
         |                    ^

**Comment by AprilArcus** [comment]
using babel-core@6.0.14, babel-loader#develop

With
`webpack.config.js`:
```JavaScript
  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel',
        query: {
          presets: ['es2015', 'stage-2']
        },
        exclude: /node_modules/
      }
    ]
  }
```

and

`.babelrc`:
```JSON
{}

```

everything swings. However, with

`webpack.config.js`:
```JavaScript
  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /node_modules/
      }
    ]
  }
```

and

`.babelrc`:
```JSON
{
  "presets": ["es2015", "stage-2"]
}

```

I fail with this stack trace:

```
/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
                           ^

TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

**Comment by t-hiroyoshi** [comment]
@MarianArlt `transform-class-properties` is included in `preset-stage-1` so this is not `preset-react`'s problem. See this http://babeljs.io/docs/plugins/preset-stage-1.

**Comment by Couto** [comment]
Hey everyone! babel-loader v6 is out. You can now install directly from npm.
Thanks everyone for the notice and testing :)

@malyw I've added a link to your upgrade guide, on the README.md. I hope you don't mind, if you do, just ping! :)

**Comment by malyw** [comment]
Hey @Couto well done!
Just updated an article section regarding `babel-loader` version 👍

**Comment by dabowheel** [comment]
Two things:
1) I was confused at first because it wouldn't transpile unless I specified the preset. The readme didn't mention the preset was necessary to go from es2015 to es5.
2.) Installing babel-preset-es2015 takes a couple minutes on my machine. My npm version is 2.14.7.  I assume that upgrading to npm 3.x would help because it wouldn't install multiple copies of the same dependencies.

**Comment by MichaelCereda** [comment]
I have an error similar to @MarianArlt 

```
ERROR in ./src/app.jsx
Module build failed: SyntaxError: /<path>/app.jsx: Unexpected token (11:4)

 React.render(
> 11 |     <h1>Hello, world!</h1>,
     |     ^
  12 |     document.getElementById('app')
  13 | );
```
i tried everything but nothing seems to work, my current settings are 
```
{
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loaders: [ 'react-hot', 'babel?presets[]=es2015' ],
}
```

am i doing something wrong? should i downgrade for now? thanks

**Comment by zerkms** [comment]
@MichaelCereda `es2015` preset does not compile jsx, there is a separated `react` one

**Comment by MichaelCereda** [comment]
Thanks @zerkms, do you mean 'babel-preset-react'  and as settings

```
{
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loaders: [ 'react-hot', 'babel?presets[]=react' ],
}
```

gives me 
```
You may need an appropriate loader to handle this file type.
|
|
| import React from 'react';
|
| React.render(React.createElement(
```
triggered on the line of "React.render"
even if the content of the file is just
```
import React from 'react';

React.render(
    <h1>Hello, world!</h1>,
    document.getElementById('app')
);
```

probably i'm doing something wrong.. :S

**Comment by zerkms** [comment]
@MichaelCereda add multiple presets, one for ES2015, another for jsx :-)

**Comment by MichaelCereda** [comment]
Thanks again @zerkms, now it finally works, here's what i did.

```
{
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loaders: [ 'react-hot', 'babel?presets[]=react&presets[]=es2015' ],
}
```

the order of the presets seems important.
I hope that this can help others

**Comment by GerryFudd** [comment]
I am encountering an issue similar to @MichaelCereda and I am attempting to implement his fix.  I have
```
    "babel-preset-es2015": "^6.5.0",
    "babel-preset-react": "^6.5.0",
```
in my dependencies and
```
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel', // requires babel-loader
        query: {
          presets: ['react', 'es2015'] // requires babel-preset-<name>
        }
      }
```
in my webpack.config.js.  When I attempt to run webpack, I still get this error
```
ERROR in ./client/elements/log.js
Module build failed: SyntaxError: /Users/davidhasenjaeger/Wirestorm/projects/TwilioBeta/client/elements/log.js: Unexpected token (4:19)
  2 | 
  3 | export default class Log extends Component {
> 4 |   static propTypes = {
    |                    ^
  5 |     text: PropTypes.string.isRequired
  6 |   };
  7 | 
```
Is there anything else that I may have missed?

**Comment by GerryFudd** [comment]
All of the jsx is interpreted correctly.  It is just the static propTypes that is causing errors.

**Comment by zerkms** [comment]
@GerryFudd static class fields are part of `stage-1` preset

**Comment by GerryFudd** [comment]
Thank you, @zerkms!  It looks like the order of the presets is important here as well.  I modified my dependencies to include
```
    "babel-preset-es2015": "^6.5.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-1": "^6.5.0",
```
and my loader in webpack.config.js to include
```
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel', // requires babel-loader
        query: {
          presets: ['react', 'es2015', 'stage-1'] // requires babel-preset-<name>
        }
      }
```
This compiles just fine now.  Cheers, all!
