### ISSUE TITLE
webpack compilation failure

### ISSUE THREAD

**Issue by happypeter** [babel/babel-loader#127]
Using babel-loader 6.x.x to build react components , failed.

Had to switch back to 5.x.x to make it work.  Maybe it's a Babel6 bug .

**Comment by happypeter** [comment]
related to https://github.com/babel/babel-loader/issues/134

**Comment by happypeter** [comment]
https://github.com/babel/babel-loader/issues/123#issuecomment-152938965

**Comment by Couto** [comment]
I'm guessing that you've achieved a solution right?

**Comment by happypeter** [comment]
Thx I think so.
