### ISSUE TITLE
how to use arrow function in babel 6.x

### ISSUE THREAD

**Issue by CellChen** [babel/babel-loader#130]
this is my babelrc config

```
{
  "presets": [
    "react",
    "es2015"
  ],
  "plugins": [
    "transform-es2015-arrow-functions"
  ]
}
```

and my component code:

```
import React from 'react';
import { render } from 'react-dom';

class App extends React.Component {
    constructor(props) {
        super(props);
    }
    _handleClick = (e) => {
        
    }
    render() {
        return (
            <div>App</div>
        );
    }
}

render(
    <App />,
    document.getElementById('app')
);
```

but it throw an error when webpack or babel main.js -p out.js

```
SyntaxError: main.js: Unexpected token (9:17)
   7 |         super(props);
   8 |     }
>  9 |     _handleClick = (e) => {
     |                  ^
  10 |         
  11 |     }
  12 |     render() {
```

**Comment by mathieumg** [comment]
You need to enable class properties. (i.e. use the appropriate plugin for that under Babel 6)

**Comment by CellChen** [comment]
@mathieumg thanks your answer.  can you give some demo code like my babelrc?

**Comment by CellChen** [comment]
```
{
  "presets": [
    "react",
    "stage-1"
  ]
}
```

solved

**Comment by mikeonline** [comment]
I found that my webpack.config.js had to be swapped from:
            presets: ['es2015','react'],
to:
             presets: ['react','es2015'],

**Comment by mikeonline** [comment]
I have set the plugin: 
            plugins: [
                 ["transform-es2015-arrow-functions", { "spec": true }]
             ]
and am using es2015 and react presets 
            presets: ['react','es2015'],
However it still does not work!
