### ISSUE TITLE
bare import error

### ISSUE THREAD

**Issue by PavelPolyakov** [babel/babel-loader#135]
Hi,

I have an error, when trying to do the next:
```
const progress = Vue.extend(import './components/progress.vue');
```

![image](https://cloud.githubusercontent.com/assets/839290/10923088/3f841f48-827f-11e5-8597-fab4e9383815.png)

Here it's stated that this syntax is possible.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

As I understand it's the issue of babel-loader, because inbrowser babel does the transpiling:
![image](https://cloud.githubusercontent.com/assets/839290/10923117/6f407178-827f-11e5-81da-8ce8ad8d1731.png)

Is this a bug, or I am doing something wrong?
I use https://github.com/vuejs/vue-loader , which babelifies the input in it's turn.

Regards,

**Comment by PavelPolyakov** [comment]
Sorry, it seems that using bare import inside the function is not possible in babel as well.
![image](https://cloud.githubusercontent.com/assets/839290/10923814/511d554a-8283-11e5-9e36-87370148b552.png)

**Comment by Couto** [comment]
The `import` statement doesn't exactly work as a function.
The syntax you're looking is something more like:

```
import Progress from 'components/progress.vue'
console.log(Progress);
```

**Comment by PavelPolyakov** [comment]
Thanks, I just do not wanted to declare a separate variable.

**Comment by Couto** [comment]
It's not really a matter of declaring a variable, the `import` statement doesn't return a value, it just exposes the value to the scope, so either the module defines something in the global scope, or you'll have to attach the value to a variable, afaik...
