### ISSUE TITLE
Broken source maps

### ISSUE THREAD

**Issue by vlkosinov** [babel/babel-loader#137]
With new babel release I got flattened folder hierarchy :scream:

## Before: 
![Before](https://raw.githubusercontent.com/vlkosinov/babel-lodaer-source-map-issue-example/master/screenshots/babel-loader-5.png)

## After:
![After](https://raw.githubusercontent.com/vlkosinov/babel-lodaer-source-map-issue-example/master/screenshots/babel-lodaer-6.png)

Example: https://github.com/vlkosinov/babel-lodaer-source-map-issue-example

**Comment by zywind** [comment]
Good to know I'm not the only one that this is happening to. I also don't see all the source files there.

**Comment by mctep** [comment]
:+1:

**Comment by Mae5tr0** [comment]
+

**Comment by ida-t** [comment]
+

**Comment by eur00t** [comment]
@vlkosinov, I also have this problem and I made a patch which works for my project. I tested it for your example, `babel6/public/app.js.map`:

before

    "sources":["webpack:///webpack/bootstrap d8405410e759e18a24c8","webpack:///index.js","webpack:///another-file-name.js"]

after

    "sources":["webpack:///webpack/bootstrap d8405410e759e18a24c8","webpack:///./src/index.js","webpack:///./src/module1/index.js","webpack:///./src/module2/another-file-name.js"]

Looks like this is exactly what is also generated in `babel5/`.

**Comment by Gvozd** [comment]
I have some improvement

Before this change (not bad variant)
```
	"sources": [
		"webpack:///webpack/bootstrap f6790d4a4ba109d67350",
		"webpack:///main.js",
		"webpack:///any.js",
		"webpack:///Pattern.js",
		"webpack:///exc.js",
		"webpack:///opt.js",
		"webpack:///rep.js",
		"webpack:///seq.js",
		"webpack:///rgx.js",
		"webpack:///txt.js"
	]
```
After this change(i not need absolut filesystem-path in my source-maps J)
```
	"sources": [
		"webpack:///webpack/bootstrap f6790d4a4ba109d67350",
		"webpack:///C:/Projects/parser/main.js",
		"webpack:///C:/Projects/parser/lib/combinators/any.js",
		"webpack:///C:/Projects/parser/lib/Pattern.js",
		"webpack:///C:/Projects/parser/lib/combinators/exc.js",
		"webpack:///C:/Projects/parser/lib/combinators/opt.js",
		"webpack:///C:/Projects/parser/lib/combinators/rep.js",
		"webpack:///C:/Projects/parser/lib/combinators/seq.js",
		"webpack:///C:/Projects/parser/lib/patterns/rgx.js",
		"webpack:///C:/Projects/parser/lib/patterns/txt.js"
	]
```

My improvement(i look it at coffee-loader):
use `sourceRoot: '',` instead `sourceRoot: process.cwd(),`
After this improvement
```
	"sources": [
		"webpack:///webpack/bootstrap f6790d4a4ba109d67350",
		"webpack:///main.js",
		"webpack:///lib/combinators/any.js",
		"webpack:///lib/Pattern.js",
		"webpack:///lib/combinators/exc.js",
		"webpack:///lib/combinators/opt.js",
		"webpack:///lib/combinators/rep.js",
		"webpack:///lib/combinators/seq.js",
		"webpack:///lib/patterns/rgx.js",
		"webpack:///lib/patterns/txt.js"
	],
```
I think this variant better that previous two

PS sorry for my bad english
