### ISSUE TITLE
Update deps babel-core

### ISSUE THREAD

**Issue by scriptjs** [babel/babel-loader#145]
babel-core deps need to be upgraded from ^6.0.0 -> ^6.1.2.
Do we need peer deps that emits warning with npm 3.

**Comment by wheresrhys** [comment]
:+1: As a work around for the time being I have `rm -Rf node_modules/babel-loader/babel-core` as  post install step

**Comment by Couto** [comment]
Why does it need to upgrade deps? the `^` accepts everything untill the left most 0, in this case 6.x.x

I really feel that the loader should specify which version of the babel-core you want to use, so it's up to you to install the correct peer-dependency.
