### ISSUE TITLE
SourceMap generation breaking with upgrade from 6.0.1 to 6.1.0

### ISSUE THREAD

**Issue by scriptjs** [babel/babel-loader#147]
Fails to build with es2015 and stage-0 presets with invalid mapping. 
at SourceMapGenerator_validateMapping [as _validateMapping] 
node_modules/babel-core/node_modules/source-map/lib/source-map/source-map-generator.js:275:15

```
    "babel-core": "^6.1.2",
    "babel-loader": "^6.1.0",
    "babel-preset-es2015": "^6.1.2",
    "babel-preset-react": "^6.1.2",
    "babel-preset-stage-0": "^6.1.2",
    "webpack": "^1.12.3"
```

The project properly builds with babel-loader@6.0.1

**Comment by aikoven** [comment]
I get the same error with `6.0.1`.

**Comment by aikoven** [comment]
This seems to be related: https://github.com/babel/babel/issues/2864

**Comment by scriptjs** [comment]
@aikoven I thought part of this is that the deps for babel-loader have not yet been updated and rely on babel-core 6.0.0. If the loader is not upgraded later today, I'll see if this has any impact if I have time. I have to evaluate 6.1.4 that is just out today.

**Comment by barbalex** [comment]
same problem here: babel-loader 6.1.0 gave invalid mapping

I am now using:

    "babel": "6.1.5",
    "babel-core": "6.1.4",
    "babel-loader": "6.0.1",
    "babel-preset-es2015": "6.1.4",
    "babel-preset-react": "6.1.4",
    "babel-preset-stage-0": "6.1.2"

this works

**Comment by scriptjs** [comment]
yes. anything greater than 6.0.1, I have this issue also.

**Comment by scriptjs** [comment]
Babel 6.3.13 resolves this issue with changes to the babel core resolve this.

**Comment by barbalex** [comment]
yep, problem solved. Thanks a lot!

**Comment by pebie** [comment]
I always have the error with Babel 6.3.13 when I try to use `devtool` `eval-source-map` in my webpack config.

My package json 

````
"babel-core": "^6.4.5",
"babel-eslint": "^4.1.6",
"babel-loader": "^6.2.1",
"babel-preset-es2015": "^6.3.13",
"babel-preset-react": "^6.3.13",
"babel-preset-stage-0": "^6.3.13"
```

`````
ERROR in ./src/demo/index.js
Module build failed: Error: /Users/.../index.js: Invalid mapping: {"generated":{"line":29,"column":104,"lastColumn":null},"source":null,"original":{"line":null,"column":null},"name":null}
````
**NB** `eval` works great.

**Comment by arvinsim** [comment]
I have the same problem. Only `eval` works for me.

**Comment by yujiangshui** [comment]
I still have this problem and you? @pebie @arvinsim
