### ISSUE TITLE
Incoming more than one parameters into babel .

### ISSUE THREAD

**Issue by WenXuanYuan** [babel/babel-loader#148]
I write my webpack.config.js like this: 

{test: /\.js$/, loaders: ['react-hot', 'babel?presets[]=es2015'], exclude: /node_modules/}

How shoud I do to set presets['react'] with 'es2015' , I find query:{presets:['es2015','react']} can't use.

I need your help, thank you!

**Comment by Couto** [comment]
```
{test: /.js$/, loaders: ['react-hot', 'babel?presets[]=es2015&presets=[]=react'], exclude: /node_modules/}
```

You can find more examples here: https://github.com/webpack/loader-utils :)

**Comment by WenXuanYuan** [comment]
Thank you . You solved my problem perfectly.
