### ISSUE TITLE
Runtime Option

### ISSUE THREAD

**Issue by arb** [babel/babel-loader#150]
It is not clear in the docs how to use the optional babel-runtime configuration. In the documentation where I think that is supposed to be [here](https://github.com/babel/babel-loader#babel-is-injecting-helpers-into-each-file-and-bloating-my-code), it just uses the es2015 configuration value on the query string. Where do you use `babel-runtime`? I tried this

```
      test: /\.js$/,
      include: [
        Path.resolve(process.cwd(), 'client')
      ],
      exclude: 'node_modules',
      loader: 'babel',
      query: {
        presets: ['es2015'],
        optional: ['runtime']
      }
    }
```

But got an error about Unknown option `optional`. What am I missing?

According to https://github.com/babel/babel-loader/issues/123#issuecomment-152673652, you shouldn't need babel-runtime anymore... but then why do I need to install it per the babel-loader documentation?

**Comment by Couto** [comment]
The README.md is outdated.
The `optional` property was [removed in babel v6](https://github.com/babel/babel/blob/master/CHANGELOG.md#600)

**Comment by dexbol** [comment]
I am a newbie and the documents also confused me . Could anybody update the docs?

**Comment by Couto** [comment]
The documents have been updated, [check](https://github.com/babel/babel-loader#babel-is-injecting-helpers-into-each-file-and-bloating-my-code)
