### ISSUE TITLE
Error: global leak detected: __core-js_shared__

### ISSUE THREAD

**Issue by asimpletune** [babel/babel-loader#152]
Hi! I'm using `babel-core/register` in some tests that're run with mocha, and it seems to be complaining about a global leak from 

```js
mocha.before(function (done) {
      createEnvironment(function (err, newDir) {
        if (err) return done(err);
        dir = newDir;
        var onlyTranspileEs6 = require("babel-core/register");
        done();
      });
    });
```

But I get an error when I run the test

```bash
npm test

> express-generator@4.13.1 test /Users/Spencer/Developer/generator
> mocha --reporter spec --bail --check-leaks test/



  1) "before all" hook
  express(1)
    (no args)
    --es6
    --ejs
    --git
    -h
    --hbs
    --help


  0 passing (2s)
  1 failing

  1)  "before all" hook:
     Error: global leak detected: __core-js_shared__
      at test/cmd.js:134:9
      at ondir (test/cmd.js:493:5)
      at FSReqWrap.oncomplete (fs.js:95:15)



npm ERR! Test failed.  See above for more details.
```

To give you more context, Mocha creates a temporary directory for each test setup, and I'm calling require on babel-core/register just within the line of code that's testing my es6 case. It's important that I avoid transpiling code that shouldn't have any ES6 in it.

**Comment by zloirock** [comment]
Expected behavior. https://github.com/zloirock/core-js/issues/51

**Comment by robkorv** [comment]
This also happens when testing with [lab](https://github.com/hapijs/lab).

```
The following leaks were detected:__core-js_shared__
```

I noticed that the library i need babel for ignores this error in it's own test.
https://github.com/jedireza/hapi-react-views/blob/d0529ad389c7c51d2c8b5d2d62870a02b8dae9ac/package.json#L7

@zloirock is ignoring the leak something you would recommend?

**Comment by fourq** [comment]
@robkorv did you ever figure out the issue with lab?

**Comment by robkorv** [comment]
@fourq, no I just ignored the error like hapi-react-views does in it's tests.

**Comment by fourq** [comment]
@robkorv thanks, that's what I've been doing.

**Comment by miguelcobain** [comment]
me too
