### ISSUE TITLE
babel 6.1 throwing syntax error for JSX

### ISSUE THREAD

**Issue by JosephShering** [babel/babel-loader#153]
I get this error when I try to use babel-loader in my webpack.config.js what could be causing this?

ERROR in ./scripts/app.jsx
Module build failed: SyntaxError: /Users/reactor/Projects/testproject/scripts/app.jsx: Unexpected token (5:15)
```
class App extends React.Component {
  render() {
    return <div></div>;
  }
}
```

**Comment by Couto** [comment]
Are you using the [react-preset](https://babeljs.io/docs/plugins/#presets) ?

**Comment by jacob-israel-turner** [comment]
I'm getting this as well.  Bumping back to these versions fixed it:

```
    "babel-core": "5.8.x",
    "babel-loader": "5.3.3",
```

**Comment by youanden** [comment]
+1 
@jacob-israel-turner Going back fixed it.

**Comment by jacob-israel-turner** [comment]
After working it out with a buddy, turns out the API changed. https://babeljs.io/blog/2015/10/29/6.0.0/

**Comment by jacob-israel-turner** [comment]
Check out 'plugin presets'
