### ISSUE TITLE
export default class broken inside custom plugin

### ISSUE THREAD

**Issue by mfellner** [babel/babel-loader#158]
I came across an issue when I was trying to upgrade my [webpack plugin](https://github.com/mfellner/static-jsx-webpack-plugin) to Babel 6.

When using a custom [webpack plugin](https://github.com/mfellner/babel-loader-react-export-test/blob/master/src/StaticJsxPlugin.js) that renders React components to static HTML, it seems that the `type` property of React.Component derived classes which are exported as ES2015 modules is wrapped inside an object `{default: Function}`.

This subsequently causes the following React error:
```
Invariant Violation: Element type is invalid: expected a string (for built-in components)
or a class/function (for composite components) but got: object.
```

The issue **does not** arise when using `module.exports` instead or without the plugin. I prepared a small project [here](https://github.com/mfellner/babel-loader-react-export-test) to illustrate my point.

Also, possibly related to https://github.com/babel/babel/issues/2700.

**Comment by just-boris** [comment]
This is looks more like an issue in `StaticJsxPlugin `. Try to replace `self.sourceChunk` [here](https://github.com/mfellner/babel-loader-react-export-test/blob/master/src%2FStaticReactSource.js#L33) 
to `self.sourceChunk.default` and problem will be solved

**Comment by scriptjs** [comment]
This is not a issue with the loader. Suggest this should be closed.

**Comment by mfellner** [comment]
@just-boris thanks for the tip. I was able to fix the issue in my code: https://github.com/mfellner/babel-loader-react-export-test/pull/1.

Do you know by any chance though what happened to the `module.exports` interop feature?

**Comment by scriptjs** [comment]
@mfellner You can read about it here: http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default

**Comment by mfellner** [comment]
@scriptjs Cool, thanks!
