### ISSUE TITLE
Why is version 6 not published?

### ISSUE THREAD

**Issue by briandipalma** [babel/babel-loader#159]
The latest version of babel loader on npm appears to be 5.X, is there any reason why the 6.X version hasn't been published as latest? Is it ready for use?

**Comment by loganfsmyth** [comment]
Looks like a bug caused because `5.x` was just bumped to `5.4`. You'll need to explicitly `npm install babel-loader@6.x` until `latest` is properly set back to `6.x`.

@Couto Can you take a look at this soon?

**Comment by ljharb** [comment]
`npm dist-tag add babel-loader@6.x latest` should do it.

**Comment by Couto** [comment]
I'm sorry! My mistake.
It should be alright by now!

**Comment by Couto** [comment]
I'm closing this issue. Please re-open if there's still a problem.

**Comment by loganfsmyth** [comment]
Thanks!
