### ISSUE TITLE
How could I use async/await in browser with babel6?

### ISSUE THREAD

**Issue by wangxiao** [babel/babel-loader#161]
babel-core 6.1.21
babel-loader 6.2.0

```
    module: {
      loaders: [{
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel',
        query: {
          plugins: ['transform-runtime'],
          presets: ['es2015', 'stage-0', 'stage-3']
        }
      }]
    }
```

have an error:

```
Uncaught TypeError: (0 , _typeof3.default) is not a function
```

**Comment by Dignifiedquire** [comment]
Seeing the same issue: https://travis-ci.org/ipfs/js-ipfs-api/jobs/92021174#L1703

**Comment by wangxiao** [comment]
@Dignifiedquire Thanks. 
My Node.js version is 0.12.7. If I update to 4.x, can I use async/await in browser?

**Comment by osomdevrepos** [comment]
@wangxiao try this 

http://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined-with-async-await

it worked for me

**Comment by liam4** [comment]
@osomdevrepos I don't think that will work for running in a web browser - it looks like the code there is node.js.

**Comment by jtHwong** [comment]
There is the same issue in my application. How to solve it in browser? Thank you.

**Comment by jesus-repos** [comment]
@liam4 @jtHwong hi guys, in order to use async/await functions with webpack and babel you need to add a babel polyfill in your entry on webpack config, this work on both, nodejs and browser, take a look:

```
    entry:  ['babel-polyfill', path_to_entry],

    module: {

        loaders: [
            {
                test: /\.js$/,
                loader: 'babel',
                query: {
                    presets: ['es2015', 'stage-0'],
	                plugins: ['transform-runtime']
                }
            },
        ]
    }
```

this is how is working for me.

**Comment by jtHwong** [comment]
Thank you, @jesus-repos. 
My config is the same as yours. But the problem was still. 
I updated my package by `npm update` . So all of my packages were newest.  Can you show your `package.json`?

**Comment by jtHwong** [comment]
I try Babel5 and everything is ok.

**Comment by sebas5384** [comment]
thanks @jesus-repos, worked here!

**Comment by d3viant0ne** [comment]
Resolving as a resolution to the original issue exists
