### ISSUE TITLE
cacheDirectory param no longer works with babel-loader 6+

### ISSUE THREAD

**Issue by trevordmiller** [babel/babel-loader#167]
I just upgraded to Babel 6 and am getting the following error:

```
Error: Cannot resolve module 'babel-loader&cacheDirectory=cache'
```

It seems that the `cacheDirectory` option no longer works with the latest babel-loader.

Here are my related dependencies:

```
    "babel-core": "^6.2.1",
    "babel-loader": "^6.2.0",
    "babel-plugin-react-intl": "^2.0.0",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "babel-preset-stage-2": "^6.1.18",
    "webpack": "^1.12.1",
```

**Comment by ishotfirst** [comment]
I haven't tested myself, but have you tried the query property?

```JavaScript
loaders: [{
  test: /\.js$/,
  exclude: /node_modules/,
  loader: 'babel',
  query: {
    cacheDirectory: true,
    presets: ['es2015'],
  }
}]
```

**Comment by fvargas** [comment]
@trevordmiller I think the problem is you're using an `&` instead of a `?`. The following should work:

'babel-loader?cacheDirectory=cache'

**Comment by Couto** [comment]
@trevordmiller is silent, so I assume the problem was solved.

**Comment by trevordmiller** [comment]
I actually gave up on upgrading to Babel 6 for the time being - ran into too many issues. But feel free to close the issue. Thanks.
