### ISSUE TITLE
Error with new version

### ISSUE THREAD

**Issue by DmitryAuine** [babel/babel-loader#169]
In my prev project i did use 5.3.2.
Today i started new project and i installed new one ^6 and when i build with webpack it throws error.

`Module parse failed: /home/auine/develop/isomorphic/node_modules/babel-loader/index.js!/home/auine/develop/isomorphic/public/src/components/app.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import React from 'react';
| 
| export default (() => {
`

`You may need an appropriate loader to handle this file type.`
So it's like loader doesn't work

I have tried use 5.3.2 and everything is good

My config:
```javascript
var path = require('path');
var webpack = require('webpack');

module.exports = {
  devtool: 'eval',
  entry: [
    './public/src/components/app'
  ],
  output: {
    path: path.join(__dirname, 'public/dist'),
    filename: 'bundle.js',
    publicPath: 'public/dist/'
  },
  module: {
    loaders: [{
      test: /\.js$/,
      exclude: /(node_modules|bower_components)/,
      loaders: ['babel']
    }]
  }
};
```

**Comment by ishotfirst** [comment]
Please read the updated usage documentation. Version 6 is major version update, and as such, things are likely not to work the same as before. In this case, you need to specify the react preset (or individual plugins). You will likely need/want to include other plugins, as well.

**Comment by lean** [comment]
same problem here. 
My config:

```javascript
		{ 
					test: /\.js$/, 
					exclude: /node_modules/,
					loader: "babel-loader",
			        query: {
			          presets: ['es2015','react']
        			}
				},
```

**Comment by DmitryAuine** [comment]
Yeap, i too did try presets and had the same problem

**Comment by ishotfirst** [comment]
That should work assuming all the dependencies are installed. Do you have babel-core, babel-loader, babel-preset-es2015, and babel-preset-react installed? If so, are you getting the "You may need an appropriate loader" error or something else?

**Comment by lean** [comment]
seems like the issue is with the regex. Ive just changed to 
```javascript 
test: /\.(js|jsx)$/ 
```
and it is working now.

**Comment by ishotfirst** [comment]
Do you use the .jsx file extension? Something like that would have been a problem with version 5, as well. Did you change the extension when you upgraded?

**Comment by d3viant0ne** [comment]
>Resolving this as the issue contains a resolution to the reported problem

**Comment by luisesantos** [comment]
Hey guys I am having exactly the same error but the curious things is that is just happening in Windows. And actually to make it even more estrange is happening in a specific directory. If I copy and paste my project in a different directory it builds properly. Have you guys seen anything like that ?
