### ISSUE TITLE
sourcemaps: inline set in .babelrc breaks source maps from babel-loader

### ISSUE THREAD

**Issue by EdwardDrapkin** [babel/babel-loader#174]
This is a pretty bizarre use-case I guess, but I had babel inlining sourcemaps and this broke babel-loader.  I had to change my configuration for babel from 'inline' to true, which wasn't a big deal, but it was odd to debug.  Babel doesn't output a map key in the result of transform() if sourcemaps are specified to be inlined, so IMO because inlining sourcemaps is handled in webpack rather than babel, you should detect and override this option for poor folks in the future.

**Comment by vasyas** [comment]
+1 the same happens to me
