### ISSUE TITLE
Detect what polyfills are needed

### ISSUE THREAD

**Issue by OliverJAsh** [babel/babel-loader#175]
Is it possible for Babel to detect which polyfills are needed and only include those? I don't want to include the whole of babel-polyfill if I'm only using Promise, for example.

/cc @sndrs

**Comment by gbrassey** [comment]
If you use `babel-plugin-transform-runtime`, only the modules that are used will be included in the final build 

See here for info: http://www.2ality.com/2015/12/babel6-helpersstandard-library.html
