### ISSUE TITLE
babel 5.3.x is ok  but babel 6.2.0  not ok

### ISSUE THREAD

**Issue by zhoujianlin8** [babel/babel-loader#176]
> 6 | ReactDOM.render(<Index />, document.getElementById('container'));

at Parser.pp.raise (/work/npms/sdk-rtool/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:22:13)

**Comment by hawkrives** [comment]
You appear to be missing the first argument to `ReactDOM.render`?

**Comment by mythmon** [comment]
The first argument appears to be missing because GitHub hides things that looks like html tags when they aren't in code blocks: Consider this (without a code block): "<foo>") vs this: "`<foo>`" (with code tags).

**Comment by hawkrives** [comment]
Excellent point.
