### ISSUE TITLE
in JSX src and href attributes are not parsed

### ISSUE THREAD

**Issue by kilianc** [babel/babel-loader#178]
I was expecting the loader to require for me the images and css files for me and based in configuration inline or save the file

**Comment by aarongodin** [comment]
Babel doesn't touch any references to static assets in your JS or JSX. There are other webpack loaders that will handle inlining CSS and images. For css, you can use [css-loader](https://github.com/webpack/css-loader) in conjunction with other loaders (see the documentation for css-loader) to inline stylesheets into your JS.

With images, you can use [url-loader](https://github.com/webpack/url-loader) to copy files into your distribution and update the references to them (url-loader fingerprints by default). You can also configure it to base64 small images.

**Comment by mjsisley** [comment]
For images, this issue in file-loader appears to be relevant: https://github.com/webpack/file-loader/issues/35
