### ISSUE TITLE
Use native promises with Babel 6

### ISSUE THREAD

**Issue by andersekdahl** [babel/babel-loader#182]
Hi!
I would like to turn off the `core-js` transform for Promise. We detect if the `Promise` global exists before loading the main bundle, and if it doesn't we load a polyfill first which exposes the `Promise` global. So our main bundle can be certain that the `Promise` global exists.

I've noticed that if I write `new Promise()` it gets picked up and the `core-js` polyfill for `Promise` is included in the main bundle. If I instead use `new window.Promise` it's not included, which is what I want, but I don't want to have to remember to reference it via `window`.

Is this possible?

**Comment by gbrassey** [comment]
+1 for blacklisting polyfills

**Comment by Couto** [comment]
Honestly I believe that is a responsibility of babel-core itself.
(Re-open if you feel otherwise)
