### ISSUE TITLE
Question about WebPack's async require pattern and 6to5...

### ISSUE THREAD

**Issue by jsg2021** [babel/babel-loader#19]
Could this example from WebPack's homepage:
```js
function loadTemplateAsync(name, callback) {
	require(["./templates/" + name + ".jade"], 
	  function(templateBundle) {
		templateBundle(callback);
	});
}
```

be written with es6 `System.import`?

like:
```es6
System.import("./some/module")
	.then(module=> doSomething(module))
	.catch(error=>...);
```

**Comment by sebmck** [comment]
Most likely. The [SystemJS](https://github.com/systemjs/systemjs) repo would probably be a better place to ask.

**Comment by jsg2021** [comment]
Hmm, I wouldn't be opposed to using SystemJS for async modules... so long as I could get the end-point built and exported to that path. 

Thanks.
