### ISSUE TITLE
webpack loader option for decorators

### ISSUE THREAD

**Issue by darul75** [babel/babel-loader#191]
hi,

I wonder how to make this loader aware of babel-plugin-syntax-decorators

```javascript
{ test: /\.js?$/, loaders: ['react-hot', 'babel?presets[]=react,presets[]=es2015'], exclude: /(node_modules|__tests__)/ },
```

Does it sound good ?

```javascript
{ test: /\.js?$/, loaders: ['react-hot', 'babel?presets[]=react,presets[]=es2015,plugins[]=syntax-decorators'], exclude: /(node_modules|__tests__)/ },
```

thx,

jul

**Comment by darul75** [comment]
Does it sound good ?

{ test: /\.js?$/, loaders: ['react-hot', 'babel?presets[]=react,presets[]=es2015,plugins[]=syntax-decorators'], exclude: /(node_modules|__tests__)/ },

**Comment by bebraw** [comment]
Looks good to me. It may be preferable to go through `.babelrc`, though.

You will probably want to enable [babel-plugin-transform-decorators-legacy](https://www.npmjs.com/package/babel-plugin-transform-decorators-legacy) as well to get the behavior you want.

**Comment by darul75** [comment]
Thanks, I had some issue because current babel6 status was not very clear about decorators implementation, I do not remember but I guess my solution was to use legacy dependency too.
