### ISSUE TITLE
I can't resolve plugin paths in babel 6

### ISSUE THREAD

**Issue by dschissler** [babel/babel-loader#196]
I'm not sure if this is a `babel` or `babel-loader` issue.  I can't resolve the plugin paths or preset paths.  This is my project structure:

* app
  * webpack
    * entries
    * commons
    * modules
* dev
  * gulpfile.js
  * node_modules
  * bower_components
  * vendor

**Comment by dschissler** [comment]
```javascript
    loaders: [{
      test: /\.js?$/,
      loader: 'babel',
      exclude: /(node_modules|bower_components)/,
      query: {
        cacheDirectory: '/tmp',
        // plugins: ['transform-runtime'],
        presets: ['es2015', 'stage-0']
        // presets: [
        //   require('babel-preset-es2015'),
        //   require('babel-preset-stage-0')
        // ]
      }
    }, {
```

**Comment by bebraw** [comment]
Can you set up a standalone project to try out? Just tried a similar configuration without any hickups.

**Comment by dschissler** [comment]
My proprietary project is based on my open source [Webird](https://github.com/perchlayer/webird) system.  I won't be able to play with that for a few weeks.

Here are some highlights from the webpack config.  Notice that its using mostly absolute paths.

```javascript
    context: webpackRoot,
   ...
    resolve: {
         root: [appModulesRoot, bowerRoot, nodeModulesRoot, themeRoot],
         modulesDirectories: [appModulesRoot, 'node_modules', 'bower_components'],
         ...
    },
    resolveLoader: {
        root: nodeModulesRoot
    },
```

**Comment by bebraw** [comment]
@dschissler I think https://github.com/babel/babel-loader/issues/166 might be related to this. If you look that up, you can see a suggested hack (`require.resolve` each preset).

**Comment by dschissler** [comment]
@bebraw thanks.  I'm trying it again now.

**Comment by bebraw** [comment]
@dschissler Ok. If you think this is duplicate of #166, feel free to close.

**Comment by dschissler** [comment]
It does appear to be a duplicate but now I'm working through some other issues.  I'll probably close this once I figure it out.

**Comment by dschissler** [comment]
@bebraw Now I'm having issues with the Bluebird Promise polyfill:

```javascript
'use strict';
// import bluebird from 'bluebird';
import 'whatwg-fetch';

// Setup Bluebird Promise polyfill for Babel
if (!window.Promise) {
//  require('babel-runtime/core-js/promise').default = require('bluebird');
  require('babel-runtime/core-js/promise').default = require.resolve('bluebird');
}
```

I'm finally running JS on my front end though so safe to say its a dupe.  Thanks.

**Comment by bebraw** [comment]
@dschissler Ok. Maybe someone in the Bluebird project has some idea about that. Hard to say what's wrong with that. No doubt something changed with Babel 6. :smile:

**Comment by dschissler** [comment]
@bebraw It is also breaking the gettext translation that I need for my nunjucks template.  If I remove bluebird polyfill setup and the calls like `{{ t('message') }}` in my templates then it all works.  That is pretty good.  I suspect that they are related so I'll see if I can solve it.
