### ISSUE TITLE
babel-loader package.json missing dependency babel-core

### ISSUE THREAD

**Issue by mrbinky3000** [babel/babel-loader#200]
babel-core is listed as a peer dependency in the package.json file.  I though peer dependencies are deprecated and are no longer installed.  Perhaps make this a regular dependency?  Using npm version 3.3.9 on OSX.

**Comment by Couto** [comment]
peer dependencies are not deprecated. 
They are just not installed automatically, and that's the point.
It should be your responsibility as a developer to figure out which version of babel-core do you want to install, I know that for most folks is just the latest but that might not be always the case :)
