### ISSUE TITLE
_angular2.default.module is not a function

### ISSUE THREAD

**Issue by aneurysmjs** [babel/babel-loader#201]
this issue came from webpack but is related with babel in the new way it exports modules and the es6 module syntax

hi there, I having this annoying issue, I'm working on a huge app, and mostly of its packages are from npm and that's pretty cool :) the problem is that there are some packages only available on bower so I have to setup webpack to use bower as is in the documentation by using resolve and the webpack.ResolverPlugin.

here is my webpack.config.js file

``` javascript
var path = require('path'),
      webpack = require('webpack');

var config = {
   //context: __dirname + '/client/app/app.js',
   devtool: 'source-map',
   stats: {
      colors: true,
      reasons: true
   },
   entry: [
      'babel-polyfill',
      './client/crm/crm.js',
      './client/crm/assets/stylus/styles.styl'
   ],
   output: {
      path: __dirname + '/client/build',
      publicPath: 'http://localhost:1989/assets/',
      filename: 'bundle.js'
   },
   resolve: {
      modulesDirectories: ['node_modules', 'bower_components']
   },
   module: {
      preLoaders: [{test: /\.js$/, loader: 'jshint-loader', exclude: /node_modules/}],
      loaders: [
         {
            test: /\.js$/,
            loader: 'babel',
            exclude: [
               path.resolve(__dirname, 'node_modules')
            ],
            // Options to configure babel with
            query: {
               plugins: ['transform-runtime'],
               presets: ['es2015', 'stage-0']
            }
         },
         {test: /\.html$/, loader: 'html', exclude: /node_modules/},
         {test: /\.css$/,  loader: 'style!css', exclude: /node_modules/},
         {test: /\.styl$/, loader: 'style!css!stylus', exclude: /node_modules/},
         {test: /\.png/,   loader: 'url?limit=100000&mimetype=image/png' },
         {test: /\.jpg/,   loader: 'file-loader' },
         {test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url-loader'},
         {test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url-loader' }
      ]
   },
   plugins: [
      new webpack.ResolverPlugin(
         new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin('bower.json', ['main'])
      )
   ]
};

if (process.env.NODE_ENV === 'production') {
   config.output.path = __dirname + '/dist';
   config.plugins.push(new webpack.optimize.UglifyJsPlugin());
   config.devtool = 'source-map';
}

module.exports = config;
```

and it loads the bower package that I need.

![load](https://cloud.githubusercontent.com/assets/4050205/12250149/d752963a-b892-11e5-96e1-aad7504c1f11.png)

but I got this error when run the app.

![angular-module](https://cloud.githubusercontent.com/assets/4050205/12250167/e7763346-b892-11e5-8b22-671b2f1f36d0.png)

Uncaught TypeError: _angular2.default.module is not a function

this is were the error points

![login](https://cloud.githubusercontent.com/assets/4050205/12250267/a96359ca-b893-11e5-99e6-a04bcb2d9d6d.png)

but if I remove the plugin

``` javascript
 new webpack.ResolverPlugin(
         new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin('bower.json', ['main'])
      )
```

everything runs normally but doesn't load the bower package I need 

hope you someone can help me, my boss will kill if I can't get this working, thanks for your attention

**Comment by Couto** [comment]
It might be a problem of the way that the package itself exports its code.
Is it possible to share the smallest possible case with the problem? (Small project just with the required files?)

**Comment by blackendstudios** [comment]
@Couto ok ok ok, sorry for the delay, I'll let you know when the repo is ready to check the case ok?

**Comment by blackendstudios** [comment]
@Couto heres the project example 
https://github.com/blackendstudios/_angular2.default.module-is-not-a-function_issue

:)

**Comment by blackendstudios** [comment]
well, this is pretty critic to me, I was trying to optimize the bundle by letting webpack to use the minified versions of the dependencies in development to make the rebundling go as fast as possible.

```javascript
var path = require('path'),
    webpack = require('webpack'),
    node_modules = path.resolve(__dirname, 'node_modules'),
    pathToAngular = path.resolve(node_modules, 'angular/angular.min.js'),
    pathToAngularAnimate = path.resolve(node_modules, 'angular-animate/angular-animate.min.js'),
    pathToAngularAria = path.resolve(node_modules, 'angular-aria/angular-aria.min.js'),
    pathToAngularHighlightjs = path.resolve(node_modules, 'angular-highlightjs/build/angular-highlightjs.min.js'),
    pathToAngularJwt = path.resolve(node_modules, 'angular-jwt/dist/angular-jwt.min.js'),
    pathToAngularSanitize = path.resolve(node_modules, 'angular-sanitize/angular-sanitize.min.js'),
    pathToAngularUiRouter = path.resolve(node_modules, 'angular-ui-router/build/angular-ui-router.min.js'),
    pathToBootstrap = path.resolve(node_modules, 'bootstrap/dist/js/bootstrap.min.js');

var config = {
   context: __dirname,
   devtool: 'source-map',
   entry: {
      main: [
         'babel-polyfill',
         './client/crm/crm.js',
         './client/crm/assets/stylus/styles.styl'
      ],
      vendors: [
         'angular',
         'angular-animate',
         'angular-aria',
         'angular-highlightjs',
         'angular-jwt',
         'angular-sanitize',
         'angular-ui-bootstrap',
         'angular-ui-router',
         'bootstrap',
         'core-js'
      ]
   },
   resolve: {
      alias: {
         'angular': pathToAngular,
         'angular-animate': pathToAngularAnimate,
         'angular-aria': pathToAngularAria,
         'angular-highlightjs': pathToAngularHighlightjs,
         'angular-jwt': pathToAngularJwt,
         'angular-sanitize': pathToAngularSanitize,
         'angular-ui-router': pathToAngularUiRouter,
         'bootstrap': pathToBootstrap
      }
   },
   output: {
      path: __dirname + '/client/build',
      publicPath: '/',
      filename: 'bundle.js'
   },
   module: {
      preLoaders: [{test: /\.js$/, loader: 'jshint-loader', exclude: /node_modules/}],
      loaders: [
         {
            test: /\.js$/,
            loader: 'babel',
            exclude: [
               path.resolve(__dirname, 'node_modules')
            ],
            // Options to configure babel with
            query: {
               cacheDirectory: true,
               plugins: ['transform-runtime'],
               presets: ['es2015', 'stage-2']
            }
         },
         {test: /\.html$/, loader: 'html', exclude: /node_modules/},
         {test: /\.css$/,  loader: 'style!css', exclude: /node_modules/},
         {test: /\.styl$/, loader: 'style!css!stylus', exclude: /node_modules/},
         {test: /\.png/,   loader: 'url?limit=100000&mimetype=image/png' },
         {test: /\.jpg/,   loader: 'file-loader' },
         {test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url-loader'},
         {test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url-loader' }
      ],
      noParse: [
         pathToAngular,
         pathToAngularAnimate,
         pathToAngularAria,
         pathToAngularHighlightjs,
         pathToAngularJwt,
         pathToAngularSanitize,
         pathToAngularUiRouter,
         pathToBootstrap
      ]
   },
   plugins: [
      new webpack.optimize.CommonsChunkPlugin('vendors', 'vendors.js'),
      new webpack.optimize.DedupePlugin(),
      new webpack.optimize.OccurenceOrderPlugin(),
      new webpack.optimize.LimitChunkCountPlugin({maxChunks: 10}),
      new webpack.optimize.MinChunkSizePlugin({minChunkSize: 3000})
   ]
};

if (process.env.NODE_ENV === 'production') {
   config.output.path = __dirname + '/dist';
   config.plugins.push(new webpack.optimize.UglifyJsPlugin());
   config.devtool = 'source-map';
}

module.exports = config;
```
the result is pretty

![bundle](https://cloud.githubusercontent.com/assets/4050205/12531709/ab5cdc70-c1cf-11e5-9927-1dc5804d2582.png)


but when I run the app, I got Uncaught TypeError: _angular2.default.module.

![bug](https://cloud.githubusercontent.com/assets/4050205/12531721/00ab3dfc-c1d0-11e5-9ffe-9272c5096980.png)


why this happens only when I use functionality that I need from webpack?

the app that I'm working on is hugeeeee, it takes like 20sec to bundle, but when I optimize It only takes 9sec

**Comment by leandroh** [comment]
I've got the same error here.

**Comment by loganfsmyth** [comment]
Hey everyone,
This is expected behavior. Angular expects to be global in the case of `bower`, so you'd load it up front and then use the `angular` global. It does not export anything, so there is no `.default` because there is nothing exported.

When using `angular` from `npm`, it uses an `index.js` file that does
```
require('./angular');
module.exports = angular;
```

which will load the global and then also nicely export it for you. Unfortunately, that means doing

```
require('angular/angular');
```
will not work, because it creates the global without exporting anything, and then same applies to

```
require('angular/angular.min');
```

If you use angular, you'd probably be best of having an entry point that loads it up front, and then use the global `angular` variable instead of importing it.

**Comment by zaenk** [comment]
_My comment might be a bit off-topic, but this is the most comprehensive bug report I found on this issue._

In my case, I started with `node_modules` only, but there were some dependencies that did not play nicely (e.g.: scoped dependencies from npm could not be resolved through Nexus proxy repository), so I used them as bower components.

But, if I understand well, I can't load modules from `node_modules` normally and in the same time load some components from bower with the resolve plugin, even if my configuration is:

```js
moduel.exports = { /*...*/
   resolve: {
      modulesDirectories: ['node_modules', 'bower_components']
   },
   plugins: [
      new webpack.ResolverPlugin(
         new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin('bower.json', ['main'])
      )
   ]
};
```

The resolve plugin not just extends the existing module resolution, but replaces it completely (at least with the configuration above, which is just a copy-paste from the webpack docs)?

_PS.: I ended up removing `bower_components` from `moduleDirectories`, `ResolverPlugin` from plugins and importing bower components by relative paths (with imports loader or script loader where needed)_

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babel-loader. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.
