### ISSUE TITLE
global is not defined with Babel 6

### ISSUE THREAD

**Issue by hoodsy** [babel/babel-loader#202]
Since upgrading to babel 6, my build compiles but errors in the browser:
```
Uncaught ReferenceError: global is not defined
(anonymous function)	@	SetCache.js?9507:5
```

I've followed the babel 6 upgrade guide, and things seem to be working out - until running in the browser.

**.babelrc**
```json
{
  "presets": [
    "es2015",
    "stage-0",
    "react"
  ]
}
```

**webpack config**
```javascript
var path = require('path')
var webpack = require('webpack')

var config = {
  devtool: 'cheap-module-eval-source-map',
  target: 'node',
  entry: [
    'webpack-hot-middleware/client',
    './client/index'
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/static/'
  },
  plugins: [
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new webpack.DefinePlugin(
      {
        'process.env.NODE_ENV': '"development"',
        'global.GENTLY': false
      }
    ),
  ],
  module: {
    loaders: [
      { test: /\.json$/, loaders: ['json'], },
      { test: /\.js$/,  loader: 'eslint', exclude: /node_modules/ },
      { test: /\.js$/,  loader: 'babel', exclude: /node_modules/ },
    ]
  },
  // build breaks on eslint without this workaround
  // https://github.com/MoOx/eslint-loader/issues/23
  eslint: {
    emitWarning: true
  },
  node: {
    __dirname: true,
  },
}
```

**Comment by Couto** [comment]
Looking at your configuration, it doesn't look like it's a babel-loader problem, however since you're familiar with the code, could you explain why you think is a babel problem? =\

**Comment by hoodsy** [comment]
It began happening after I upgraded to Babel 6, and I haven't been able to
find many related issues out there. The only thing that changed about my
build was the Babel config.

That being said, maybe I should open an issue with webpack.

**Comment by mmahalwy** [comment]
@hoodsy did you fix this?

**Comment by hoodsy** [comment]
Yes, by adding an alias to redux-devtools (v3).

**Comment by gaearon** [comment]
What is the full filename of `SetCache.js` compared to your project? Are you 100% confident you are not transpiling third party code (such as Lodash) with Babel?

**Comment by hoodsy** [comment]
@gaearon I exclude node_modules in my loaders, but I can't say I'm 100% confident, as I can't reproduce the issue.

**Comment by gaearon** [comment]
Let’s close then. If you find a way to repro please let us know.

**Comment by seancolyer** [comment]
Just as a posterity comment in case any one else comes across this in the future. I ran across a very similar issue in one of the projects I was working on due to the implicit addition of `'use strict';` to the top of files from using babel/babel-loader.

If you are lazily writing to the global space (and yes, you shouldn't), you might hit undefined cases for code that otherwise works with webpack.

**Comment by gravitypersists** [comment]
the future is not too far off @seancolyer - I've been banging my head on this, I was just happy to randomly see a new comment after frantically reading through this issue for the fifteenth time in the last two days. Seems to be related to https://github.com/webpack/webpack/issues/1963
