### ISSUE TITLE
the 'exclude' option avabile in CLI ?

### ISSUE THREAD

**Issue by LuoZijun** [babel/babel-loader#203]
hi, guys:

in webpack config json file:

```js
{
"test": /\.js?$/, loader: 'babel', 
"query": { presets: ['es2015', 'react', 'stage-0', 'stage-1', 'stage-2', 'stage-3'] },
"exclude": /node_modules/,
}
```

in CLI:

```bash
webpack --entry=app.js --output-file=build.js \
    --module-bind "js=babel?presets[]=react,presets[]=es2015,presets[]=stage-0,presets[]=stage-1,presets[]=stage-2,presets[]=stage-3" \
    --progress --colors
```

How can i add `exclude` option in CLI ?
thx.

**Comment by loganfsmyth** [comment]
`exclude` is a webpack feature, not a babel-loader one. The webpack cli has limits, why not stick with the json config? I have no idea if webpack supports this on the cli, asking in their support channel seems best.

**Comment by LuoZijun** [comment]
@loganfsmyth thx.
