### ISSUE TITLE
Reliance on symbol `React` when loading JSX?

### ISSUE THREAD

**Issue by ChrisRus** [babel/babel-loader#204]
Blundering my way out of the zone of ignorance after some time away (updating from jsx-loader) and pounding out a current baseline build for React projects. For whatever reason, I've gotten into the habit of CAPITALIZING module names and note curiously:

```JavaScript
const React = require('react');
const ReactDOM = require('react-dom');

var rootComponent = React.createClass({
render: function() {
return (<html><head><title>Test</title></head><body>Test</body></html>);
}
});

module.exports = rootComponent;
```

... loads w/out error. However, if I capitalize REACT:

```JavaScript
var REACT  = require('require');
```

... then 

```
ERROR in ReferenceError: React is not defined
    at Object.<anonymous> (bundle.js:19667:22)
    at __webpack_require__ (bundle.js:30:30)
    at Object.<anonymous> (bundle.js:61:22)
    at __webpack_require__ (bundle.js:30:30)
    at bundle.js:50:18
    at bundle.js:53:10
    at webpackUniversalModuleDefinition (bundle.js:3:20)
    at bundle.js:10:3
    at ContextifyScript.Script.runInNewContext (vm.js:18:15)
    at module.exports (/home/cdr/code/ChrisRus/WEB_master/node_modules/eval/eval.js:62:12)
```

No big thing but somewhat odd. Without looking into it my guess is that my lack of observance for normal naming convention (REACT vs React) has exposed some code path the presumes too much?

Edit: Actually, this issue may track back into some preset modules? I'm just figuring this stuff out again. FWIW:

```JavaScript
  "devDependencies": {
    "babel": "^6.3.26",
    "babel-core": "^6.4.5",
    "babel-loader": "^6.2.1",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "react": "^0.14.6",
    "react-dom": "^0.14.6",
    "static-site-generator-webpack-plugin": "^2.0.1",
    "webpack": "^1.12.11",
    "webpack-dev-server": "^1.14.1"
  }
```

Thanks, C

**Comment by rikbrowning** [comment]
When updating to "REACT" did you also update the React.createClass to be REACT.createClass?

**Comment by ChrisRus** [comment]
Hmm. I'll go see. Thanks - it's so obvious it's actually possible!

**Comment by gaearon** [comment]
Please provide specific code reproducing the issue, if any. I don’t see capitalization you are referring to in your example. Neither React nor Babel cares how you call your imports, as long as you reference them in the code by the same names. Closing as doesn’t appear a real issue but please feel free to post reproducing code if you are sure something is wrong.

**Comment by ChrisRus** [comment]
thank you @gaearon - this was indeed my error. sorry for the noise.
