### ISSUE TITLE
babel-loader does not support Webpack 2

### ISSUE THREAD

**Issue by dschissler** [babel/babel-loader#206]
The package.json file needs to be updated to allow Webpack 2 beta.

**Comment by arturparkhisenko** [comment]
:+1:

**Comment by Couto** [comment]
I currently (at least until the next weekend) don't have the time to properly dev/test this.
Could you guys provide a PR and explore what kind of work has to be done to make the loader work with Webpack 2? Thanks :)

**Comment by dschissler** [comment]
I have a feeling that it is compatible and just differs in that it provides
extra ES6 features and drops node 0.10 support.  I could be wrong though.

**Comment by ryanhiebert** [comment]
I know very little about this, but it seems to work. I upgraded to webpack 2, and everything seemed to work, including this package, webpack-dev-server, and webpack-dev-middleware, though npm complained about them.

**Comment by dschissler** [comment]
I'm getting several complaints from various loaders and so I'm just trying to get the packages upgraded until whatever is blocking me is resolved.

**Comment by twhitbeck** [comment]
Indeed, everything seems to work just fine with `webpack@2.0.5-beta`. `package.json` should just be updated so that newer version of webpack satisfies the peerDependency, so that npm doesn't yell `UNMET PEER DEPENDENCY`

**Comment by piecyk** [comment]
:+1:

**Comment by twhitbeck** [comment]
Then again, webpack2 is still in beta, this change isn't necessary to use `babel-loader` with webpack2, and usage with webpack2 should be thoroughly tested before the project states support for it. I retract my recommendation for now.

**Comment by dignifiedquire** [comment]
I'm happy to do a PR maybe this could be just published as beta as well, but it's really problematic when npm peer dependencies are unhappy as this stops shrinkwrap from happening.

**Comment by gaearon** [comment]
https://github.com/babel/babel-loader/pull/208

**Comment by Couto** [comment]
This has landed on master thanks to @gaearon 
I'm going to close the issue, however feel free to open if problems arise.
