### ISSUE TITLE
Webpack watch mode with babel-loader works only when new line is added

### ISSUE THREAD

**Issue by kiranps** [babel/babel-loader#209]
while using babel-loader with webpack watch mode changes made in a single line are not detected. if add another line watch mode works. webpack-dev-server do not have this issue it detects changes made in single line

code
[https://github.com/kiranps/ES6-Starter.git](https://github.com/kiranps/ES6-Starter.git)

**Comment by Couto** [comment]
This is hardly a babel-loader problem.
You should report this in the [webpack](https://github.com/webpack/)'s issue tracker ;)
