### ISSUE TITLE
babel-preset-react presence in npm install command

### ISSUE THREAD

**Issue by zachlysobey** [babel/babel-loader#213]
In the README, the following line references `babel-preset-react` as though its required for this module. I can see some people possibly just blindly cut/pasting it, so maybe it makes sense to leave that off?

> `npm install babel-loader babel-core babel-preset-es2015 babel-preset-react --save-dev`

A bit of a nitpick, I know, but more than happy to do the PR if you think this makes sense to change

**Comment by Couto** [comment]
Kick a PR with the changes! It's more than welcome ;)

**Comment by hzoo** [comment]
@Ghirro got it!
