### ISSUE TITLE
Custom transformer and es2015 preset

### ISSUE THREAD

**Issue by finom** [babel/babel-loader#217]
I'm trying to use custom CJS transformer as a plugin:

```js
loaders: [{
	test: /.js?$/,
	loader: 'babel-loader',
	exclude: /node_modules/,
	query: {
		presets: ['es2015'],
		plugins: ['transform-es2015-modules-simple-commonjs']
	}
}
```

Usually a transformer listed in plugins overrides (eg. uses plugins from "plugins" before plugins from "presets") ``transform-es2015-modules-commonjs`` by itself (command line + .babelrc). But webpack uses ``transform-es2015-modules-commonjs`` anyway. What could be a reason of this behavior? What can I do (don't want to create custom preset or list all needed plugins used by es2015)?

Thanks.

**Comment by hzoo** [comment]
There is no way of doing that at the moment. You just get the preset (no overriding) - right now you'll have to either list the plugins you want or use a preset someone already created if you don't want to make one.

We are working on an idea of this in https://github.com/babel/babel/pull/3331
