### ISSUE TITLE
Module parse failed for ES2015 Class

### ISSUE THREAD

**Issue by RevillWeb** [babel/babel-loader#222]
Hi,

I'm trying to bundle a simple ES2015 web app and I am receiving the following error:

> ERROR in ./~/rebel-router/src/rebel-router.js
> Module parse failed: /home/leon/Code/webpack-test/node_modules/rebel-router/src/rebel-router.js Line 17: Unexpected token
> You may need an appropriate loader to handle this file type.
> | }
> | 
> | export class RebelRouter extends HTMLElement {
> |     attachedCallback() {
> |         this.createShadowRoot();
>  @ ./src/app.js 3:19-78

My configuration file is as follows:

```
module.exports = {
    context: __dirname,
    entry: "./src/app.js",
    output: {
        path: __dirname + "/dist",
        filename: "bundle.js"
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                loader: 'babel-loader',
                query: {
                    presets: ['es2015']
                }
            }
        ]
    }
};
```

I have created a sample repository to demonstrate the issue available here: https://github.com/RevillWeb/webpack-test.git

I've gone through all the documentation and as far as I can tell I am doing everything correctly. The RebelRouter class transpiles perfectly fine with babel alone - any help would be greatly appreciated!

Thank you.

**Comment by loganfsmyth** [comment]
Path: `/home/leon/Code/webpack-test/node_modules/rebel-router/src/rebel-router.js` 
vs: `exclude: /node_modules/,`

You have an untranspiled ES6 file in your `node_modules` but you have configured your loader to ignore `node_modules`.

**Comment by RevillWeb** [comment]
Omg, idiot award. Thank you! (Teach me to try this so early in the morning)
