### ISSUE TITLE
 UNMET PEER DEPENDENCY webpack@1 || ^2.1.0-beta

### ISSUE THREAD

**Issue by sudanvellakovilkanakavel** [babel/babel-loader#225]
Hi,

I am getting the following error when i  try to install

CJBTDLDD0003:reactApp kanaks$ install babel-loader

I am in the process of setting up environment for React  JS

I am new to Node & React. Kindly help.

**Comment by loganfsmyth** [comment]
Sounds like you're installing this Babel webpack loader but have not installed webpack itself. That is what this error means.

**Comment by sudanvellakovilkanakavel** [comment]
Hi thanks for your replay .
Error is exactly the same as you told.
 In addition my webpack  is installed in another path (but globally only). then I used npm config set prefix ~/.npm-global and  npm install -g babel webpack webpack webpack-dev-server and fixed the error.
