### ISSUE TITLE
[BABEL] Note: The code generator has deoptimised the styling of {file} as it exceeds the max of "100KB".

### ISSUE THREAD

**Issue by ApurvaB** [babel/babel-loader#227]
Hi , I am getting error as Using following config 
[BABEL] Note: The code generator has deoptimised the styling of {file} as it exceeds the max of "100KB".
``````````
const JS_LOADER = {
  test: /.jsx?$/,
  include: [
    path.resolve(__dirname, '../src'),
  ],
  exclude: /(node_modules|bower_components)/,
  loader: 'babel',
  query: {compact : false}
};
```````

**Comment by IsuruDilhan** [comment]
In react/redux/webpack/babel build fixed this error by removing script tag type text/babel

`<script type="text/babel" src="/js/bundle.js"></script>`

Into
`<script src="/js/bundle.js"></script>`
