### ISSUE TITLE
Cannot use jsx spread attribute in es5 with babel loader

### ISSUE THREAD

**Issue by TylerYang** [babel/babel-loader#229]
Hi guys, I was trying to use the spread attribute in jsx with es5.
Below is what my codes look like,
```javascript
render() {
    var props = this.props;
    return (
         <button onClick={this.handleClick} {...props}></button>
    );
}
```
When I try to use the `babel-loader` to compile, I always get the error info below.

```output
/app/components/Button/index.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import _extends from 'babel-runtime/helpers/extends';
| var React = require('react');
| require('./Button.scss');
 @ ./app/pages/App/index.js 6:10-44
```

Here is my package.json.
```
"devDependencies": {
    "babel": "^6.5.2",
    "babel-core": "^6.7.2",
    "babel-eslint": "^5.0.0",
    "babel-loader": "^6.2.4",
    "babel-plugin-transform-react-jsx": "^6.7.4",
    "babel-plugin-transform-runtime": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-runtime": "^6.6.1",
    "console-stamp": "^0.2.0",
    "css-loader": "^0.23.1",
    "eslint": "^2.3.0",
    "eslint-config-airbnb": "^6.1.0",
    "eslint-loader": "^1.3.0",
    "eslint-plugin-flow-vars": "^0.2.1",
    "eslint-plugin-react": "^4.2.1",
    "html-webpack-plugin": "^2.10.0",
    "image-webpack-loader": "^1.6.3",
    "json-loader": "^0.5.4",
    "node-sass": "^3.4.2",
    "sass-loader": "^3.1.2",
    "style-loader": "^0.13.0",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.14",
    "webpack-dev-server": "^1.14.1"
  }

```

And I cannot get any info in the document is talking about this. (helper, extends) 

Any ideas? Thx.

----update

The interesting thing is when I try to compile my sample code in [babel online](http://babeljs.io/repl/#?evaluate=true&presets=react&code=var%20el%20%3D%20React.createClass(%7B%0A%20%20render%3A%20function()%7B%0A%20%20%20%20var%20props%20%3D%20this.props%3B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3Cbutton%20%7B...props%7D%3EWow%3C%2Fbutton%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D)%3B)

It will auto inject the `_extend` helper into my code. So I add `var _extends = require('babel-runtime/helpers/_extends')` into my module. 

Then this output became this,
```output
/app/components/Button/index.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import _extends2 from 'babel-runtime/helpers/extends';
| var _extends = require('babel-runtime/helpers/extends');
| var React = require('react');
 @ ./app/pages/App/index.js 6:10-44
```
So what can I do? 
Besides, I am now update my code in the below way, it works (because babel don't need to use the _extend method)

```javascript
var extends = require('babel-runtime/helpers/extends');
var Whatever = React.createClass({
    render() {
        var props = _extend({}, this.props, {onClick: this.handleClick});

        return (
            <button {...props}></button>
        );
    }
})
```

**Comment by loganfsmyth** [comment]
You can't use transform-runtime without one of the module plugins or the general es2015 preset.

**Comment by TylerYang** [comment]
Oh, just install the `babel-plugin-transform-object-assign`  and add it to my webpack config. It's working now. Thx. 

   ```
 loaders: [{
     test: /\.js?/,
     exclude: /node_modules/,
     loader: 'babel-loader',
     query: {
         presets: ['react'],
         plugins: ['transform-object-assign', 'transform-runtime']
      }
 }],
```
