### ISSUE TITLE
AbortOnError not working?!?!?

### ISSUE THREAD

**Issue by husterk** [babel/babel-loader#233]
I am trying to force my webpack build to fail if the schema validation step fails. I have tried the following configuration which does not seem to work. I can see the schema validation error logged to the console but I can't get the Webpack build to fail when this happens. Is there another approach that I should be using?

**Webpack Config for using Babel-Loader**

```
{
  test: /\.(js|jsx)$/,
  exclude: /node_modules/,
  loaders: [
    'react-hot',
    'babel?plugins[]=' + path.join(__dirname, '../Relay/BabelRelayPlugin')
  ]
}
```

**BabelRelayPlugin Config**

```
var getbabelRelayPlugin = require('babel-relay-plugin');
var schema = require('./Schema.json');

module.exports = getbabelRelayPlugin(
  schema.data,
  {
    abortOnError: true
  });
```

I have seen on the [(Babel Relay Plugin)](https://facebook.github.io/relay/docs/guides-babel-plugin.html) documentation page that there is a `{enforceSchema: true}` option but I can't seem to get this to work either.

**Comment by JesperKihlberg** [comment]
Did you succeed?

**Comment by husterk** [comment]
No. To the best of my knowledge this issue still exists.

**Comment by danez** [comment]
I couldn't find any reference to abortOnError in the relay documentation. Also does not seem to be related to babel-loader.
