### ISSUE TITLE
Why delete options.cacheDirectory?

### ISSUE THREAD

**Issue by wied03** [babel/babel-loader#235]
This should be an easy one since I'm new to this, but why do this in index.js?

It's probably because of loader chaining but I don't see where options is passed to anyone else besides babel or the cache module.

**Comment by loganfsmyth** [comment]
Passing options to Babel is the problem. It would throw because of the unknown option.

**Comment by wied03** [comment]
Ahh OK. I was wrong then. Thanks for the clarification.
