### ISSUE TITLE
babel-loader@6.2.4 wants webpack@1 || ^2.1.0-beta

### ISSUE THREAD

**Issue by pke** [babel/babel-loader#239]
And I have webpack 2.1.0-beta.5 installed.

Whats the issue here?

```
npm ERR! peerinvalid The package webpack@2.1.0-beta.5 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer babel-loader@6.2.4 wants webpack@1 || ^2.1.0-beta
npm ERR! peerinvalid Peer webpack-dev-server@2.0.0-beta wants webpack@>=2.0.3-beta <3
```

**Comment by UnsungHero97** [comment]
I'm seeing the same thing, and I've tried `v2.1.0-beta.7`. I thought this was resolved by https://github.com/babel/babel-loader/pull/220.

Can anyone comment on this issue?

**Comment by fgarci03** [comment]
I had the exact same problem installing a project.

What is your version of npm? Mine was 2.15.1, so I updated to 3.9.1 with 'npm install -g npm@next' (I'm using node 4.x so npm 3.x doesn't come by default).

It still issued a warning in this package, but the installation was successful and I haven't had any problems so far.

I'd like to know more about this issue though...

**Comment by UnsungHero97** [comment]
I was able to get around this by changing the peer dependency version for `webpack` to `^2.1.0-beta` in `package.json` for `webpack-dev-server`:

```
"peerDependencies": {
  "webpack": "^2.1.0-beta"
},
```

It's definitely not a solution to the problem, but it unblocked me. Alternatively, since you're trying to use the `webpack` beta, you could try switching to the `webpack-dev-server` beta as well:

```
"webpack-dev-server": "^2.1.0-beta",
```

**Comment by StephanBijzitter** [comment]
Why do we need webpack at all?

I use babel to execute my tests, and nothing more than that.

**Comment by xdissent** [comment]
@StephanBijzitter because it's another configurable level of your build chain that allows for, but goes beyond, babel. I think most people ITT have this kind of configuration and can't simply use babel alone.

**Comment by hzoo** [comment]
This shouldn't be an issue anymore? If you go to https://semver.npmjs.com/ with webpack and what's currently in the package.json `1 || ^2.1.0-beta` it does highlight the betas

**Comment by pke** [comment]
I didn't have time to check it out again yet.

**Comment by d3viant0ne** [comment]
@StephanBijzitter - This is the babel loader for `webpack` if you aren't using webpack then there is no need to use the loader. On the other hand, using the loader without `webpack` isn't going to work, hence the `peerDependency`.
