### ISSUE TITLE
Issue on transpilation es2015 

### ISSUE THREAD

**Issue by wickedrahul** [babel/babel-loader#247]
I'm unable to figure out where why this is unable to be compiled:
render() {
        return (
            <div>Hey There</div>
        );
    }

Relevant package.json:

"dependencies": {
    "babel": "^6.5.2",
    "babel-core": "^6.8.0",
    "babel-loader": "^6.2.4",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-react-html-attrs": "^2.0.0",
    "babel-plugin-transform-class-properties": "^6.8.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "jquery": "^2.2.3",
    "react": "^15.0.2",
    "react-dom": "^15.0.2",
    "webpack": "^1.13.0"
  }

 webpack.config.js:

var debug = process.env.NODE_ENV !== "production";
var webpack = require('webpack');

module.exports = {
  context: __dirname,
  devtool: debug ? "inline-sourcemap" : null,
  entry: "./script.js",
  output: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel-loader',
        query: {
          presets: ['react', 'es2015', 'stage-0'],
          plugins: ['react-html-attrs', 'transform-class-properties', 'transform-decorators-legacy'],
        }
      }
    ],
    path: __dirname + "/js",
    filename: "scripts.min.js"
  },
  plugins: debug ? [] : [
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.optimize.UglifyJsPlugin({ mangle: false, sourcemap: false }),
  ],
};

**Comment by loganfsmyth** [comment]
The snippet you posted isn't valid on its own and you haven't actually told us what isnt working. Please elaborate. Do you get an error or what?

**Comment by wickedrahul** [comment]
@loganfsmyth Hey thanks. I figured out the problem was snippet. I had wrongly put 'loaders' under 'output'  instead of 'module'. Thanks very much anyways.
P.S The error BTW was, "You may need an appropriate loader to handle this file type."
