### ISSUE TITLE
 Only file URLs of the form  allowed running in Node

### ISSUE THREAD

**Issue by aunz** [babel/babel-loader#251]
I have enjoyed using babel-loader with Webpack for a long time and had no trouble. But since yesterday, out of the blue, I stumbled across this error since yesterday and scratching my head crazily.

`Module build failed: Error: Unable to fetch "C:\xxx\node_modules\babel-loader\index.js". Only file URLs of the form  allowed running in Node.
Error loading C:\XXX\node_modules\babel-loader\index.js
 @ multi server`

On Windows 10 64bit
Node 6.2.0 via nvm windows
Webpack@2.1.0-beta.7
babel-loader@6.2.4

Also experienced similar error with url-loader, json-loader
(I have searched and found similar errors with SystemJS, but not babel-loader)

Not sure if this is the appropriate place to post this, but please help!

**Comment by loganfsmyth** [comment]
If it's happening with multiple loaders, it's unlikely to be a `babel-loader` issue. I'd recommend dropping by Webpack's support channel. I unfortunately have no idea what that error message is trying to say.

**Comment by aunz** [comment]
Thanks @loganfsmyth, after many hours of digging, I realised it's `postcss-loader` with `postcss-import`. `postcss-import` version 8.1.1+ has a dependency on jspm which has a dependency on systemjs, which breaks on Windows in this case.

**Comment by koistya** [comment]
@aunz have you found a workaround for this issue?
