### ISSUE TITLE
when i execute gulp appear this Using removed Babel 5 option: base.stage

### ISSUE THREAD

**Issue by CusProjects** [babel/babel-loader#255]
[BABEL] /Users/gibran/Desktop/React-For-Beginners-Starter-Files-master/01 - Introduction - Start Here/scripts/main.js: Using removed Babel 5 option: base.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets while parsing file: /Users/gibran/Desktop/React-For-Beginners-Starter-Files-master/01 - Introduction - Start Here/scripts/main.js

.babelrc
{
  "presets": ["es2015", "react"]
}

package.json

{
  "name": "catch-of-the-day",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "autobind-decorator": "1.3.2",
    "babel-core": "^6.0.0",
    "babel-loader": "^6.0.0",
    "babel-preset-es2015": "^6.0.0",
    "babel-preset-react": "^6.0.0",
    "babel-preset-stage-2": "^6.0.0",
    "babelify": "^7.3.0",
    "browser-sync": "2.9.11",
    "browserify": "11.2.0",
    "connect-history-api-fallback": "1.1.0",
    "firebase": "2.3.1",
    "gulp": "3.9.0",
    "gulp-autoprefixer": "3.1.0",
    "gulp-notify": "2.2.0",
    "gulp-rename": "1.2.2",
    "gulp-stylus": "2.1.0",
    "gulp-uglify": "1.4.2",
    "gulp-util": "3.0.7",
    "history": "1.12.5",
    "install": "0.1.8",
    "re-base": "1.2.1",
    "react": "^15.0.0",
    "react-addons-css-transition-group": "^15.0.0",
    "react-catalyst": "0.3.0",
    "react-dom": "^15.0.0",
    "react-mixin": "3.0.0",
    "react-router": "1.0.0-rc3",
    "vinyl-buffer": "1.0.0",
    "vinyl-source-stream": "1.1.0",
    "watchify": "3.4.0"
  }
}

Please, help...
Regards.

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babel-loader. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.
