### ISSUE TITLE
Webpack  installation failed

### ISSUE THREAD

**Issue by pyprism** [babel/babel-loader#261]
I tried to install babel , webpack and others  using this command
```
npm install --save-dev babel-core babel-loader babel-plugin-transform-decorators-legacy babel-preset-react babel-preset-stage-0 webpack-bundle-tracker babel-preset-es2015-webpack
```
then I got this error
```
npm WARN babel-loader@6.2.4 requires a peer of webpack@1 || ^2.1.0-beta but none was installed.
```
What is the correct way to install webpack 2 with babel-loader ?

**Comment by loganfsmyth** [comment]
The error is telling you you've installed a bunch of Babel-related modules, and modules for connecting Webpack and Babel, but you haven't installed `webpack` itself.
