### ISSUE TITLE
Issue with lerna / babel-loader

### ISSUE THREAD

**Issue by reggi** [babel/babel-loader#262]
I've created a specific repo just for this issue, that shows what's happening.

https://github.com/reggi/webpack-lerna-babel-loader-issue

For some reason when I build the module without babel (using normal `require`) it works perfectly but when I implement `babel-loader`, it's not working.

Here's the stackoverflow post:

http://stackoverflow.com/questions/37947576/issue-with-lerna-webpack

Here's the bundles that are being created:

**Without `babel-loader` excluding `node_modules`**

https://github.com/reggi/webpack-lerna-babel-loader-issue/blob/master/packages/usage/bundle-without-exclude.js#L70

> Cannot find module \"@reggi/beta\"

**With `babel-loader` excluding `node_modules`**

https://github.com/reggi/webpack-lerna-babel-loader-issue/blob/master/packages/usage/bundle-with-exclude.js#L77

> Cannot find module \"/Users/thomasreggi/Desktop/webpack-issue/packages/beta\"

**Without `babel-loader` & switching code to `require`**

https://github.com/reggi/webpack-lerna-babel-loader-issue/blob/master/packages/usage/bundle-without-babel.js#L97

> Includes everything perfectly.

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babel-loader. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.
