### ISSUE TITLE
support setting global option at root of webpack config like eslint

### ISSUE THREAD

**Issue by e-cloud** [babel/babel-loader#265]

**Comment by TuckerWhitehouse** [comment]
Appears to be undocumented, but supported already.

https://github.com/babel/babel-loader/blob/master/index.js#L36
https://github.com/babel/babel-loader/pull/223

**Comment by cesarandreu** [comment]
According to the ["What's new in webpack 2"](https://gist.github.com/sokra/27b24881210b56bbaff7#loader-options--minimize) gist, options are supposed to be passed using the LoaderOptionsPlugin (once webpack 2 is out). So it probably doesn't makes sense to implement this.

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babel-loader. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.
