### ISSUE TITLE
 babel bug ? 

### ISSUE THREAD

**Issue by jun-lu** [babel/babel-loader#268]
````
class abc extends Object{
	a(){
    document.body.innerHTML = "call a()"
	}
}

var a = new abc()
a.a() // error
````

why ? a.a() // error

 code  <http://codepen.io/jun-lu/pen/dXJoPY>

**Comment by zloirock** [comment]
[`babel` does not support extending built-in constructors by default.](https://babeljs.io/docs/usage/caveats/#classes) Also, it's an incorrect place for `babel` issues.

**Comment by jun-lu** [comment]
soga  Thanks
