### ISSUE TITLE
Module import returns error if not in same directory as the importer 

### ISSUE THREAD

**Issue by ashraffayad** [babel/babel-loader#269]
I usw webpack 2.1.0 beta 17. This  section returns the following error
ERROR in ../Spinner/src/Spinner.js
Module parse failed: /components/Spinner/src/Spinner.js Unexpected token

```
import React, { Component } from 'react'
import ImageMixin from './ImageMixin' // works fine
import Spinner from '../../Spinner/src/Spinner.js' // error
```
I move the "Spinner" component to the same level. and it works fine!!

```
import React, { Component } from 'react'
import ImageMixin from './ImageMixin' // works fine
import Spinner from './Spinner.js' // works fine
```
Any idea why? The import path in the first example is correct!

Webpack.config.js
```
const path = require('path')
const webpack = require('webpack')

module.exports = {
    debug: true,
    devtool: 'cheap-module-eval-source-map',
    noInfo: true,
    entry: [
        'webpack-hot-middleware/client?reload=true',
        './src/index'
    ],
    target: 'web', 
    output: {
        path: `${__dirname}/src`,
        publicPath: 'http://localhost:3000/',
        filename: 'bundle.js'
    },
    plugins: require('./tools/dev-plugins'),
    module: {
        loaders: require('./tools/loaders')
    }
}
```
loaders.js
```
const path = require('path')
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const precss = require('precss')

module.exports = [
    {test: /\.js$/, include: path.join(process.cwd(), 'src'), loader: 'babel',
        exclude: /node_modules/,
        query: {
            presets: ['react', 'es2015-native-modules']
        }},
    //{ test: /\.css$/, loaders: ['style-loader', 'css-loader!postcss-loader!resolve-url']},
    //{ test: /\.scss$/, exclude: /node_modules/, loaders: ['style-loader','css-loader?sourceMap!postcss-loader!resolve-url!sass-loader?sourceMap'] },
    // with extract-text-plugin
    { test: /\.css$/, loaders: ExtractTextPlugin.extract('style-loader', 'css-loader?!postcss-loader!resolve-url')},
    { test: /\.scss$/, exclude: /node_modules/, loaders: ExtractTextPlugin.extract('style-loader','css-loader?sourceMap!postcss-loader!resolve-url!sass-loader?sourceMap') },
    { test: /\.(png|jpg|gif)$/, exclude: /node_modules/, loader: 'url-loader', query:{limit:10000,name:'images/[name].[ext]'} },
    { test: /\.(ttf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/, loader : 'file-loader', query:{limit:10000,name:'fonts/[name].[ext]' } }
]
```

dev-plugins.js
```
const webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const ExtractTextPlugin = require('extract-text-webpack-plugin')

module.exports = [
    new webpack.DefinePlugin({
        'process.env.NODE_ENV': JSON.stringify('development'), // Tells React to build in either dev or prod modes. https://facebook.github.io/react/downloads.html (See bottom)
        __DEV__: true
    }),
    new ExtractTextPlugin('styles.css'),
    new webpack.optimize.CommonsChunkPlugin({ name: 'vendor', minChunks: Infinity, filename: 'vendor.js' }),
    new webpack.LoaderOptionsPlugin({ minimize: true, debug: false }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new HtmlWebpackPlugin({     // Create HTML file that includes references to bundled CSS and JS.
        template: __dirname + '/index.ejs',
        minify: {removeComments: true, collapseWhitespace: true},
        inject: true
    })
]

```

**Comment by loganfsmyth** [comment]
Given that you have `include: path.join(process.cwd(), 'src')`, this would entirely depend on the `cwd()` at the time you executed this.

What specifically is your directory structure now and what was it before you moved the file?

**Comment by ashraffayad** [comment]
Sorry, that I have to elaborate on this :). I keep the node_modules directory high up the directory tree, that way I can share it among many projects instead of installing it over and over again. 
in every sub project, I just create a symbolic link to the package.json file. that way I can execute "npm start" from any sub directory.

react-projects/
----package.json
----node_modules/
----components/
--------Spinner/
------------package.json (symlink)
------------src/
----------------index.js
----------------Spinner.js
--------Image/
------------package.json (symlink)
------------src/
----------------index.js
----------------Image.js

The `path.join(process.cwd(), 'src')` always resolves right because I always execute it from within a parent directory of '/src'. Which is 'Image/' in this case.
if the index.js didn't resolve, then I would get the following error instead:
```
ERROR in multi main
Module not found: Error: Can't resolve './src/index' in '/home/ashraf/Desktop/React-Projects/components/Image'
 @ multi main
```
In my case the `components/Image/index.js` resovles fine. and it's able to import `Image.js`
But the` Image.js` is unable to import` ../../Spinner/src/Spinner.js` and I get this error:

```
ERROR in ../Spinner/src/Spinner.js
 // this is a correct path
Module parse failed: /home/ashraf/Desktop/React-Projects/components/Spinner/src/Spinner.js  
Unexpected token (10:8)
You may need an appropriate loader to handle this file type.
| const Spinner = () => {
|     return (
|         <div className="spinner"></div>
|     )
| }
 @ ../Spinner/index.js 1:0-35
 @ ./src/Image.js
 @ ./src/index.js
 @ multi main

```

Sorry for the long explanation :)

**Comment by danez** [comment]
Interesting setup and idea.

Regarding the problem:
By setting `include` for the loader to ` path.join(process.cwd(), 'src')` you are telling the loader to only transpile files in this folder, which does not include `Spinner/src`. And as you have ES2015 code there webpack is not able to parse it. 

What you could try is removing the `include` altogether. Then it should work, BUT you have to carefully check then if the `exclude` is really working, because you don't want to transpile `node_module`s. I have the feeling you might need to use an absolute path in the `exclude` `path.join(__dirname, "../path/to/node_modules"),`.

**Comment by ashraffayad** [comment]
@danez Thanks a million. The problem was 'include' as you said.
