### ISSUE TITLE
Expand and Vet v6.x documentation

### ISSUE THREAD

**Issue by d3viant0ne** [babel/babel-loader#277]
- There are a number of issues related to 6.x changes and the associated documentation that needs to be resolved.
- Better documentation around `.jsx` usage and the `webpack.config.js` for the React folks.
- Should really be extracted into something other than a `README.md`

Relates to #198 
Relates to #212

**Comment by loganfsmyth** [comment]
I think I'm just gonna close this. Someone's welcome to do it, but having the issue doesn't seem that helpful.
