### ISSUE TITLE
Webpack "inline-source-maps" not applied "correctly"

### ISSUE THREAD

**Issue by timse** [babel/babel-loader#284]
according to the README:

> Note: The sourceMap option is ignored, instead sourceMaps are automatically enabled when webpack is configured to use them (via the devtool config option).

source-maps options are taken from Webpack. While this works as far as _source-maps are active_ it does not for inline-source-maps in particular.

while it does fall back to Webpack source-maps in case no source-maps option is set on the loader: https://github.com/babel/babel-loader/blob/master/index.js#L55-L57 this is only a boolean flag, but does not set `inline` in case of `inline-source-maps`.

This can be an issue if babel is not the only loader, but there is e.g. a typescript loader in front which itself produces `inline-source-maps`, because those then get discarded by babel, thus producing errors.

The fix itself is simple: just specify the source-maps options via query-params in the loader `babe-loader?sourceMap=inline`. This is fine, however this should either be documented, the README should be amended, or one could actually check if the `inline-source-map` is active in Webpack and then set `options.sourceMap` to `inline` instead of `true`.

I am happy to make a pull-request. Not sure what solution would be preferred.

**Comment by danez** [comment]
Thanks for the investigation and sorry for the late reply.

What I do not understand yet is why the loaders should care about inlining sourcemaps like the ts-loader is doing it. Isn't that webpacks job? Because the babel-loader receives an inputSourceMap, that another loader might have produced. Could be that this inputSourceMap is somehow ignored somewhere.

**Comment by Marsup** [comment]
@danez My PR seems to fix it, can't guarantee it's THE solution though, maybe someone more knowledgeable about webpack than me will have a better fix.

**Comment by danez** [comment]
@Marsup Thanks, I asked some of the other loader authors, let's see if someone has more insight.

You also use multiple loaders for js?

**Comment by Marsup** [comment]
No, only one.

**Comment by loganfsmyth** [comment]
Normally Webpack is the thing that adds the inline map, rather than the loaders themselves, so changing that part of the logic shouldn't be needed. A reproducible example of the issue you're seeing would be the best next step I think.

**Comment by Marsup** [comment]
I jumped the gun a bit, it's working better, but it's not really working as now the browser is showing me the transpiled version, but at least breakpoints work...

**Comment by danez** [comment]
I'm also currently investigating. We had this issues in my company with babel-loader and webpack for quite some time, but nobody investigated so far.

**Comment by Marsup** [comment]
I'm going to stop hijacking this issue as it seems more and more likely that it's a `source-map` issue, not sure it's so related to this bug anymore.

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babel-loader. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.
