### ISSUE TITLE
Fat Arrow compiling function twice issue

### ISSUE THREAD

**Issue by lynxionxs** [babel/babel-loader#285]
When i use a Fat Arrow as function for object keys webpack compiles it like this...

```javascript

// Before compiling
{
    key1: (arg1) => {
        // ...
    }
}

// After compiling ['es2015']
{
    key1: function key1(arg1) {
         // ...
    }
}
```

Why is "key1" created twice ?
It should compile like

```javascript 
{
    key1: function(arg1) {
        // ...
    }
}
```

**Comment by abouthiroppy** [comment]
This problem is babel core.

Please ask a question in babel.
FYI: https://github.com/babel/babel#looking-for-support

Thanks.

**Comment by danez** [comment]
I think this is done so that stacktraces would show 'key1' and not 'anonymous function'. What is the problem you have with it?

**Comment by loganfsmyth** [comment]
Functions that are anonymous automatically get a name based on where they are declared, so in a real ES6 environment you see

```
var obj = {
    key1: (arg1) => {}
};
console.log(obj.key1.name); // 'key1'
```
that is the behavior being emulated here.

From http://www.ecma-international.org/ecma-262/7.0/#sec-object-initializer-runtime-semantics-propertydefinitionevaluation

> PropertyDefinition:   PropertyName: AssignmentExpression
>  1. Let propKey be the result of evaluating PropertyName.
 1. ReturnIfAbrupt(propKey).
 1. Let exprValueRef be the result of evaluating AssignmentExpression.
 1. Let propValue be ? GetValue(exprValueRef).
 1. If IsAnonymousFunctionDefinition(AssignmentExpression) is true, then
   1. Let hasNameProperty be ? HasOwnProperty(propValue, "name").
   1. If hasNameProperty is false, perform SetFunctionName(propValue, propKey).
 1. Assert: enumerable is true.
 1. Return CreateDataPropertyOrThrow(object, propKey, propValue).

Specifically step 5 assigns names to any anonymous object properties based on the name of the property.
