### ISSUE TITLE
REGRESSION: 6.2.5 includes babelrc even if babelrc: false is specified

### ISSUE THREAD

**Issue by aaronjensen** [babel/babel-loader#290]
**I'm submitting a bug report**

**Webpack Version:**
2.1.0-beta.21

**Babel Core Version**:
6.13.2

**Babel Loader Version**:
6.2.5

**Please tell us about your environment:**
OSX 10.11.6

**Current behavior:**

babel-loader includes my babelrc even if `babelrc: false` is specified in loader options. This is a regression, 6.2.4 worked properly.

**Expected/desired behavior:**

babel-loader would not do this.

I can't get a repro up just yet, but I will try to soon if it is necessary.

This may repro it: Set up https://github.com/sapegin/react-styleguidist and include a `.babelrc` with:

```
      "presets": [
        ["es2015", { "modules": false }],
      ]
```

then try to run the styleguide server.

**Comment by aaronjensen** [comment]
This seems to have been caused by react-styleguidist using a different version. Now that we're both on 6.2.5 this seems to work. Closing.

**Comment by hulkish** [comment]
I'm seeing this same behavior in  `babel-loader@6.3.2`
