### ISSUE TITLE
please give the solution  for 1:2 error Parsing error: Illegal import and export declaration

### ISSUE THREAD

**Issue by chandrasekarb** [babel/babel-loader#295]
ERROR in ./app/src/cmpt/Worldmap/Worldmap.jsx

/home/venkat/Programs/ss/app/src/cmpt/Worldmap/Worldmap.jsx
  1:2  error  Parsing error: Illegal import declaration

✖ 1 problem (1 error, 0 warnings)

ERROR in ./app/src/utils/media.js

/home/venkat/Programs/ss/app/src/utils/media.js
  1:2  error  Parsing error: Illegal export declaration

✖ 1 problem (1 error, 0 warnings)

**Comment by danez** [comment]
Please add more information, we cannot help you if you do not provide enough information.
So we would need at least your babel config, the webpack config and the the sourcecode of these two files.

**Comment by chandrasekarb** [comment]
**webpack config file**

const webpack = require('webpack');

const path = require('path');
const HtmlwebpackPlugin = require('html-webpack-plugin');

const ROOT_PATH = path.resolve(__dirname);
const PROD = process.env.NODE_ENV === 'production';

const env = process.env.NODE_ENV || 'development';

module.exports = {
  devtool: PROD ? '' : 'source-map',
  entry: [
    path.resolve(ROOT_PATH, 'app/src'),
  ],
  module: {
    preLoaders: [
      {
        test: /\.jsx?$/,
        loaders: PROD ? [] : ['eslint'],
        include: path.resolve(ROOT_PATH, 'app'),
      },
    ],
    loaders: [{
      test: /\.jsx?$/,
      exclude: /node_modules/,
      loader: 'react-hot',
    },
    {
      test: /\.jsx?$/,
      exclude: /node_modules/,
      loader: 'babel',
      query: {
        stage: 0,
      },
    },
    {
      test: /\.(png|jpg|svg|gif|eot|woff|woff2|ttf)$/,
      loader: 'file-loader?name=[path][name]-[hash].[ext]',
    }],
  },
  resolve: {
    extensions: ['', '.js', '.jsx', '.scss', '.css'],
    alias: {
      cmpt: path.resolve(ROOT_PATH, 'app/src/cmpt'),
      containers: path.resolve(ROOT_PATH, 'app/src/containers'),
      pages: path.resolve(ROOT_PATH, 'app/src/pages'),
      actions: path.resolve(ROOT_PATH, 'app/src/actions'),
      utils: path.resolve(ROOT_PATH, 'app/src/utils'),
      common: path.resolve(ROOT_PATH, 'common'),
      reducers: path.resolve(ROOT_PATH, 'app/src/reducers'),
      config: path.join(ROOT_PATH, 'config', env),
    },
  },
  output: {
    path: PROD ? path.resolve(ROOT_PATH, 'dist') :
      path.resolve(ROOT_PATH, 'app/build'),
    publicPath: '/',
    filename: 'bundle.js',
  },
  devServer: {
    contentBase: path.resolve(ROOT_PATH, 'dist'),
    historyApiFallback: true,
    hot: true,
    inline: true,
    progress: true,
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new HtmlwebpackPlugin({
      title: 'myapp',
      template: 'index.html',
    }),
  ],
};




**Worldmap.jsx**


import React from 'react';
import WorldMap from 'grommet/components/WorldMap';
import 'grommet/grommet.min.css';

const GrometWorldMap = () => {
  return (
	<WorldMap series={[
	  {
	    "continent": "NorthAmerica",
	    "label": "North America",
	    "value": 40,
	    "colorIndex": "graph-1",
	  },
	  {
	    "continent": "Australia",
	    "label": "Australia",
	    "value": 10,
	    "colorIndex": "graph-4",
	  }]} legend={true} units="B" />

  );
};

export default GrometWorldMap;




**media.js**


export function checkImage(url, callback) {
  const img = new Image();
  img.onerror = img.onabort = function onerror() {
    callback(false);
  };
  img.onload = function onsucces() {
    callback(true);
  };
  img.src = url;
}

export function addHttp(url) {
  const prefix = 'http';
  if (url.substr(0, prefix.length) !== prefix) {
    return 'http://' + url;
  }
  return url;
}





**Error**


ERROR in ./app/src/cmpt/Worldmap/Worldmap.jsx

/home/venkat/Programs/ss/app/src/cmpt/Worldmap/Worldmap.jsx
1:2 error Parsing error: Illegal import declaration

✖ 1 problem (1 error, 0 warnings)

ERROR in ./app/src/utils/media.js

/home/venkat/Programs/ss/app/src/utils/media.js
1:2 error Parsing error: Illegal export declaration

✖ 1 problem (1 error, 0 warnings)

**Comment by loganfsmyth** [comment]
That is an error from eslint, not from babel-loader. Your linter config has likely not enabled support for ES 6 modules.

**Comment by hzoo** [comment]
It would be nice to have a ESLINT: BABEL: for errors

But yeah since it has `1:2 error` it's definetely eslint

**Comment by chandrasekarb** [comment]
how to fix it please give the solution

**Comment by hzoo** [comment]
This doesn't look like a babel/babel-loader issue - http://eslint.org/docs/user-guide/configuring make sure your eslint config has ecmaVersion 6, env: es6
