### ISSUE TITLE
over one hundred repetitive lines on stderr and a 10 second delay on first compiled file

### ISSUE THREAD

**Issue by ohjames** [babel/babel-loader#296]
**I'm submitting a bug report**

**Webpack Version:**
1.13.2

**Babel Core Version**:
6.14.0

**Babel Loader Version**:
6.2.5

**Please tell us about your environment:**
Linux

**Current behavior:**
The first time I compile any babel file I get a 10 second delay and a tonne of errors on stderr:

```
resolve failed:  { [Error: Cannot find module 'grunt-mocha-test'] code: 'MODULE_NOT_FOUND' } grunt-mocha-test
resolve failed:  { [Error: Cannot find module 'grunt-env'] code: 'MODULE_NOT_FOUND' } grunt-env
resolve failed:  { [Error: Cannot find module 'grunt-contrib-watch'] code: 'MODULE_NOT_FOUND' } grunt-contrib-watch
resolve failed:  { [Error: Cannot find module 'grunt-contrib-jshint'] code: 'MODULE_NOT_FOUND' } grunt-contrib-jshint
resolve failed:  { [Error: Cannot find module 'grunt-cli'] code: 'MODULE_NOT_FOUND' } grunt-cli
```

It prints those 5 lines about 15 times... so I get more than a hundred of those logs on my screen. There's this big 10 second long delay while all this is happening, and then the loader compiles the file and gets along with compiling the rest of the files instantly.

If I install `babel-cli` and run the `babel` command and give it an input file, it compiles fast without any log messages like this to the terminal.

None of the files in my webpack project are referencing these `grunt-*` dependencies, they are used only in my `gruntfile` which shouldn't be loaded by my webpack configuration (I added `webpack` to my exclude just to be absolutely sure but the same thing still occurred).

If I use `webpack-dev-server` then the issue only occurs when I change the first file or if the cache is dirty when it loads.

**Comment by loganfsmyth** [comment]
Without a reproducible example, I'm not sure what to say. This sounds more like a Webpack issue that a Babel issue.

**Comment by ohjames** [comment]
If I comment out the babel loader everything is fine and there is no delay, I only see it when the babel-loader is enabled and when it compiles its first file.

**Comment by loganfsmyth** [comment]
If you can trim down a reproducible example, we can certainly try to help, but as it I don't think there is enough info.

**Comment by ohjames** [comment]
I see the error the first time you call `babel.transform()` (line 38 of `index.js`).

**Comment by ohjames** [comment]
I guess it's babel doing this, no idea why though... or why `babel-cli` manages to avoid it. Maybe it's a node 0.10 specific issue.

**Comment by loganfsmyth** [comment]
If you have a stacktrace showing line numbers, please include it in the bug report.

**Comment by ohjames** [comment]
The errors came from `es-2015-loose` preset... no idea why babel is scanning all those dependencies, I think the issue is over there. Thanks for your responses.

**Comment by hzoo** [comment]
@ohjames FYI es2015-loose is deprecated because you can pass options to the es2015 preset
