### ISSUE TITLE
Add option to disable compression of cached files

### ISSUE THREAD

**Issue by kganser** [babel/babel-loader#300]
**I'm submitting a feature request**

**Webpack Version:**
1.10.x/2.x

**Babel Core Version**:
6.x

**Babel Loader Version**:
5.4.x/6.2.x

**Please tell us about your environment:**
OSX 10.x / Linux / Windows 10

**Current behavior:**
All cached files are gzipped.

**Expected/desired behavior:**
Would like an option to disable gzipping of cached files for improved load speed.

This should be fairly simple to implement.  I was able to bypass compression locally by just commenting out some lines in [fs-cache.js](https://github.com/babel/babel-loader/blob/master/lib/fs-cache.js), but I figured that this would be a nice config option in general.

Thanks,
Klaus

**Comment by loganfsmyth** [comment]
This should be fixed with https://github.com/babel/babel-loader/pull/574
