### ISSUE TITLE
README: Add 'Unexpected token import/export' to Troubleshooting section

### ISSUE THREAD

**Issue by kevinSuttle** [babel/babel-loader#312]
Seems like a very common sticking point.

``` json
"babel-cli": "^6.16.0",
"babel-core": "^6.17.0",
"babel-loader": "^6.2.5",
```

**Comment by hzoo** [comment]
Do you mean telling users to make a babelrc/query option? If you'd like you can make a PR

**Comment by kevinSuttle** [comment]
Yeah, like this, but you know, useful. :) 

http://babeljs.io/docs/faq/#why-am-i-getting-a-syntax-errorunexpected-token

**Comment by kevinSuttle** [comment]
For me, it's putting the following 2 lines at the top of my Webpack config, _and_ entry file.

```js
require('babel-register');
require('babel-polyfill');
```

**Comment by kevinSuttle** [comment]
There might also be some direction on fixing this via https://github.com/webpack/exports-loader and or https://github.com/webpack/imports-loader.

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babel-loader. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.
