### ISSUE TITLE
README references babel-runtime & selfContained instead of external-helpers

### ISSUE THREAD

**Issue by thetalecrafter** [babel/babel-loader#32]
See: https://babeljs.io/docs/usage/external-helpers/

**Comment by sebmck** [comment]
Why should it reference external-helpers?

**Comment by thetalecrafter** [comment]
Sorry, I was in a rush when I first submitted the issue. I just didn't want to forget.

This is more of a question than an issue. Both the readme here, and the babel site have a section for what to do about possible bloat from babel. On the site, which I assume is more authoritative, it talks about using external helpers. In the readme here it talks about selfContained, which seems by my reading to be more about not impacting global environment rather than reducing final bundle size. Which seems less applicable to the case of writing an application using webpack.

It would be helpful to have a little more explanation as to when and why you'd do which. A page on the babel site would probably be most appropriate, the readme likely just pointing to it.

**Comment by sebmck** [comment]
Not a single page on the website links to the external helpers except for in the nav. The `selfContained` transformer is promoted because it's the most appropriate for basically every scenario.

**Comment by thetalecrafter** [comment]
In that case I'd suggest having a page in the navigation for selfContained, instead of external helpers. Currently selfContained is buried in the transformers page.

**Comment by sebmck** [comment]
Good idea, can you open an issue on [babel.github.io](https://github.com/babel/babel.github.io)? I usually get sidetracked and don't want to forget about it.

**Comment by thetalecrafter** [comment]
I'll do that. I know the feeling. That's why I opened the issue with so little detail initially. :)

**Comment by sebmck** [comment]
Great, thanks!
