### ISSUE TITLE
Babel-loader doesn't transpile code on linux

### ISSUE THREAD

**Issue by lghiur** [babel/babel-loader#323]
**I'm submitting a bug report**

**Webpack Version:**
1.13.3

**Babel Core Version**:
6.14

**Babel Loader Version**:
6.2.7

**Please tell us about your environment:**
Linux

**Current behavior:**
When building the project the code isn't transpiled, it is just copied into the build folder. I've tried to transpile the code using bable cli and it works and it also works perfectly on Windows.

**Expected/desired behavior:**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

babel config:

```
{
  test: /\.js?$/,
  exclude: /(node_modules|build|coverage)/,
  loader: 'babel',
  query: {
    presets: ['es2015', 'stage-0'],
    plugins: [
      "transform-runtime"
    ]
  }
```

* **What is the expected behavior?**

the code should be transpiled

Please advise,
Laurentiu

**Comment by lghiur** [comment]
It was because of transform-runtime plugin apparently. After I removed that plugin, it started to work

**Comment by hzoo** [comment]
It's hard to know the issue without seeing the input code? If you think it was transform-runtime then it was most likely that you didn't include `babel-runtime` as a dependency?
