### ISSUE TITLE
Presets not passed to Babel when using query property

### ISSUE THREAD

**Issue by blacksonic** [babel/babel-loader#325]
**I'm submitting a bug report**

**Webpack Version:**
2.1.0-beta.25

**Babel Core Version**:
6.18.0

**Babel Loader Version**:
6.2.7

**Please tell us about your environment:**
Linux Ubuntu 16.04 LTS

**Current behavior:**
Babel loader only works with presets when I add them as a string after the loader.
```
{
  test: /\.js$/,
  loader: 'babel?presets[]=es2015&presets[]=angular2',
}
```
When i change it to the query property it stops working.
```
{
  test: /\.js$/,
  loader: 'babel',
  query: {
    presets: ['latest', 'angular2']
  }
}
```
Even the example on the new site is failing.
```
options: {
  presets: ['latest', 'angular2']
}
```
The error i get is: ``` Module build failed: Error: parseQuery should get a string as first argument ```

**Expected/desired behavior:**
With Webpack 1 both ways worked, now query property seems to be neglected.

**How to reproduce.**
In my [TodoMVC repository](https://github.com/blacksonic/angular2-esnext-todomvc/blob/master/webpack.common.config.js) changing the config and running ```npm start``` throws the error.

**Motivation**
Without this configuration from code is really hard.

**Comment by blacksonic** [comment]
Calling ```JSON.stringify``` on the query seems to solve the issue.

**Comment by TheLarkInn** [comment]
Hmm could you do a fresh npm install. Loader utils should be able to handle that currently and I have not been able to reproduce. Just want to confirm.

**Comment by abouthiroppy** [comment]
Thank you for reporting!
I tried to check this problem. However, I was not able to cause a problem 😢

**Comment by blacksonic** [comment]
Npm tricked me...
After doing a clean install it works fine. Upgraded from Webpack 1 to 2 today and unfortunately loader utils remained on an older version.

Thanks for helping.
