### ISSUE TITLE
Recover from EROFS

### ISSUE THREAD

**Issue by frontsideair** [babel/babel-loader#327]
**I'm submitting a bug report**
**I'm submitting a feature request**

**Webpack Version:**
1.13.2

**Babel Core Version**:
6.17.0

**Babel Loader Version**:
6.2.7

**Please tell us about your environment:**
Linux

**Current behavior:**
Fails if target `node_modules` directory is read-only

**Expected/desired behavior:**
It should recover and should disable caching

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
- Make `node_modules` read-only (in my case, it's generated this way by a build tool)
- Run webpack-dev-server (in my case, create-react-app's npm start)

* **What is the expected behavior?**
It should run, without caching

* **What is the motivation / use case for changing the behavior?**
I know this is not the common use case, but out build process depends on Nix package manager, which fetches and builds node dependencies for our project in a read-only directory. When I try to run dev server, it fails since `node_modules/.cache` is read-only. I want it to recover as best as it can.

**Comment by danez** [comment]
Thanks for reporting. 
We currently already have a fallback to the tmp-directory if no `node_modules` directory cannot be find. We could do the same if it is readonly. Would that be satisfy your usecase?

**Comment by frontsideair** [comment]
I think it would work, and it would be better than my suggestion of no caching. Thanks!

**Comment by frontsideair** [comment]
Is there any update or timeline on this?

**Comment by frontsideair** [comment]
I spared some time to fix this myself, can you check it out?

**Comment by frontsideair** [comment]
Awesome, thanks! Now we need a release so create-react-app can use it and they can make a release.
