### ISSUE TITLE
Feature Query: Filesystem Cache?

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel-loader#34]
I work on a pretty big app and transpiling everything take a while on the first webpack build pass. Would you be open to a PR to add a filesystem cache to this module like `babel/register` does? I implemented it in a custom loader and for us, it reduces the initial build pass by ~20 seconds. I'd be happy to submit a PR to add it to the this as a optional flag.

**Comment by Couto** [comment]
Any way to see your custom loader? Just to check the inner workings. 
But as far as I can tell that sounds like an excellent PR :+1:

**Comment by loganfsmyth** [comment]
@Couto This is what I had thrown together for my test: https://gist.github.com/loganfsmyth/b0c0ed5d9f6eafecd5cc

It's a few weeks old (still using "6to5") and has some purpose-specific stuff for our usage, but it demonstrates what I mean. We're not acutally using this yet, I just have it on a branch. I'd want to change to using `path.join(os.tmpdir(), '/babel-cache')` or something for the dir. I have it caching based on content, babel version, and args, which I think makes the most sense. Probably want the cache location to be configurable by param too.

It takes out build times from 39 -> 22 seconds once the cache is populated, so restarting our watcher scripts and stuff is much faster and it seems like something that others would benefit from, at least as an optional thing.

**Comment by Couto** [comment]
I have to admit that I didn't have the opportunity to test it, but as far as I can see, I'm pretty ok with a PR, specially if it is behind a flag :)

On the other hand, I feel that you could also direct this PR directly to webpack so that all loaders could benefit of the cache improvements, but it's just an idea.

**Comment by jtangelder** [comment]
This would be cool, our build takes about 2 minutes initial, which is way too long.

**Comment by loganfsmyth** [comment]
I'm going to try to get a PR together soon.

**Comment by loganfsmyth** [comment]
@jtangelder Submitted a PR, I'd be interested to hear how that works for you.

**Comment by jtangelder** [comment]
Awesome, initial build now is at 50% of the time!

**Comment by Couto** [comment]
You guys can find this on version 4.2.0.

I'll try to ring the guys at webpack at gitter to see if they want to consider something similar to other loaders.

**Comment by jtangelder** [comment]
A webpack 'cache-loader' would make sense :-)

**Comment by Couto** [comment]
@jtangelder I agree actually. I've merged because the benefits are indeed great, but I also believe that this shouldn't live specifically inside the babel-loader, and that other loaders should benefit, either by updating webpack or an independent loader :+1:
