### ISSUE TITLE
Improper configuration in webpack.config.js does not produce error message

### ISSUE THREAD

**Issue by zrrtcs** [babel/babel-loader#341]
**I'm submitting a bug report**
**I'm submitting a feature request**

**Webpack Version:**
1.13.3

**Babel Core Version**:
6.18.2

**Babel Loader Version**:
6.2.8

**Please tell us about your environment:**
OSX 10.12.1

**Current behavior:**
Under webpack.config.js, when module.loaders[x].include is given a string instead of an array, webpack will still run but no error message is shown and ES6 code is not transpiled to ES5 properly.

**Expected/desired behavior:**
A warning indicating module.loaders[x].include should be an array as noted in documentation and halt the execution.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
1. webpack.config.js
https://gist.github.com/zrrtcs/13aa9a4d6b2bae89b6955a94927470dc
2. run ./node_modules/.bin/webpack

* **What is the expected behavior?**
It should display warning/error and halt transpiling

* **What is the motivation / use case for changing the behavior?**
Spent hours  on why ES6 code is not transpiled to desired ES5

**Comment by loganfsmyth** [comment]
Unfortunately this isn't actionable for us.

1. `include` is a feature of Webpack itself, not `babel-loader`.
2. If Webpack did validate it (which Webpack 2 does, but Webpack 1 does not), the value is allowed to be a string.

See the docs here: https://webpack.github.io/docs/configuration.html#module-loaders

> A condition may be a RegExp (tested against absolute path), a string containing the absolute path, a function(absPath): bool, or an array of one of these combined with “and”.

So while a string is allowed, it is matched against an absolute path, so your example would need to be `__dirname + '/src/'`

**Comment by zrrtcs** [comment]
thank you for the explaination @loganfsmyth
