### ISSUE TITLE
'latest' not work!

### ISSUE THREAD

**Issue by keyiis** [babel/babel-loader#350]
**Webpack Version:**
2.1.0-beta.25

**Babel Core Version**:
6.11.4

**Babel Loader Version**:
6.2.4

**Please tell us about your environment:**
Windows 10

**Current behavior:**
**webpack.config**
```
{
        test: /\.js$/,
        exclude: /(node_modules|server|backup|output)/,
        loader: 'babel-loader',
        query: {
          presets: ['latest']
        }
      }
```
**package.json**
```
    "babel-core": "^6.11.4",
    "babel-loader": "^6.2.4",
    "babel-polyfill": "^6.13.0",
    "babel-preset-latest": "^6.16.0",
```
**error**
`Module build failed: Error: Cannot find module 'babel-preset-es2015' (While processing preset: "D:\\work\\nodejs\\angular\\angular2-electron\\node_modules\\babel-preset-latest\\lib\\index.js")`

**Comment by keyiis** [comment]
When i remove babel-preset-latest and install 'babel-preset-es2015 babel-preset-es2016 babel-preset-es2017' ,change webpack.config

```
{
        test: /\.js$/,
        exclude: /(node_modules|server|backup|output)/,
        loader: 'babel-loader',
        query: {
          presets: ['es2015','es2016','es2017']
        }
      }
```
issuse resolved!my node version 6.9.2,so i think babel-loader 'latest' not work with npm 3?

**Comment by keyiis** [comment]
update :
although no error happen in package process,but when i run packaged app get error:
`Object.entries is not a function`
so 'es2016','es2017' still not work.

**Comment by abouthiroppy** [comment]
@keyiis Please change `query` to `options `.

**Comment by michaelalhilly** [comment]
Changing query to options to not fix the issue for me. Is anyone using preset-latest with babel-loader?

**Comment by hzoo** [comment]
Using babel-preset-latest or any latest is unrelated to using a built-in like `Object.entries is not a function` - that has to do with using babel-polyfill.

I don't see any particular reason latest doesn't work with babel-loader on npm 3. I would `rm -rf node_modules` and npm install again.
