### ISSUE TITLE
Should I use `cacheDirectory` in production build?

### ISSUE THREAD

**Issue by mrdulin** [babel/babel-loader#351]
I use this parameter, but it seems not to boost my first build in development.

By the way, should I use it in production build?

Thanks for anwser!

**Comment by bebraw** [comment]
If you perform the production build on a server (one off build), caching might actually hurt performance a notch.

**Comment by loganfsmyth** [comment]
Personally, I would not recommend using it in production, since the cache isn't always guaranteed to update if a plugin you depend on updates.
