### ISSUE TITLE
why use a '0' before the function

### ISSUE THREAD

**Issue by taikongfeizhu** [babel/babel-loader#352]
**Webpack Version:**
1.13

**Babel Core Version**:
6.21.0

**Babel Loader Version**:
6.2.10

**Please tell us about your environment:**
OSX 10.x / Linux

before compile：

```js
function createDOMForm(option) {
  return createBaseForm({
    ...option,
  }, [mixin]);
}
```

after compile:

```js
function createDOMForm(option) {
  return (0, _createBaseForm2["default"])((0, _extends3["default"])({}, option), [mixin]);
}
```

I don't understand why use a '0' before the _createBaseForm2 and _extends3 ?

**Comment by loganfsmyth** [comment]
The answer here should cover it. It changes `this` in the called function. https://stackoverflow.com/questions/31034945/babels-funny-import
