### ISSUE TITLE
Build throws syntax error in node: }.apply(null, __WEBPACK_AMD_REQUIRE_ARRAY__));

### ISSUE THREAD

**Issue by aight8** [babel/babel-loader#363]
**I'm submitting a bug**

I have no clue from where this comes from, but I faced this error SO many times in the last year.

**Webpack Version:**
2.2

**Babel Core Version**:
6.22.2

**Babel Loader Version**:
6.2.10

**Please tell us about your environment:**
macOS

**Current behavior:**
When compiling my app for server side rendering, and require the server bundle (to start the server), a syntax error appear.

**Expected/desired behavior:**
No syntax error, just run the server build in node.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

```
/....../build/server/index.js:11412
    }.apply(null, __WEBPACK_AMD_REQUIRE_ARRAY__));
     ^
  SyntaxError: Unexpected token .
```
----
```
return function getPage(nextState, cb) {
    require(['./pages/' + pageName + '.jsx'], module => {
      cb(null, module.default);
    });
  }
```
It's this one. I can't use import either because it must be on top level. No clue how to solve that.

**Comment by abouthiroppy** [comment]
Could you show us your repo?

**Comment by tomaszpupiec** [comment]
I have the same problem, my code looks like:

`
require([templatePath], (tpl) => {
	this.template = '<div page="' + pageName + '">' + tpl + '</div>';
	callback(tpl);
       }
);
`

Seems that problem is using "apply" with arrow function.
Any solution ?

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babel-loader. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.

If someone runs into this, please create a reproducible example and open a new issue. Thanks!
