### ISSUE TITLE
React.DOM pragma error

### ISSUE THREAD

**Issue by callum** [babel/babel-loader#37]
See https://github.com/callemall/material-ui/issues/364

I'm having this same issue with a different library. I would have thought they could be safely ignored.

**Comment by sebmck** [comment]
This is expected behaviour. Otherwise Babel will use `React.DOM` will be used as the JSX pragma and it will absolutely break Babel's third party support for JSX. Please report potential issues like this on the [Babel](https://github.com/babel/babel) repo in the future.
