### ISSUE TITLE
You may need an appropriate loader to handle this file type with react@15.4.2, webpack@2.2.1 and babel-loader@6.2.10

### ISSUE THREAD

**Issue by wood1986** [babel/babel-loader#370]
**Webpack Version:**
2.2.1

**Babel Core Version**:
6.22.1

**Babel Loader Version**:
6.2.10

**Please tell us about your environment:**
Linux

**Current behavior:**
it gives an error `You may need an appropriate loader to handle this file type with`

**Expected/desired behavior:**
no error

```
  //package.json
  "babel-core": "^6.22.1",
  "babel-loader": "^6.2.10",
  "babel-preset-es2015": "^6.22.0",
  "babel-preset-react": "^6.22.0",
  "css-loader": "^0.26.1",
  "extract-text-webpack-plugin": "^2.0.0-rc.2",
  "html-webpack-plugin": "^2.28.0",
  "node-sass": "^4.5.0",
  "react": "^15.4.2",
  "react-dom": "^15.4.2",
  "sass-loader": "^4.1.1",
  "style-loader": "^0.13.1",
  "uglifyjs-webpack-plugin": "^0.1.2",
  "webpack": "^2.2.1"
```

```
//webpack.config.js
const HtmlWebpackPlugin = require('html-webpack-plugin'),
      UglifyJSPlugin = require('uglifyjs-webpack-plugin'),
      ExtractTextPlugin = require("extract-text-webpack-plugin"),
      path = require("path");

module.exports = {
  "entry": ["./app/index.js"],
  "output": {
    "path": "output",
    "filename": "[name]-[chunkhash].js",
    "libraryTarget": "umd"
  },
  "module": {
    rules: [
      {
        "exclude": "/node_modules/",
        "include": "./app/",
        "loader": "babel-loader",
        "options": {
          "presets": ["es2015", "react"]
        },
        "test": /\.jsx?$/
      },
      {
        "exclude": "/node_modules/",
        "use": ExtractTextPlugin.extract({
          "fallbackLoader": "style-loader",
          "loader": ["css-loader", "sass-loader"]
        }),
        "test": /\.scss$/
      }
    ]
  },
  plugins: [
    new HtmlWebpackPlugin(),
    new ExtractTextPlugin("[name]-[contenthash].css")
  ]
}
```

```
//./app/index.js
let React = require("react"),
    ReactDom = require("react-dom");

ReactDom.render(
  <div id="root"></div>,
  document.getElementsByTagName("body")
);
```

**Comment by loganfsmyth** [comment]
Would you be able to include the full error output?

**Comment by loganfsmyth** [comment]
If I had to guess, you want
```
        "exclude": "/node_modules/",
        "include": "./app/",
```
to be
```
        "include": __dirname + "/app/",
```
or
```
        "exclude": /node_modules/,
```

paths have to be absolute paths, or regexes.

**Comment by wood1986** [comment]
```
ERROR in ./app/index.js
Module parse failed: /root/index.js Unexpected token (7:2)
You may need an appropriate loader to handle this file type.
|
| ReactDom.render(
|   <div id="river"></div>,
|   document.getElementsByTagName("body")
| );
 @ multi ./app/index.js
Child html-webpack-plugin for "index.html":
       [0] ./~/lodash/lodash.js 540 kB {0} [built]
       [1] (webpack)/buildin/global.js 509 bytes {0} [built]
       [2] (webpack)/buildin/module.js 517 bytes {0} [built]
       [3] ./~/html-webpack-plugin/lib/loader.js!./~/html-webpack-plugin/default_index.ejs 540 bytes {0} [built]
```

**Comment by wood1986** [comment]
I think you solve my problem

**Comment by brenopolanski** [comment]
hey @wood1986 

I have the same problem. How you solved?

**Comment by wood1986** [comment]
I think you miss the `"options": { "presets": ["es2015", "react"] },` in the babel-loader.
Of course you need to have `"babel-preset-es2015": "^6.22.0", "babel-preset-react": "^6.22.0",`

**Comment by brenopolanski** [comment]
well.. i am using these version of `"babel-preset-es2015"` and `"babel-preset-react"`.

I have the file `.babelrc` with:

```
{
  "presets": ["es2015", "stage-0", "react"],
  "plugins": ["react-hot-loader/babel"]
}
```

But it not work

**Comment by wood1986** [comment]
I set those values inside the webpack.config.js instead of .babelrc. I am not familar with .babelrc

**Comment by lgordey** [comment]
@wood1986 Hey man!
How you solve this problem?

**Comment by WwupengP** [comment]
I have the same problem.I think it do'nt use babel-loader before execute eslint.

**Comment by Bijayini** [comment]
//package.json file
"dependencies": {
    "path": "^0.12.7",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "webpack": "^3.0.0",
    "webpack-dev-server": "^2.5.0"
  },
  "devDependencies": {
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "html-webpack-plugin": "^2.28.0"
  }


//.babelrc file
{
  "presets": [
    "es2015", "stage-0", "react"
  ]
}

//webpack.config.js
const webpack = require('webpack');
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    entry:'./app/index.js',
    output: {
        path:path.resolve('dist'),
        filename: 'bundle.js'
    },

    module:{
        rules:[
            {test:'/\.js$/' , loader:'babel-loader', exclude: '/node_modules/'},
            {test:'/\.jsx$/' , loader:'babel-loader', exclude: '/node_modules/'}
        ]


    },
    plugins:[
        new HtmlWebpackPlugin({
            template: './app/index.html',
            filename: 'index.html',
            inject: 'body'
        })
    ]

};

//Index.js file

import React from 'react';
import ReactDOM, { render } from 'react-dom';
import App from './components/App';

ReactDOM.render(<App />, document.getElementById('root'));


//App.js file

import React from 'react';

export default class App extends React.Component{
    render() {
        return (
            <p> hi </p>
        );
    }
}

Error:

ERROR in ./app/index.js
Module parse failed: /Users/bijayinp/Desktop/appsec-setup/appsec-frontend/app/index.js Unexpected token (5:16)
You may need an appropriate loader to handle this file type.
| import App from './components/App';
|
| ReactDOM.render(<App />, document.getElementById('root'));
|
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./app/index.js

**Comment by Couto** [comment]
@Bijayini Your test values are a string value, which means that it won't match during the test resolution.
You can switch to:

```
  {test: /\.js$/ , loader:'babel-loader', exclude: '/node_modules/'},
  {test: /\.jsx$/ , loader:'babel-loader', exclude: '/node_modules/'}
```

**Comment by Bijayini** [comment]
@Couto Thank you a lot.

**Comment by alekhyaem** [comment]
//package.json file
{
  "name": "react",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "dependencies": {
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "webpack": "^3.0.0",
    "webpack-dev-server": "^2.5.0"
  },
  "devDependencies": {},
  "scripts": {
     "webpack": "webpack",
    "start": "webpack-dev-server --hot"
  },
  "author": "",
  "license": "ISC"
}



//webpack.config.js
var webpack = require("webpack");
var folder = __dirname;
var config = {
   entry: './main.js',
	
   output: {
      path: folder + './',
      filename: 'index.js',
   },
	
   devServer: {
      inline: true,
      port: 8080
   },
	
   module: {
      loaders: [
         {
            test: /\*.jsx?$/,
            exclude: /node_modules/,
            loader: 'babel',
				
            query: {
               presets: ["es2015", "react"]
            }
         }
   ]
   }
}

module.exports = config;






//main.js
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App.jsx';

ReactDOM.render(<App />, document.getElementById('app'));



//App.jsx
import React from 'react';

 class App extends React.Component{ {
   render() {
      return (
         <div>
            Hello World!!!
         </div>
      );
   }
}

export default App




//index.html
<!DOCTYPE html>
<html lang = "en">

   <head>
      <meta charset = "UTF-8">
      <title>React App</title>
   </head>

   <body>
      <div id = "app"></div>
      <script src = "index.js"></script>
   </body>

</html>


//Error
ERROR in ./main.js
Module parse failed: E:\react\app\main.js Unexpected token (5:16)
You may need an appropriate loader to handle this file type.
| import App from './App.jsx';
|
| ReactDOM.render(<App />, document.getElementById('app'));
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./main.js
webpack: Failed to compile.

**Comment by Bijayini** [comment]
@alekhyaem 
can you please change your `loader` to `babel loader`
//webpack.config.js
```

loaders: [
{
test: /*.jsx?$/,
exclude: /node_modules/,
loader: 'babel-loader',

        query: {
           presets: ["es2015", "react"]
        }
     }
]

```

**Comment by Bijayini** [comment]
In your `main.js` you are rendering in div having id 'app'. What you are rendering , it's not mentioned

//main.js
```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App.jsx';

ReactDOM.render(<App />, document.getElementById('app'));
```

**Comment by alekhyaem** [comment]
@Bijayini ,Thanks.
I am rendering like this in my main.js. Still i was getting same error
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App.jsx';

ReactDOM.render(<App />, document.getElementById('app'));

**Comment by NimitzDEV** [comment]
hi @alekhyaem , Are you using webpack 3? I upgrade my webpack to version 3.0 today, since then I ran into the same issue.
In webpack 3, it use `rules` instead of `loaders`.
I solved this problem by changing the config
You can check it[ here ](https://webpack.js.org/configuration/module/#module-rules)

**Comment by mastari** [comment]
@Couto It worked! Thanks!

**Comment by cb1993** [comment]
"author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.8.0",
    "babel-eslint": "^6.0.4",
    "babel-loader": "^6.2.4",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-react-transform": "^2.0.2",
    "babel-plugin-rewire": "^1.0.0-rc-2",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-runtime": "^6.8.0",
    "babel-plugin-webpack-alias": "1.3.0",
    "babel-polyfill": "^6.8.0",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-1": "^6.5.0",
    "css-loader": "^0.25.0",
    "express": "^4.14.0",
    "file-loader": "^0.9.0",
    "git-rev-sync": "^1.8.0",
    "json-loader": "^0.5.4",
    "less-loader": "^2.2.3",
    "lodash": "^4.17.4",
    "postcss-cssnext": "^2.8.0",
    "postcss-loader": "^1.1.1",
    "postcss-modules-values": "^1.2.2",
    "resolve-url": "^0.2.1",
    "resolve-url-loader": "^2.0.0",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^1.15.0",
    "webpack-dev-middleware": "^1.8.4",
    "webpack-hot-middleware": "^2.13.2"
  },
  "dependencies": {
    "babel-plugin-add-module-exports": "^0.2.1",
    "classnames": "^2.2.5",
    "eventsource-polyfill": "^0.9.6",
    "immutable": "^3.8.1",
    "less": "^2.7.1",
    "react": "^15.4.2",
    "react-addons-pure-render-mixin": "^15.4.2",
    "react-doc-meta": "^0.2.0",
    "react-dom": "^15.4.2",
    "react-icons": "^2.2.3",
    "react-redux": "^4.4.5",
    "react-router": "^3.0.0",
    "react-scroll": "^1.4.5",
    "react-transform-hmr": "^1.0.4",
    "redux": "^3.5.2",
    "redux-loop": "^2.2.2"
  }
}

**Comment by cb1993** [comment]
`"author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.8.0",
    "babel-eslint": "^6.0.4",
    "babel-loader": "^6.2.4",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-react-transform": "^2.0.2",
    "babel-plugin-rewire": "^1.0.0-rc-2",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-runtime": "^6.8.0",
    "babel-plugin-webpack-alias": "1.3.0",
    "babel-polyfill": "^6.8.0",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-1": "^6.5.0",
    "css-loader": "^0.25.0",
    "express": "^4.14.0",
    "file-loader": "^0.9.0",
    "git-rev-sync": "^1.8.0",
    "json-loader": "^0.5.4",
    "less-loader": "^2.2.3",
    "lodash": "^4.17.4",
    "postcss-cssnext": "^2.8.0",
    "postcss-loader": "^1.1.1",
    "postcss-modules-values": "^1.2.2",
    "resolve-url": "^0.2.1",
    "resolve-url-loader": "^2.0.0",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^1.15.0",
    "webpack-dev-middleware": "^1.8.4",
    "webpack-hot-middleware": "^2.13.2"
  },
  "dependencies": {
    "babel-plugin-add-module-exports": "^0.2.1",
    "classnames": "^2.2.5",
    "eventsource-polyfill": "^0.9.6",
    "immutable": "^3.8.1",
    "less": "^2.7.1",
    "react": "^15.4.2",
    "react-addons-pure-render-mixin": "^15.4.2",
    "react-doc-meta": "^0.2.0",
    "react-dom": "^15.4.2",
    "react-icons": "^2.2.3",
    "react-redux": "^4.4.5",
    "react-router": "^3.0.0",
    "react-scroll": "^1.4.5",
    "react-transform-hmr": "^1.0.4",
    "redux": "^3.5.2",
    "redux-loop": "^2.2.2"
  }
}
`

**Comment by cb1993** [comment]
`var path = require('path')
var common = require('./webpack.common')

module.exports = {
    devtool: '#cheap-module-eval-source-map',
    entry: [
        'eventsource-polyfill',
        'webpack-hot-middleware/client', './index'
    ],
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js',
        publicPath: '/'
    },
    resolve: common.getResolve(),
    plugins: [
        common.getPlugin('occurrenceOrder'),
        common.getPlugin('HMR'),
        common.getPlugin('noErrors'),
        common.getPlugin('buildInfo'),
        common.getPlugin('ignoreIconv'),
    ],
    postcss: common.getPostCss(),
    node: common.getNode(),
    module: {
        loaders: common.getLoaders()
    }
}`

**Comment by cb1993** [comment]
`var path = require('path')
var common = require('./webpack.common')

module.exports = {
    devtool: '#cheap-module-eval-source-map',
    entry: [
        'eventsource-polyfill',
        'webpack-hot-middleware/client', './index'
    ],
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js',
        publicPath: '/'
    },
    resolve: common.getResolve(),
    plugins: [
        common.getPlugin('occurrenceOrder'),
        common.getPlugin('HMR'),
        common.getPlugin('noErrors'),
        common.getPlugin('buildInfo'),
        common.getPlugin('ignoreIconv'),
    ],
    postcss: common.getPostCss(),
    node: common.getNode(),
    module: {
        loaders: common.getLoaders()
    }
}`

**Comment by sammwaura** [comment]
package.json
"name": "react-project",
    "version": "1.0.0",
    "description": "react test project",
    "main": "index",
    "scripts": {
        "server": "babel-node server/index.js",
        "build": "babel server/index.js --out-dir dist --copy-files && webpack --config webpack.config.dev.js",
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "samuel mwaura",
    "license": "ISC",
    "dependencies": {
        "express": "^4.16.2",
        "lodash": "^4.17.4"
    },
    "devDependencies": {
        "babel": "^6.23.0",
        "babel-cli": "^6.26.0",
        "babel-loader": "^7.1.2",
        "babel-preset-env": "^1.6.0",
        "babel-preset-es2015": "^6.24.1",
        "babel-preset-react": "^6.24.1",
        "cli": "^1.0.1",
        "css-loader": "^0.28.7",
        "node": "^8.3.0",
        "react": "^16.0.0",
        "react-dom": "^16.0.0",
        "react-hot-loader": "^3.1.1",
        "react-router": "^4.2.0",
        "webpack": "^3.7.1",
        "webpack-dev-middleware": "^1.12.0",
        "webpack-hot-middleware": "^2.20.0"
    },
    "keywords": []
}


import React from "react";
import { Route, IndexRoute} from "react-router";

import App from "./components/App.js";
import Greetings from "greetings";
import SignupPage from "./components/signup/SignupPage";

export default (
  <Route path="/" component={App}/>
     <IndexRoute component={Greetings} />
     <Route path="signup" component={SignupPage} />
  </Route>

import React from "react";
import NavigationBar from "NavigationBar";

class App extends React.Component {
 render() {
   return   (
     <div className="container">
       <NavigationBar />
       {this.props.children}
     </div>
    );
 }
}

export default App

problem
ERROR in ./client/routes.js
Module parse failed: C:\Users\Samuel Mwaura\Desktop\reactproject\client\routes.js Unexpected token (9:2)
You may need an appropriate loader to handle this file type.
|
| export default (
|   <Route path="/" component={App}/>
|      <IndexRoute component={Greetings} />
|      <Route path="signup" component={SignupPage} />
 @ ./client/index.js 4:0-29
 @ multi (webpack)-hot-middleware/middleware.js ./client/index.js

**Comment by vijay-maripi** [comment]
guys i'm facing similar problem ,i just started learning react js and facing with this 
my error:--
---------------------------------------------------------------
ERROR in ./src/app/index.js
Module build failed: SyntaxError: Unexpected token (7:6)

     render(){
     return{
     <div>
          ^<h1>hello</h1>
       </div>

 @ multi main
------------------------------------------------------------------

my webpack.config.js:
------------------------------
var path = require("path");

var DIST_DIR = path.resolve(__dirname, "dist");
var SRC_DIR = path.resolve(__dirname, "src");

var config = {
    entry: SRC_DIR + "/app/index.js",
    output: {
        path: DIST_DIR + "/app",
        filename: "bundle.js",
        publicPath: "/app/"
    },
    module: {
        loaders: [
            {
                test: /\.js?/,
                include: SRC_DIR,
                loader: "babel-loader",
                query: {
                    presets: ["react", "es2015", "stage-2"]
                }
            }
        ]
    }
};

module.exports = config;

-------------------------------------------------------------------------------
my package.json:
---------------------

{
  "name": "reactjs-basics",
  "version": "1.0.0",
  "description": "Some basic ReactJS",
  "main": "index.js",
  "scripts": {
    "start": "npm run build",
    "build": "webpack -d && cp src/index.html dist/index.html && webpack-dev-server --content-base src/ --inline --hot",
    "build:prod": "webpack -p && cp src/index.html dist/index.html"
  },
  "keywords": [
    "reactjs"
  ],
  "author": "Maximilian Schwarzmüller",
  "license": "MIT",
  "dependencies": {
    "react": "^15.6.2",
    "react-dom": "^15.6.2"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^6.4.1",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-2": "^6.11.0",
    "webpack": "^1.13.1",
    "webpack-dev-server": "^1.14.1"
  }
}

-------------------------------------------------------------------------------------

my index.js:
------------------

import React from "react";
import { render } from "react-dom";

class App extends React.component{
  render(){
    return{
      <div>
      <h1>hello</h1>
      </div>

    };
  }
}
render(<App/>, window.document.getElementById("app"));

----------------------------------------------------------------------------------------

my index.html:
-------------------
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ReactJS Basics</title>
</head>
<body>
  <div id="app"></div>
<script src="/app/bundle.js"></script>
</body>
</html>

-----------------------------------------------------------------------------

guys can anyone help me with this ,thank you :)

**Comment by uzmakhan18** [comment]
Facing Same issue. Kindly help me. 

Webpack.config.js

var path = require('path');
var webpack = require('webpack');
    
module.exports = {
    entry: './js/app.js',
    output: {
        path: path.resolve(__dirname, 'build'),
        filename: 'app.bundle.js'
    },
    
    devServer: {
        inline: true,
        contentBase: './dist',
        port: 9877
    },
    resolve: {
        extensions: ['.js', '.jsx']
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                loader: 'babel-loader',
                query: {
                    presets: ['es2015', 'react']
                }
            }
        ]
    },
    stats: {
        colors: true
    },
    devtool: 'source-map'
};


package.json

{
  "name": "todo-assignment",
  "version": "1.0.0",
  "description": "simple todo application",
  "main": "index.js",
  "scripts": {
    "webpack": "webpack",
    "start": "webpack --config webpack.config.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "todo"
  ],
  "author": "Uzma Parveen Khan",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.3",
    "babel-preset-es2015": "^6.24.0",
    "babel-preset-react": "^6.23.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "webpack": "^2.7.0",
    "webpack-cli": "^2.0.12"
  },
  "dependencies": {}
}

js/app.js

import React from 'react';
import ReactDOM from 'react-dom';

import HelloWorld from './helloworld.jsx';

ReactDOM.render(
    <HelloWorld/>,
    document.getElementById('container')
);

helloworld.jsx

import React from 'react';

export default class HelloWorld extends React.Component{
    render(){
        return <h1>Hello World from 'helloworld.jsx'!</h1>
    }
}

index.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div id="container"></div>
</body>
</html>


Please help !!

**Comment by CreatiCoding** [comment]
I have same error, but I can't solve it. I think it is about babel. Someone help me..T_T

**Comment by Rahulshahare** [comment]
this little code work for me
  {test: /\.jsx$/ , loader:'babel-loader', exclude: '/node_modules/'}

**Comment by jose920405** [comment]
@Rahulshahare 

Your code exactly where you should go?

i'm trying:

```
 module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        use: [
          {
            loader: 'babel-loader',
            exclude: '/node_modules/',
            options: {
              presets: ['es2015'], //Fixing `ERROR in bundle.js from UglifyJs`
            },
          },
        ],
      },
    ],
```

But not works

**Comment by liuqi0328** [comment]
I got same error! 
I am configuring my react project and it shows me '<' got error which is not common. I guess this is babel configuration problem, not the code itself. However I am still trying to set up .babelrc...

`
app/routes.js: Unexpected token (11:4)

   9 | 
  10 | export default (
> 11 |     <Route handler={App}>
       |      ^
  12 |         <Route path='/' handler={Home} />
  13 |     </Route>
  14 | );
`

**Comment by ashwinkalyanpur** [comment]
Failed to compile.

./src/registerServiceWorkers.js
  Line 15:  'isLocalhost' is not defined              no-undef
  Line 17:  'registerValidSW' is not defined          no-undef
  Line 20:  'checkValidServiceWorker' is not defined  no-undef

not allowing me to build the project

**Comment by VidushiR** [comment]
Facing the same error .. Error is:ERROR in ./src/index.js 5:16
Module parse failed: Unexpected token (5:16)
You may need an appropriate loader to handle this file type.
| import App from './components/App';
|
> ReactDOM.render(<App />, document.querySelector('#root'));
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js main[1]
i ｢wdm｣: Failed to compile.

Here is my webpack.config.js file"

```
module.exports = {
    entry: './src/index.js', 
    output: {
        filename: '[name].bundle.js', 
        path: __dirname, 
        publicPath: __dirname
    }
};
```

my indexx.js file

```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './components/App';
 
ReactDOM.render(<App />, document.querySelector('#root'));
```

my package.json file
```

{
  "name": "videos",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "axios": "^0.18.0",
    "lodash": "^4.17.11",
    "react": "^16.8.1",
    "react-dom": "^16.8.1",
    "react-scripts": "^2.1.5"
  },
  "scripts": {
    "dev": "webpack-dev-server --env.development",
    "prod": "webpack --env.production",
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "uglify-js-brunch": "^2.10.0",
    "webpack": "^4.29.5",
    "webpack-cli": "^3.2.3",
    "webpack-dev-server": "^3.2.1"
  }
}

```

please help me to solve this error.
TIA!

**Comment by mylittleZ** [comment]
> @Couto Thank you a lot.

how did you solve this?I am the  same error as you.and i can't solve it

**Comment by timkraut** [comment]
We had the issue that our Webpack configuration worked just fine locally but failed in the CI pipeline.  For whatever reason, we have to use `use: [...]` instead of `loaders: [...]` to load multiple loaders in sequence and use `exclude: /node_modules/` without excluding additional directories. Maybe this is helpful for someone with this issue.

**Comment by Gudu4Real** [comment]
Have the same problem. 

```
WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in ./src/lib.js 5:2
Module parse failed: Unexpected token (5:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| export const hello = (
>   <h1
|     id="title"
|     className="header"
 @ ./src/index.js 3:0-42 7:9-14 7:20-27
```
Here is the lib.js 
```
import React from "react";
import text from "title.json";

export const hello = (
  <h1
    id="title"
    className="header"
    style={{ background: "Yellow", color: "white" }}
  >
    {text.hello}
  </h1>
);

export const goodbye = (
  <h1
    id="title"
    className="header"
    style={{ background: "Yellow", color: "white" }}
  >
    {text.goodbye}
  </h1>
);

```
Here is the Webpack.config.js

```
var webpack = require("webpack");

module.export = {
  entry: "./src/index.js",
  mode: "development",
  output: {
    path: "dist/assets",
    filename: "bundle.js",
    publicPath: "assets"
  },

  devServer: {
    inline: true,
    contentBase: "./dist",
    port: 3000
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /(node_modules)/,
        loader: "babel-loader"
      },

      {
        test: /\.json$/,
        exclude: /(node_modules)/,
        loader: "json-loader"
      }
    ]
  }
};
```
Package.json

```
{
  "name": "react_review",
  "version": "1.0.0",
  "description": "Reviewing the react JS library ",
  "main": "index.js",
  "scripts": {
    "start": "./node_modules/.bin/webpack-dev-server"
  },
  "author": "Paul Gudu",
  "license": "ISC",
  "dependencies": {
    "babel-cli": "^6.26.0",
    "json-loader": "^0.5.7",
    "react": "^16.12.0",
    "react-dom": "^16.12.0"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-loader": "^8.0.6",
    "babel-preset-latest": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "webpack": "^4.41.6",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.10.3"
  }
}

```

And the babelrc 

```
{
  "presets": [
    "@babel/preset-latest",
    "@babel/preset-react",
    "@babel/preset-stage-0"
  ]
}
```

**Comment by clr1235** [comment]
I have the same problem.
webpack.config.js 
{
    test: /\.(j|t)sx?$/,
    include: [resolve('src')],
    exclude: /node_modules/,
    use: [
      {
        loader: 'babel-loader',
        
        options: {
          babelrc: false,   // 不启用.babelrc文件中的配置
          presets: [
            '@babel/preset-env',
            '@babel/preset-react',
            ['@babel/preset-typescript', {
              allExtensions: true // 支持所有文件扩展名
            }]
          ],
          plugins: [
            ['import', { libraryName: 'antd', libraryDirectory: 'lib', style: true }],
            ['@babel/plugin-proposal-decorators', { legacy: true }],
            ['@babel/plugin-proposal-class-properties', { loose: true }],
            '@babel/plugin-syntax-dynamic-import'
          ]
        }
      }
    ]
  }

ERROR:
ERROR in ./index.tsx 7:2
Module parse failed: Unexpected token (7:2)
You may need an appropriate loader to handle this file type, currently no loader
s are configured to process this file. See https://webpack.js.org/concepts#loade
rs
|
| ReactDOM.render(
>   <Hello compiler="typeScript" framework="react" />,
|   document.getElementById('root')
| )
 @ multi ./index.tsx app[0]


help

**Comment by EagleEyeKestreI** [comment]
> I have the same problem.
> webpack.config.js
> {
> test: /.(j|t)sx?$/,
> include: [resolve('src')],
> exclude: /node_modules/,
> use: [
> {
> loader: 'babel-loader',
> 
> ```
>     options: {
>       babelrc: false,   // 不启用.babelrc文件中的配置
>       presets: [
>         '@babel/preset-env',
>         '@babel/preset-react',
>         ['@babel/preset-typescript', {
>           allExtensions: true // 支持所有文件扩展名
>         }]
>       ],
>       plugins: [
>         ['import', { libraryName: 'antd', libraryDirectory: 'lib', style: true }],
>         ['@babel/plugin-proposal-decorators', { legacy: true }],
>         ['@babel/plugin-proposal-class-properties', { loose: true }],
>         '@babel/plugin-syntax-dynamic-import'
>       ]
>     }
>   }
> ]
> ```
> 
> }
> 
> ERROR:
> ERROR in ./index.tsx 7:2
> Module parse failed: Unexpected token (7:2)
> You may need an appropriate loader to handle this file type, currently no loader
> s are configured to process this file. See https://webpack.js.org/concepts#loade
> rs
> |
> | ReactDOM.render(
> 
> > ,
> > |   document.getElementById('root')
> > | )
> > @ multi ./index.tsx app[0]
> 
> help



> I have the same problem.
> webpack.config.js
> {
> test: /.(j|t)sx?$/,
> include: [resolve('src')],
> exclude: /node_modules/,
> use: [
> {
> loader: 'babel-loader',
> 
> ```
>     options: {
>       babelrc: false,   // 不启用.babelrc文件中的配置
>       presets: [
>         '@babel/preset-env',
>         '@babel/preset-react',
>         ['@babel/preset-typescript', {
>           allExtensions: true // 支持所有文件扩展名
>         }]
>       ],
>       plugins: [
>         ['import', { libraryName: 'antd', libraryDirectory: 'lib', style: true }],
>         ['@babel/plugin-proposal-decorators', { legacy: true }],
>         ['@babel/plugin-proposal-class-properties', { loose: true }],
>         '@babel/plugin-syntax-dynamic-import'
>       ]
>     }
>   }
> ]
> ```
> 
> }
> 
> ERROR:
> ERROR in ./index.tsx 7:2
> Module parse failed: Unexpected token (7:2)
> You may need an appropriate loader to handle this file type, currently no loader
> s are configured to process this file. See https://webpack.js.org/concepts#loade
> rs
> |
> | ReactDOM.render(
> 
> > ,
> > |   document.getElementById('root')
> > | )
> > @ multi ./index.tsx app[0]
> 
> help

hello, have you solved this?

**Comment by Tpona** [comment]
Anybody solved this problem? ))

**Comment by sauravvsonu** [comment]
Module parse failed: Unexpected token (11:25)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
|   restart() {
>      this.game = new Game{
|       CONFIG.WIDTH,
|       CONFIG.HEIGHT,
 @ ./index.js 1:0-48 3:24-35
 @ ./bootstrap.js
i ｢wdm｣: Failed to compile.


what is error in line "this.game = new Game{ "  not getting

**Comment by Couto** [comment]
> what is error in line "this.game = new Game{ " not getting

As far as I know, `new Game{` is not a valid syntax in JavaScript. Maybe you meant something like `new Game(` ?

**Comment by UtmostCreator** [comment]
I had the same issue.

You may encounter this problem if you have some error e.g. in JS file like this: `const makeImage (url) => {//some code}`. there is no assign operator `=`  in this line of code after the `makeImage`, and it throws this error too (at least webpack 5.0 and higher).

**Comment by soumyavidushi** [comment]
updating .babelrc and webpack.config.ts like below resolved the issue for me
.babelrc

{
"presets": ["@babel/react"]
}

webpack.config.ts

const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    entry: './app/index.js',
    module: {
      rules: [{ test: /\.(js|jsx)$/, use: "babel-loader", exclude: /node_modules/ },
      { test: /\.css$/, use: ["style-loader",'css-loader']}]
    },
    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: 'index_bundle.js'
    },
    plugins: [
      new HtmlWebpackPlugin({
        template: 'app/index.html'
      })
    ],
    mode: 'development'
}
