### ISSUE TITLE
Transpile ES6 Class to library (AMD) fails

### ISSUE THREAD

**Issue by kevguy** [babel/babel-loader#373]
I'm trying to write a class in ES6 and transpile it into a library as an AMD module with Babel (and bundle with jQuery in the same file) so people can use it like this:

    <script src="Foo.js"></script>
    <script>
        var dummy = new Foo();
    </script>

I followed the solution [here][1] and arrange my folder like this:
    
    -dist
    -js
      |--Foo.js
      |--main.js
    -lib
      |--jquery.js
    -node_modules
    -webpack.config.js
    -.babelrc
    -.eslintrc
    -package.json

and `Foo.js`:

    import $ from '../lib.jquery.js';

    export default class Foo {
        constructor(){
            /* jQuery stuff */
        }
    }

and `main.js`:
    
    module.exports = require('./Foo.js').default;

and `webpack.config.js`:
    
    require('babel-polyfill');
    const path = require('path');
    const webpack = require('webpack');

    module.exports = {
        name: "bundle-js",
        entry: {
            Foo: [
                // configuration for babel6
                'babel-polyfill',
                './js/main.js'
            ]
        },
        output: {
            path: path.resolve(__dirname, 'dist'),  // ./build
            filename: '[name].bundle.js',
            library: 'Foo',
            libraryTarget: 'umd'
        },
        module: {
            rules: [{
                test: /\.js$/,
                loader: ['babel-loader', 'eslint-loader'],
                exclude: /node_modules/,
            }]
        },
        stats: {
            colors: true
        },
        devtool: 'source-map'
    };

and `.babelrc`:

    {
        "plugins": ["transform-es2015-modules-amd"],
        "presets": ["react", "es2015","stage-0"]
    }

And I kept getting this error:

    js/main.js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null

I've been Googling for a week and I couldn't find any solutions except the link I included. I can't tell if I'm writing the wrong config or if there's actually an issue with babel-loader. Can somebody please look into it and tell me what went wrong so I can fix it? AMD is more of my preference, so if someone has a solution that uses CommonJS and does the same thing, I'm open to it.

  [1]: http://stackoverflow.com/questions/37912857/exporting-a-class-with-webpack-and-babel-not-working

**Comment by danez** [comment]
This is not an issue with babel-loader, but with babel itself. 

Relevant issues:
https://github.com/babel/babel/issues/4281
https://github.com/babel/babel/issues/4072

Try changing `Foo.js` to as a workaround:

```js
var Foo = require('./Foo.js');
module.exports = Foo.default;
```
