### ISSUE TITLE
Can "arguments" be passed into super()?

### ISSUE THREAD

**Issue by trusktr** [babel/babel-loader#38]
I'm trying something like

```js
class Foo extends Bar {
  constructor() {
    super(arguments);
  }
}
```

which doesn't work. But if I manually name the arguments like

```js
class Foo extends Bar {
  constructor(one, two, three) {
    super(one, two, three);
  }
}
```

then it works!

Is there something regarding `super` and `arguments` that I've missed?

**Comment by trusktr** [comment]
Oh, duh! It's not the same as using `.apply(ctx, arguments)`.

**Comment by Couto** [comment]
In ES6 (or ES2015 I'm never quite sure about the new name) you hardly need to use the arguments keyword and you can just use the spread operator, [take a look](https://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=false&spec=false&code=class%20Bar%20{%0A%20%20constructor%20%28...args%29%20{%0A%20%20%20%20console.log%28args%29%3B%0A%20%20}%0A}%0A%0Aclass%20Foo%20extends%20Bar%20{%0A%20%20constructor%20%28...args%29%20{%0A%20%20%20%20super%28...args%29%3B%0A%20%20}%0A}%0A%0Avar%20foo%20%3D%20new%20Foo%281%2C2%2C3%29)

**Comment by trusktr** [comment]
@Couto Ah, cool!
