### ISSUE TITLE
Emit Errors not Warnings

### ISSUE THREAD

**Issue by DylanPiercey** [babel/babel-loader#382]
**I'm submitting a feature request**

**Webpack Version:**
2.x

**Babel Core Version**:
6.x

**Babel Loader Version**:
6.2.x

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
Currently babel-loader emits soft errors / warnings on syntax errors within babel.

**Expected/desired behavior:**
Either make it so that the loader emits errors or add a configuration option to change from warnings to errors.

* **What is the motivation / use case for changing the behavior?**
This makes it so that the errors do not show up nicely when paired with 'webpack-hot-middleware/client-overlay' which expects errors and also seems kinda weird that a syntax error is a warning.

**Comment by danez** [comment]
All the loader is doing afaik is throwing an exception when an error happens (if not using cacheDirectory) or setting `err` in the async-callback (when using cacheDirectory), and in both cases I expect webpack to handle these as errors.

Are you using `cacheDirectory`?

**Comment by DylanPiercey** [comment]
I am not using cacheDirectory. But this is weird, I just spent a bit looking through everything and I can see that you are throwing the error but I am honestly not too familiar with how webpack handles that. At any rate it's still going on. This may not be an issue with this module but if not would you have any ideas? My CSS build (using css-loader) seems to work fine and emits errors properly.
