### ISSUE TITLE
babel-loader doesn't work for webpack-dev-server

### ISSUE THREAD

**Issue by zzzgit** [babel/babel-loader#393]
https://stackoverflow.com/questions/42396438/babel-loader-doesnt-work-for-webpack-dev-server

I have post a question on stackoverflow,but no one can help me.
I upload the source code to [github](http://github.com/zzzgit/bug_with_webpack-dev-server).Is there someone could help me?

**Comment by zzzgit** [comment]
the reason is that I have not installed a local webpack-dev-server,and just use a global one.
I wonder how come is get a result like this?

**Comment by danez** [comment]
Mixing global and local node_modules do not work. global modules like webpack-dev-server will only search for all loaders in the global installed packages, and the same applies for local ones. You might be able to work around this by using the webpack option resolveLoader: https://webpack.js.org/configuration/resolve/#resolveloader
