### ISSUE TITLE
babel-loader failing to transpile webpack2

### ISSUE THREAD

**Issue by hendrikeng** [babel/babel-loader#394]
**I'm submitting a bug report**
Somehow babel-loader refuses to transpile the code, as it did before 

**Webpack Version:**
 "webpack": "2.2.1"

**Babel Core Version**:
 "babel-core": "^6.23.1"

**Babel Loader Version**:
"babel-loader": "^6.3.2"

**Please tell us about your environment:**
OSX 10.12.3

**Current behavior:**
babel loader wont transpile the code from es2015 to es5
````
ERROR in ./src/js/index.js
Module build failed: SyntaxError: 'import' and 'export' may only appear at the top level (8:2)

   6 | const flickity = document.querySelector('.js-slider--hero');
   7 | if (flickity) {
>  8 |   import('./modules/flickity')
     |   ^
   9 |     .then(module => module.flickity);
  10 | }
````

**Expected/desired behavior:**
transpiling to es5 (worked before)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

https://gist.github.com/hendrikeng/97f191de4b07d55670e3f10bcf817f74

**Comment by loganfsmyth** [comment]
`import()` is brand new experimental proposal. Since you are using Webpack 2, I'd expect your Webpack config to be

     {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader?presets[]=es2015',
        query: {
          presets: [['es2015', {modules: false}]],
          plugins: ['syntax-dynamic-import'],
        }
      }

You'll also have to `npm install --save-dev babel-plugin-syntax-dynamic-import`

**Comment by hendrikeng** [comment]
thanks a lot, its working 👍
