### ISSUE TITLE
Babel throughing error for ES6 syntax.

### ISSUE THREAD

**Issue by MaddulaSaiKrishna** [babel/babel-loader#399]
Hi,

Im setting up environment for React JS using webpack and babel. But im getting error with babel-loaders.
Here are my setup files.
# **Package.json:**

```
{
  "name": "reactjs",
  "version": "0.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babel-core": "^6.23.1",
    "babel-loader": "^6.3.2",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-react": "^6.23.0",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "webpack": "^2.2.1"
  }
}
```

# **webpack.config.js:**

```
var webpack = require('webpack');
var path = require('path');

var BUILD_DIR = path.resolve(__dirname, 'src/client/public');
var APP_DIR = path.resolve(__dirname, 'src/client/app');

var config = {
  entry: APP_DIR + '/index.jsx',
  output: {
    path: BUILD_DIR,
    filename: 'bundle.js'
  },
  module : {
    loaders : [
      {
        test : /\.jsx?/,
        include : APP_DIR,
        loader : 'babel'
      }
    ]
  }
};

module.exports = config;
```

# **# .babelrc:**

```
{
  "presets" : ["es2015", "react"]
}
```

# **Below is the error im getting:**

```
ERROR in C:/wamp/www/React js/src/client/app/index.jsx
Module parse failed: C:\wamp\www\React js\src\client\app\index.jsx Unexpected to
ken (6:11)
You may need an appropriate loader to handle this file type.
| class App extends React.Component {
|   render () {
|     return <p> Hello React!</p>;
|   }
| }
```

**Comment by hzoo** [comment]
Can you format you code/config? It's hard to see what's going on here.

You can use ` ``` ` for code blocks

**Comment by loganfsmyth** [comment]
Maybe you need to use `\` instead of `/` in `APP_DIR`?

**Comment by MaddulaSaiKrishna** [comment]
@hzoo  Code formatted.

**Comment by MaddulaSaiKrishna** [comment]
@loganfsmyth  It also didnt worked. As per the error console given, it is able to read the code but it is not able to understand ES6/JSX syntax is what im suspecting.

**Comment by MaddulaSaiKrishna** [comment]
The problem is with env path variable. Previously, I'm able to access webpack from node_modules/.bin folder but config file is somewhere in my root directory(not in .bin folder).This is the reason for the issue. After modifying env path variable and running webpack, resolved this issue.
