### ISSUE TITLE
Inconsistency with React's jsx-loader

### ISSUE THREAD

**Issue by omerts** [babel/babel-loader#40]
Hello,

First of all thanks for the great library. 
I am using Babel along with React & Webpack, and your loader is very handy. 
There is a small inconsistency between React and babel-loader in using spread attributes in JSX.
If we take the following example:
```javascript
 var { checked, title, ...other } = this.props;
...
<label>
        <input {...other}
          checked={checked}
          className={fancyClass}
          type="checkbox"
        />
```
In Babel I get the following error:
![image](https://cloud.githubusercontent.com/assets/4996164/6615320/8f74362a-c8ab-11e4-8722-b8ff12611761.png)

**Comment by Couto** [comment]
There's nothing much that babel-loader can do about the output of the generated code, since this just abstract the babel's library in a way useful to webpack.
 
You should report the issue on [babel's issue tracker](https://github.com/babel/babel/issues) itself :)

**Comment by sebmck** [comment]
Hey @omertes, this is the repo for the webpack plugin. Potential issues
like these should be reported on the main babel repo. I'm a bit confused by
what the actual issue is. Can you elaborate more?

On Thursday, 12 March 2015, omerts <notifications@github.com> wrote:

> Hello,
>
> First of all thanks for the great library.
> I am using Babel along with React & Webpack, and your loader is very
> handy.
> There is a small inconsistency between React and babel-loader in how
> spread objects names are after the spread.
> If we take the following example:
>
>  var { checked, title, ...other } = this.props;
>
> In React, to use the ...other you use it along with the "...", and in
> Babel it is used without the "...".
>
> For example:
> -React:
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel-loader/issues/40>.
>


-- 
Sebastian McKenzie

**Comment by omerts** [comment]
Wow you guys are quick :) 
Ok, I will report it in the main babel repo.
@sebmck, I just updated the issue, hope it is clearer.
