### ISSUE TITLE
babel-polyfill - error Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by ozee31** [babel/babel-loader#401]
**I'm submitting a bug report**

**Webpack Version:**
1.14.0

**Babel Core Version**:
6.23.1

**Babel Loader Version**:
6.3.2

**Please tell us about your environment:**
Windows 10

**Current behavior:**
I try to use babel-polyfill for ie11 with webpack

```
entry: {
    app: ['babel-polyfill','./src/main.js']
}
```

After ie11 reconize Array.includes but in some pages i have error in other browsers like Firefox
`error Error: only one instance of babel-polyfill is allowed`

**Comment by abouthiroppy** [comment]
Have you imported with `./src/main.js` already?

**Comment by ozee31** [comment]
yes but i have the same message

**Comment by abouthiroppy** [comment]
Please you exclude `babel-polyfill` from your codes or exclude from webpack.entry.
There can only be one instance of `babel-polyfill`.

**Comment by danez** [comment]
as @abouthiroppy already said, you either load the app bundle twice or you import babel-polyfill somewhere else in your code. Ensure it is only used once.

**Comment by ozee31** [comment]
I only included it once but i have always this message. But not every time, just on some components. 
It must be my fault

**Comment by IvanKelber** [comment]
I came across this error and found that I was loading my javascript inside the body of my application instead of the head.

**Comment by tmm1** [comment]
> I came across this error and found that I was loading my javascript inside the body of my application instead of the head.

Really, so moving into `<head>` fixed it? That seems strange..

**Comment by aaronromeo** [comment]
I had a similar problem using [webpacker](https://github.com/rails/webpacker). I was loading two javascript apps on the same page using the `javascript_pack_tag`. I'm assuming each one loads an instance of `babel-polyfill`. I was able to resolve the issue by merging both apps and using a single loading point.

**Comment by ozee31** [comment]
I close my issue, think you for yours answers

**Comment by swarajban** [comment]
I was also seeing this error, but after checking my html, I was also including my bundled JS twice. Fixed by updating my HTML to ensure I only include my bundle once

**Comment by lipemat** [comment]
There was another 3rd party library which included the `babel-polyfill` in their bundle. To fix this I had to remove the `babel-polyfill` from the entry in `webpack.config` and add a conditional require to the top of my `index.js` which is the entry point. 

Before webpack.config:
```
module.exports = {
	devtool : devtool,
	entry : [
		'babel-polyfill', './src/index'
	]
}

```
After webpack.config:
```
module.exports = {
	devtool : devtool,
	entry : [
		'./src/index'
	]
}
```
Added to the top of ./src/index.js:
```
if (!global._babelPolyfill) {
	require('babel-polyfill');
}
```
Now everything works without issue.

**Comment by timperkins** [comment]
I had a Chrome extension that was using babel-polyfill, which was causing this error. Took forever to track that down!

Another way to fix this is by setting `global._babelPolyfill = false;` at the top of your index.js file.

**Comment by samfullman** [comment]
@lipemat I did the first part of what you said for a different project (https://github.com/richardtallent/vue-simple-calendar/tree/2.2.1) but without the `if(!global.etc)..` part added and it worked fine.  However that may be the requirements of that package in this case.

**Comment by yvele** [comment]
Related to https://github.com/babel/babel/issues/4019

**Comment by codejamninja** [comment]
Idempotent Babel Polyfill can be imported multiple times

```sh
npm install --save idempotent-babel-polyfill
```

```js
import 'idempotent-babel-polyfill';
```

**Comment by MarkSky** [comment]
Excuse me!
I would like to know where to put `import 'idempotent-babel-polyfill';`?
In my index.js or in webpack.config.js?

**Comment by nicolo-ribaudo** [comment]
You should replace every `"babel-polyfill"` (either in imports, or in your webpack config's `entry` option) with `idempotent-babel-polyfill`

**Comment by visualjerk** [comment]
When you need to actually import 'babel-polyfill' instead of require it, you can achieve @lipemat's solution by adding a new file **require-babel-polyfill.js** with following contents:

```javascript
export default (() => {
  if (!global || !global._babelPolyfill) {
    require('babel-polyfill')
  }
})()
```

and import that file in at the top of your apps entry point (index.js):

```javascript
import './require-babel-polyfill.js'
```

**Comment by codejamninja** [comment]
@visualjerk, aka idempotent-babel-polyfill

**Comment by visualjerk** [comment]
@codejamninja Yeah, seems like your module is achieving the same. I actually did not try it out, because the solution was pretty simple.

Thanks for putting this on npm, making it even easier to use.

**Comment by codejamninja** [comment]
@visualjerk, it also works in the browser, because babel-polyfill attaches to the window object in a browser.

**Comment by hejiaji** [comment]
@lipemat this approach is the good way

**Comment by mohanasundarR** [comment]
@swarajban thanks man it helped me too

**Comment by BlackeyCat** [comment]
thanks

**Comment by saptarshimondal** [comment]
> Idempotent Babel Polyfill can be imported multiple times
> 
> ```shell
> npm install --save idempotent-babel-polyfill
> ```
> 
> ```js
> import 'idempotent-babel-polyfill';
> ```

This solved my issue with firefox extension, Thanks.
