### ISSUE TITLE
babelrc: false still reads .babelrc file

### ISSUE THREAD

**Issue by hulkish** [babel/babel-loader#418]
**I'm submitting a bug report**

**Webpack Version:**
2.2.1

**Babel Core Version**:
~5.24.0~
6.24.0

**Babel Loader Version**:
6.4.0

**Please tell us about your environment:**
maxOS 10.12.3

**Current behavior:**
When using `babelrc: false`, babel-loader still reads from babelrc file

**Expected/desired behavior:**
Should not read from babelrc file

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
https://gist.github.com/hulkish/5d225beda0fc6cc1c1332befc00f0edf

* **What is the expected behavior?**
(per the example) react-hot-loader/babel should **not** be included in bundle. However, it indeed does show up.

* **What is the motivation / use case for changing the behavior?**
babelrc: false should completely ignore all .babelrc files

**Comment by hulkish** [comment]
anyone else seeing this?

**Comment by loganfsmyth** [comment]
I think that option may not work on `babel-loader` for Babel 5.

**Comment by hulkish** [comment]
@loganfsmyth I corrected my typo, thanks for pointing out - I'm actually using `babel-core@6.4.0`

**Comment by loganfsmyth** [comment]
You'll want to make sure both `babel-core` and `babel-loader` are up to date.

**Comment by hulkish** [comment]
@loganfsmyth I'm using the latest for both.

I wonder... could it be that I'm using `options` instead of `query`? Isn't it `options` for webpack 2?  Ex: https://gist.github.com/hulkish/5d225beda0fc6cc1c1332befc00f0edf#file-webpack-config-js

**Comment by loganfsmyth** [comment]
Have you verified that if you comment out the line in the .babelrc you don't see any of your code you're seeing in there? Maybe it is getting in there some other way?

**Comment by existentialism** [comment]
@hulkish options/query shouldn't be a problem as [`loaderUtils.getOptions`](https://github.com/babel/babel-loader/blob/7.0/src/index.js#L96) does a [check for both](https://github.com/webpack/loader-utils/blob/master/lib/getOptions.js).

**Comment by hulkish** [comment]
What could cause `babel-loader` to be ignoring my babelrc: false`?

**Comment by hulkish** [comment]
ive determined this is related to my configHash function being too narrow in scope

**Comment by shahankit** [comment]
@hulkish I'm having same issue. I'm having similar webpack config file and want to skip babelrc and rather use the config set in webpack file.

```
module: {
  loaders: [
    {
      test: /\.js$/,
      loader: 'babel-loader',
      include: path.join(__dirname, 'app'),
      options: {
        babelrc: false,
        presets: ['react', 'es2015', 'stage-0'],
        plugins: ['babel-plugin-transform-decorators-legacy']
      }
    },
    {
      test: /\.css$/,
      loaders: ['style-loader','css-loader','postcss-loader']
    },
    {
      include: /\.json$/,
      loaders: ["json-loader"]
    }
  ]
},
```
