### ISSUE TITLE
DeprecationWarning: loaderUtils.parseQuery()

### ISSUE THREAD

**Issue by danielverejan** [babel/babel-loader#422]
Related to [loader-utils issue](https://github.com/webpack/loader-utils/issues/56)

**Webpack Version:**
2.2.1

**Babel Core Version**:
6.24.0

**Babel Loader Version**:
6.4.0

**Please tell us about your environment:**
Windows 10, node 7.7.2

**Current behavior:**
It throws deprecation warnings at `lib/index.js:96:35`

**Comment by existentialism** [comment]
@danielverejan try https://github.com/babel/babel-loader/releases/tag/v7.0.0-alpha.3

**Comment by phfaster** [comment]
@existentialism don't work:( With v7-alpha.3 error "ERROR in Entry module is not found: Error: Can not resolve 'babel-loader'". And I could not solve it in any way :(

**Comment by mnpenner** [comment]
`babel-loader@7.0.0-alpha.3` made the warning go away for me.

**Comment by danielverejan** [comment]
What are the known issues of alpha 3 if any?

**Comment by danielverejan** [comment]
@phfaster your problem my be in something else, can you post the full error log?

**Comment by phfaster** [comment]
@danielverejan yes, I also think that the error is in another. Webpack does not find loaders installed using the npm commands i --save-dev `babel/babel-loader.git#fork`

Console offered two debug-files:
[2017-03-16T08_10_48_680Z-debug.txt](https://github.com/babel/babel-loader/files/847051/2017-03-16T08_10_48_680Z-debug.txt)
[2017-03-16T08_10_48_688Z-debug.txt](https://github.com/babel/babel-loader/files/847050/2017-03-16T08_10_48_688Z-debug.txt)

**Comment by danielverejan** [comment]
You should use this for installs
`npm install babel-loader --save-dev`  
no need there for *commands* or the *.git#fork*...  
if you want to install a specific version of it use that
`npm install babel-loader@7.0.0-alpha.3 --save-dev`   
read more on [npm docs](https://docs.npmjs.com/getting-started/installing-npm-packages-locally)

**Comment by phfaster** [comment]
@danielverejan Thaaanks! I found this installation method when I could not install Gulp.JS version 4 using `gulp@4`. Now everything works, thanks! :)

**Comment by burrack** [comment]
@danielverejan 
So to solve this issue I should wait for version 7.0.0 to come out?

**Comment by danielverejan** [comment]
@burrack or install the v7.0.0-beta.1

**Comment by danez** [comment]
Fixed with 7.0.0
