### ISSUE TITLE
Babel loader don't work with native async functions

### ISSUE THREAD

**Issue by TrustNik** [babel/babel-loader#429]
**I'm submitting a bug report**

**Webpack Version:**
1.14.0

**Babel Core Version**:
6.24

**Babel Loader Version**:
6.4.1

**Please tell us about your environment:**
OSX 10.x

I am setting up a project that will only be used in newest Chrome (55+), so I am sure that it will support async await natively. Therefore I don't need any transpiling of such constructions.
babel-cli works perfectly fine for me, leaving async constructions untouched.
However if I try to setup the same using webpack and babel-loader I get the following error:

```
ERROR in ./src/index.js
Module parse failed: /Users/trustnik/work/fl4re/babel-async/node_modules/babel-loader/lib/index.js!/Users/trustnik/work/fl4re/babel-async/src/index.js Unexpected token (3:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (3:6)
    at Parser.pp$4.raise (/Users/trustnik/work/fl4re/babel-async/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/trustnik/work/fl4re/babel-async/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/trustnik/work/fl4re/babel-async/node_modules/acorn/dist/acorn.js:581:61)
```

I've created a simple repo with the repro of my issue.

https://github.com/TrustNik/babel-async

Here one can see [.babelrc](https://github.com/TrustNik/babel-async/blob/master/.babelrc)
[webpack.config.js](https://github.com/TrustNik/babel-async/blob/master/webpack.config.js)
[index file](https://github.com/TrustNik/babel-async/blob/master/src/index.js)
and [the result I get](https://github.com/TrustNik/babel-async/blob/master/build/cli-out.js) running **npm run babel-cli** task. This task is using vanilla babel-cli to transpile.
If I try to run **npm run webpack-cli** I get the issue mentioned above.

Since everything works fine with babel-cli, I think this issue is related to webpack and babel-loader setup. Please redirect me otherwise.

Thanks

**Comment by loganfsmyth** [comment]
It's definitely not clear from that error, but Webpack 1 itself does not support async functions, so if you pass them through Babel (which you're doing right from what I can see), Webpack itself will throw, which is what you're seeing here.

**Comment by TrustNik** [comment]
Thank you @loganfsmyth !
I've added a [commit](https://github.com/TrustNik/babel-async/commit/144c12e5e723cc4c581db468c8795b2f3bcb912e) where I switch to webpack2 and everything works.
Closing this issue.
