### ISSUE TITLE
modules

### ISSUE THREAD

**Issue by tarikme** [babel/babel-loader#432]
## **BEFORE YOU SUBMIT** please read the following:

*Delete what isn't applicable below*
**I'm submitting a bug report**
**I'm submitting a feature request**
**I'm submitting a support request** => Please do not submit support request here, see note at the top of this template.

**Webpack Version:**
1.10.x/2.x

**Babel Core Version**:
6.x

**Babel Loader Version**:
5.4.x/6.2.x

**Please tell us about your environment:**
OSX 10.x / Linux / Windows 10

**Current behavior:**

**Expected/desired behavior:**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by hzoo** [comment]
There's not enough info here to help with your request, so closing, can reopen if you provide reproduction steps, etc.

Thanks for making an issue! However, issues are not for support questions but rather for reporting bugs/features requests.

If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
