### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by charlespeters** [babel/babel-loader#436]
**Webpack Version:**
2.3.2

**Babel Core Version**:
6.18.2

**Babel Loader Version**:
6.4.1

**Please tell us about your environment:**
macOS 10.12.4

**Current behavior:**
Not compiling JSX files that live in node_modules

**Expected/desired behavior:**
To resolve JSX files and compile without error

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

https://gist.github.com/charlespeters/a2cd11cabc68b9ffa332f542ac82d65a

**Comment by loganfsmyth** [comment]
You have ` exclude: /(node_modules|bower_components)/,` in the `babel-loader` config explicitly skipping `node_modules`. If you don't want that, I'd recommend changing the regex to allow the module you want through.
