### ISSUE TITLE
forceEnv does not merge default & env-specific options

### ISSUE THREAD

**Issue by BrendonEarl** [babel/babel-loader#437]
**I'm submitting a bug report**

**Webpack Version:**
2.3.3

**Babel Core Version**:
6.24.0

**Babel Loader Version**:
6.4.1

**Please tell us about your environment:**
OSX 10.12.3

**Current behavior:**
Using the `forceEnv` option only includes options found within that environment tag in .babelrc

**Expected/desired behavior:**
According to [babel documentation](https://babeljs.io/docs/usage/babelrc/#env-option) when using an environment: 

> Options specific to a certain environment are merged into and overwrite non-env specific options

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

In Webpack config:
```js
{
	test: /\.js?$/,
	enforce: "post",
	exclude: /node_modules/,
	use: {
		loader: 'babel-loader',
		options: {
			forceEnv: 'client-production'
		}
	}
}
```
in .babelrc
```json
{
	"presets": ["stage-0"],
	"plugins": ["transform-decorators-legacy", "transform-inline-environment-variables"],
	"env": {
		"client-production": {
			"presets": ["react", ["es2015", {"modules": false}]]
		},
	}
}
```

* **What is the expected behavior?**

Babel should receive options:
```json
"presets": ["react", ["es2015", {"modules": false}], "stage-0"],
"plugins": ["transform-decorators-legacy", "transform-inline-environment-variables"]
```
but instead seems to receive only:
```json
"presets": ["react", ["es2015", {"modules": false}]]
```
* **What is the motivation / use case for changing the behavior?**

To align the behaviour of forceEnv with babel documentation of using environment variables (`NODE_ENV` or `BABEL_ENV`)

**Comment by BrendonEarl** [comment]
Additionally, it appears as though this case is not tested in [loader.test (ln 92 & following tests)](https://github.com/babel/babel-loader/blob/ed8711d5275d9d59422d34252b5a99cf67869029/test/loader.test.js#L92).

This may also be related to #184, however I'm unclear on the scope of that issue and would like to address this bug specifically

**Comment by danez** [comment]
babel-loader is not doing anything related to env handling besides setting the environment variable. This seems like an issue in babel itself. 

`env` is also probably going to be deprecated in babel 7.0, because of all this issues and instead you should use `.babelrc.js` which is proper javascript.
