### ISSUE TITLE
Please make plain objects iterable with for...of

### ISSUE THREAD

**Issue by Polyergic** [babel/babel-loader#443]
**I'm submitting a feature request**

**Webpack Version:**
webpack@2.2.0-rc.3

**Babel Versions**:
babel-polyfill@6.20.0
babel-runtime@6.22.0

**Please tell us about your environment:**
macOS Sierra 10.12.4

**Current behavior:**

Use of a for...of loop on a plain object causes the runtime error "undefined is not a function".

This error is badly uninformative; it can occur on a line that has no function calls that could be undefined, or on a line that does have function calls which work correctly.

That there is an error is consistent with the claim that plain objects are not iterable, made in https://github.com/babel/babel-loader/issues/84#issuecomment-120138968.

**Expected/desired behavior:**

Please make plain objects iterable.
If you refuse that, please make it a compiler error.
If you refuse both of those, please make it a more informative runtime error.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

Instance variable declaration:
```
    resourceTree: any = {}; // Dictionary of sectionName:string => section:any which is a dictionary of resourceLabel:string => resource:StudentResource
```
Inside instance method body:
```
            for( let resource of this.resourceTree[sectionName] ) {
```

* **What is the expected behavior?**

Iterating over the values of the object, _just like the ES6 for...of_

* **What is the motivation / use case for changing the behavior?**

1. Following the Principle of Least Surprise

2. Compatibility with ECMAScript

3. I suspect it has less run-time overhead

This particular instance method is returning the contents of a dictionary as an array for backward compatibility.  Here's how I wanted to write the loop:
```
            for( let resource of this.resourceTree[sectionName] ) {
                resources.push( resource );
            }
```
Simple, runs in O(n) with a fairly small constant.

Here's what I changed it to:
```
            for( let key in this.resourceTree[sectionName] ) {
                let resource:StudentResource = this.resourceTree[sectionName][key];
                resources.push( resource );
            }
```
It looks like most of the work in the body of the loop is dereferencing all of the names involved in getting the resource from the key.  It still runs in O(n), but without digging in to compiler internals it looks like the constant will be significantly larger.

**Comment by hzoo** [comment]
This repo is babel-loader, it doesn't handle how the code is compilied.

If you need to iterate over an object then you need to use a for in loop, or to add Object.keys/values/entries yourself.

Yes object's aren't iterable in that way, the point is that you need to wrap the Object in a `Object.keys(obj)` or something like that.

**Comment by hzoo** [comment]
https://github.com/babel/babel/pull/4747 I'd be cool with making the compiled for of loop a regular for loop if you use Object.keys/values,etc though

**Comment by Polyergic** [comment]
Sorry, I shouldn't have assumed that the repo where I found the problem was the one where I should make the feature request.

**Comment by hzoo** [comment]
Objects don't define a Symbol.iterator method to iterate over, and this is why you need to use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys or for..in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in

There really isn't a runtime error for us to make.

> Sorry, I shouldn't have assumed that the repo where I found the problem was the one where I should make the feature request.

Yeah the original issue was reported in this repo as well. Just for future reference, babel-loader is a loader for webpack so the code is just about intergrating babel with webpack. https://github.com/babel/babel is the main repo

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
