### ISSUE TITLE
Config babel in webpack 2 doesn't work while in .babelrc does, is this normal?

### ISSUE THREAD

**Issue by pronan** [babel/babel-loader#446]
**I'm submitting a bug report**

**Webpack Version:**
2.0

**Babel Core Version**:
6.24.1

**Babel Loader Version**:
7.0.0

**Please tell us about your environment:**
Ubuntu Server 14.04

**Current behavior:**

In the webpack config file, I enter the following lines according to [official docs][1]:

    {
      test: /\.js$/,
      exclude: /(node_modules|bower_components)/,
      use: {
        loader: 'babel-loader',
        options: {
          presets: ['env'],
          plugins: [require('babel-plugin-transform-object-rest-spread')]
        }
      }
    }

But code such as `{...{a:1}}` will raise syntax error. If I config it in `.babelrc` file like this:

    {
      "plugins": ["transform-object-rest-spread"],
      "presets": ["env"],
    }

Everything will be ok even if I delete the whole `options` in webpack config file.

**Expected/desired behavior:**

I want to know if this is normal. 

  [1]: https://github.com/babel/babel-loader

**Comment by searsaw** [comment]
I found this #428 which addresses this.  This would be an issue if you have a `.babelrc` and try to config babel in the webpack config. Try adding `babelrc: false` to the options object in your `babel-loader` config.

**Comment by pronan** [comment]
Thanks.
