### ISSUE TITLE
Module parse failed: (My Path) Unexpected token (6:4) You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by zanas28** [babel/babel-loader#448]
I often get this problem. what I have to do to resolve it ?

Module parse failed: E:\LEARN-PROGRAMMING\React-Scratch\source\index.js Unexpected token (6:4)
You may need an appropriate loader to handle this file type.
|
| ReactDOM.render(
|     <App />,
|     document.getElementById('app')
| );
 @ multi webpack-dev-server/client?http://0.0.0.0:3000 webpack/hot/only-dev-server ./source/index
webpack: Failed to compile.

this is my webpack.config

var path = require('path');
var webpack = require('webpack');

module.exports = {
  devtool: 'inline-source-map',

  entry: [
    'webpack-dev-server/client?http://0.0.0.0:3000', // WebpackDevServer host and port
    'webpack/hot/only-dev-server', // "only" prevents reload on syntax errors
    './source/index' // Your appʼs entry point
  ],

  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/static/'
  },

  resolve: {
    extensions: ['.js', '.jsx']
  },

  plugins: [
    new webpack.HotModuleReplacementPlugin()
  ],

  module: {
    loaders: [{
      test: /\.(js|jsx)$/,
      loaders: ['babel-loader'],
      include: path.join(__dirname, 'src')
    }]
  }
};

Thanks

**Comment by loganfsmyth** [comment]
Your `include` is for `src` but it looks like the directory is called `source`.
