### ISSUE TITLE
Look for .babelrc.js (babel-core v7 compatibility)

### ISSUE THREAD

**Issue by ismay** [babel/babel-loader#452]
**I'm submitting a feature request**

**Webpack Version:**
2.3.0

**Babel Core Version**:
7+

**Babel Loader Version**:
7.0.0

**Please tell us about your environment:**
OSX Sierra

**Current behavior:**

Since babel 7 (which is currently in alpha), it's possible to specify the config with a `.babelrc.js` file. However, babel-loader doesn't yet look for this file, so when using babel-core 7+ with a webpack build, babel-loader and a `.babelrc.js`, my build fails.

**Expected/desired behavior:**

Look for a `.babelrc.js` and use that if it exists. It's backwards compatible so shouldn't have to be a breaking change.

* **What is the motivation / use case for changing the behavior?**

Allowing this config will make dynamic configuration of babel easier, plus it'll prepare babel-loader for the upcoming release.

See also: https://github.com/babel/babel/pull/4892

**Comment by danez** [comment]
Thanks, this will be done in #456.

**Comment by ismay** [comment]
@danez Awesome, thanks

**Comment by ykadosh** [comment]
Has this been fixed yet? I'm using `babel-loader@8.0.5` and `babel/core@7.4.0` but it ignores `.babelrc.js` files completely.

**Comment by juanca** [comment]
I thought I had the same problem but it looks like I forgot the leading `.` in the filename. 

> `babelrc.js` => `.babelrc.js`

I practically have the same set up -- brand new repo:

- `@babel/core@7.4.3`
- `@babel/preset-env@7.4.3`
- `@babel/preset-react@7.0.0`
- `babel-loader@8.0.5`
- `react@16.8.6`
- `react-dom@16.8.6`
- `webpack@4.29.6`
- `webpack-cli@3.3.0`
