### ISSUE TITLE
peerDependencies is deprecated

### ISSUE THREAD

**Issue by necolas** [babel/babel-loader#47]
In short, `peerDependencies` should probably be removed:

See for context: https://github.com/npm/npm/issues/6565

**Comment by Couto** [comment]
oh thank god! :)

I'm in lazy mode, since is kinda late already here... so sorry for asking this, but what's the best approach? Just move peerDependencies to regular dependencies?

**Comment by necolas** [comment]
Yes I think you can make babel-core a dependency and drop webpack (which doesn't seem to be used by your tests either).

**Comment by gaearon** [comment]
I don't see anywhere in that issue that they are going to be **removed**. The issue says their **behavior will change** (no longer automatically installing).

**Comment by necolas** [comment]
I didn't say it would be removed :). But `babel-core` shouldn't be a `peerDependency` as well as a `dependency`.

**Comment by gaearon** [comment]
Why not? It's a way to specify compatibility.

**Comment by gaearon** [comment]
If babel-core was moved to dependencies it'd be more complicated to pick specific Babel builds. Being able to pick a specific build is important for tool like Babel that has large impact on your code.

**Comment by necolas** [comment]
Well it's already in the dependencies https://github.com/babel/babel-loader/blob/master/package.json#L7

**Comment by Couto** [comment]
It's in the dependencies for consistency with other babel utilities like [grunt-babel](https://github.com/babel/grunt-babel/blob/240a168f2d31aa5171a55d2359e0c3085d67c959/package.json#L40) and [gulp-babel](https://github.com/babel/gulp-babel/blob/bf9df3a7d1d827ba79c6ee8019d4103e434e38d2/package.json#L40)

In my opinion babel-core should live in the peer dependencies without requesting a specific version (*) so that users can pick their favorite version, however I'll do like others do to avoid confusion. 

I'm going, eventually, to remove the current peer dependencies in the next versions.

**Comment by necolas** [comment]
Yeah it's tricky, because I agree with gaearon's point (and had similar complaints with jscs-loader). Hah, perhaps peerDependencies is the way to go after all in this case.

**Comment by jhnns** [comment]
The current README is misleading because peerDependencies are not deprecated. Auto-installing is deprecated.

And I can confirm @gaearon concerns: It should stay as peerDependencies. I've experienced similar issues with the less- and sass-loader.

**Comment by Couto** [comment]
I agree :)

However I can't really fix it right now (or today) if you're up for a PR that should be faster!

**Comment by SpaceK33z** [comment]
Is it intended behavior that `babel-core` now is installed twice in npm 2+? Once as peer dependency and once as normal dependency of `babel-loader`. `babel-core` is 21mb...

**Comment by gaearon** [comment]
I don't think it's intended behavior. Delete both, set most recent versions in package.json and run npm install again?

**Comment by SpaceK33z** [comment]
That changes nothing, which makes sense, because if you look in the `package.json` of this package, you will see that `babel-core` is defined twice as a dependency.

**Comment by gaearon** [comment]
@SpaceK33z lol, you're right! I don't know why.

@sairion Any idea why it's both a peer, a regular, and a dev dep?

**Comment by Couto** [comment]
Actually, for no special reason other than it was left forgotten. 

A PR is more than welcome, and I'll try to merge as soon as possible, since I am on mobile! 


On August 10, 2015 12:30:24 PM GMT+01:00, Dan Abramov <notifications@github.com> wrote:
>@SpaceK33z lol, you're right! I don't know why.
>
>@sairion Any idea why it's both a peer, a regular, and a dev dep?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/babel/babel-loader/issues/47#issuecomment-129413151

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SpaceK33z** [comment]
In #94 I've deleted the peer and dev dependency. This would the most consistent option, right? `gulp-babel` and `grunt-babel` also only have `babel-core` as dependency.

**Comment by tomasdev** [comment]
Hey guys

I'm getting
```
± npm install --save babel-loader
npm WARN peerDependencies The peer dependency babel-core@^5.0.0 included from babel-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "babel-loader"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package babel-core does not satisfy its siblings' peerDependencies requirements!

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tomas/WORK/Events/events-v2/npm-debug.log
```

But there's no "xxx@version wants yyy@version" in the npm-debug.log file

**Comment by gaearon** [comment]
@tomasdev 

You probably already have `babel-core@6.x` and are trying to install `babel-loader@5.x`. They are incompatible. Stay on 5.x for everything until support comes.

**Comment by d3viant0ne** [comment]
For reference - `peerDependencies` these days are used to convey supported versions of a library where multiple versions can be used. In this case, `webpack `1.x || 2.x` which has been removed as a `devDependency` bable-core and the es2015 preset are moving into devDeps.
