### ISSUE TITLE
Support webpack 3

### ISSUE THREAD

**Issue by tomkel** [babel/babel-loader#473]
`warning "babel-loader@7.0.0" has incorrect peer dependency "webpack@2".`

https://github.com/webpack/webpack/releases/tag/v3.0.0

**Comment by evilebottnawi** [comment]
@danez friendly ping

**Comment by danez** [comment]
@evilebottnawi Please stop pinging random people in Issues and PullRequest. We all have lives outside of OpenSource and we will try to fix stuff as soon as we can here. Pinging people (especially only after several hours) will not make it more likely that we look at stuff. Thank you.

**Comment by evilebottnawi** [comment]
@danez I do not ping random people, but only those who are responsible for the repository, if you do not have the time, please respond to this problem and report that anyone can help you with this. Ignore requests and do not respond to them is disrespect, do not you think so?

**Comment by evilebottnawi** [comment]
Btw, github have label (example `help wanted`) and it is good practice for avoid pinging.
