### ISSUE TITLE
upgrade to be webpack@3 compatible

### ISSUE THREAD

**Issue by rachelslurs** [babel/babel-loader#474]
**I'm submitting a feature request**

**Webpack Version:**
3.0

**Babel Core Version**:
6.24.1

**Babel Loader Version**:
7.0.0

**Please tell us about your environment:**
OSX 10.12.5

**Current behavior:**
Running npm i after upgrading to webpack 3 returns `babel-loader@7.0.0 requires a peer of webpack@2 but none was installed.`

**Expected/desired behavior:**
babel-loader can be webpack3 compatible 🙂

**Comment by danez** [comment]
This was done in 7.1.0
