### ISSUE TITLE
Experimental flag deprecated, how to set stage flag with Babel 5.0 release

### ISSUE THREAD

**Issue by box-turtle** [babel/babel-loader#48]
Previously I configured babel-loader in webpack.config.js like this:
```
            { test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader?experimental'},
```
Now that experimental is deprecated, how do I specify the stage param?

I tried

```
            { test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader?stage=1'},
            { test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader?stage 1l'},
            { test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader?{stage: 1}'},
```
I also tried adding .babelrc to root of my project with 

```
{
  "stage": 1
}
```

**Comment by woodb** [comment]
:+1:

**Comment by sebmck** [comment]
@woodb You're still using the `experimental` option so of course it's going to error.

**Comment by sebmck** [comment]
@box-turtle Can you please provide that error messages you're getting?

**Comment by babsonmatt** [comment]
How should stage be passed?

**Comment by sebmck** [comment]
`'babel-loader?stage=1'` or `'babel-loader?{"stage": 1}'` _should_ work, no reason they shouldn't.

**Comment by babsonmatt** [comment]
Thanks for the help. Turns out my issue was not having latest babel-core / babel-runtime.  Installing with @latest did the trick, and the stage option works just fine.

**Comment by box-turtle** [comment]
same here @babsonmatt, needed to update other dependencies and everything works fine.

thanks for quick response @sebmck. Fantastic job on all these tools around babel - you do the work of 10 men!

**Comment by woodb** [comment]
@sebmck the experimental flag is still an example in the README

**Comment by sebmck** [comment]
@woodb Fixed, thanks.
