### ISSUE TITLE
[Discuss] Remove internal caching in favour of `cache-loader`

### ISSUE THREAD

**Issue by michael-ciniawsky** [babel/babel-loader#486]
**I'm submitting a feature request**

☝️ 

**Babel Core Version**:
`^6.0.0`

**Babel Loader Version**:
`8.0.0` :)

**Please tell us about your environment:**
OSX 10.x / Linux / Windows 10

**Current behavior:**

`babel-loader` caches files on it's own

**Expected/desired behavior:**
**What is the motivation / use case for changing the behavior?**

Find a convention for loader caching that works across loaders and doesn't require `n` implementations

**Comment by danez** [comment]
We recently change some caching (reading babelrc, checking for file existence etc) to be completely done by webpack (#460) and not the babel-loader. We still cache the actual babel transpile result atm. 

If we would remove this it would drastically slow down the loader when not using the cache-loader. I also haven't looked at the cache loader yet and don't know how it works.
