### ISSUE TITLE
jsnext:main transpiling

### ISSUE THREAD

**Issue by damianobarbati** [babel/babel-loader#488]
I really do not understand what's the current status in Webpack / babel-loader in transpiling dependencies in node_modules, can anyone please clarify? 
I tried to stick to every issue opened everywhere.

1) Is webpack / babel-loader transpiling `jsnext:main` file?
2) If yes, is webpack / babel-loader transpiling `jsnext:main` file in node_modules even if node_modules is in exclude key?

My situation:
```
rules: [{
    test: /\.(js|mjs)$/i,
    exclude: [/node_modules/],
    use: [{
        loader: 'babel-loader', //settings specified in package.json
    },{
        loader: 'eslint-loader', //settings specified in package.json
    }
}]
```
In my dependency package.json I tried:
```
"main": "index.js", <= not working (not transpiled)
"jsnext:main": "index.js", <= not working (not transpiled)
"module": "index.js", <= not working (not transpiled)
```
Neither is working without removing `exclude: [/node_modules/],` but this can't be used in any medium-to-big sized project because of infinite compilation times.

But then: why is https://github.com/lodash/lodash/blob/es/package.json any different from my https://github.com/damianobarbati/react-create-app/blob/master/package.json? 
`lodash-es` is getting transpiled even being in node_modules (and excluded) but my `react-create-app` is not: HELP!

https://github.com/webpack/webpack/issues/2902

**Comment by danez** [comment]
babel-loader/babel is only transpiling what you tell it to transpile.

webpack is respecting the `module` field in package.json, but the definition of the `module` field is not to be ES2018, but rather parseable by node or browser except that it uses import/export. This is then used to do tree shaking in webpack, but not to transpile node_modules.

**Comment by sibelius** [comment]
can we have an option to enable transpiling all jsnext:main and module on node_modules?

**Comment by loganfsmyth** [comment]
@sibelius That is something you'd set up in your Webpack config, not as part of babel-loader.

**Comment by sibelius** [comment]
I think it makes sense to have something like this in a helper or as an option
