### ISSUE TITLE
Babelrc config is not merged when using env

### ISSUE THREAD

**Issue by VladShcherbin** [babel/babel-loader#489]
**I'm submitting a bug report**

**Webpack Version:**
3.1.0

**Babel Core Version**:
6.25.0

**Babel Loader Version**:
7.1.1

**Please tell us about your environment:**
OSX 10.12.5

**Current behavior:**

If my `.babelrc` config there are global plugins and env presets. When I run webpack with `BABEL_ENV=client`, global plugins in config are not used, only `env.client` ones are.

Here is babelrc:

```json
{
  "env": {
    "client": {
      "presets": ["react", ["env", { "targets": { "browsers": "last 2 versions" } }]]
    }
  },
  "plugins": [
    "transform-class-properties",
    "transform-export-extensions",
    "transform-object-rest-spread"
  ]
}
```

**Expected/desired behavior:**

Babel should merge global and env config.

---

**The same configuration works in node 8.1**

**Comment by danez** [comment]
Please report this to babel, this repository is only about the babel-loader. The `env` option is also going to be deprecated in the next major version of babel. Instead you will be able to write the config in javascript.

**Comment by VladShcherbin** [comment]
@danez it is working in babel, I'm using babel with node 8.1 with the same config and it is working.
