### ISSUE TITLE
Module error : unexcepted token.

### ISSUE THREAD

**Issue by dalip123** [babel/babel-loader#492]
./node_modules/.bin/webpack -d
Hash: fa95135118e7d7ced0c6
Version: webpack 3.3.0
Time: 117ms
    Asset    Size  Chunks             Chunk Names
bundle.js  3.1 kB       0  [emitted]  main
   [0] ./src/index.js 248 bytes {0} [built] [failed] [1 error]

ERROR in ./src/index.js
Module parse failed: /home/dalip/Desktop/todo-react/src/index.js Unexpected token (11:2)
You may need an appropriate loader to handle this file type.
| 
| render(
|   <Provider store={store}>
|     <App />
|   </Provider>,

1.10.x/2.x

**Babel Core Version**:
6.x

**Babel Loader Version**:
5.4.x/6.2.x

**Please tell us about your environment:**
OSX 10.x / Linux / Windows 10

**Current behavior:**

**Expected/desired behavior:**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by danez** [comment]
Please provide more information as otherwise we cannot help you.
What does src/index.js look like? How does your babel config look like?

**Comment by dalip123** [comment]
thanks @danez . My problem is solved. It was syntax issue.
