### ISSUE TITLE
babel-loader babel-cli projects must have babel-core as devDependency

### ISSUE THREAD

**Issue by haraldrudell** [babel/babel-loader#497]
babel-loader/lib./index.js:
var babel = require("babel-core")

BUG
babel-core may not be available for project that use babel-cli as devDependency
babel-cli may cause babel-core to be installed under babel-cli therefore not accessible to babel-loader

GETAROUND:
npm install --save-dev babel-core

Linux Webpack 3.4.1 Node8

**Comment by danez** [comment]
That's why we have a peer dependency on babel-core
https://github.com/babel/babel-loader/blob/master/package.json#L18
