### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'Object' of undefined" after upgrade to Babel 5.0

### ISSUE THREAD

**Issue by euforic** [babel/babel-loader#50]
## Babel Versions
- **babel-core**: 5.0.12
- **babel-runtime**: 5.0.12
- **babel-loader**: 5.0.0

It seems like it might be an issue where the `babel-runtime` is not being bundled in properly

Everything works fine if compiled with babel < 5.0
Not sure if the modules I am using are causing the problem since they where compiled with a babel version < 5.0

## Modules Precompiled w/ Babel < 5.0

[react-gestures](https://github.com/bh5-js/react-gestures)
[gmaps-places-autocomplete](https://github.com/bh5-js/gmaps-places-autocomplete)
[cync](https://github.com/bh5-js/cync)

## Browser Error

```
Uncaught TypeError: Cannot read property 'Object' of undefined
file: ./~/babel-runtime/~/core-js/library/modules/$.js
```
![screen shot 2015-04-09 at 11 58 12 am](https://cloud.githubusercontent.com/assets/395386/7074507/e688c2ae-deaf-11e4-87a1-18257adc7498.png)

## Webpack Config
```js
var webpack = require('webpack')
  , path = require('path')
  , WebpackDevServer = require('webpack-dev-server')
  , CommonChunkPlugin = require('webpack/lib/optimize/CommonsChunkPlugin');

var commonPlugin = new CommonChunkPlugin('vendor', 'vendor.bundle.js');

// Simple dev / production switch
function _env(dev, production) {
  return process.env.BUILD_ENV === 'production' ? production : dev;
}

function _path(p) {
  return path.join(__dirname, p);
}

var compiler = module.exports = {
  plugins: [commonPlugin],
  devtool: _env('eval', false),
  entry: {
    app: _path('src/index.js'),
    vendor: ['superagent','react','immutable', 'google']
  },
  output: {
    path: _path('www'),
    filename: 'bundle.js', //this is the default name, so you can skip it
  },
  module: {
    loaders: [
      { test: /\.(js|jsx)$/, loader: 'babel-loader?stage=1&optional=runtime', exclude:['node_modules'] },
      { test: /\.(css|less)$/, loader: 'style-loader!css-loader?' + _env('sourceMap=1&', '') + 'importLoaders=1!autoprefixer' },
      { test: /\.(png|jpg|jpeg|gif)$/, loader: 'url?limit=8192'},
      { test: /\.(eot|woff|ttf|svg)$/, loader: 'url?limit=8192'}
    ]
  },
  externals: _env({
    react: 'React',
    immutable: 'Immutable',
    google: 'google'
  },{ google: 'google'}),
  resolve: {
    alias: {
      superagent: 'superagent/lib/client'
    },
    extensions: ['', '.css', '.react.js', '.js', '.jsx']
  }
};


if (process.env.BUILD_ENV !== 'production') {
  var server = new WebpackDevServer(webpack(compiler), {
    hot: false,
    quiet: false,
    noInfo: false,
    filename: "bundle.js",
    contentBase: _path('src'),
    publicPath: "/",
    headers: { "X-Development-Build": true },
    stats: { colors: true },
    historyApiFallback: false,
  });
  server.listen(8090, "localhost", function() {});
}
```

**Comment by sebmck** [comment]
You most likely have a 4.x `babel-runtime`. Please remove your `node_modules` folder and `npm install` again.

**Comment by euforic** [comment]
@sebmck tried that already and also did a `npm cache clean`

**Comment by sebmck** [comment]
Not sure what's causing this then:

```
$ node
> require("babel-runtime/core-js")["default"].Object.defineProperty
[Function: defineProperty]
```

**Comment by euforic** [comment]
@sebmck I think the problem might be a compatibility issue with iojs. Switched to node 0.12.x and it works now.

**Comment by sebmck** [comment]
@euforic 

```
$ iojs
> require("babel-runtime/core-js")["default"].Object.defineProperty
[Function: defineProperty]
```

**Comment by euforic** [comment]
@sebmck never mind It's still happening in both. It seems like a circular dependency issue with the runtime files.

**Comment by euforic** [comment]
I think I found the problem module https://github.com/bh5-js/cync still not sure whats breaking things though.

**Comment by euforic** [comment]
I still get the error with the simple example below, but if I remove the `constructor` function the error is gone.

- babel-loader: 5.0.0
- babel-core: 5.1.10
- babel-runtime: 5.1.10
- react: 0.13.1

### index.js

```js
import React from 'react';

class MyComponent extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    return <div> test </div>;
  }
}
React.render(<MyComponent/>, document.getElementById('main'));
```

### index.html

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bug Example</title>
    <meta name="description" content="">
    <script src='//cdnjs.cloudflare.com/ajax/libs/react/0.13.1/react.js'></script>
  </head>
  <body>
    <div id="main"></div>
    <script type="text/javascript" src="/bundle.js"></script>
  </body>
</html>
```

### webpack.config.js

```javascript
var webpack = require('webpack');

module.exports = {
  entry: {
    app: './index.js'
  },
  output: {
    path: './build',
    filename: 'bundle.js',
    publicPath: '/'
  },
  devtool: 'inline-source-maps',
  module: {
    loaders: [
      { test: /\.(js|jsx)$/, loader: 'babel?stage=0&optional=runtime', exclude:['node_modules'] }
    ]
  },
  externals: {
    react: 'React',
  },
  resolve: {
    extensions: ['', '.js', '.jsx']
  }
};
```

**Comment by euforic** [comment]
here is a jsfiddle to demo the error https://jsfiddle.net/euforic/5vjqabv3/474/

**Comment by sebmck** [comment]
Can you verify that you're using the latest `babel-runtime` please. cc @zloirock

**Comment by zloirock** [comment]
@sebmck emm? In last example I don't see `core-js`, only helpers.

**Comment by sebmck** [comment]
@zloirock Look at the jsfiddle, the error is being thrown on the line `module.exports = __webpack_require__(10).core.Object.keys;`.

**Comment by zloirock** [comment]
Interesting. Don't test it with webpack. I will investigate the problem in the evening.

**Comment by zloirock** [comment]
Looks like bug it config. Webpack run `runtime` transformer on `core-js` files.

**Comment by sebmck** [comment]
Change your `exclude` filter to `/node_modules/`.

**Comment by euforic** [comment]
@sebmck yep that fixes it. Thanks for all the help!
