### ISSUE TITLE
ERROR in multi

### ISSUE THREAD

**Issue by willin** [babel/babel-loader#508]
## **BEFORE YOU SUBMIT** please read the following:
 
**I'm submitting a bug report**

**Webpack Version:**
3.5.6

**Babel Core Version**:
6.26

**Babel Loader Version**:
7.1.2

**Please tell us about your environment:**
OSX 10.12

**Current behavior:**

webpack entry

```js
{
entry: ['app.js','module.js']
}
```

```
ERROR in multi ../webpack-server-bundle/src/index.js
Module not found: Error: Can't resolve 'babel-loader' in '/Users/willin/Documents/dwing/others/src'
 @ multi ../webpack-server-bundle/src/index.js
ERROR in multi ../webpack-server-bundle/src/index.js
Module not found: Error: Can't resolve 'babel-loader' in '/Users/willin/Documents/dwing/others/src'
 @ multi ../webpack-server-bundle/src/index.js
```

```js
{
entry: ['app.js'] // even only one  error
}
```

```js
{
entry: 'app.js' // only this can success
}
```

**Expected/desired behavior:**

```js
const config = require('../config');

const entry = [
  path.resolve(__dirname, '../src/index.js'),
  ...config.enabledModules.map(x => path.resolve(__dirname, `../src/${x}/index.js`))
];
```

* **What is the expected behavior?**

bundle entries

* **What is the motivation / use case for changing the behavior?**

https://github.com/AirDwing/webpack-server-bundle/blob/master/src/server.js#L9-L13

webpack dynamic modules bundle

**Comment by loganfsmyth** [comment]
Looks like this was fixed in the related issue.
