### ISSUE TITLE
JSX support in README

### ISSUE THREAD

**Issue by sethen** [babel/babel-loader#51]
Hello,

I am new to webpack and I was looking for a loader that would compile my ES6/JSX.  There is no mention of having JSX support in your README.  I think you should add it as it would be helpful to know for new comers to webpack looking to do the same.

Aside from that, thanks for the loader.

**Comment by sebmck** [comment]
Babel support JSX, yes. `babel-loader` is just an integration for [Babel](https://babeljs.io). It's overkill to list every single feature that Babel supports in the README of every single plugin and integration.

**Comment by sethen** [comment]
Meh, just thought it was worth a mention for those of us who missed it in the Babel docs.

**Comment by sebmck** [comment]
It's one of the headings and focuses of the homepage.

**Comment by sethen** [comment]
Yeah, I just skimmed it and missed that part is all.

**Comment by sethen** [comment]
Yeah, I just skimmed it and missed that part is all. I was more worried about the ES6 support and I must've missed the React/JSX support. Through the various sites looking at webpack stuff, I was curious about JSX/ES6 support. Looking at this loader, I was under the impression I was in need of something for JSX as well.

This wasn't a request to list every single feature of babel, merely a mention that JSX support is available as well so there is no need for an additional loader for webpack.
