### ISSUE TITLE
Babel v7 beta 0 spread not working

### ISSUE THREAD

**Issue by dnalborczyk** [babel/babel-loader#511]
not sure if this is a bug in babel, the babel-plugin(s), or babel-loader. Though the following works with the babel-cli.

**Webpack Version:**
v3.5.6

**Babel Core Version**:
v7.0.0-beta.0

**Babel Loader Version**:
v7.1.2

**Please tell us about your environment:**
OSX 10.13 High Sierra beta

minimal repro:
```
export default function(a) {
  return { ...a };
}
```
exception during webpack build: Unexpected token. You may need an appropriate loader to handle this file type

```
Unexpected token (2:11).
You may need an appropriate loader to handle this file type.
|
| exports.default = function (a) {
|   return { ...a };
| };
```

it seems to only have a problem when ES6 modules are being used.

used plugins:
babel-plugin-transform-es2015-modules-commonjs 7.0.0-beta.0
babel-plugin-transform-object-rest-spread 7.0.0-beta.0

**Comment by iulo** [comment]
your webpack.config.js ?

**Comment by dnalborczyk** [comment]
@iulo  I was going to create a minimal project to reproduce the above behavior. On the way doing so, I found that this has nothing to do with Babel-loader, or Babel nor the transforms itself.

It's the way we are using [lerna](https://github.com/lerna/lerna) with a monorepo, and the way npm is loading modules hierarchically.

I want to bring up this issue at the lerna and npm repositories to find out more information about patterns or potential workarounds -- or even a potential fix.

Thank you!
