### ISSUE TITLE
Cannot Convert UMD ES6 to UMD ES5

### ISSUE THREAD

**Issue by DrLongGhost** [babel/babel-loader#512]
**I'm submitting a bug report**

**Webpack Version:**
3.5.6

**Babel Core Version**:
6.26.0

**Babel Loader Version**:
7.1.2

**Please tell us about your environment:**
OSX 10.12.6

**Current behavior:**
I cannot use babel-loader to convert an ES6 UMD module to an ES5 UMD module. Instead it seems to force a change to the module type. 

My UMD module that begins with the following code:

```
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define([], factory);
  } else if (typeof module === 'object' && module.exports) {
    // Node. Does not work with strict CommonJS, but
    // only CommonJS-like environments that support module.exports,
    // like Node.
    module.exports = factory();
  } else {
    // Browser globals (root is window)
    let MODULE_NAME = 'myModule';
    root[MODULE_NAME] = factory();
  }
}(this, function () {
```
I have the following webpack.config.js:

```
var webpack = require('webpack');

module.exports = {
  entry: {
    main: "./src/voicevibes.js"
  },
  output: {
    path: __dirname + "/dist",
    filename: "voicevibes.js"
  },
  plugins: [],
  module: {
    loaders: [{
      test: /\.js$/,
      exclude: /node_modules/,
      loader: 'babel-loader',
      query: {
        presets: [["es2015", {
          "modules": false,
        }]],
      }
    }]
  }
};
```

And .babelrc:

```
{
  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ]
  ]
}
```

**Expected/desired behavior:**
The resulting file should honor the "modules:false" setting and preserve the existing/working UMD module code. It should transform my ES6 code into ES5 code without messing with the module type or module loading at all. The resulting code should continue to be able to be loaded in a browser via a <script> tag and have the module register itself on windows.myModule.

I can very easily get the desired behavior by using babel-cli with the above .babelrc. It works perfectly. But when I try to do the same via babel-loader, it breaks the module completely.

**Current behavior**
babel-loader adds a bunch of  __webpack_require__ code to the top of the file. It also mangles the conditional logic of the UMD code, transforming "if (typeof define === 'function' && define.amd) {" into "if (true)", which I guess changes the UMD into an AMD module? Even removing the top 2 conditionals to force the "Browser globals" conditional to be executed doesn't restore the functionality, as it has been mangled somehow by all the __webpack_require__ stuff.

* **What is the expected behavior?**
See above

* **What is the motivation / use case for changing the behavior?**
This is obviously a bug of some sort (or a shortcoming of the documentation). There should be a way to use babel-loader to convert an ES6 UMD module to an ES5 UMD module, instead of breaking/transforming it. If babel-cli can support the transformation, babel-loader should be able to do the same, but I can't get it to work.

**Comment by hzoo** [comment]
So `modules: false` means don't transform anything and leave the imports for another tool to transform (webpack). Thus the stuff you are seeing is what webpack is doing, what docs are you looking at? Also `modules: false` means don't transform import/export. You can paste what you have in the REPL to see what Babel transforms it to as well.

It sounds (I'm not sure) like you are just confused by what webpack itself is doing?

**Comment by DrLongGhost** [comment]
This is the code that babel-loader adds to the top of my file:

```
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, {
/******/ 				configurable: false,
/******/ 				enumerable: true,
/******/ 				get: getter
/******/ 			});
/******/ 		}
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = 0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
```

Something in that code (plus the fact that it *changes* the behavior of the UMD conditionals (including forcing one of the conditionals to *if (true)*) completely breaks the module. I don't even think it's valid UMD anymore.

As I mentioned, babel-cli doesn't do any of this. 

I'll concede that I don't fully understand what Webpack is doing (I guess it's trying to normalize the module loading somehow), but shouldn't I be able to have babel-loader export a working ES5 UMD module? Because right now I can't get it to.

If there is some other configuration or option that I can pass to make this work, that would be great to know. But as of now, the only way I can convert my module to ES5 is with babel directly, because Webpack seems to break it.

**Comment by loganfsmyth** [comment]
Webpack's job, unless told otherwise, is to take a module and process all of its dependencies into a single file that can be loaded as a `<script>`, which means if you pass it a UMD file, it's going to process it and format it however it needs to.  In doing so, it does a lot of analysis of code code and does things like converting code in the file to `true` and `false`. It does this because by passing the module to Webpack, you're using Webpack itself as the UMD loader, meaning the output you get isn't usable as a UMD module. If you want your bundled file from Webpack to be usable as UMD, you need to tell it that: https://webpack.js.org/configuration/output/#output-librarytarget

I can't tell if that's what you actually want though. Either way, this is definitely not a Babel issue. Whatever's getting turned to `true` is something that Webpack has decided is `true`, and without an example it's hard to say why it decided that.

**Comment by DrLongGhost** [comment]
Thanks for the insight. I understand this a bit better now. The libraryTarget option is probably what I was looking for, since it does fix the issue (as does using expose-loader). libraryTarget ensures the file is a valid UMD but it does still contain a lot of extra boilerplate that babel-cli does not add. Maybe this is unavoidable since that's just fundamentally how Webpack works. Still, I'm not sure if I like including that boilerplate in my production build, since it definitely is not needed.

Still at least it works now. Thanks again!
