### ISSUE TITLE
Babel 7 beta seems to misinterpret quotes

### ISSUE THREAD

**Issue by drcmda** [babel/babel-loader#513]
**I'm submitting a bug report**

**Webpack Version:**
3.5.6

**Babel Core Version**:
7.0.0-beta.0

**Babel Loader Version**:
7.1.2

**Please tell us about your environment:**
OSX 10.13 High Sierra

**Current behavior:**

Trying to use nodes zlib, never had problems with it before. It has the following line that seems to throw Babel off:

    s.bl_tree[curlen * 2]/*.Freq*/ += count;

```
ERROR in ./node_modules/pako/lib/zlib/trees.js
Module parse failed: /Users/xxxxxx/node_modules/babel-loader/lib/index.js??ref--0!/Users/drcmda/dev/polygons/node_modules/pako/lib/zlib/trees.js Unexpected token (1057:10)
You may need an appropriate loader to handle this file type.
|         s.bl_tree[curlen * 2]
|         /*.Freq*/
|         ++;
|       }
| 
```

**Comment by loganfsmyth** [comment]
@babel-bot move to babel/babel

**Comment by loganfsmyth** [comment]
Definitely looks like a bug to me.

That said, we don't generally recommend running Babel on code that isn't your own, since it can break things. We always recommend `exclude: /node_modules/` in your `babel-loader` section of the Webpack config.

**Comment by hzoo** [comment]
aside: actually that's an interesting way to find bugs 😛

**Comment by drcmda** [comment]
@loganfsmyth i usually never exclude in order to get more gains. Never had any problems with it, but either way, wouldn't have found it otherwise. 😇

**Comment by loganfsmyth** [comment]
It'll make your builds _way_ slower. The main issue though is that since we default to processing things as modules, we add `use strict` to the top of every file you process, which can break things. We also rewrite top-level `this` to `undefined` which breaks some things.

I've refiled this in https://github.com/babel/babel/issues/6253, so going to close here.
