### ISSUE TITLE
warning babel-loader@7.1.2 has incorrect peer dependency

### ISSUE THREAD

**Issue by alansouzati** [babel/babel-loader#517]
**Webpack Version:**
3.4.1

**Babel Core Version**:
6.5.2

**Babel Loader Version**:
7.1.2

**Please tell us about your environment:**
OSX 10.12

**Current behavior:**

> warning "babel-loader@7.1.2" has incorrect peer dependency "webpack@2 || 3".

**Expected/desired behavior:**

Maybe the peerDependency entry should be updated to the following?

```
   "webpack": "^2.0.0 || ^3.0.0"
```

I would  be happy to submit the pull request if you guys agree with this change.

**Comment by alansouzati** [comment]
FYI. This issue is only when using `yarn install`, `npm install` does not show any warning.

**Comment by Andarist** [comment]
Does it only warn you? Other than that are you able to use packages without any issues? What version of the `yarn` do you use?

**Comment by alansouzati** [comment]
I'm able to use without problems. I use yarn 1.1.0 (the latest)

**Comment by Andarist** [comment]
Imho the issue should be filed to `yarn`, especially that `npm` handles it ok and that this is just causing a warning and not breaking the installed modules.
