### ISSUE TITLE
Add `include` in the documentation

### ISSUE THREAD

**Issue by PezCoder** [babel/babel-loader#519]
I have a mono-repo where I wanted to run babel-loader in a certain directory & not everywhere, I've had a hard time finding how to do that.
Since there are lot more elements to blacklist here, it's good to have just a whitelist folder where we would want to run babel-loader.

Also this is what [Webpack configuration](https://webpack.js.org/configuration/) doc suggests:
> // Best practices:
> // - Try to avoid exclude and prefer include

I think the intention of having `exclude` in the babel-loader documentation is to say explicitly about excluding vendor modules but it'll be good to also show an `include` example, just in case for people like me working on mono-repo or who just want to have a folder needed to be run using babel-loader & not the whole repo.

If agree, I'll be happy to create a pr

**Comment by loganfsmyth** [comment]
If you'd like to add an example in a PR, go for it.
