### ISSUE TITLE
Experimental version bugs

### ISSUE THREAD

**Issue by mhaagens** [babel/babel-loader#524]
**I'm submitting a bug report**

**Webpack Version:**
3.8.1

**Babel Core Version**:
7.0.0-beta.5

**Babel Loader Version**:
7.1.2

**Please tell us about your environment:**
OSX 10.12

**Current behavior:**
When running webpack after following the setup instructions it errors saying it cannot find "@babel/env". Should the require be "@babel/preset-env" instead?
When I change it to "@babel/preset-env" it errors out saying;
```Cannot find module babel-helper-regex'```

**Comment by andreolvr** [comment]
Same error here.

**Comment by existentialism** [comment]
@mhaagens thanks for the report! Small difference... `@babel/env` works as shorthand inside a .babelrc file, but won't work when used to install the package (`npm i @babel/preset-env`).

As for the `Cannot find module babel-helper-regex` issue, have you tried using `babel-loader@8.0.0-beta.0`?

**Comment by andreolvr** [comment]
Yes, the error occurs with `babel-loader@8.0.0-beta.0`.

**Comment by mhaagens** [comment]
Thanks for helping me out!

Now using babel-loader@next (8.0.0-beta.0) with the same results.
Error from babelrc:
```Couldn't find preset "@babel/env" relative to directory```

If I change it to @babel/preset-env it works, but still get the same ```babel-helper-regex``` issue.

Seems like this isn't very stable, maybe it shouldn't be the recommended way to get started as stated in the readme?

**Comment by andreolvr** [comment]
I think the readme file is wrong. If i run `npm install --save-dev babel-loader @babel/core @babel/preset-env webpack` as stated in the file, npm installs babel-loader 7 and webpack 2, and these packages are not compatible with @babel/core and @babel/preset-env. I think the correct command should be `npm install --save-dev babel-loader@8.0.0-beta.0 @babel/core @babel/preset-env webpack@3.x`. And `webpack 3.x | babel-loader >= 7.1` should be `webpack 3.x | babel-loader >= 8` If you want, i can create a pull request later.

**Comment by mhaagens** [comment]
But I'm using webpack 3.8.1, babel-loader 8.0.0-beta.0, @babel/core 7.0.0-beta.5 and @babel/preset-env 7.0.0-beta.5 and I'm still getting errors?

**Comment by abouthiroppy** [comment]
webpack version seems to be OK but we should update it...(old)
https://www.npmjs.com/package/webpack
https://github.com/babel/babel-loader/blob/master/package.json#L42
https://github.com/babel/babel-loader/blob/master/yarn.lock#L4967

**Comment by andreolvr** [comment]
@mhaagens i get this error too, but i think it's a bug that will be fixed, and once its fixed, the readme file should already be ok.

**Comment by hzoo** [comment]
updated the readme

**Comment by andreolvr** [comment]
@hzoo awesome, but what about the yarn commands?

**Comment by jowy** [comment]
Here's an example of my babel-loader config. I do not use .babelrc since I have a few different webpack files and find it easier to control babel granularly this way:

```
{
  test: /\.js$/i,
  use: {
    loader: 'babel-loader',
    options: {
      compact: true,
      babelrc: false,
      presets: [
        ['@babel/env', {
          targets: {
            browsers: [
              'last 2 versions',
              'not IE <= 10',
            ],
          },
        }],
        '@babel/preset-react',
      ],
      plugins: [
        ['graphql-tag'],
        ['styled-components', {
          displayName: false,
        }],
        ['transform-object-rest-spread'],
        ['@babel/transform-modules-commonjs', {}],
      ],
    },
  },
  exclude: /node_modules/,
},
```

Note the `options.babelrc: false` and defining an empty object for the `@babel/transform-modules-commonjs` placeholder.

This seems to fix the plugin, however it's just a workaround. Hope this helps someone! :)

This however does not seem to fix scripts that rely on .babelrc... I am currently fighting that.
