### ISSUE TITLE
Remove cacheDirectory in favor of using cache-loader

### ISSUE THREAD

**Issue by hzoo** [babel/babel-loader#525]
Less to maintain, and it was inspired by babel-loader?

https://github.com/webpack-contrib/cache-loader

**Comment by michael-ciniawsky** [comment]
Does this have consensus amongst `babel-loader`maintainers? I can do it 🙃

**Comment by DrewML** [comment]
Would certainly be nice to maintain less code 😸.

@michael-ciniawsky I suspect the only way we'd get consensus is after seeing traces. If you're interested, it would be awesome to see some comparative benchmarks between the 2 options.

**Comment by alunny-stripe** [comment]
FYI on a large codebase (~3300 modules) at Stripe, we found babel-loader with caching to be significantly faster than cache-loader + babel-loader:

Warm-cache initial build:
```
# cache-loader + babel-loader
Time: 23586ms

# babel-loader with cache option
Time: 22481ms 
```

Rebuild after change to entry point

```
# cache-loader + babel-loader
Time: 9144ms

# babel-loader with cache option
Time: 4578ms 
```

(with cache-loader 1.2.2 and babel-loader 7.1.1)

**Comment by timm-aym** [comment]
I observed something similar:

Initial build time (we need to execute webpack twice due to `react-loadable` JSON generation):

no cache: 65s
cache-loader (2. full run): 41s
babel-loader with cache (2. full run): 33s

**Comment by loganfsmyth** [comment]
I think personally, Babel will always have more information about caching based on its own inputs and outputs, so I'd rather keep caching in `babel-loader` until `babel/core` itself has a caching framework like https://github.com/babel/babel/issues/8605
