### ISSUE TITLE
Update babel-loader to use the async version of babel.transform

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel-loader#532]
Like https://github.com/babel/babel/issues/6784, but for babel-loader.

This one probably won't be as difficult since there is less complex surrounding logic.

**Comment by michael-ciniawsky** [comment]
It's `babel.transform(code, options, (err, result) => result)` for async usage ?

**Comment by danez** [comment]
We need to ensure, that we set the peer deps then correct for babel to be >=beta.X where X is the number where it gets released.

**Comment by michael-ciniawsky** [comment]
There seems to be no `async` version of `babel.transform` ? Only `babel.transformFile` works async. Maybe I'm doing something wrong ¯\_(ツ)_/¯

**Comment by loganfsmyth** [comment]
> It's babel.transform(code, options, (err, result) => result) for async usage ?

That is correct. That was added in the PR referenced in the linked issue, so it has not been published yet. When we get a `@babel/core@7.0.0-beta.32` it'll be in there.

**Comment by loganfsmyth** [comment]
This is done!
