### ISSUE TITLE
[bug] Strange compilation of ES6 `import`

### ISSUE THREAD

**Issue by AlexKVal** [babel/babel-loader#54]
With this versions (`babel-loader@4.3.0`)
```json
"dependencies": {
  "babel-core": "5.1.10",
  "babel-loader": "4.3.0",
  "webpack": "1.8.5"
}
```
```sh
$ git clone git@github.com:AlexKVal/bug_babel_webpack.git
$ npm istall
```

this code [client.js](https://github.com/AlexKVal/bug_babel_webpack/blob/master/client.js)
```js
import plugin from './client_plugin';
console.log("hello " + plugin.p)
```
compiles OK
```sh
$ webpack
```
into this code [bundle.js](https://github.com/AlexKVal/bug_babel_webpack/blob/master/bundle.js)
```js
var plugin = _interopRequire(__webpack_require__(1));
console.log("hello " + plugin.p);
```

But with the `babel-loader@5.0.0`
```sh
$ npm i babel-loader@5.0.0
$ webpack
```
it compiles into this [bundle.js](https://github.com/AlexKVal/bug_babel_webpack/blob/wrong/bundle.js)
```js
var _plugin = __webpack_require__(1);
var _plugin2 = _interopRequireWildcard(_plugin);
console.log("hello " + _plugin2["default"].p);
```

And in that case if I run
```js
eval('console.log("hello " + plugin.p)');
```
I've got a `ReferenceError` `cannot find "plugin"`

[Webpack config](https://github.com/AlexKVal/bug_babel_webpack/blob/master/webpack.config.js):
```js
module.exports = {
  entry: "./client.js",
  output: {
    path: __dirname,
    filename: "bundle.js"
  },
  module: {
    loaders: [
      { test: /\.js/, loader: 'babel', exclude: /node_modules/ }
    ]
  }
};
```

Here is the [trash project](https://github.com/AlexKVal/bug_babel_webpack) for bug reproducing.

**Comment by sebmck** [comment]
This is a problem relating to the output so should be reported on the [main babel repo](https://github.com/babel/babel).

**Comment by sebmck** [comment]
Also this isn't an issue or a bug. The use of `eval` is illegal in ES6 modules (they're strict mode).

**Comment by AlexKVal** [comment]
Done.

BTW: You are fast :+1:

**Comment by AlexKVal** [comment]
The problem is the project `react-bootstrap` is using `eval()` for developing mode.
[react-bootstrap](https://github.com/react-bootstrap/react-bootstrap/blob/master/docs/src/ReactPlayground.js#L249)
With previos babel@4 version all is working OK.
It needs to upgrade dependencies, but because of that strange `import` compilation in new `babel@5`,
it is not possible for now.

May be there is another solution ? What would you suggest ?

**Comment by sebmck** [comment]
The only scenario where imports aren't realiased like that is with `import * as foo from "bar";`. The reason they're done like that in 5.x is for live bindings.

**Comment by AlexKVal** [comment]
I see. 
In such case it needs to refactor the `react-bootstrap` development mode.

Thank you for your fast feedback.

**Comment by AlexKVal** [comment]
Thank you for your help.
Your advice with `import * as foo from "bar";` helped.

**Comment by lss876** [comment]
@sebmck     The use of eval is illegal in ES6 modules (they're strict mode).
hi sebmck, the use of eval is illegal in ES6 or in strict mode?
