### ISSUE TITLE
Configuration priority between package.json and loader options

### ISSUE THREAD

**Issue by darkalor** [babel/babel-loader#542]
**I'm submitting a bug report**

**Webpack Version:**
3.8.1

**Babel Core Version**:
6.26

**Babel Loader Version**:
7.12

**Please tell us about your environment:**
Linux / Win 8

**Current behavior:**
If babel config is present both in `package.json` and webpack config - `package.json` config seems to take higher priority. If that matters - running webpack through node API in watch mode.

**Expected/desired behavior:**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

webpack config loaders:
```       
        {
          test: /\.js?$/,
          exclude: /(node_modules)/,
          use: [{
            loader: 'babel-loader',
            options: {
              presets: [
                ['env', { modules: false }],           <----------
                'react',
                'stage-0',
              ],
              plugins: [
                'transform-async-to-generator',
                'transform-regenerator',
                'transform-runtime',
                'lodash',
              ],
            },
          }],
        },
```

package.json
```
  "babel": {
    "presets": [
      "react",
      "stage-0",
      "env"           <----------
    ]
  }
```

* **What is the expected behavior?**
The actual loader config should take precedence, and `modules: false` should work (it does not). 

* **What is the motivation / use case for changing the behavior?**
I'm not sure if this is a bug per se or by design, but it seems more natural to have the inline loader configs to have higher than external babel configs.

**Comment by michael-ciniawsky** [comment]
```diff
        {
          test: /\.js?$/,
          exclude: /(node_modules)/,
          use: [{
            loader: 'babel-loader',
            options: {
              presets: [
                ['env', { modules: false }],           <----------
                'react',
                'stage-0',
              ],
              plugins: [
                'transform-async-to-generator',
                'transform-regenerator',
                'transform-runtime',
                'lodash',
              ],
+             babelrc: false
            },
          }],
        },
```

**Comment by darkalor** [comment]
@michael-ciniawsky Thank you, while that does not answer my question it guided me to https://github.com/babel/babel-loader/issues/428 and I'll continue there
