### ISSUE TITLE
Remove `forceEnv` option in favor of `envName`

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel-loader#543]
After https://github.com/babel/babel/pull/6834 lands, we'll have a way in core itself to set the env name, so `babel-loader` won't have to do its current gross hacks to set the environment for Babel.

We should remove this option from the master branch, and most importantly, we should throw a helpful error message for users if they do set it, telling them to use `envName` instead.

**Comment by michael-ciniawsky** [comment]
Simply `env` (`options.env`) `babel --env $(name)` && `envs` to store them ?

**Comment by loganfsmyth** [comment]
@michael-ciniawsky I'm not quite sure what you're asking? That other PR adds `--env-name`, but this issue isn't related to the CLI.

**Comment by michael-ciniawsky** [comment]
Ohh sry I was lazy I should have comment in the PR instead :), my suggestion is to rename 

`envName` => `env`
`env` => `envs`

in https://github.com/babel/babel/pull/6834

**Comment by loganfsmyth** [comment]
Gotcha. I think we're pretty hesitant to make breaking changes like that at the moment, simply because it'll make the transition for people harder without tons of benefits.

**Comment by michael-ciniawsky** [comment]
I wasn't aware that this would be a breaking change for `babel` that nitpick is definitely not worth it then :)

**Comment by loganfsmyth** [comment]
Changing `env` to `envs` could technically be done in a backward-compatible way if we explicitly checked the type, I just feel like it'll add confusion for users. Then also we need additional logic to make sure people don't somehow pass an option for both blocks, and we'd need to handle both types of options in our config merging logic. It just seems like a lot of additional complexity.

**Comment by loganfsmyth** [comment]
This was fixed in #586
