### ISSUE TITLE
babel-loader with object-rest-spread = Cannot read property 'useBuiltIns' of undefined

### ISSUE THREAD

**Issue by stephen-last** [babel/babel-loader#547]
**I'm submitting a bug report**

**Webpack Version:** 3.9.0
**Babel Core Version**: 7.0.0-beta.32
**Babel Loader Version**: 8.0.0-beta.0
**Please tell us about your environment:** Windows 7 Pro

**Current behavior:**

When trying to use `@babel/plugin-proposal-object-rest-spread` I get:

> C:\node\clcommerce\node_modules\@babel\plugin-proposal-object-rest-spread\lib\index.js:13
>   var _opts$useBuiltIns = opts.useBuiltIns,
>                                ^
> 
> TypeError: Cannot read property 'useBuiltIns' of undefined
>     at _default (C:\node\clcommerce\node_modules\@babel\plugin-proposal-object-rest-spread\lib\index.js:13:32)
>     at Function.memoisePluginContainer (C:\node\clcommerce\node_modules\babel-core\lib\transformation\file\options\option-manager.js:113:13)
>     at Function.normalisePlugin (C:\node\clcommerce\node_modules\babel-core\lib\transformation\file\options\option-manager.js:146:32)
>     at C:\node\clcommerce\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
>     at Array.map (<anonymous>)
>     at Function.normalisePlugins (C:\node\clcommerce\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
>     at OptionManager.mergeOptions (C:\node\clcommerce\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
>     at OptionManager.init (C:\node\clcommerce\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
>     at compile (C:\node\clcommerce\node_modules\babel-register\lib\node.js:103:45)
>     at loader (C:\node\clcommerce\node_modules\babel-register\lib\node.js:144:14)

This is my config:

```js
{
          test: /\.js$/,
          exclude: /(node_modules|bower_components)/,
          use: {
            loader: 'babel-loader',
            options: {
              presets: [
                ['@babel/preset-react'],
                ['@babel/preset-env', { 'targets': { 'browsers': [ 'IE 7' ] } }]
              ],
              plugins: [
                ['@babel/plugin-proposal-object-rest-spread', { 'useBuiltIns': false }],
                ['@babel/plugin-proposal-class-properties', { 'spec': true }]
              ]
            }
          }
        }
```

**Expected/desired behavior:** To run without error

I'm submitting this here because I don't see this error when running babel from the command line, only when using `babel-loader`. 

I've tried changing the `useBuiltIns` option (`true`, `false` and not specified) but that has no effect, I still see this error.

Is it a bug in the beta..? ...or am I doing something wrong..?

**Comment by stephen-last** [comment]
Closing and moving issue...

I'm using `webpack.config.babel.js` and it seems this isn't working. If I go back to using `webpack.config.js` with `require()`'s it works, my issue isn't with `babel-loader`.

**Comment by SKalt** [comment]
@stephen-last you were requiring `babel-plugin-transform-object-rest-spread`, right? I've noticed `@babel/plugin-transform-object-rest-spread` is in the README but does not exist on the npm registry, and wanted to check in before I raise a separate issue.

**Comment by Kovensky** [comment]
It's currently called `@babel/plugin-proposal-object-rest-spread`; it should get renamed to `@babel/plugin-transform-object-rest-spread` once it gets promoted to stage 4

**Comment by SKalt** [comment]
Thanks, in that case I'll avoid altering the README.
