### ISSUE TITLE
An error of `_Object$defineProperty` with `babel-runtime`

### ISSUE THREAD

**Issue by Shafley** [babel/babel-loader#553]
**react-native Version:**
0.50.4

**react-native-vector-icons Version**:
^4.4.2

**babel-plugin-transform-runtime Version**:
6.23.0

**Please tell us about your environment:**
Mac OS X 10_13_1

**Current behavior:**

`Unhandled JS Exception: Unexpected identifier '_Object$defineProperty'. import call expects exactly one argument. (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:97215)`
          
```js
// .babelrc
{
  "presets": ["react-native", "env", "stage-0"],
  "plugins": ["transform-decorators-legacy", ["transform-runtime", {
    "polyfill": false,
    "helpers": false,
    "regenerator": true
  }]
}
```
```js
// index.bundle  line 97215
__d(/* react-native-vector-icons/lib/react-native.js */function(global, require, module, exports) {'use strict';

import _Object$defineProperty from 'babel-runtime/core-js/object/define-property';
import _Object$keys from 'babel-runtime/core-js/object/keys';
Object.defineProperty(exports, "__esModule", {
  value: true
});

var _reactNative = require(12            ); // 12 = react-native

_Object$keys(_reactNative).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;

  _Object$defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _reactNative[key];
    }
  });
});
}, 931, null, "react-native-vector-icons/lib/react-native.js");
```
I found the source code of  `react-native-vector-icons/lib/react-native.js` only one line code below:
```js
export * from 'react-native'
```
 
**Expected/desired behavior:**
no error

**Comment by DrewML** [comment]
@babel-bot move to babel/babel

**Comment by DrewML** [comment]
This repository is for issues with the `webpack` loader for Babel. Please open your issue in https://github.com/babel/babel/issues

**Comment by loganfsmyth** [comment]
This is a duplicate of https://github.com/babel/babel/issues/2877 which has been fixed in Babel 7's beta releases.
