### ISSUE TITLE
Babel use with objects failing

### ISSUE THREAD

**Issue by Ziden** [babel/babel-loader#556]
Hi. I`m tryng to use Babel-loader on an old project, and i notice some issues regarding when babel loader is working on wrapped objects, is this its default behaviour ? I am not sure if this is a bug or something im doing wrong, i could not find much about it over google, so this is my last resource.

Would i need to change something to my code to make it work ?

This are my current specs:
 Webpack: 3.19.0
 babel/core: 7.0.0-beta.34
babel-loader: 8.0.0-beta.0

Please refer to my packages.json if needed:

http://paste.ubuntu.com/26187880/

I`m tryng to load a single file wrapped in a function:

http://paste.ubuntu.com/26187814/

Resuming, something old, that is built like this:

```js
(  window.global = { } )();
```

This is my webpack config:

```js
const webpackConfig = {
    context: __dirname,
    entry: {
        app: '../../JavaScript/Namespacing.js'
    },
    module: {
        rules: [
          {
            test: /.jsx?$/,
            exclude: /(node_modules|bower_components)/,
            use: {
              loader: 'babel-loader',
            }
          }
        ]
    },
    output: {
      path: __dirname + "/../../static/js",
      filename: "[name].js"
    },
    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            "window.jQuery": "jquery"
        })
    ],
}
```

And the error i get on my file is the following:

`Plugin/Preset files are not allowed to export objects, only functions.`

So, am i missing something or this is a issue?

Thanks for any attention.

**Comment by existentialism** [comment]
@Ziden you'll want to switch _all_ of your babel-* related deps to scoped & and matching beta version, i.e. (@babel/preset-env, @babel/preset-react, etc)

**Comment by Ziden** [comment]
Hi

I actually did the oposite, i downgraded every version since we had other stuff depending on older versions of babel.

```
const webpackConfig = {
    context: __dirname,
    devtool: 'source-map',
    entry: {
        app: '../../JavaScript/Namespacing.js'
    },
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                exclude: /(node_modules|bower_components)/,
                include: [
                   "../../JavaScript/Namespacing.js"
                ],
                use: [{
                    loader: 'babel-loader',
                    options: {
                        babelrc: false,
                        presets: ["es2015","react"]
                    }
                }
                ]
            }
        ]
    },
    output: {
      path: __dirname + "/../../static/js",
      filename: "[name].js"
    },
    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            "window.jQuery": "jquery"
        })
    ],
}
```
with my old babel deps now

```
    "babel": "^6.23.0",
    "babel-cli": "^6.26.0",
    "babel-eslint": "7.2.3",
    "babel-plugin-transform-class-properties": "6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.8.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "*",
    "babel-preset-react": "*",
```
But then its when things started to get really weird. 

http://prntscr.com/hnxuf6

I feel i`m really missing something trivial here....

**Comment by existentialism** [comment]
Did you downgrade babel-loader to 6.x as well?

**Comment by Ziden** [comment]
It was version 7.

I changed now to 6 and i get a different error.

```
 Module parse failed: Unexpected token (20:22)
You may need an appropriate loader to handle this file type.
| 
|    function onOpen(kwindow) {
|       ReactDOM.render(<InsertCrossReference data={data} close={closedialog } />, kwindow[0]);
```

Isnt this where  `presets: ["es2015","react"]`  should miss something ?

Thanks for your time, by the way, being very helpfull.

**Comment by Ziden** [comment]
I`m really confused as information seems not centralized for neither webpack or babel. It was seeming that babel loader was not handlin the files, so i changed the module loader config structure to the old one

```
   module: {
        loaders: [
            {
                test: /\.(js|jsx)$/,
                loader: 'babel-loader',
                exclude: /(node_modules|bower_components)/,
                options: { // tryed query as well
                    presets: ['env', 'react', 'es2015']
                }
            },
        ],
    },
```

I get this message

http://prntscr.com/hnz0y3

What am i missing here ??? I`ve been googlin for the day and every place has a different configuration, i can`t tell what is what, im actually going for trial and error, and i feel bad about it lol i just cant figure this out !

**Comment by Ziden** [comment]
Just noticed, if i remove 'es2015' it works. WHY ? Ive seen SEVERAL examples of react and es2015 presets, over and over.... -.-

**Comment by existentialism** [comment]
Can you post a small repo that reproduces your issue? It's quite difficult to debug this :)

**Comment by hzoo** [comment]
> WHY ? Ive seen SEVERAL examples of react and es2015 presets, over and over.... -.-

The error says you are missing the class properties transform. That is from doing something like `class A { a = 1; }` which is a TC39 Proposal and not a part of es2015 or react or env. It is included in the Stage 2 preset https://babeljs.io/docs/plugins/transform-class-properties/.

**Comment by OKNoah** [comment]
I am getting the same error, but have done as @existentialism suggested and upgraded to `@babel/*` stuff.

```json
"scripts": {
    "build": "./node_modules/.bin/webpack --config ./webpack.config.js",
    "dev": "yarn run build --watch"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.35",
    "@babel/preset-env": "^7.0.0-beta.35",
    "babel-eslint": "^8.0.3",
    "babel-loader": "^8.0.0-beta.0",
    "babel-preset-flow": "^6.23.0",
    "eslint": "^4.13.1",
    "foxx-cli": "^0.2.0",
    "webpack": "^3.10.0",
    "webpack-shell-plugin": "^0.5.0"
  }
```

**Comment by nicolo-ribaudo** [comment]
You should also update the Flow preset.

**Comment by nicolo-ribaudo** [comment]
Also, I recommend not using `^` on beta versions since they could break.

**Comment by OKNoah** [comment]
@nicolo-ribaudo Thanks. I had removed `flow` from webpack, but not `.babelrc`, which I think caused my confusion.

**Comment by Ziden** [comment]
Just for curiosity, i downgraded everything except webpack.

Instead of

```
 module: {
        rules: [ ]
    },
```

Im using

```
module: {
    loaders: []
}
```

And to be honest, as im using webpack 3, the rules should be the correct one. Now i got everything working, this is my final config just if anyone have the same problem. I`ve downgraded babel and all its sub components to 6xx and im using this config in webpack:

```
{
    context: __dirname,
    devtool: 'source-map',
    entry: {
        app: [
            'babel-polyfill',
            'files.js'
        ]
    },
    module: {
        loaders: [
            {
                test: /\.(js|jsx)$/,
                loader: 'babel-loader',
                exclude: /(node_modules|bower_components)/,
                options: {
                    plugins: ['transform-runtime'],
                    presets: ['env','stage-0','react'],
                }
            },
        ],
    },
    // JQ and JQ-UI are in bower + npm, TODO- Remove from Bower
    resolve : {
        alias: {
          "jquery-ui": "jquery-ui/jquery-ui.js",      
          modules: path.join(__dirname, "node_modules"),
        }
    },
    output: {
      path: staticPath,
      filename: "[name].js"
    },
    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            "window.jQuery": "jquery",
        })
    ],
}
```

Everything worked nicely, HOWEVER.... JS code is not being transpilled !!!

On IE, i get an error on this line:

```
// Load entry module and return exports
 	return __webpack_require__(__webpack_require__.s = 0);
```

It seems i have to go trial and error so hard on webpack + babel-loader ... I dont have any clue why the code is not being transpilled. Es2015 should handle that shouldnt it ?

My packages just in case:

```
    "babel": "^6.23.0",
    "babel-cli": "^6.26.0",
    "babel-eslint": "7.2.3",
    "babel-loader": "^6.0.0",
    "babel-plugin-transform-class-properties": "6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.8.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "*",
    "babel-preset-stage-0": "^6.24.1",
    "babel-runtime": "^6.26.0",
    "webpack": "^3.10.0",
```

I've read several articles / tutorials that points on that this would work... Any ideas ?

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babel-loader. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.
