### ISSUE TITLE
is there an option for output path of build files?

### ISSUE THREAD

**Issue by xgqfrms-gildata** [babel/babel-loader#561]
is there an option for output path of build files?

> just like this way.

![image](https://user-images.githubusercontent.com/29531779/34924107-5bf4523e-f9dc-11e7-813b-dec5692bb091.png)

I want to use the plugin's option to overwrite the webpack output option.

**Comment by loganfsmyth** [comment]
Output them where? Seems more like it would be a Webpack question than a Babel one, but I can try to help if it's clearer what you mean.

**Comment by xgqfrms-gildata** [comment]
I just want to separate my js files & css files in different folder.

> for example:

```code
"src/js " => "build/js/"

"src/css " => "build/css/"

```
but, now it's all in one folder, how can I do that?


![image](https://user-images.githubusercontent.com/29531779/34967453-e7e8e216-fa9d-11e7-9d88-9c4ba56e6a7a.png)

**Comment by xgqfrms-gildata** [comment]
I'm Looking forward to your reply.

**Comment by xgqfrms-gildata** [comment]
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/694#issuecomment-354961762

**Comment by loganfsmyth** [comment]
Sorry, I don't know the right approach for that. I'd recommend using Webpack's recommended support channels from https://github.com/webpack/webpack#support 

https://gitter.im/webpack/webpack is probably the best place to start.

**Comment by xgqfrms-gildata** [comment]
# my solution

https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/694#issuecomment-362549892
