### ISSUE TITLE
Consider publishing either v7 or v8 additionally under a different NPM name

### ISSUE THREAD

**Issue by simonbuchan** [babel/babel-loader#562]
**I'm submitting a feature request**

## Summary

Please consider publishing, in addition to it's current name, either babel-loader@7 or babel-loader@8 with a different name, so that both may be used in one webpack config.

## Example

```js
module.exports = {
  ...,
  module: {
    rules: [
      { test: /\.js$/, include: /node_modules/, loader: 'babel6-loader',
        // note, haul (see below) actually requires more options, use
        // defaults.module.rules[1].use[1].options here to grab the defaults
        options: { presets: ['react-native'] } },
      { test: /\.[tj]sx?$/, exclude: /node_modules/, loader: 'babel-loader' },
    ],
  },
};
```

## Background

I have a solution where I can share code using babel 7's new `typescript` transform between web and react-native. There is a project [`haul`](https://github.com/callstack/haul) which supports building react-native using webpack, but it doesn't yet support babel 7.

In part this is because `react-native` package ships code that must be transpiled but cannot be parsed in babel 7 since babylon 7 is stricter and rejects a couple of react-native files, and in any case, `babel-preset-react-native` doesn't work in babel 7, so it's fiddly to get the correct config.

After a while I've managed to work around the issues and get a working build with my source compiled using babel 7, but `react-native` compiled using babel 6 with the default `haul` config, but I have to use a quite ugly workaround: since I need both `babel-loader@7` and `babel-loader@8` installed, which [is not supported by npm](https://github.com/npm/npm/issues/5499), I followed the suggested workaround of a stub npm package that renames babel-loader:

```
// package.json
{ ...
  "dependencies": {
    ...
    "babel-loader": "8.0.0-beta.0",
    "babel6-loader": "file:./babel6-loader",
    ..
  }
}
// babel6-loader/package.json
{ "name": "babel6-loader", "version": "7.1.2", "dependencies": { "babel-loader": "7.1.2" } }
// babel6-loader/index.js
module.exports = require('babel-loader');
```

If this is accepted, I could simply post "here's a webpack.haul.js file you can use" for my team.

**Comment by probablyup** [comment]
`@babel/webpack-loader` might make sense given the new scoping structure.

**Comment by loganfsmyth** [comment]
For now we've decided not to publish Babel's integrations with other tools under the `@babel` scope. I also in general have my doubts about us maintaining this. I think, if multiple versions are your goal, it would be better to leave it up to users to publish packages that bundle up everything and address their goals.

**Comment by simonbuchan** [comment]
Fair enough, with Babel 7 being final and having decent support in the popular tools now there's not much motivation for this anymore.
