### ISSUE TITLE
the error.codeFrame maybe always undefined

### ISSUE THREAD

**Issue by HairyRabbit** [babel/babel-loader#568]
**I'm submitting a bug report**

**Webpack Version:**
3

**Babel Core Version**:
7

**Babel Loader Version**:
8

**Please tell us about your environment:**
Windows 10

**Current behavior:**
```js
error.codeFrame //=> undefined
```

![image](https://user-images.githubusercontent.com/5752902/35282940-ce247882-0091-11e8-8609-8ab68f82b90c.png)

Hi, I want to disabled the error stack, but something wrong with `err.hideStack`. I test the value 
 of error.codeFrame  that always be undefined.

**Comment by loganfsmyth** [comment]
Disabling the code frame isn't currently a feature of Babel 7.x. If you'd like to discuss that, let's move this to the https://github.com/babel/babel.
