### ISSUE TITLE
README is confusing

### ISSUE THREAD

**Issue by MadaraUchiha** [babel/babel-loader#573]
**I'm submitting a bug report**

**Webpack Version:**
N/A

**Babel Core Version**:
N/A

**Babel Loader Version**:
N/A

**Please tell us about your environment:**
N/A

**Current behavior:**
Current docs say in a small, grayed out font that these are the docs for the next version of Babel (which is still in beta), then continues to detail installation options for both.

If you miss the rather small notice at the top, you'd think that the documentation applies to babel installed normally via npm, and get errors that don't appear in the documentation.

**Expected/desired behavior:**
The documentation should make it clear that the information presented will not work for the current version of Babel. Or be fixed so that it does work for the current version of Babel.

----

I see a few options:
1. Make the notice larger and more prominent, and remove the installation instructions for the current version.
2. Make the documentation show everything for both versions (as it does with the installation instructions)

WDYT?

**Comment by loganfsmyth** [comment]
Since Babel 7 is now stable, this seems to have been resolved.
