### ISSUE TITLE
Alternative solution to using ProvidePlugin with babel polyfill

### ISSUE THREAD

**Issue by akatechis** [babel/babel-loader#576]
**I'm submitting a feature request** (I think)
I upgraded my babel set up today, and found that `@babel/polyfill` was breaking my ProvidePlugin injection for `bluebird` as Promise. After fiddling (unsuccessfully) with a bootstrap module, I decided to use the following solution which (IMO) is less obtrusive to the user's application code. Felt like sharing it with you all, and see if you'd like to include it in the docs in the relevant section. The solution, just uses webpack to replace the `runtime/core-js/promise` module with `bluebird` during build time. Just add the following to the `plugins` array of your configuration:

```javascript
new webpack.NormalModuleReplacementPlugin(/@babel\/runtime\/core-js\/promise/, resource => {
    resource.request = "bluebird";
  })
```

**Webpack Version:**
3.10.X

**Babel Core Version**:
7.0.0-beta.39

**Babel Loader Version**:
8.0.0-beta.0

**Please tell us about your environment:**
Windows 10

**Comment by loganfsmyth** [comment]
I think realistically at this point, in-place swapping Bluebird for native promises is a mistake. If you want to do it, you can, but it's not something I'd recommend. If you want to convert a native promise to a Bluebird promise, you can always use `Bluebird.resolve(p)` to get one.
