### ISSUE TITLE
Changes to the `.babelrc` file do not invalidate the cache

### ISSUE THREAD

**Issue by thasmo** [babel/babel-loader#587]
**I'm submitting a bug report.**

**Current Behavior**
When using `cacheDirectory: true` the cache does not get invalidated between changes to `.babelrc` contents. Disabling the cache works as expected and changes to `.babelrc` are reflected in the generated bundle.

**Expected Behavior**
When using `cacheDirectory: true` the cache should be invalidated between changes to the `.babelrc` file as mentioned in the docs.

**Versions**
* node: 9.5.0
* npm: 5.6.0
* webpack: 3.11.0
* babel-loader: 8.0.0-beta.1
* @babel/core": "^7.0.0-beta.40",
* OS: Windows 10 Pro 64-bit

**Configuration**
```js
{
    loader: 'babel-loader',
    options: {
        cacheDirectory: true,
    },
}
```

**Comment by danez** [comment]
Did this work with beta.0? Do you know?

**Comment by thasmo** [comment]
@danez, I think it didn't work either, hence I opened babel/babel#7427 when I was using beta.0.

**Comment by danez** [comment]
I keep it open for now, because the only case i found was a bug I introduced in beta.1.

**Comment by danez** [comment]
I released beta.2 which should fix the problem that was introduced in beta.1 If it still does not work, we need to investigate more.

**Comment by thasmo** [comment]
This seems to work now, using `beta.2`. :+1:
