### ISSUE TITLE
cacheDirectory does not work if set to /var/cache/<cachedir>

### ISSUE THREAD

**Issue by csvan** [babel/babel-loader#589]
*Delete what isn't applicable below*
**I'm submitting a bug report**

**Webpack Version:**
3.11.x

**Babel Core Version**:
6.x

**Babel Loader Version**:
7.1.x

**Please tell us about your environment:**
Windows 7 Enterprise, Cygwin

**Current behavior:**
Setting `cacheDirectory: '.babelcache'` successfully creates cache in the `.babelcache` dir, setting `cacheDirectory: true` successfully creates cache in default cache dir. 

However, setting `cacheDirectory: '/var/cache/babelcache'` results in no directory or cache being created, even though the executing user has RWX priviliges for the target.  No error is generated by the loader, and build still succeeds.

**Expected/desired behavior:**
The corresponding cache dir should be created in /var/cache/babelcache

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
Set cacheDirectory to the faulty value above.

* **What is the expected behavior?**
The corresponding cache dir should be created in /var/cache/babelcache

* **What is the motivation / use case for changing the behavior?**
Consistency, and the possibility to share cache across build environments.

**Comment by danez** [comment]
Can you check it might be in `/tmp/`. This could happen if the webpack process has no write permissions in a directory.

**Comment by csvan** [comment]
@danez checked `/tmp/`, nothing there unfortunately.

**Comment by csvan** [comment]
Other stuff I've tried:

1) chmod 777 on `/var/cache/babelcacge`
2) chmod 777 on `/var/cache` (!!!)
3) chmod +x on the above dirs.

None of the above solves it.

**Comment by danez** [comment]
Where do you set the cacheDirectory? What does the config look like?

**Comment by csvan** [comment]
Like so:

```
 module: {
      loaders: [
        {
          test: /\.js$/, 
          loader: 'babel-loader',
          include: [/* ... */],
          query: {
              cacheDirectory: '/var/cache/babelcache',
          },
        },
  /* ... */
}
```

**Comment by csvan** [comment]
As an update: it does seem like this works as expected on a Linux machine, but for some reason not on Cygwin.

**Comment by loganfsmyth** [comment]
I'm not sure there's anything clear here for us to do, so I'm going to close this. It seems most likely that it would be some kind of permissions issue, but it is hard to say. Babel doesn't do anything special when writing to disk though.
