### ISSUE TITLE
Allow earlier loaders to pass an AST directly to babel-loader

### ISSUE THREAD

**Issue by jiangjiu** [babel/babel-loader#597]
## **BEFORE YOU SUBMIT** please read the following:

**I'm submitting a feature request**

**Webpack Version:**
4.1.0

**Babel Core Version**:
7.x

**Babel Loader Version**:
8.x

**Please tell us about your environment:**
OSX 10.12 

**Current behavior:**
babel-loader just receive a source(string) and parse it.

i have processed some work(babel.parse=>process=>gen Code ) before I pass source to babel-loader.

**Expected/desired behavior:**
preProcess(babel.parse => process=>gen process) then 

babel-loader: parse=>process =>gen process

* **What is the expected behavior?**
preProcess(babel.parse => process) then  i wish i can pass babylonAST to babel-loader directly.

* **What is the motivation / use case for changing the behavior?**
it can reduce the parsing&&compiling process at a time

**Comment by loganfsmyth** [comment]
There's the possibility of skipping parsing, but code generation is generally still important to create the sourcemap for the content. Given that parsing is generally pretty fast, I'm not super convinced that this would be a big gain.

**Comment by jiangjiu** [comment]
thx for your reply~

could babel-loader provide an option so that  I can pass a AST to it directly?

seriously，what i preprocessed doesn't care more about sourcemap，i am focus the performance......

once unnecessary  parse&&gen will slow down my App's build-time even 10s.....(app's size is big)

**Comment by jquense** [comment]
There are a few cases where i do some quick work in front of babel-loader, it seems like nice win to have babel-loader accept an ast in those cases. Does code generation and sourcemaps get messed up if you start with an AST? Maybe there should be a `babel.generate()` method to pair with the new `babel.parse`?

**Comment by loganfsmyth** [comment]
If someone wants to explore doing this, I'd be up for continuing this discussion, I just don't want to give the idea that I'd generally recommend this. I also have no idea how easy or not it would be. Also, if you're making a bunch of changes to files before passing it to Babel, it seems like it'd be a lot better to just implement whatever changes you want to make as a Babel plugin to avoid the extra step in the first place.

If we were to support something like this, the only way I could see it being feasible is if the previous loader returned the original sourcecode, the original sourcemap, and the AST from after whatever transformation you did. I don't know how that integrates with Webpack and don't particularly have the time to explore it, but if someone else does I can review.

**Comment by xtuc** [comment]
Duplicates of https://github.com/babel/babel-loader/issues/539?

**Comment by loganfsmyth** [comment]
@xtuc I think this is slightly different. This is about `babel-loader` accepting arguments from earlier loaders, not about passing the AST to Webpack itself.

**Comment by xtuc** [comment]
Sorry @loganfsmyth, I didn't fully read this tbh. At least they are linked together now.

**Comment by jiangjiu** [comment]
yeah, write a bable-plugin is a good idea~
i will preprocess the code in my plugin.
thx for your help~

**Comment by loganfsmyth** [comment]
I'm going to close this since it's not clear there is anything actionable for this. If someone did want to explore it, feel free to do so, but it is not clear that it is worth doing.
