### ISSUE TITLE
Support for loadPartialConfig by user

### ISSUE THREAD

**Issue by timneutkens** [babel/babel-loader#598]
**I'm submitting a feature request**

**Babel Core Version**:
7.x

**Expected/desired behavior:**

Babel 7.x has a new feature where babelrc is resolved relative to the file that's being compiled. It also introduces `loadPartialConfig`. To make `loadPartialConfig` play nice with babel-loader we need a way to get the currently compiling file since `loadPartialConfig` needs it to get the correct `.babelrc` chain.

based on feedback from @loganfsmyth here: https://github.com/zeit/next.js/pull/4050#discussion_r176888131

* **What is the motivation / use case for changing the behavior?**

In Next.js we resolve the chain ourselves to apply custom plugins (react-hot-loader) and presets (`next/babel` preset)

**Comment by loganfsmyth** [comment]
What I'm thinking is we could expose an API for this kind of thing for users of `babel-loader` who want to wrap the loader, but still used its functionality. It seems like we could have an API like

```
const configs = new Set();

module.exports = require("babel-loader/custom")((babel, options) => {
  const isDev = options.isDev;
  const isServer = options.isServer;
  delete options.isDev;
  delete options.isServer;

  const config = babel.loadPartialConfig(options);

  const options = config.options;
  if (config.babelrc) {
    if (!isServer && !configs.has(config.babelrc) {
      configs.add(config.babelrc);

      console.log(`> Using external babel configuration`)
      console.log(`> Location: "${config.babelrc}"`)
    }
  } else {
    options.presets.push(presetItem);
  }

  if (dev && !isServer) {
    options.plugins.push(hotLoaderItem);
  }

  return options;
});
```

Then you could stick that in your own file and pass the path of that to Webpack as a loader.

Thoughts?

**Comment by loganfsmyth** [comment]
@KyleAMathews @jquense I realize this is probably something Gatsby should be doing too if you want to use `loadPartialConfig`. You're also currently resolving the config once up front which means `overrides` won't work. 

Looking Gatsby over more, I realize one hard part for you is that you pass the actual user-level config to your `modifyBabelrc`. I'd assume that happens once up front right now, but to align with how Babel expects things to work, it seems like you'd be a lot better off running that once up front with an empty config, then look up the user's config later.

**Comment by vjpr** [comment]
@loganfsmyth Is your comment here out of date now? https://github.com/babel/babel-loader/issues/598#issuecomment-375934667

See issue I ran into using this approach in next: https://github.com/zeit/next.js/issues/4301

**Comment by loganfsmyth** [comment]
@timneutkens Alright, I've posted #619. Take a look at the README in there. With this you should be able to reproduce your loader logic with

```
module.exports = require("babel-loader").custom(babel => {
  const presetItem = babel.createConfigItem(...);
  const hotLoaderItem = babel.createConfigItem(...);

  const configs = new Set();

  return {
    customOptions(options);
      const custom = {
        isDev: options.isDev,
        isServer: options.isServer,
      };
      const loader = Object.assign({}, options);
      delete loader.isDev;
      delete options.isServer;

      return { custom, loader };
    },
    config(cfg, { customOptions }) {
      const options = Object.assign({}, cfg.options);
      if (cfg.babelrc) {
        if (!isServer && !configs.has(config.babelrc)) {
          configs.add(config.babelrc);

          console.log(`> Using external babel configuration`)
          console.log(`> Location: "${config.babelrc}"`)
        }
      } else {
        options.presets = [...options.presets || [], presetItem];
      }

      if (isDev && !isServer) {
        options.plugins = [...options.plugins || [], hotLoaderItem];
      }

      return options;
    } 
  }
});
```

**Comment by loganfsmyth** [comment]
#619 landed so this is all set.
