### ISSUE TITLE
I have the same issues this is my webpack.config.js

### ISSUE THREAD

**Issue by tuannguyen1997** [babel/babel-loader#601]
const webpack = require('webpack');

module.exports = {
    entry: __dirname+ '/client/index.jsx',
    devServer: {
        hot: true,
        historyApiFallback: {
            index: __dirname+ '/client/index.jsx'
        }
    },
    output: {
        path: __dirname+ '/public/js',
        filename: 'bundle.js'
    },
    resolve: {
        modules: ['node_modules'],
        extensions: ['', '.js', '.jsx']
    },
    module: {
        loader:[
            {
                test: /\.jsx?$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                query: {
                    presets: ['es2015','react']
                }
            }
        ]
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
    ]
};

**Comment by loganfsmyth** [comment]
What same issue? There is not enough information here to help you.

**Comment by tuannguyen1997** [comment]
@loganfsmyth tks for your attention. i have solve my problem , my stupid
