### ISSUE TITLE
Typescript: Unable to re-export a type with Webpack 4

### ISSUE THREAD

**Issue by renchap** [babel/babel-loader#603]
**I'm submitting a bug report**
**Webpack Version:** 4.4.1
**Babel Core Version**: 7.0.0-beta.44
**Babel Loader Version**: 8.0.0-beta.0
**Please tell us about your environment:** 

I am using Bable beta with the typescript preset.

In one file, I define and export a type:
```ts
// a.ts
export type MyType = "a" | "b";
```

In another file, I re-export this type:
```ts
// b.ts
export { MyType } from "./a.ts";
```

**Current behavior:**

The export line is not present when `a.ts` is compiled using Babel. The re-export line in `b.ts` is compiled to:
```
export { MyType } from "./b";
```

Webpack fails with this error:
```
    ERROR in ./app/client/utils.ts
    79:0-51 "export 'myType' was not found in './a'
     @ ./b.ts
```

**Expected/desired behavior:**

It worked fine with Webpack 3, I am not sure why.
`babel` should not output anything for the re-export but it does. I am not sure why Webpack 3 was not complaining about the issue, but now Webpack 4 does.

I am not sure if this should be filled in this repo, or with Webpack or Babel core. I can provide a repro if this is needed and the correct place for this issue.

**Comment by bsouthga** [comment]
potentially related: https://github.com/TypeStrong/ts-loader/issues/751

**Comment by loganfsmyth** [comment]
I'm not sure this is an issue we can fix. Unfortunately TS overloads import and export to work for both types and values, so the only way to know whether to remove it would be to actually have a running TS typechecker. Unfortunately even if that were an option, Babel has no way to perform async operations like querying a server during the transformation process.

**Comment by Kovensky** [comment]
This is also a problem you would encounter with `ts-loader` if you were using the `--isolatedModules` option, which emits code without knowledge of the types of other modules (types only used for checking, not emit).

**Comment by donaldpipowitch** [comment]
@andy-ms Do you have an idea how/if this can be solved by any chance? I see re-exported types in many projects, this could be quite a problem for them, if they want to use Babels TypeScript preset 🤔

**Comment by mkazlauskas** [comment]
`export * from './a'` seems to be working

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babel-loader. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.

Since this isn't specific to `babel-loader` and is a general issue with TS in Babel, any further discussions should be in https://github.com/babel/babel

**Comment by andy-ms** [comment]
That's a compile error under `--isolatedModules`, which should always be set when using babel.

**Comment by donaldpipowitch** [comment]
So this means that type re-exports will never be usable with Babel, right? I think this was the only thing from our existing code base which stopped us from using Babel. 🤔

**Comment by andy-ms** [comment]
You can still do are-export if it's clear that you're exporting a type:
```ts
import { T as a_T } from "./a";
export type T = a_T;
```
You can also do `export * from "./a";`.

**Comment by donaldpipowitch** [comment]
I see, thank you for the first workaround!

**Comment by ubnt-marc-khouri** [comment]
@donaldpipowitch I've also had success (at least with my config) with the following, no `as` needed:

```
import { T } from "./a";
export type T = T;
```

**Comment by mbrowne** [comment]
Thanks @ubnt-marc-khouri for the workaround. Note that if you're re-exporting a generic type, you have to include the parameters for it to work correctly, e.g.:

```ts
import { QueryResult } from 'somewhere'
export type QueryResult<TData, TVariables> = QueryResult<TData, TVariables>
```

Unfortunately if your parameters have default values, you have to repeat the same default values defined on the original type, e.g.:

```ts
export type QueryResult<TData = any, TVariables = OperationVariables> = QueryResult<TData, TVariables>
```

The odd thing is that this actually used to work fine with a previous version of babel-loader and webpack. In our app it was working with webpack@3.12.0, babel-loader@8.0.5, and babel-preset-react-app@7.0.2 (and no, we were not using ts-loader).

**Comment by niksumeiko** [comment]
This issue will be fixed in Typescript 3.8. They already have a merged PR [microsoft/TypeScript#35200](https://github.com/microsoft/TypeScript/pull/35200) that will introduce `import type`, `export type` keywords.

A new syntax for type-only imports and exports will look as follows:
```ts
import type T from './mod';
import type { A, B } from './mod';
import type * as Types from './mod';
 
export type { T };
export type { T } from './mod';
```
 
https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/

**Comment by Akiyamka** [comment]
@niksumeiko, that cool, but not supported by babel-loader;
`export type { IGeocoder } from './types';` crush build with `Unexpected token` error

**Comment by petmat** [comment]
The last comment here by @Akiyamka addresses an issue I've ran into lately. I still get an `Unexpected token` error. Is this syntax supported or not?
```typescript
export type { IGeocoder } from './types';
```

**Comment by SapienTech** [comment]
@petmat I had same issue, and updating to latest babel fixed it for me.

**Comment by iyobo** [comment]
@SapienTech to be more exact, to get this to work I had to specifically update to `"@babel/preset-typescript": "^7.12.7",`
