### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by taoqf** [babel/babel-loader#605]
## **BEFORE YOU SUBMIT** please read the following:

**I'm submitting a bug report**

**Webpack Version:**
4.0.0-beta.3

**Babel Core Version**:
6.26.0

**Babel Loader Version**:
7.1.4

**Please tell us about your environment:**
Linux

**Current behavior:**
```sh
BabelLoaderError: SyntaxError: Unexpected token (26:17)
> 26 |     const a = { ...data, no }
```

**Expected/desired behavior:**
Do not throw out exception

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

```js
const data = {a:'abc'};
const no = 123;
const a = { ...data, no };
```

**Comment by nicolo-ribaudo** [comment]
What is your configuration? You need to enable the object-rest-spread plug-in.

**Comment by taoqf** [comment]
Thanks, I did not find that plugin.
