### ISSUE TITLE
How can I use the Babel Slack?

### ISSUE THREAD

**Issue by jjloneman** [babel/babel-loader#607]
How can I use the Babel Slack? The new issue instructions say:
> If you have a support request or question please submit them to [StackOverflow](http://stackoverflow.com/questions/tagged/babel) using the tag `[babel]` or the [Babel Slack](babeljs.slack.com). Future support requests will be closed.

I did post to StackOverflow but I didn't get a response. I'd like to use the Slack, but it looks like I have to have an account on the Slack team to get in (I do have different Slack accounts for different Slack teams, but I don't have one with the Babel Slack team). I get the following message:

> Don't have an account on this workspace yet?
> Contact the workspace administrator for an invitation

Is it possible to get an account so I can further get help with my problem? Thanks.

**Comment by loganfsmyth** [comment]
You should be able to register at https://slack.babeljs.io/

**Comment by jjloneman** [comment]
Ah, thank you! Is it possible to include that link in the comments when creating a new issue? There is a link to babeljs.slack.com but not slack.babeljs.io.
