### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by nakulnagariy** [babel/babel-loader#608]
Error Message:
ERROR in ./src/index.js
Module parse failed: Unexpected token (4:2)
You may need an appropriate loader to handle this file type.
|
| render(
|   <h1 id = 'title'
|     className = 'header'>
|     Hello World

Index.js
============
```
const { render } = ReactDOM;

```
render (
  <h1 id = 'title'
    className = 'header'>
    Hello World
  </h1>,
  document.getElementById('react-container')
)
```
```

webpack.config.js
===============
```
var webpack = require("webpack");

module.export = {
    entry: "./src/index.js",
    output: {
        path: "dist/assets",
        filename: "bundle.js",
        publicPath: "assets"
    },
    devServer: {
        inline: true,
        contentBase: "./dist",
        port: 3000
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                exclude:/(node_modules)/,
                loader: ["babel-loader"],
                query: {
                    presets: ['es2015']
                }
            }
        ]
      }
}
```

i don't know, what I'm missing? any help would be appreciated.

**Comment by nicolo-ribaudo** [comment]
You need to include the react preset to transpile jsx.

**Comment by nakulnagariy** [comment]
Thanks @nicolo-ribaudo for the quick reply but I didn't get it. did you mean that I need to add this "presets: ['transpile jsx']", sry but I didn't get it.

even i have the .babelrc file where i added some presets: 

{
    "presets": ["react"]
}

**Comment by nakulnagariy** [comment]
Thanks @nicolo-ribaudo , working fine now. appreciate your effort. you can close this now.
