### ISSUE TITLE
@babel/core no longer found by babel-loader

### ISSUE THREAD

**Issue by lunelson** [babel/babel-loader#609]
**I'm submitting a bug report**

**Webpack Version:**
4.x

**Babel Core Version**:
7.0.0-beta.44

**Babel Loader Version**:
8.0.0-beta.2

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
I'm developing a live-compiling dev-server which uses webpack and needs to self-contain its dependencies. It was working well up until recently; now `@babel/core` seems to have become unhooked from `babel-loader` and client apps (which depend on my package) can no longer serve or build JS unless `@babel/core` is included among their dependencies, which was a configuration overhead I was trying to avoid.

**Expected/desired behavior:**
`babel-loader` should know where to find `@babel/core`. Perhaps there is a way to write the loader config, such that core gets required in?

**Comment by lunelson** [comment]
BTW the package is https://github.com/lunelson/penny

**Comment by loganfsmyth** [comment]
Strange, since you have both `babel-loader` and `@babel/core` in your dependencies, it should automatically load that one. Would it be possible for you do make a reproducible example?

**Comment by lunelson** [comment]
I can't manage to reproduce it right now 😦. I'll re-open or make a new issue if I can isolate it 🤷‍♂️
