### ISSUE TITLE
.babelrc or config package.json is not considered

### ISSUE THREAD

**Issue by matsp** [babel/babel-loader#624]
**I'm submitting a bug report**

**Webpack Version:**
4.9.1

**Babel Core Version**:
7.0.0-beta.49

**Babel Loader Version**:
8.0.0-beta.3

**Please tell us about your environment:**
Windows 10

**Current behavior:**
babel-loader doesn't include config options from ".babelrc" or "package.json

**Expected/desired behavior:**
babel-loader uses ".babelrc" or "package.jso"

webpack: 
```javascript
{
        test: /\.js$/,
        loader: 'babel-loader',
        options: {
          babelrc: true,
          cacheDirectory: true
        }
 }
```

workaround:
```javascript
{
        test: /\.js$/,
        loader: 'babel-loader',
        options: {
          babelrc: true,
          extends: path.join(__dirname + '/.babelrc'),
          cacheDirectory: true
        }
 }
```
* **What is the expected behavior?**

Before I configured babel trough "package.json". I just regonized this issue because I disabled comments in babel and found comments in my output.

* **What is the motivation / use case for changing the behavior?**

**Comment by sebinsua** [comment]
I'm affected by this issue, too. However, it was appearing with beta.2 in my case.

The workaround you posted fixes it for me, however I would like to debug this more.

**Comment by matsp** [comment]
@sebinsua

Only using the new api with babel.config.js also fix this problem for me.

**Comment by swashcap** [comment]
Still seeing this problem with `babel-loader@8.0.0-beta.4`. My temporary workaround is to load the `.babelrc` contents manually and merge them into `options`:

```diff
diff --git a/webpack.config.js b/webpack.config.js
index d8535a8..43d7a84 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -1,11 +1,23 @@
+const fs = require('fs')
+const path = require('path')
+
 module.exports = {
   module: {
     rules: [{
       exclude: /node_modules/,
       loader: 'babel-loader',
-      options: {
-        cacheDirectory: true
-      },
+      /**
+       * babel-loader doesn't load the .babelrc
+       * @todo Remove once the issue is addressed
+       * {@link https://github.com/babel/babel-loader/issues/624}
+       */
+      options: Object.assign(
+        {
+          babelrc: false,
+          cacheDirectory: true
+        },
+        JSON.parse(fs.readFileSync(path.join(__dirname, '.babelrc'), 'utf-8'))
+      ),
       test: /\.js$/
     }, {
       exclude: /node_modules/,
```

**Comment by EvHaus** [comment]
I have a similar problem. `babel-loader` works correctly if the `.babelrc` is right next to my `package.json` directory, but if it's located 1 directory above (I use a monorepo) -- then it's not loaded.

Not sure if that's intentional or not.

**Comment by felixfbecker** [comment]
I'm affected by this too after trying to upgrade everything to v7. *I think* that this is only happening when transpiling `node_modules` (which I need to do for a dependency) - I don't get any errors for the files in my project, but the config is not considered for files in node_modules and I get errors that plugins are missing. 

Could it be that because these files are in node_modules, the config search "stops" at the package.json of the dependency, instead of traversing up? Or maybe looking in parent directories is broken in general?

**Comment by loganfsmyth** [comment]
For those having issues here, I'd recommend that you read over http://babeljs.io/docs/en/config-files#file-relative-configuration It is most likely the limitations on how `.babelrc` files are resolved that are tripping you up, and those docs should be able to give you some direction and understanding.

**Comment by vzaidman** [comment]
also take a look at this:
https://babeljs.io/docs/en/options#babelrcroots

**Comment by felixfbecker** [comment]
I've read that, but I don't understand what changed here between v7 -> v8?

**Comment by loganfsmyth** [comment]
@felixfbecker The differences between Babel 6 and Babel 7 in http://babeljs.io/docs/en/config-files#6x-vs-7x-babelrc-loading should help a bit. If compilation of `node_modules` is expected, then chances are you'll want to use a [project-wide config file](http://babeljs.io/docs/en/config-files#project-wide-configuration) instead of a `.babelrc`.

**Comment by felixfbecker** [comment]
So it matter whether the config file is a JS file or a JSON file? I prefer JSON because it can get autocompletion and validation against JSON schema

**Comment by loganfsmyth** [comment]
No, the important differentiation is that we `.babelrc` and `package.json#babel` config values only apply to the specific package that they are inside of, and will no longer affect `node_modules` files. For that, you'll either need to use Babel auto-searching for `babel.config.js` files, or pass the name of an explicit file. If you want a `babel.config.json` file instead, that's fine, but you'd need to pass the path to the file explicitly, e.g. `configFile: "./babel.config.json"` in your Webpack config `babel-loader` options.

**Comment by mohsenuss91** [comment]
> @sebinsua
> 
> Only using the new api with babel.config.js also fix this problem for me.

babelrc still ignored, 
@matsp how to fix that please!
