### ISSUE TITLE
Use Webpack mode to setup Babel environment

### ISSUE THREAD

**Issue by MindaugasVarkalys** [babel/babel-loader#631]
Currently to change Babel environment it's needed to specify `BABEL_ENV` variable or add additional `envName` configuration to loader's options.

Wouldn't be great if by default babel-loader would use webpack `mode` to set proper environment for Babel without any additional configuration?

**Comment by loganfsmyth** [comment]
I'm not aware of any other loaders that toggle their behavior based on `mode`. I think it makes more sense for that to be up to users to set in their Webpack config.
