### ISSUE TITLE
Babel doesnt seem to recognise jsx even though presets are loaded

### ISSUE THREAD

**Issue by Return-1** [babel/babel-loader#633]
Im not sure what it is that im missing in my configration. Im know the proper `webpack.config` file is used and i've added the presets both to `.babelrc` and presets on webpack.config. The presets are locally installed, i can see them in `node_modules`. Anything obvious that im missing?

**webpack.conf**
```
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
module.exports = {
  entry: path.join(__dirname, "demoapp"),
  output: {
    path: path.join(__dirname, "docs"),
    filename: "bundle.js"
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        use: "babel-loader",
        exclude: /node_modules/,
        presets: [
         "react",
        "es2015",
        "stage-2"
        ]
      },
      {
        test: /\.css$/,
        use: ["style-loader", "css-loader"]
      }
    ]
  },
  // plugins: [
  //   new HtmlWebpackPlugin({
  //     template: path.join(__dirname, "demoapp/index.html")
  //   })
  // ],
  resolve: {
    extensions: [".js", ".jsx"]
  },
  devServer: {
    contentBase: path.join(__dirname, "docs"),
    port: 8000,
    stats: "minimal"
  }
};
```

**package.json**
```
"devDependencies": {
    "babel-cli": "^6.2.0",
    "babel-core": "^6.2.1",
    "babel-loader": "^6.2.0",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "babel-preset-stage-2": "^6.24.1",
    "copy-webpack-plugin": "^4.5.1",
    "css-loader": "^0.22.0",
    "html-webpack-plugin": "^3.2.0",
    "extract-text-webpack-plugin": "^0.9.1",
    "json-loader": "^0.5.3",
    "node-sass": "^3.4.2",
    "react": "^0.14.0 || ^15.0.0",
    "react-dom": "^0.14.0 || ^15.0.0",
    "sass-loader": "^3.1.2",
    "style-loader": "^0.13.0",
    "webpack": "^1.15.0",
    "webpack-cli": "^3.0.8",
    "webpack-dev-server": "^1.12.1",
    "webpack-emit-all-plugin": "^1.0.0"
  },
```

**babel.rc**

```
{
    "presets": [
        "react",
        "es2015",
        "stage-2"
    ]
}
```

**Comment by nathanbuchar** [comment]
See #624. Try using the new `babel.config.json` instead of `.babelrc` :)

```js
// babel.config.js
module.exports = {
    presets: [
        'react',
        'es2015',
        'stage-2'
    ]
};
```

**Comment by jglynn43** [comment]
I'm seeing the same behavior in v8 with a monorepo. The `babel.config.js` is in the parent directory. Running babel directly in one of the packages with the `config-file` option works, e.g.
```
npx babel --verbose --config-file ../../babel.config.js src/
```
transpiles the JSX correctly and I can see the console log statements from the `babel.config.js` being emitted.  Setting the `root` or `babelrcRoots` in the babel-loader options seems to have no effect when running webpack and I do not see the console logs in the output. The behavior is the same running `lerna` commands from the parent directory.

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babel-loader. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.
