### ISSUE TITLE
Unable to build node 10 target with spread syntax

### ISSUE THREAD

**Issue by cainrus** [babel/babel-loader#635]
**I'm submitting a bug report**

**Webpack Version:**
3.12.0

**Babel Core Version**:
7.0.0-beta.51

**Babel Loader Version**:
8.0.0-beta.4

**Please tell us about your environment:**
OSX 17.5.0

**Current behavior:**

Can build with babel-cli:
```
$ npx babel index.js -o ./dist.js
$ cat ./dist.js

const a = {
  q: 1
};
const b = {
  w: 2
};
const c = { ...a,
  ...b
};

```
Unable to build with babel-loader:
```
$ npx webpack;

ERROR in ./index.js
Module parse failed: Unexpected token (7:12)
You may need an appropriate loader to handle this file type.
|   w: 2
| };
| const c = { ...a,
|   ...b
| };
```

**Expected/desired behavior:**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
Demo repo https://github.com/cainrus/webpack3-babel-loader8-babel7

* **What is the expected behavior?**
Build without errors.

* **What is the motivation / use case for changing the behavior?**
I'm using @babel/preset-env to tansform and polyfill only unsupported ES features.
Node 10 is supporting spread syntax, but I can't compile code with babel-loader.
I still can compile without any errors with @babel/cli command line

**Comment by loganfsmyth** [comment]
I believe you'll need to upgrade Webpack to 4.x since the object spread syntax will pass through Babel to Webpack and it needs to be able to parse it too.
