### ISSUE TITLE
Babel-loader disables webpack HMR for node app by default

### ISSUE THREAD

**Issue by tranvansang** [babel/babel-loader#648]
*Delete what isn't applicable below*
**I'm submitting a bug report**

**Webpack Version:**
4.12.1

**Babel Core Version**:
6.26.3

**Babel Loader Version**:
7.1.4

**Please tell us about your environment:**
Linux: 

> LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.1 LTS
> Release:	18.04
> Codename:	bionic

**Current behavior:**
Babel disables HMR in server side without `{"modules": false}` option

**Expected/desired behavior:**
Babel should leave the HMR work by default or print some warning text

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
This is the result of what I had spent hours to figure out the reason why HMR does not work.

If following guide in [this website](https://hackernoon.com/hot-reload-all-the-things-ec0fed8ab0), HMR works. However, if removing `{"modules": false}`  option in `env` preset, `module.hot.accept`'s callback is called, but app is not updated.

* **What is the expected behavior?**
`{"modules": false}` should be set by default, or even without it, babel should leave HMR work. I will also appreciate if anyone could explain me the reason of this option.

* **What is the motivation / use case for changing the behavior?**
There are bunch of options and configuration, it will be painful to find which one is misconfigured

**Comment by loganfsmyth** [comment]
With https://github.com/babel/babel-loader/pull/660 and Babel 7, this should be resolved.
