### ISSUE TITLE
Babel-Loader 5.1 breaks downstream loaders

### ISSUE THREAD

**Issue by AprilArcus** [babel/babel-loader#65]
with

```JavaScript
loaders: [
    {
        test: /\.js$/,
        loaders: [
            'ng-annotate',
            'babel?' + JSON.stringify({
                cacheDirectory: true,
            }),
            'eslint'
        ]
    }
]
```

```
ERROR in ./app/core/app.core.module.js
Module build failed: TypeError: Cannot read property 'length' of undefined
    at new Lut (/var/webclient/node_modules/ng-annotate-loader/node_modules/ng-annotate/build/es5/lut.js:16:37)
    at ngAnnotate (/var/webclient/node_modules/ng-annotate-loader/node_modules/ng-annotate/build/es5/ng-annotate-main.js:1018:15)
    at Object.module.exports (/var/webclient/node_modules/ng-annotate-loader/loader.js:10:13)
```

**Comment by vsolovyov** [comment]
I also experience this issue. I'm using `webpack.optimize.CommonsChunkPlugin` and this is what I get if I update `babel-loader` from 5.0.0 to 5.1.0:

    ERROR in ./frontend/src/main.jsx
    Module build failed: Error: ENOENT, open 'true/350c59cae6b7bce3bb58c8240147581bfdc9cccc.json.gzip'
     @ multi app

    ERROR in ./~/react-bootstrap/lib/index.js
    Module build failed: Error: ENOENT, open 'true/f3009735d056ed1affa726a9c730f97c175bfc38.json.gzip'
     @ multi vendor

**Comment by Couto** [comment]
`cacheDirectory=true` must be set as a boolean not a string, like in your example.
if you have an updated version of webpack you can set options using the `query` property like:

```
loaders: [
    {
        test: /\.js$/,
        loaders: [
            'ng-annotate',
            'babel?cacheDirectory',
            'eslint'
        ]
    }
]
```

**Comment by Couto** [comment]
oh! my answer  was to @vsolovyov 
I'm still looking at the original issue.

**Comment by vsolovyov** [comment]
@Couto it helped with my problem, thank you!

**Comment by Couto** [comment]
@AprilArcus I've merged a PR that might solve your problem, could you give it a test please? (I'm on the go and I don't have a test case for your problem =| )

**Comment by AprilArcus** [comment]
Works great!

**Comment by Couto** [comment]
Glad to hear :)
