### ISSUE TITLE
babel-loader won't transpile module with .mjs extension when using preset-env

### ISSUE THREAD

**Issue by miaulightouch** [babel/babel-loader#653]
**Webpack Version:**
4.16.5

**Babel Core Version**:
7.0.0-rc.1

**Babel Loader Version**:
8.0.0-beta.4

**Please tell us about your environment:**
Windows 10

**Current behavior:**
babel-loader won't transpile node module.

**Expected/desired behavior:**
bundle would be transpiled into es5.

**reproduce:**
1. clone this repo: https://github.com/miaulightouch/debug-babel-issue
2. run `npm run build:cjs` and look into bundle, `const` declaration is still there. 

**What is the expected behavior?**
imported module should be transpiled.

**Comment by foresightyj** [comment]
@miaulightouch I am having the same problem. Since you closed the issue, you must have found a solution. May I ask how you solved it? Thanks.
