### ISSUE TITLE
babel-loader not looking for "@babel/core", only for "babel-core"

### ISSUE THREAD

**Issue by SpencerDuball** [babel/babel-loader#654]
## **babel-loader not looking for `@babel/core`, only for `babel-core`

**I'm submitting a bug report**

**Webpack Version:**
4.16.5

**Babel Core Version**:
7.0.0-rc.1

**Babel Loader Version**:
7.1.5

**Please tell us about your environment:**
Linux - Ubuntu 18.04 / Darwin - MacOS
- I have tried this on both environments with the same issue, and same solution.

**Current behavior:**
Currently it appears that `babel-loader` is not searching for `@babel/core`, and instead only searching for `babel-core`.

JSFiddle of my config files:
[package.json & webpack.config.js](https://jsfiddle.net/f0h4o7ac/)

Error output:
```bash
ERROR in ./src/index.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-core'
```

```./node_modules/babel-loader/lib/index.js``` current behavior:
```js
"use strict";

var babel = require("babel-core"); // Error is here. Should look for and input "@babel/core" when installed.
var loaderUtils = require("loader-utils");
var path = require("path");
var cache = require("./fs-cache.js");
var exists = require("./utils/exists");
var relative = require("./utils/relative");
var read = require("./utils/read");
var resolveRc = require("./resolve-rc.js");
var pkg = require("../package.json");
var fs = require("fs");
/* CLIP */
/* ... */
```

* **What is the expected behavior?**
```./node_modules/babel-loader/lib/index.js``` expected behavior:
```js
"use strict";

var babel = require("@babel/core"); // Error is here. This is the expected behavior
var loaderUtils = require("loader-utils");
var path = require("path");
var cache = require("./fs-cache.js");
var exists = require("./utils/exists");
var relative = require("./utils/relative");
var read = require("./utils/read");
var resolveRc = require("./resolve-rc.js");
var pkg = require("../package.json");
var fs = require("fs");
/* CLIP */
/* ... */
```

**How to fix:**
Simply changing the line above to `"@babel/core"` fixes the issue no problem. This seems like it is probably a quick fix, I have a deadline to meet this week and won't have time to look over the code immediately. If someone else knows where to implement a quick fix for this, great. If not I will be checking on it this weekend after my deadline at work and try to get a solution submitted.

Thanks in advance if someone beats me to it.

**Comment by loganfsmyth** [comment]
For Babel 7.x you need to use the beta version of `babel-loader`.

**Comment by worc** [comment]
ran into the same issue, an older version of babel-loader wasn't looking for `@babel/core`:

```
ERROR in ./src/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-core'
```
