### ISSUE TITLE
used declatoris syntax, babel-loader throw an error: TypeError: Cannot read property 'left' of null

### ISSUE THREAD

**Issue by bigbigbo** [babel/babel-loader#656]
**Webpack Version:**
4.16.5

**Babel Core Version**:
7.0.0-rc.1

**Babel Loader Version**:
8.0.0-beta.0

**Please tell us about your environment:**
Windows 7

**Current behavior:**
I'd like to use the declatoris syntax，like this
```js
@withRouter
class extends React.Component
```

babel-loader configuration is
```js
{
        test: /\.(js|jsx)$/,
        include: [paths.appSrc],
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env', '@babel/preset-react'],
            plugins: [
              '@babel/transform-runtime',
              ['@babel/plugin-proposal-decorators', { legacy: true }],
              ['@babel/plugin-proposal-class-properties', { loose: true }],
              '@babel/proposal-do-expressions',
              '@babel/proposal-export-default-from',
              '@babel/proposal-export-namespace-from',
              '@babel/proposal-optional-chaining',
              '@babel/proposal-throw-expressions',
              '@babel/syntax-dynamic-import',
              '@babel/syntax-import-meta',
              'react-hot-loader/babel',
              'add-module-exports',
              'dva-hmr'
            ],
            cacheDirectory: true
          }
}
```
when I build, babel-loader throw an error
```js
ERROR in ./src/layouts/AppWrapper.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'left' of null
    at NodePath._getKey (E:\cool-feeling\node_modules\@babel\traverse\lib\path\family.js:132:25)
    at NodePath.get (E:\cool-feeling\node_modules\@babel\traverse\lib\path\family.js:124:17)
    at NodePath._getPattern (E:\cool-feeling\node_modules\@babel\traverse\lib\path\family.js:164:21)
    at NodePath.get (E:\cool-feeling\node_modules\@babel\traverse\lib\path\family.js:126:17)
    at ExportsFinder.findExports (E:\cool-feeling\node_modules\babel-plugin-add-module-exports\lib\index.js:89:17)
    at E:\cool-feeling\node_modules\babel-plugin-add-module-exports\lib\index.js:74:17
    at Array.forEach (<anonymous>)
    at ExportsFinder.isOnlyExportsDefault (E:\cool-feeling\node_modules\babel-plugin-add-module-exports\lib\index.js:72:38)
    at AssignmentExpression (E:\cool-feeling\node_modules\babel-plugin-add-module-exports\lib\index.js:22:21)
    at NodePath._call (E:\cool-feeling\node_modules\@babel\traverse\lib\path\context.js:53:20)
 @ ./src/pages/index/router.js 24:41-76
 @ ./src/pages/index/index.js
 @ multi (webpack)-dev-server/client?http://localhost (webpack)/hot/dev-server.js ./src/pages/index/index.js
```
I use [https://babeljs.io/docs/en/next/babel-plugin-proposal-class-properties.html](https://babeljs.io/docs/en/next/babel-plugin-proposal-class-properties.html) and I don't think I've set it wrong.
**Expected/desired behavior:**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
 [https://github.com/bigbigbo/cool-feeling](https://github.com/bigbigbo/cool-feeling)

* **What is the expected behavior?**
I can use declatoris syntax normally

* **What is the motivation / use case for changing the behavior?**
null

thanks!

**Comment by bigbigbo** [comment]
when I remove `babel-plugin-add-module-exports`, it can run well

**Comment by bigbigbo** [comment]
`babel-plugin-add-module-exports` does not seem to have made any adaptation to `babel@7.0.0-rc.1`

**Comment by loganfsmyth** [comment]
I'm confused about your example code
```
@withRouter
class extends React.Component
```
should be a syntax error because the class is not exported and does not have name.

That said, this does seem like an issue with `add-module-exports` so I'm going to close in favor of https://github.com/59naga/babel-plugin-add-module-exports/issues/63.

**Comment by bigbigbo** [comment]
@loganfsmyth sorry, this example code has brought you confusion.  In fact, this is a shortened code :smile:
