### ISSUE TITLE
warning "@vue/cli-plugin-babel > babel-loader@8.0.0-beta.4" has unmet peer dependency "webpack@>=2".

### ISSUE THREAD

**Issue by erwin16** [babel/babel-loader#659]
**Webpack Version:**
4

**Babel Core Version**:
7.0

**Babel Loader Version**:
8.0.0-beta.4

**Please tell us about your environment:**
OSX 10.13.6

**Current behavior:**
updating config with yarn , warning 
    warning "@vue/cli-plugin-babel > babel-loader@8.0.0-beta.4" has unmet peer dependency "webpack@>=2".

**Expected/desired behavior:**
no warning ...  as webpack is > 2 

* **What is the motivation / use case for changing the behavior?**
avoid resetting dependencies on project update

**Comment by pungggi** [comment]
Did you try with 8.0.0-beta.6

**Comment by loganfsmyth** [comment]
there doesn't appear to be anything specific we can do here. Perhaps your dependency flattening did not run properly?
