### ISSUE TITLE
module.exports is missing

### ISSUE THREAD

**Issue by vzaidman** [babel/babel-loader#673]
**I'm submitting a bug report**

**Webpack Version:**
4.17.1 (latest)

**Babel Core Version**:
7.0.0 (latest)

**Babel Loader Version**:
8.0.2 (latest)

**Please tell us about your environment:**
Windows 10

**Current behavior:**

Just updated to babel 7. We have a "feature toggle" system that serves the right module for dynamic configs (so `a` in `import a from 'a'` can be changed dynamically).

After upgrading from `8.0.0-beta.4` to `8.0.2` i got the following error:
`module.exports` is no longer an object, but it is undefined and I cant assign to it.

I found out it started on `8.0.0-beta.6`

![image](https://user-images.githubusercontent.com/5188459/44996971-b2e29280-afb3-11e8-8e67-09f8be8df97a.png)

**Expected/desired behavior:**

Like in the left image where it works.

**Steps to reproduce**

add a debugger to any file

**Comment by loganfsmyth** [comment]
Most likely this is from #660. Without knowing the details of what your code is doing, it is hard to say more, but most likely you're doing something that Webpack doesn't like.
