### ISSUE TITLE
WebPack is not outputting newest file after babel installation

### ISSUE THREAD

**Issue by AhmerRiaz** [babel/babel-loader#675]
Webpack was working well before babel installation but after that it isn't generating newest file. I am using webpack version 4.17.2 and babel loader version 8.0.2. How to fix this issue, as i have integrated webpack into gulp automation. Kindly Guide me how to fix this issue and rectify it as i am using it first time .

Here is the Webpack.config.js file

var path = require('path');
module.exports = {
    entry: './app/assets/scripts/App.js',
    output: {
        path: path.resolve(__dirname, "./app/temp/script"),
        filename: 'App.js'
    },

    module: {
        rules: [{
            test: /\.js$/,
            exclude: /(node_modules)/,
            use: {
                loader: 'babel-loader',
                options: {
                    presets: ['es2015']
                }
            }
        }]
    }
}
Here is Package.json file

    {
      "name": "travel-site",
      "version": "1.0.0",
      "dependencies": {
        "jquery": "^3.2.1",
        "jquery-smooth-scroll": "2.2.0",
        "lazysizes": "4.0.1",
        "normalize.css": "7.0.0",
        "picturefill": "3.0.2",
        "waypoints": "4.0.1"
      },
      "devDependencies": {
        "@babel/preset-env": "^7.0.0",
        "autoprefixer": "7.1.6",
        "babel-core": "^6.26.3",
        "babel-loader": "^8.0.2",
        "babel-preset-es2015": "^6.24.1",
        "browser-sync": "2.18.13",
        "del": "^3.0.0",
        "gulp": "^3.9.1",
        "gulp-cssnano": "2.1.2",
        "gulp-imagemin": "4.0.0",
        "gulp-modernizr": "1.0.0-alpha",
        "gulp-postcss": "^7.0.0",
        "gulp-rename": "^1.2.2",
        "gulp-rev": "8.1.0",
        "gulp-svg-sprite": "^1.4.0",
        "gulp-svg2png": "^2.0.2",
        "gulp-uglify": "^3.0.0",
        "gulp-usemin": "^0.3.28",
        "gulp-watch": "^4.3.11",
        "postcss-hexrgba": "^1.0.1",
        "postcss-import": "^11.0.0",
        "postcss-mixins": "^6.2.0",
        "postcss-nested": "^2.1.2",
        "postcss-simple-vars": "^4.1.0",
        "webpack": "^4.17.2",
        "webpack-cli": "^3.1.0"
      }
    }

**Comment by loganfsmyth** [comment]
Would you be able to more clearly explain what issue you are seeing? What "newest file" are we talking about? It would be great if you could produce a small repository that demonstrates the issue.

I'll also add that you're `babel-loader` version 8.x requires `@babel/core` and you appear to be using `babel-core`, which should immediately throw an exception when you run Webpack.

**Comment by AhmerRiaz** [comment]
I was trying to say that, it is not compiling js files after I installed
babel but the issue is resolved now after installing @babel/core.

I have a question, Can I use @babel/preset-es2015 in my presets?

 Thanks

**Comment by nicolo-ribaudo** [comment]
`es2015` has been deprecated, but `@babel/preset-env` supports all what `es2015` does and much more!

**Comment by AhmerRiaz** [comment]
Thanks a lot for helping me out.
