### ISSUE TITLE
no longer able to include a path inside node_modules after upgrading to v8

### ISSUE THREAD

**Issue by adambiggs** [babel/babel-loader#676]
## **BEFORE YOU SUBMIT** please read the following:
**I'm submitting a bug report**

**Webpack Version:** 4.18.0

**Babel Core Version**: 7.0.0

**Babel Loader Version**: 8.0.2

**Please tell us about your environment:** OSX 10.13.6

**Current behavior:**
`SyntaxError: Unexpected token import` at runtime when importing modules from e.g. `node_modules/@my-org-namespace/src/some-es6-module.js`

**Expected/desired behavior:**
`node_modules/@my-org-namespace/src/some-es6-module.js` should be processed by Babel. This worked fine before updating to `@babel/core@7`/`babel-loader@8`.

Simplified webpack config:
```js
// ...
{
  module: {
    rules: [
      {
        test: /\.js$/,
        use: 'babel-loader',
        include: [
          path.join(__dirname, 'src'),
          path.join(__dirname, 'node_modules/@my-org-namespace')
        ]
      },
    ]
  }
}
```

**Comment by loganfsmyth** [comment]
Assuming you're using a `.babelrc` file, you'll want to update your config to use a project-wide config file: http://babeljs.io/docs/en/config-files#project-wide-configuration
