### ISSUE TITLE
Automatic strict mode not working on OSX/Ubuntu

### ISSUE THREAD

**Issue by goffreder** [babel/babel-loader#69]
I'm using `babel-loader` as a loader in my `webpack` config file as it's explained in the docs (https://babeljs.io/docs/using-babel/#webpack), and I use `webpack-dev-server` for the automatic reload of the page. This is my whole `webpack.config.js`:

    var webpack = require('webpack');
    
    module.exports = {
        devtool: process.env.NODE_ENV !== 'production' ? 'eval' : null,
    
        entry: "./app/App.js",
    
        output: {
            path: '__build__',
            publicPath: '__build__',
            filename: 'build.js'
        },
    
        module: {
            loaders: [{
                test: /\.js$/,
                exclude: /node_modules\//,
                loader: 'babel-loader'
            }, {
                test: /\.css$/,
                loader: "style!css"
            }, {
                test: /\.(eot|woff2|ttf|svg|woff)$/,
                loader: 'url-loader'
            }]
        },
    
        plugins: [
            new webpack.DefinePlugin({
                'process.env': {
                    'NODE_ENV': '"' + process.env.NODE_ENV + '"'
                }
            }),
            new webpack.ProvidePlugin({
                React: "react"
            })
        ]
    };

With this configuration, on OSX and Ubuntu I have no problems, but on Windows 8 it breaks, saying that I'm trying to get a `WebSocket` out of `undefined`. By inspecting the code, I found out that because of the automatic strict mode, in the `browser.js` file of the `ws` package (a dependency of `webpack-dev-server`, it tries to set `this` as a variable, which is prevented by the strict mode.
So on Windows I had to blacklist the strict mode, but on OSX/Ubuntu it seems that it's already blacklisted, there's no `"use strict";` in my files. Is it a bug or I am missing something?

**Comment by Couto** [comment]
It seems to me, although I might be wrong, that the problem is not with babel-loader but with webpack-dev-server.

Does the error disappears  if you don't use the babel-loader?

**Comment by goffreder** [comment]
It seems that the problem is neither `babel-loader`'s nor `webpack-dev-server`'s. It's Windows' (guess it's not much of a surprise...): https://github.com/webpack/webpack-dev-server/issues/174
