### ISSUE TITLE
Module build failed (from ./node_modules/babel-loader/lib/index.js)

### ISSUE THREAD

**Issue by bibiehy** [babel/babel-loader#695]
win10

dependencies:
    "@babel/runtime": "^7.1.2",
    "react": "^16.5.2",
    "react-dom": "^16.5.2"

devDependencies:
    "@babel/core": "^7.1.2",
    "@babel/plugin-transform-runtime": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.4",

webpack.config.js
![image](https://user-images.githubusercontent.com/35096473/46291111-3b0e8480-c5c0-11e8-9269-573a09c0775b.png)

.babelrc
![image](https://user-images.githubusercontent.com/35096473/46291207-714c0400-c5c0-11e8-9379-c3ffef680d8f.png)

Error Image:
![image](https://user-images.githubusercontent.com/35096473/46290948-ce938580-c5bf-11e8-9a74-0ecea0837823.png)

**Comment by yogeshR5** [comment]
@bibiehy  i got same error now. what you did to resolved it.

**Comment by claudiuTicu** [comment]
anyone managed to fix this issue ?
