### ISSUE TITLE
Setting env from loader

### ISSUE THREAD

**Issue by ovidijusr** [babel/babel-loader#696]
**I'm submitting a feature request**

**Webpack Version:**
4.x

**Babel Core Version**:
7.00

**Babel Loader Version**:
8.0.0

**Please tell us about your environment:**
OSX 10.14

**Current behavior:**

I have different env inside babel.config file that uses different plugins (test, build and default)
I would like to choose build env but I cannot select in on babel-loader (besides setting env variable which is kinda hacky)

I would like to set env so webpack could use plugins that is set on different environments 

* **What is the motivation / use case for changing the behavior?**

for example jest: sets env to test automatically while webpack doesn't. I understand that I could write out the plugins inside babel-loader webpack, but then they would be split between two files (webpack.conf.js and babel.config.js) which for me does not makes sense

My babel file currently looks like this

```
module.exports = {
  presets: [
    ['@babel/preset-env',
      { modules: false },
    ],
    '@babel/preset-react',
  ],
  plugins: [
    '@babel/plugin-syntax-dynamic-import',

  ],
  env: {
    build: {
      plugins: ['./src/utils/babel/xxxPlugin', {
        functionNameArr: ['translate', 't'], // Functions that would be included in translatales.js
      }],
    },
    test: { // For jest
      presets: [
        '@babel/preset-env',
        '@babel/preset-react',
      ],
      plugins: [
        'transform-require-context', // For jest because require.context is webpack function
        ['module-resolver', // Used for theme based imports
          {
            root: './src',
            alias: {
              'assets/logos/logo': './src/assets/logos/xxx.svg',
            },
          },
        ],
      ],
    },
  },
};
````

**Comment by loganfsmyth** [comment]
You can use the [`envName`](https://babeljs.io/docs/en/options#envname) option to explicitly select the env.
