### ISSUE TITLE
Does not respect .babelrc in project when importing npm dependency.

### ISSUE THREAD

**Issue by ksmith97** [babel/babel-loader#697]
**I'm submitting a bug report**

**Webpack Version:**
4.17.1

**Babel Core Version**:
7.0.0

**Babel Loader Version**:
8.0.0

**Please tell us about your environment:**
Windows 10

**Current behavior:**
When babel is configured via .babelrc it does not apply this configuration to imported dependencies from node_modules.  It has to be specified in the babel-loader config in the webpack.config.js

**Expected/desired behavior:**
It should be applying the .babelrc configuration to all dependencies based on include/exclude config.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
https://github.com/ksmith97/WebpackIssue

* **What is the expected behavior?**
The .babelrc should be used to transpile all dependencies.  However, the resulting bundle still has arrow functions in the superagent portion of the code.

* **What is the motivation / use case for changing the behavior?**
As code is updated to ES6 not all library authors export IE compatible code.  We should be able to specify our desired global config in .babelrc

**Comment by loganfsmyth** [comment]
This is expected behavior in Babel 7. I'd recommend reading through https://babeljs.io/docs/en/config-files. If you want to compile `node_modules`, you'll want to use a `babel.config.js` file.
