### ISSUE TITLE
Supported webpack versions?

### ISSUE THREAD

**Issue by vikr01** [babel/babel-loader#709]
## **BEFORE YOU SUBMIT** please read the following:

**I'm submitting a bug report**

**Webpack Version:**
3.x

**Babel Core Version**:
7.x

**Babel Loader Version**:
8.x

**Please tell us about your environment:**
Linux

**Current behavior:**
`babel-loader@^8.0.0` fails with `webpack` v3, but `babel-loader@8.0.0-beta.4` works.

`peerDependencies` of `babel-loader` say it can be used with `webpack@>=2`, but README says `webpack` 4.x and package is tested with `webpack@^4.0.0`.

vuejs/vue#8948

**Comment by loganfsmyth** [comment]
What specifically fails on Webpack 3? If it isn't working, that is likely a bug.

**Comment by vikr01** [comment]
Found your answer to the same error [here](https://github.com/webpack/webpack/issues/4039#issuecomment-419284940). The issue was that `module.exports` was used in a file that was also using `import`. Thanks!
