### ISSUE TITLE
Stage 1 + "runtime" produces a bundle with cycles

### ISSUE THREAD

**Issue by ide** [babel/babel-loader#71]
Here's my webpack config:
```js
module.exports = [
  {
    name: 'browser',
    entry: './web/index.js',
    output: {
      path: path.join(__dirname, 'build'),
      filename: 'bundle.js',
      publicPath: '',
    },
    module: {
      loaders: [
        {
          test: /\.js$/,
          exclude: '/node_modules/',
          loader: 'babel-loader',
          query: {
            stage: 1,
            optional: ['runtime'],
          },
        },
        { test: /\.css$/, loader: 'style-loader!css-loader' },
      ],
    },
  }
]
```

index.js contains one line: `var React = require('react');`

When the bundle.js is loaded in the browser, there's some exception that looks like it's due to a cycle where a module ends up requiring itself while it is still being initialized. Removing the "runtime" option fixes the bug.

**Comment by Couto** [comment]
As far as I can tell, I'm tempted to say that it's not a babel-loader problem, but babel's itself.
Does that also happen if you transpile the file using the babel-cli? e.g.: `babel ./web/index.js --out-file ./build/bundle.js --stage 1 --optional runtime`

**Comment by ide** [comment]
babel froze for me on the command-line but I managed to fix this specific issue by excluding node_modules from the paths looked at by the webpack loaders.

**Comment by Couto** [comment]
Ah! Now that you mentioned it, I see it in your configuration, you've used a string instead of a regex in your exclude property... yeah that it's quite problematic.

Glad that you were able to fix it! :+1:
