### ISSUE TITLE
Array.findIndex not defined

### ISSUE THREAD

**Issue by TimothyKrell** [babel/babel-loader#73]
I'm loading the babel-runtime, but Array.findIndex seems to not be shimmed. Am I doing something wrong here?

my loader configuration:
```js
{ test: /.jsx?$/, loader: 'babel-loader?stage=0&optional[]=runtime', exclude: /(node_modules)|(bower_components)/ }
```

**Comment by Couto** [comment]
As far as I can tell, at least looking at your config, I see nothing wrong.

If other features from the runtime are working for you, I'll have to assume that it's a problem with babel itself and you should open a [issue there](https://github.com/babel/babel/issues).

**Comment by TimothyKrell** [comment]
OK. Will do. Thanks!

**Comment by zloirock** [comment]
Runtime transformer not adds prototype methods. Use [`babel/polyfill`](https://babeljs.io/docs/usage/polyfill/) or default version [`core-js`](https://github.com/zloirock/core-js) if you need it.

**Comment by TimothyKrell** [comment]
@zloirock Could you point me in the right direction on how to configure webpack to load the polyfill? I've been searching, but I'm not clear on the best way to do it with webpack.

**Comment by maitriyogin** [comment]
Hi, I'm having the same issue. Iv tried including require('babel/polyfill') into my entry file but get can't find exception.. Is the polyfill included with babel core or do I need to npm install it?
/stephen

**Comment by Couto** [comment]
Can someone provide me a small test case? (Some code and webpack config?) 
No matter what I do on my examples I always have `Array.findIndex` available.

**Comment by maitriyogin** [comment]
Hi,
I managed to get this working!
Forgot to include babel/polyfill to my entry config option in webpack. Also I only had babel-loader, so I did a npm babel install..
And hey presto everything worked.
/stephen

**Comment by d3viant0ne** [comment]
Resolving as a resolution exists for the original issue.
