### ISSUE TITLE
babel-loader 8.0.4 with babel 7.x does not load files contained in node_modules

### ISSUE THREAD

**Issue by kalutheo** [babel/babel-loader#730]
**I'm submitting a bug report**

**Webpack Version:**
4.25.1

**Babel Core Version**:
7.1.2

**Babel Loader Version**:
8.0.4

**Please tell us about your environment:**
OSX 10.x 

**Current behavior:**
I have a project with the following webpack.config : 
```
  module: {
    rules: [
      {
        test: /\.js[x]?$/,
        exclude: [/node_modules\/(?!@vp).*/],
        loader: 'babel-loader'
      },
```
and babelrc : 

```
{
  "presets": [
    "@babel/preset-flow",
    ["@babel/preset-env",
    {
      "targets": {
        "browsers": ["last 5 Chrome versions"]
      }
    }],
    "@babel/preset-react"
  ],
  "plugins": [
    // Stage 2
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",

    // Stage 3
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    ["@babel/plugin-proposal-class-properties", { "loose": false }],
    "@babel/plugin-proposal-json-strings"
  ]
}

```

- js files contained in the `src/` folder  of my  my project are properly loaded by babel
- js files contained in `node_modules/@vp-something` are not loaded by babel and i get SyntaxErrors . 

**Expected/desired behavior:**

- js files contained in the `src/` folder  of my  my project are properly loaded by babel-loader
- js files contained in  `node_modules` should be ignored expect js files contained in `node_modules/@vp-something`, they should be  properly loaded by babel-loader

**Comment by loganfsmyth** [comment]
You'll want to use a project-wide `babel.config.js` file: https://babeljs.io/docs/en/config-files#project-wide-configuration `.babelrc` files only apply to individual packages, not their dependencies.

**Comment by kalutheo** [comment]
it works ! thanks @loganfsmyth  you saved my day :-D
