### ISSUE TITLE
Bug : Customized Loader (async undefined)

### ISSUE THREAD

**Issue by lukepolo** [babel/babel-loader#737]
**I'm submitting a bug report**

**Webpack Version:**
4.26.0

**Babel Core Version**:
7.1.6

**Babel Loader Version**:
8.0.4

**Please tell us about your environment:**
OSX 10.13

**Current behavior:**
       
TypeError: Cannot read property 'async' of undefined
    at /Users/luke/Code/opensource/varie/varie-bundler/node_modules/babel-loader/lib/index.js:50:26

**Expected/desired behavior:**
No errors

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

You can test this out by using this repo : 

1. clone https://github.com/variejs/varie/tree/feature/babel-config
2. npm install
3. npm run dev

The bundle config is here : 
This is what im changing , https://github.com/variejs/varie-bundler/pull/53/files , 

Here is the gist of a build successful build (without the changes to get babel custom)
https://gist.github.com/lukepolo/19d1a36f24d66584173826582526479d

* **What is the expected behavior?**
Successful build.

* **What is the motivation / use case for changing the behavior?**
We are trying to change the 1 presets parameters  without overriding all parameters.

```js
module.exports = {
  presets: [["varie-app", {
    useBuiltIns : "entry"
  }]],
};
```
Then through the bundler we want to add `modern`

```js
module.exports = {
  presets: [["varie-app", {
    useBuiltIns : "entry",
    modern : true,
  }]],
};
```

This would allow us to build asynchronously rather than 1 bundle at a time. Everything works except this piece of the puzzle.

**Comment by loganfsmyth** [comment]
You've just got a typo, you're creating a new loader and then invoking it with no arguments: https://github.com/variejs/varie-bundler/pull/53/files#diff-5736b94b2ee8b3b95379b55ba9585e76R8

```
module.exports = require("babel-loader").custom(babel => {
  return () => {
    return {
    };
  }
})(); 
```
should be
```
module.exports = require("babel-loader").custom(babel => {
  return () => {
    return {
    };
  }
}); 
```

**Comment by lukepolo** [comment]
You were indeed correct
