### ISSUE TITLE
Error in babel-loader 5.1.3

### ISSUE THREAD

**Issue by thealjey** [babel/babel-loader#74]
Lines 42 and 43 attempt to assign to undefined variables, which results in an error:
#### babel-loader/index.js
    cacheDirectory = options.cacheDirectory;
    cacheIdentifier = options.cacheIdentifier;
when changed to look like the following, everything starts to work again:

    var cacheDirectory = options.cacheDirectory;
    var cacheIdentifier = options.cacheIdentifier;

**Comment by Couto** [comment]
I have the patch ready. Im just waiting to get out of the train to push it.

**Comment by darul75** [comment]
well, I do not know if patch is including something else, but just this changes (var declarations) fixes issue but stops webpack build in my case...;)

at the end it shows 
```
69% 311/312 build modules `
```
with nothin else after ;)

**Comment by Couto** [comment]
That's weird.
Can you upload your configuration?

**Comment by darul75** [comment]
{ test: /\.js?$/, loaders: ['react-hot', 'babel'], exclude: [/node_modules/, /__tests__/] },

**Comment by emmenko** [comment]
Same problem, thanks for patching it! :+1:

**Comment by Couto** [comment]
Ok the variable problem is fixed, and on npm (5.1.4)
However I believe that @darul75 has a new problem. I'll open a new issue with that.
