### ISSUE TITLE
babel-loader does ignores files on node_modules

### ISSUE THREAD

**Issue by aprilmintacpineda** [babel/babel-loader#741]
"webpack": "^4.26.1",
"babel-loader": "^8.0.4",

Under `modules.rules`:

```js
{
  test: path.join(__dirname, '../node_modules/fluxible-js'),
  enforce: 'pre',
  use: [
    'babel-loader',
    {
      loader: 'webpack-loader-clean-pragma',
      options: {
        pragmas: [
          {
            start: '/** @fluxible-config-use-JSON */',
            end: '/** @end-fluxible-config-use-JSON */'
          },
          {
            start: '/** @fluxible-no-synth-events */',
            end: '/** @end-fluxible-no-synth-events */'
          },
          {
            start: '/** @fluxible-config-sync */',
            end: '/** @end-fluxible-config-sync */'
          },
          {
            start: '/** @fluxible-config-persist */',
            end: '/** @end-fluxible-config-persist */'
          }
        ]
      }
    }
  ]
}
```

I know that it works and webpack honors the file rule because `webpack-loader-clean-pragma` works and does what it is told to. BUT babel-loader does not.

I've read about this --> https://babeljs.io/docs/en/babel-register#ignores-node-modules-by-default and tried:

```js
{
  test: path.join(__dirname, '../node_modules/fluxible-js'),
  enforce: 'pre',
  use: [
    {
      loader: 'babel-loader',
      options: {
         ignores: []
      }
    },
    {
      loader: 'webpack-loader-clean-pragma',
      options: {
        pragmas: [
          {
            start: '/** @fluxible-config-use-JSON */',
            end: '/** @end-fluxible-config-use-JSON */'
          },
          {
            start: '/** @fluxible-no-synth-events */',
            end: '/** @end-fluxible-no-synth-events */'
          },
          {
            start: '/** @fluxible-config-sync */',
            end: '/** @end-fluxible-config-sync */'
          },
          {
            start: '/** @fluxible-config-persist */',
            end: '/** @end-fluxible-config-persist */'
          }
        ]
      }
    }
  ]
}
```

I also tried this --> https://babeljs.io/docs/en/options#ignore

I think "WE" should be able to decide weather or not to parse a file or not regardless of where it's coming from. Removing that option away takes out creativity and freedom to code.

The only thing it doesn't parse is the spread. Because after the build, I'm no longer expecting to see any spread op anywhere on the vendors file. But the spread is still there.

**Comment by nicolo-ribaudo** [comment]
What is your babel configuration? Even if you are including node_modules, `.babelrc` doesn't work accross different packages so you'll need to use `babel.config.js`.

**Comment by aprilmintacpineda** [comment]
Ah yeah, sorry I forgot that part. Here's my `.babelrc.js`

```js
/** @format */

module.exports = {
  presets: ['@babel/preset-env', '@babel/preset-flow'],
  plugins: [
    '@babel/plugin-transform-runtime',
    'babel-plugin-inferno',
    '@babel/plugin-syntax-jsx',
    '@babel/plugin-syntax-dynamic-import'
  ]
};
```

**Comment by nicolo-ribaudo** [comment]
> I tried duplicating the babelrc config to babel.config.js. Now I'm getting errors everywhere...

At runtime or at compile time? What errors? Does the output file looks like Babel transpiled your dependencies?

**Comment by aprilmintacpineda** [comment]
Hmm.. weird... now it works. Last night it didn't. It exited with errors saying that a module's file was not found. The output is now okay. I didn't change anything other than update webpack to 4.27.0 since I saw them released a new update.

If the issue comes up again, I'll reopen...
