### ISSUE TITLE
Add additional info about settings babel config.

### ISSUE THREAD

**Issue by dimensi** [babel/babel-loader#753]
Now webpack 4 has completely taken over the processing of es modules. And it is possible in the settings of babel-preset-env and plugin-transform-runtime, to use options that remove the transformation of the modules. I think adding information about this will be useful for newbies like me. Not every person will come to the conclusion that the transformation of modules can be completely removed or whether these settings should be touched at all.
I think many people know about Babel, but about how to install it climb right here.

**Comment by daranhep** [comment]
can you be more specific about this? i'm a noob and have problems installing it properly.

**Comment by dimensi** [comment]
i talk about adding help info in README.md about how to off process modules by babel.
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "entry",
        "modules": false,
      }
    ]
  ],
  "plugins": [
    ["@babel/plugin-transform-runtime", {
      "useESModules": true,
    }]
  ]
}
```
