### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by csmirror** [babel/babel-loader#760]
How to fix this? v1.1.0
![image](https://user-images.githubusercontent.com/3611066/51501715-1f83ef80-1de4-11e9-969a-1f09fc9c31e4.png)

**Comment by kogai** [comment]
I'd faced the same situation, and interestingly when try to parse a file which this error occurred by using babel-cli (like `npx babel src/routes/routes.js`) it does not claim any error 🤔

**Comment by loganfsmyth** [comment]
This is not a Babel issue: https://github.com/webpack/webpack/issues/8656
