### ISSUE TITLE
options:{filename:'path/to/.babelrc'}

### ISSUE THREAD

**Issue by jimwmg** [babel/babel-loader#761]
I had seen the source code of babel-loader ;
with babel-loader@7 ,it support the config like this ,filename;
but with babel-loader@8 ,what should i do to relalize this ?

```javascript
{
        test: /\.js$/,
        exclude: getExcludeBabelPath(),
        // 不能babel babel-runtime
        include: getBabelPath(),
        use: [{
          loader: 'babel-loader',
          options: {
            'filename': path.join(cml.root, 'chameleon.js')
          }
        }

        ]
      },
```

**Comment by jrichardsz** [comment]
Any updated?

**Comment by nicolo-ribaudo** [comment]
Filename is the name of the file being transpiled. You probably want the `configFile` option, which should point to a `babel.config.json`-like file.

**Comment by krutoo** [comment]
now there is some way to indicate where the configuration lies?

**Comment by nicolo-ribaudo** [comment]
@krutoo Yes, `configFile`: https://babeljs.io/docs/en/options#configfile (as mentioned at https://github.com/babel/babel-loader/issues/761#issuecomment-593139841).
