### ISSUE TITLE
Pass through the source filename to babel transform (and plugins)

### ISSUE THREAD

**Issue by tzvipm** [babel/babel-loader#767]
**I'm submitting a feature request**

**Webpack Version:**
4.25.1

**Babel Core Version**:
7.2.2

**Babel Loader Version**:
8.0.5

**Please tell us about your environment:**
OSX 10.14.2

**Current behavior:**
I wrote a plugin for babel that relies on the `opts.filename` and `opts.filenameRelative` properties. It seems to be working within `babel-loader` for the purposes of analyzing the adjacent files, but the filename itself seems to be modified. 

**Expected/desired behavior:**
Babel plugins should be able to access some unmodified version of the `filename` and `cwd` when invoked via `babel-loader`.

**What is the motivation / use case for changing the behavior?**
I need to get access to the full source file path to use for generating a legible id and hash.

**Comment by loganfsmyth** [comment]
What modification to the filename are you seeing?

**Comment by tzvipm** [comment]
```
const extension = path.extname(filenameRelative);
const legible = path.basename(filenameRelative, extension);
```

**Comment by loganfsmyth** [comment]
Hmm, since it's a relative path it's certainly possible it could start with `..`, but stripping the extension on its own shouldn't be a problem.

Would you be able to make an example repository to demonstrate the issue?

**Comment by tzvipm** [comment]
@loganfsmyth, thanks for all your help. In trying to replicate with a small test repo, I realized that the issue in my case was that `awesome-typescript-loader` was executing before babel and messing with the file paths.

**Comment by loganfsmyth** [comment]
Perfect, glad you got it worked out!
