### ISSUE TITLE
Build hangs

### ISSUE THREAD

**Issue by Couto** [babel/babel-loader#77]
According to @darul75 on #74, his build hangs:

```
69% 311/312 build modules `
```

His config is: 
```
{ test: /\.js?$/, loaders: ['react-hot', 'babel'], exclude: [/node_modules/, /__tests__/] },`
```

Feel free to add anything that I'm missing.

**Comment by thealjey** [comment]
on my system it doesn't hang, however it did get significantly slower then it used to be

**Comment by darul75** [comment]
hi ok, it was due an incompatibility between sass-loader and node-sass, took me a while to find it. thx

**Comment by Couto** [comment]
@darul75 that's cool! Less work for me! ;)
@thealjey Does that still happen with the cache on/off ??

**Comment by thealjey** [comment]
`cacheDirectory: true` - 2654ms, `cacheDirectory: false` - 3049ms

so, cacheDirectory does make it compile slightly faster
unfortunately I don't know what the compilation time was before I updated babel this morning, I never checked, it was just fast enough for me
I'll try downgrading and comment here as soon as I have the time

**Comment by thealjey** [comment]
sorry, I was wrong, after I tried downgrading it turned out that it was not faster after all
I guess that's what happens, when you judge too soon, without measuring stuff first

**Comment by Couto** [comment]
@thealjey no problem :)
