### ISSUE TITLE
App not running in IE (Polyfill issue)

### ISSUE THREAD

**Issue by nchagas** [babel/babel-loader#771]
Hello ,

I am not being able to open my react app in IE. I've tried importing babel-polyfill in my src/index.js, App.js and still not working. I'm using webpack. 

Any idea how to resolve this?
Thanks in advance

**Comment by nicolo-ribaudo** [comment]
"Not working" isn't enough.

What are your error messages (with full stack traces)/Babel config/webpack config/package.json?

**Comment by nchagas** [comment]
> "Not working" isn't enough.
> 
> What are your error messages (with full stack traces)/Babel config/webpack config/package.json?
