### ISSUE TITLE
Babel transform seems to be stripping some path separators on Windows?

### ISSUE THREAD

**Issue by brandonweiss** [babel/babel-loader#777]
**I'm submitting a bug report**

**Babel Core Version**:
^7.4.0

**Please tell us about your environment:**
Windows Server, version 1803

**Current behavior:**

I have some code that is run through Babel like so:

```javascript
let code = `import React from "C:\Users\travis\build\brandonweiss\charge\node_modules\react\index.js"`

let result = babelTransform(code, {
  presets: [
    require.resolve("@babel/preset-react"),
    [
      require.resolve("@babel/preset-env"),
      {
        targets: {
          node: "current",
        },
      },
    ],
  ],
})

result.code
```

This is the output (roughly):

```javascript
"use strict";
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;
var _UsersRavisUildRandonweisschargeOde_modulesEactindex = _interopRequireDefault(require("C:Users\travis\build\brandonweisscharge\node_modules\reactindex.js"));
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

The important part is:

```
"C:Users\travis\build\brandonweisscharge\node_modules\reactindex.js"
```

On Linux it works fine, but on Windows, Babel seems to have mysteriously removed two of the path separators, munging the path.

**Expected/desired behavior:**

The path should be:

```
"C:Users\travis\build\brandonweiss\charge\node_modules\react\index.js"
```

**Comment by nicolo-ribaudo** [comment]
This can be reproduced in the REPL: https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIgGEAuAHQFUBnJKS0mKFAN2DoCMBXYAGwBNS2jAHa8IQgO5JWdNAAsUUAOZJSQiLyQB9EOo7ckdKKgylgIpAA8AdACtK-IA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015&prettier=false&targets=&version=7.4.2

@babel-bot Move to babel/babel

**Comment by brandonweiss** [comment]
Dammit, sorry, that’s what I meant to do! 🤦‍♂️ Had too many tabs open. Thanks for the REPL/link!

**Comment by brandonweiss** [comment]
Done! https://github.com/babel/babel/issues/9765
