### ISSUE TITLE
trouble with spread operator

### ISSUE THREAD

**Issue by lionkeng** [babel/babel-loader#78]
Hi there. Need some help with transpiling a spread operator. 
I have code that looks like this:
```javascript
    var {
      style,
      useContent,
      contentType,
      contentStyle,
      ...other
    } = this.props;
```

with `jsx-loader?harmony`, webpack happily transpiles. But with `babel-loader`, I am getting an error that looks like this:

> ERROR in ./app/jsx/components/fullwidth-section.jsx
> Module build failed: SyntaxError:  /Users/keng/work/virtuosityworks/aubusson/app/jsx/components/fullwidth-section.jsx: Unexpected token (54:6)
>  52 |       contentType,
>  53 |       contentStyle,
>  `> 54 |       ...other
>     |       ^
 >  55 |     } = this.props;
>   56 | 

My module config for babel-loader looks like this:
>      { test: /\.jsx?$/, loaders: ['babel-loader'], exclude: /node_modules/},

**Comment by hzoo** [comment]
I think you need `babel-loader?stage=1` (experimental features)

**Comment by lionkeng** [comment]
@hzoo Thanks! that worked.
