### ISSUE TITLE
Babel-loader with “@babel/preset-typescript” can not transform the git submodule tsx file?

### ISSUE THREAD

**Issue by flytam** [babel/babel-loader#782]
I use the babe-loader with "@babel/preset-typescript" in webpack, it looks can't transform my git submodule's ts file. It arcurred the error.How can i deal with it?(lib dir is my git sub module)

![image](https://user-images.githubusercontent.com/20512530/55862569-48c64780-5bab-11e9-9812-dc48dd946a0a.png)

My webpack config is
```
    rules: [
      {
        test: /\.(jsx?|tsx?)$/,
        exclude: /node_modules/,
        use: ['babel-loader']
      }
    ]
```
```
// babelrc
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": false
      }
    ],
    "@babel/preset-react",
    "@babel/preset-typescript"
  ],
  "plugins": ["@babel/plugin-proposal-class-properties"]
}

```

How to solve it?

**Comment by flytam** [comment]
It can work correctly when i don't package the sub module's ts file

**Comment by nicolo-ribaudo** [comment]
Does the submodule have a package.json file? If so, .babelrc isn't applied across different packages: you need to use `babel.config.js`

**Comment by flytam** [comment]
ok. It work well ,thanks!

**Comment by uyarn** [comment]
> Does the submodule have a package.json file? If so, .babelrc isn't applied across different packages: you need to use `babel.config.js`

thanks you sir
