### ISSUE TITLE
../node_modules/dnd-core/lib/reducers/index.js Module parse failed: Unexpected token (12:16) You may need an appropriate loader to handle this file type. |             type: action.type, |             payload: { |                 ...action.payload, |                 prevTargetIds: get(state, 'dragOperation.targetIds', []), |             },

### ISSUE THREAD

**Issue by Reshmabcu** [babel/babel-loader#793]
## **BEFORE YOU SUBMIT** please read the following:

*Delete what isn't applicable below*
**I'm submitting a bug report**
**I'm submitting a feature request**
**I'm submitting a support request** => Please do not submit support request here, see note at the top of this template.

**Webpack Version:**
1.10.x/2.x

**Babel Core Version**:
6.x

**Babel Loader Version**:
5.4.x/6.2.x

**Please tell us about your environment:**
OSX 10.x / Linux / Windows 10

**Current behavior:**

**Expected/desired behavior:**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by nicolo-ribaudo** [comment]
What is your Babel configuration?

**Comment by Reshmabcu** [comment]
> What is your Babel configuration?

{
  "_from": "babel-core@6.26.0",
  "_id": "babel-core@6.26.0",
  "_inBundle": false,
  "_integrity": "sha1-rzL3izGm/O8RnIew/Y2XU/A6C7g=",
  "_location": "/babel-core",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "babel-core@6.26.0",
    "name": "babel-core",
    "escapedName": "babel-core",
    "rawSpec": "6.26.0",
    "saveSpec": null,
    "fetchSpec": "6.26.0"
  },
  "_requiredBy": [
    "/babel-jest",
    "/babel-register",
    "/jest-runtime",
    "/react-scripts"
  ],
  "_resolved": "https://registry.npmjs.org/babel-core/-/babel-core-6.26.0.tgz",
  "_shasum": "af32f78b31a6fcef119c87b0fd8d9753f03a0bb8",
  "_spec": "babel-core@6.26.0",
  "_where": "C:\\Users\\User\\Documents\\thesis\\react_express_starter-master\\client\\node_modules\\react-scripts",
  "author": {
    "name": "Sebastian McKenzie",
    "email": "sebmck@gmail.com"
  },
  "bundleDependencies": false,
  "dependencies": {
    "babel-code-frame": "^6.26.0",
    "babel-generator": "^6.26.0",
    "babel-helpers": "^6.24.1",
    "babel-messages": "^6.23.0",
    "babel-register": "^6.26.0",
    "babel-runtime": "^6.26.0",
    "babel-template": "^6.26.0",
    "babel-traverse": "^6.26.0",
    "babel-types": "^6.26.0",
    "babylon": "^6.18.0",
    "convert-source-map": "^1.5.0",
    "debug": "^2.6.8",
    "json5": "^0.5.1",
    "lodash": "^4.17.4",
    "minimatch": "^3.0.4",
    "path-is-absolute": "^1.0.1",
    "private": "^0.1.7",
    "slash": "^1.0.0",
    "source-map": "^0.5.6"
  },
  "deprecated": false,
  "description": "Babel compiler core.",
  "devDependencies": {
    "babel-helper-fixtures": "^6.26.0",
    "babel-helper-transform-fixture-test-runner": "^6.26.0",
    "babel-polyfill": "^6.26.0"
  },
  "homepage": "https://babeljs.io/",
  "keywords": [
    "6to5",
    "babel",
    "classes",
    "const",
    "es6",
    "harmony",
    "let",
    "modules",
    "transpile",
    "transpiler",
    "var",
    "babel-core",
    "compiler"
  ],
  "license": "MIT",
  "name": "babel-core",
  "repository": {
    "type": "git",
    "url": "https://github.com/babel/babel/tree/master/packages/babel-core"
  },
  "scripts": {
    "bench": "make bench",
    "test": "make test"
  },
  "version": "6.26.0"
}

**Comment by Reshmabcu** [comment]
> What is your Babel configuration?

can you please help me out.. It gives me too much pain. actually i am a beginner so i have not too much knowledge about it.

**Comment by nicolo-ribaudo** [comment]
That's not your configuration. I meant your babelrc or babel.config.js file.
