### ISSUE TITLE
Setting corejs version for @babel/preset-env does not work

### ISSUE THREAD

**Issue by bensampaio** [babel/babel-loader#796]
**I'm submitting a bug report**

**Webpack Version:**
4.35.2

**Babel Core Version**:
7.5.0

**Babel Loader Version**:
8.0.6

**Please tell us about your environment:**
macOS 10.14.5

**Current behavior:**

According to the migration instructions [here](https://babeljs.io/blog/2019/03/19/7.4.0#migration-from-core-js-2) I should be able to set the `corejs` version used by `@babel/preset-env` to 3. However, when doing that in the webpack configuration via this loader I get the following error: `Error: [BABEL] <path>: Invalid Option: corejs is not a valid top-level option.`

**Expected/desired behavior:**

Well I would expect the option to be valid since it is mentioned in the migration instructions.

**Comment by existentialism** [comment]
@bensampaio can you show us your babel config?

**Comment by bensampaio** [comment]
The relevant part of my webpack config looks like this:

```
  module: {
    rules: [
      {
        loader: 'babel-loader',
        options: {
          cacheDirectory: true,
          plugins: ['@babel/plugin-syntax-dynamic-import'],
          presets: [
            ['@babel/preset-env', {
              corejs: 3,
              targets: 'last 2 versions, not dead',
              useBuiltIns: 'usage',
            }],
            '@babel/preset-react',
          ]
        },
        test: /\.(jsx?|mjs)$/
        type: 'javascript/auto',
      },
      // other loaders
    ]
  }
```

Without `corejs: 3` this configuration works as expected.

**Comment by bensampaio** [comment]
@existentialism did this help or do you need more information?

**Comment by existentialism** [comment]
@bensampaio your config looks correct, so either your version of @babel/preset-env is old, or something else is going on.

Can you provide a small repro that reproduces the problem, b/c it works fine locally (and we have a number of tests that cover the option)

**Comment by bensampaio** [comment]
@existentialism I figured it out. Yarn was not resolving my dependencies correctly. I upgraded yarn and now it is using the correct version of babel-loader.
