### ISSUE TITLE
Spread operator failing after babel update

### ISSUE THREAD

**Issue by HRK44** [babel/babel-loader#798]
**I'm submitting a bug report**

**Webpack Version:**
3.8.1

**Babel Core Version**:
7.5.0

**Babel Loader Version**:
8.0.6

**Please tell us about your environment:**
Linux

**Current behavior:**
```
ERROR in ./src/utils/logger/logger.js
Module parse failed: Unexpected token (50:10)
You may need an appropriate loader to handle this file type.
|           filename: 'logs/infos.%DATE%.log',
|           level: process.env.LOG_LEVEL || 'info',
|           ...config
|         }), new _winstonDailyRotateFile.default({
|           name: 'error-file',
 @ ./src/app.js 9:37-69
 @ multi ./src/app.js
```
**Expected/desired behavior:**

Should work fine since spread operator is already handled by nodejs

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

This is related to this issue : https://stackoverflow.com/questions/56900902/babel-with-nodejs-not-working-spread-operator

package.json: 

```
"devDependencies": {
        "@babel/cli": "7.5.0",
        "@babel/core": "7.5.0",
        "@babel/node": "7.5.0",
        "@babel/plugin-proposal-class-properties": "7.5.0",
        "@babel/plugin-transform-runtime": "7.5.0",
        "@babel/preset-env": "7.5.2",
        "babel-eslint": "10.0.2",
        "babel-loader": "8.0.6",
        "eslint": "6.0.1",
        "nodemon": "1.19.1",
        "webpack": "3.8.1",
        "webpack-node-externals": "1.7.2"
    },
    "dependencies": {
        "@babel/runtime": "7.5.2",
        "winston": "3.2.1",
        "winston-daily-rotate-file": "3.9.0"
    }
```

.babelrc:

```
{
    "plugins": [
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-transform-runtime"
    ],
    "presets": [
        [
            "@babel/preset-env",
            {
                "modules": "commonjs",
                "targets": {
                    "node": "current"
                },
                "useBuiltIns": "usage",
                "corejs": { "version": 3, "proposals": true }
            }
        ]
    ]
}
```

webpack.config.js:

```
'use strict';

const path = require('path');
const webpack = require('webpack');
const nodeExternals = require('webpack-node-externals');

/*-----------------------------
Server Config
-----------------------------*/
module.exports = {
    name: 'server',
    target: 'node',
    externals: [nodeExternals({
        modulesDir: path.join(__dirname, '/node_modules')
    })],
    context: __dirname,

    entry:  [
        path.join(__dirname, 'src/app.js')
    ],

    output: {
        path: path.join(__dirname, '/build'),
        filename: 'server.js',
        libraryTarget: 'commonjs2'
    },

    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: [
                    path.join(__dirname, '/node_modules'),
                ],
                use: [
                    {
                        loader: 'babel-loader'
                    }
                ]
            }
        ]
    },

    plugins: [
        new webpack.optimize.AggressiveMergingPlugin()
    ],

    devtool: 'cheap-eval-source-map',

    resolve: {
        extensions: ['.js'],
        modules: ['node_modules']
    }
};
```

* **What is the expected behavior?**

I'm just using `NodeJS` v10+, only using babel for the `import/export` es6 module syntax for node. Spread operator should be handled by node js so I don't want babel to do anything about that.

**Comment by nicolo-ribaudo** [comment]
> Spread operator should be handled by node js so I don't want babel to do anything about that.

Yeah exactly, Babel isn't doing anything. The problem is that you are using an old webpack version which doesn't understand object spread.
You can either update webpack, or transpile object spread.

**Comment by HRK44** [comment]
@nicolo-ribaudo I'm confused as why it was working before with the same webpack version, and stopped working once I updated the babel packages ?

**Comment by nicolo-ribaudo** [comment]
Do you havea `yarn.lock`/`package-lock.json` file?

**Comment by HRK44** [comment]
Yes I'm using npm and I have `package-lock.json`, I have updated webpack to 4.x and it seems to work correctly now.

**Comment by nicolo-ribaudo** [comment]
Which was the previous Babel version? If you had a lockfile updating Babel shouldn't cause anu change in acorn (the parser used by webpack) :thinking:

**Comment by HRK44** [comment]
Sorry for the delayed answer.

This is my `package.json` changelog when it was working to when it was not working :

```
     "devDependencies": {
-        "@babel/cli": "7.2.3",
-        "@babel/core": "7.2.2",
-        "@babel/node": "7.2.2",
-        "@babel/plugin-proposal-class-properties": "7.3.0",
-        "@babel/plugin-transform-runtime": "7.2.0",
-        "@babel/preset-env": "7.3.1",
-        "babel-loader": "8.0.5",
-        "webpack": "3.8.1",
+        "@babel/cli": "7.5.0",
+        "@babel/core": "7.5.0",
+        "@babel/node": "7.5.0",
+        "@babel/plugin-proposal-class-properties": "7.5.0",
+        "@babel/plugin-transform-runtime": "7.5.0",
+        "@babel/preset-env": "7.5.2",
+        "babel-loader": "8.0.6",
         "webpack": "3.8.1",
         "webpack-node-externals": "1.7.2"
     },
     "dependencies": {
-        "@babel/runtime": "7.3.1",
+        "@babel/runtime": "7.5.2",
     }
```

**Comment by HRK44** [comment]
And this is working :

```
    "devDependencies": {
        "@babel/cli": "7.5.0",
        "@babel/core": "7.5.0",
        "@babel/node": "7.5.0",
        "@babel/plugin-proposal-class-properties": "7.5.0",
        "@babel/plugin-transform-runtime": "7.5.0",
        "@babel/preset-env": "7.5.2",
        "babel-loader": "8.0.6",
        "webpack": "4.35.3",
        "webpack-cli": "^3.3.5",
        "webpack-node-externals": "1.7.2"
    },
    "dependencies": {
        "@babel/runtime": "7.5.2",
    }
```

**Comment by JLHwung** [comment]
You can check the `acorn` (Parser used by Webpack) version by
```
npx nls why acorn
```

Make sure it is higher than `5.4.0`, the first version with [object spread support](https://github.com/acornjs/acorn/blob/5.7.3/CHANGELOG.md#540-2018-02-01).

**Comment by vuthpov** [comment]
Hi,
I also get the same error.
this is my package.json 
`  "dependencies": {
    "@testing-library/react": "^9.3.2",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "@types/styled-components": "^5.1.0",
    "@types/yup": "^0.29.2",
    "formik": "^2.1.4",
    "react": "16.11.0",
    "react-dom": "16.11.0",
    "react-scripts": "3.4.1",
    "react-spring": "^9.0.0-rc.3",
    "styled-components": "^5.1.1",
    "typescript": "~3.7.2",
    "yup": "^0.29.1"
  },
  "devDependencies": {
    "@babel/core": "^7.10.2",
    "@babel/plugin-proposal-class-properties": "^7.10.1",
    "@babel/plugin-transform-typescript": "^7.10.1",
    "@babel/preset-env": "^7.10.2",
    "@babel/preset-react": "^7.10.1",
    "babel-loader": "^8.1.0",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11"
  },`
and this is my .babelrc
`{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-typescript"
  ]
}`

**Comment by vuthpov** [comment]
Hi,
I also get the same error.
Here is my package.json
```
   "dependencies": {
    "@testing-library/react": "^9.3.2",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "@types/styled-components": "^5.1.0",
    "@types/yup": "^0.29.2",
    "formik": "^2.1.4",
    "react": "16.11.0",
    "react-dom": "16.11.0",
    "react-scripts": "3.4.1",
    "react-spring": "^9.0.0-rc.3",
    "styled-components": "^5.1.1",
    "typescript": "~3.7.2",
    "yup": "^0.29.1"
  },
  "devDependencies": {
    "@babel/core": "^7.10.2",
    "@babel/plugin-proposal-class-properties": "^7.10.1",
    "@babel/plugin-transform-typescript": "^7.10.1",
    "@babel/preset-env": "^7.10.2",
    "@babel/preset-react": "^7.10.1",
    "babel-loader": "^8.1.0",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11"
  },
```
and this is my .babelrc
```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-typescript"
  ]
}
```
