### ISSUE TITLE
These dependencies were not found:

### ISSUE THREAD

**Issue by chancelee** [babel/babel-loader#799]
These relative modules were not found:

* ../../views/Meeting/meetingList in ./src/router/modules/meeting.js
* ./modules/Schedule in ./src/router/index.js

 WAIT  Compiling...                                                                                                                    10:26:53 AM

 94% asset optimization

 ERROR  Failed to compile with 15 errors                                                                                               10:26:55 AM

These dependencies were not found:

* @/views/Meeting/MeetingRoomList in ./src/router/modules/meeting.js
* @/views/Meeting/applyList in ./src/router/modules/meeting.js
* @/views/Meeting/meetingAdd in ./src/router/modules/meeting.js
* @/views/Meeting/meetingDetail in ./src/router/modules/meeting.js
* @/views/Meeting/meetingEdit in ./src/router/modules/meeting.js
* @/views/Meeting/meetingReply in ./src/router/modules/meeting.js
* @/views/Meeting/meetingSign in ./src/router/modules/meeting.js
* @/views/Meeting/meetingSignReply in ./src/router/modules/meeting.js
* @/views/Meeting/meetingSignView in ./src/router/modules/meeting.js
* @/views/Meeting/viewTable in ./src/router/modules/meeting.js
* @/views/feedBack/feedBackAdd in ./src/router/modules/feedBack.js
* @/views/feedBack/feedBackList in ./src/router/modules/feedBack.js
* AlloyTouch in ./node_modules/_babel-loader@7.1.5@babel-loader/lib?{"plugins":[["babel-plugin-transform-modules",{"cube-ui":{"transform":"cube-ui/src/modules/${member}","kebabCase":true}}]]}!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/packages/simpleScroll/simplescroll.vue

To install them, you can run: npm install --save @/views/Meeting/MeetingRoomList @/views/Meeting/applyList @/views/Meeting/meetingAdd @/views/Meeting/meetingDetail @/views/Meeting/meetingEdit @/views/Meeting/meetingReply @/views/Meeting/meetingSign @/views/Meeting/meetingSignReply @/views/Meeting/meetingSignView @/views/Meeting/viewTable @/views/feedBack/feedBackAdd @/views/feedBack/feedBackList AlloyTouch

-----------------

**Comment by nicolo-ribaudo** [comment]
How is this related to babel-loader?

You probably need to configure webpack to correctly resolve `@` in paths.
