### ISSUE TITLE
ReactDOM.render Unexpected token

### ISSUE THREAD

**Issue by acollazomayer** [babel/babel-loader#802]
Module parse failed: Unexpected token (7:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
> ReactDOM.render(<App />, document.getElementById('app'));

**Webpack Version:**
^4.37.0,

**Babel Core Version**:
^7.5.5

**Babel Loader Version**:
^8.0.6

**Please tell us about your environment:**
OSX 10.3

**Current behavior:**
Module parse failed: Unexpected token (7:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
> ReactDOM.render(<App />, document.getElementById('app'));

**Expected/desired behavior:**
Be able to run app

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
I dont know if it is a bug or a wierd configuration, but you can test this by installing npm install -g react-active-admin

then on a folder run ra init, and then run dev. When you run the dev server you will encounter this issue

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by gunn4r** [comment]
@acollazomayer Just wondering what happened with this? I am having the same issue with a project that WAS working fine. I'm assuming its something simple but just curious what ended up being your fix.  It's like its not having the react preset applied for some reason.
