### ISSUE TITLE
babel-loader@7.1.5" has incorrect peer dependency "babel-core@6".

### ISSUE THREAD

**Issue by HimaChitalia** [babel/babel-loader#811]
**I'm submitting a bug report**

**Webpack Version:**
4.41.0

**Babel Core Version**:
7.6.2

**Babel Loader Version**:
7.1.5

**Please tell us about your environment:**
 Windows 10

**Current behavior:**
Gets the warning while installing
babel-loader@7.1.5" has incorrect peer dependency "babel-core@6".

![image](https://user-images.githubusercontent.com/25187472/66367260-6fe6b180-e961-11e9-9c9a-52d493383d67.png)

**Comment by JLHwung** [comment]
> webpack 4.x | babel-loader 8.x | babel 7.x

Please install babel-loader 8 if you are using babel 7.
