### ISSUE TITLE
Question: modules : false

### ISSUE THREAD

**Issue by Legends** [babel/babel-loader#819]
I want to tell the `babel-loader` to not transform modules: `modules : false`.
Do I have to tell the loader explicitly and if yes, where do I have to put `modules : false`
in respect to the following configuration:

```
 {
        test: /\.m?js$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env']   
          }
        }
      },
```

**Comment by JLHwung** [comment]
> Do I have to tell the loader explicitly

Nope, `modules: false` is defaults when you are using babel-loader, see https://github.com/babel/babel-loader/issues/521

If you want to add other options to preset-env, wrap the name and preset options into an extra brackets:
```js
{
        test: /\.m?js$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: [['@babel/preset-env', { useBuiltIns: "usage" }]]   
          }
        }
      },
```
