### ISSUE TITLE
why npm babel file gets created 

### ISSUE THREAD

**Issue by novaknole** [babel/babel-loader#830]
**Webpack Version:**
4.41.5

**Babel Core Version**:
6.x

**Babel Loader Version**:
8.0.6

**Please tell us about your environment:**
MacOS

**Current behavior:**
I have this:

```
{
                test: /\.js$/,
                exclude: /node_modules/,
                use: { loader: 'babel-loader' }
            },
```

I also use `HtmlWebpackPlugin` in which I use `webpack.chunks` to include built js and css files dynamically.  I also use `splitChunks` plugin like this:

```
splitChunks: {
            chunks: 'all',
            maxInitialRequests: Infinity,
            minSize: 0,
            cacheGroups: {
                vendor: {
                    test: /[\\/]node_modules[\\/]/,
                    name (module) {
                        const packageName = module.context.match(/[\\/]node_modules[\\/](.*?)([\\/]|$)/)[1];
                        return `npm.${packageName.replace('@', '')}`;
                    }
                }
            }
        }
```

What really happens now is when I built for production, there is a new file called `npm.babel.[hash].js and after running the file,  there's `npm.babel.[hash].js` file included as the last one.
I don't understand why this file gets created. I guess that's because of my `splitChunks` configuration. 

**Question:**

 Is that file necessary to be included? is it necessary to be included as the last file? maybe i should add regex not to create a file if it's babel. Something like this. Any idea?

**Expected/desired behavior:**
That file shoudn't be included at all.

**Comment by nicolo-ribaudo** [comment]
Probably it's `@babel/runtime` or `@babel/polyfill`?

**Comment by novaknole** [comment]
This is what I have in `package.json`

```
"@babel/plugin-syntax-dynamic-import": "^7.8.3",
"@babel/plugin-transform-runtime": "^7.8.3",
"babel-loader": "^8.0.6",
```

and this is what I have in `.babelrc`

`
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "modules": false,
                "targets": {
                    "browsers": ["> 1%", "last 2 versions", "not ie <= 8", "ie >= 11"]
                }
            }
        ]
    ],
    "plugins": [
        "@babel/plugin-syntax-dynamic-import",
        [
            "@babel/plugin-transform-runtime",
            {
                "regenerator": true
            }
        ]
    ]
}
`

**Comment by nicolo-ribaudo** [comment]
Add `console.log(module.context)` to the `splitChunks`'s plugin function you have posted in your original example. One of those paths will contain `node_modules/@babel` or `node_modules/babel`: that's the file which is getting included.

**Comment by novaknole** [comment]
So, should I leave it like this? that npm.babel included after the main.js file in the end?  or should I add regex in splitchunksplugin not to include it?

**Comment by nicolo-ribaudo** [comment]
I don't get why you are not sure about it: what are you doing for all the other chunks? You should do the same thing.

**Comment by novaknole** [comment]
all the generated chunks still get changed from ES6 to ES5. So including npm.babel doesn't make the difference at all. That's why I am asking.

**Comment by nicolo-ribaudo** [comment]
I don't think that `npm.babel` contains the transpiler, it probably contains `@babel/runtime` (i.e. runtime helpers, like `regenerator`).
