### ISSUE TITLE
minimist < 1.2.3 showing in npm audit

### ISSUE THREAD

**Issue by createthis** [babel/babel-loader#836]
Installed babel-loader `8.1.0` today, still seeing this from `npm list`:
<img width="381" alt="Screen Shot 2020-03-20 at 1 22 30 PM" src="https://user-images.githubusercontent.com/1695880/77189413-e578b100-6aad-11ea-90dd-adb91333e6f1.png">

Npm vulnerability: https://www.npmjs.com/advisories/1179

**Comment by existentialism** [comment]
@createthis loader-utils has a json5@^1.0.1 dep, you can try removing json5 from your lock file so it can grab the latest.

**Comment by createthis** [comment]
@existentialism I did `rm package-lock.json && npm install && npm list`. It's still the same result.

Looks like updating dep to `loader-utils` `2.0.0` would resolve the situation as it would pull in `json5@2.1.2`. However, that's a breaking change so users can't do it from `package.json`.

**Comment by existentialism** [comment]
@createthis clearing the audit warning definitely doesn't require loader-utils@2,  this repo doesn't have it :)

Instead of killing the whole lockfile, maybe try removing just the `minimist@1.2.0` entry and running `npm i`?

**Comment by nicolo-ribaudo** [comment]
Or try `npm --depth 9999 update minimist`

**Comment by createthis** [comment]
Adding `"minimist": "^1.2.3",` to package.json solves the problem, it's just less than ideal.

**Comment by nicolo-ribaudo** [comment]
It shouldn't be needed. There is a reason if almost everyone uses `^` in their dependencies: it's to automatically get updates :man_shrugging:

**Comment by DomTripodi93** [comment]
if you add the following below browserlist in package.json:

`
  "resolutions": {
    "minimist": "^1.2.3"
  }
`

then delete node_modules and run 
`
npx npm-force-resolutions && npm install
`
it will resolve the issue

**Comment by evilebottnawi** [comment]
@existentialism can be closed, because it is fixed a long time ago, need regenerate lock file
