### ISSUE TITLE
for...of loop produces "Uncaught TypeError: myObject[Symbol.iterator] is not a function" error

### ISSUE THREAD

**Issue by andfaulkner** [babel/babel-loader#84]
The transpiler currently seems to be unable to handle for...of loops. Using them causes Uncaught TypeError: myObject[Symbol.iterator] is not a function

For example, the following code:
```javascript
    var myObject = {
        "key1": "value1",
        "key2": "value2",
        "key3": "value3",
        "fn1": function(){ 
            console.log("fn1 ran!"); 
        },
        "fn2": function(param){
            console.log(param); 
        },
        "number1": 4
    }
	
    for (let item of myObject){
        console.log(item);
    }
```

...which gets converted into:
```javascript
    var myObject = {
        "key1": "value1",
        "key2": "value2",
        "key3": "value3",
        "fn1": function fn1() {
            console.log("fn1 ran!");
        },
        "fn2": function fn2(param) {
            console.log(param);
        },
        "number1": 4
    };

    var _iteratorNormalCompletion = true;
    var _didIteratorError = false;
    var _iteratorError = undefined;

    try {
        for (var _iterator = myObject[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
            var item = _step.value;
            console.log(item);
        }
    } catch (err) {
        _didIteratorError = true;
        _iteratorError = err;
    } finally {
        try {
            if (!_iteratorNormalCompletion && _iterator["return"]) {
                _iterator["return"]();
            }
        } finally {
            if (_didIteratorError) {
                throw _iteratorError;
            }
        }
    }
```

...produces the following error when run:
```
 'Uncaught TypeError: someObj[Symbol.iterator] is not a function'
 utilMainModule  @                               app.js:28208
 (anonymous function)  @                   app.js:28316
 _curFld    @	                                      app.js:28317
 __webpack_require__   @                   app.js:30
 main    @	                                      app.js:523
 navdrawerModule   @	                      app.js:26701
 (anonymous function)   @                  app.js:26873
 moduleNm    @                                    app.js:26875
 __webpack_require__    @                  app.js:30
                   [.............(more items)..........]
(anonymous function) @                     app.js:10
webpackUniversalModuleDefinition @ app.js:9
(anonymous function) @                     app.js:53
```

This occurs in both Chrome and Firefox. I've tried it in several different places in my codebase, with the same result every time.

**Comment by Couto** [comment]
Have you imported the [polyfill](https://babeljs.io/docs/advanced/caveats/)?

**Comment by andfaulkner** [comment]
I'm using the es6-shim node module.

However, I'm not using the Babel-specific module - I'll give that a try.

**Comment by Couto** [comment]
I haven't tried babel with other shims, but to use `for of` you'll have to, at least, shim the `Simbol` and `prototype[Symbol.iterator]`

**Comment by andfaulkner** [comment]
Just installed it. I ensured babel was explicitly installed in my node_modules `npm install babel --save-dev`, then added  `require("babel/polyfill");` to the top of my app's javascript entry point. Same issue.

I'm going to try explicitly including it via a <script> tag.

**Comment by andfaulkner** [comment]
Tried including it in the `<head>` section of my html entry point - it still produced the same error. It's definitely loading it, and it does so prior to everything else (I added a single console log to browser-polyfill.js to confirm this). 

I also tried excluding my other polyfill library, but this also didn't work.

Any other thoughts?

**Comment by zloirock** [comment]
`es6-shim` support `Symbol.iterator` [only with native `Symbol`](https://github.com/paulmillr/es6-shim/blob/master/es6-shim.js#L237) and causes conflicts in you case. Use `babel/polyfill` / `core-js` instead of `es6-shim`.

**Comment by andfaulkner** [comment]
I've already removed es6-shim, and already included babel/polyfill, but I'm still getting the same error.

**Comment by zloirock** [comment]
@andfaulkner stop... I didn't saw your code. Plain objects are not iterable. You can use something like
```js
for (let item of Object.entries(myObject)){
  console.log(item);
}
```
or add custom iterator to your object.

**Comment by andfaulkner** [comment]
Aha! Success! 

Thanks a trillion, I mean it :)

**Comment by Polyergic** [comment]
What?  Plain objects are not iterable?  Why?

**Comment by nabilfreeman** [comment]
@Polyergic https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of

Only arrays etc. can be used with `for ... of`. To iterate over just keys, you need to use `for ... in`.

(I just learnt this)

**Comment by therealwolf42** [comment]
@nabilfreeman When I use for ... in - I get 

TS1005: 'of' expected.

> for await (let c of content){
>    console.log(content)
> }

any idea?

**Comment by danez** [comment]
@therealwolf42 `TS1005` looks verz much like typescript and not babel.

**Comment by loganfsmyth** [comment]
> Only arrays etc. can be used with

The first bit there seems a bit misleading Any iterable object can be used with `for...of`. Arrays just happen to be one type of iterable object.

Generally the way to iterate an object's keys these days would be

```
Object.keys(obj).forEach(key => {
    const value = obj[key];
    // ...
});
```
or if you polyfill `Object.entries` then
```
for (const [key, value] of Object.entries(obj)) {
    // ...
}
```

**Comment by Polyergic** [comment]
The real problem here is that when you try to iterate over a non-iterable object, you get a bad error message.  Different implementations give different error messages, but every one I've seen has been bad.

[`for...of`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) iterates over values (not keys); for an `Array` the keys are whole numbers starting with 0, and are often unimportant, so iterating over the values makes sense.  While it sometimes make sense to iterate over the values that correspond to the (not generally numerical) keys of a plain object, the `for...of` construct does not allow that, so it fails with an (incomprehensible) error message.

[`for...in](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in) iterates over keys (not values); for an `Array` the keys are whole numbers starting with 0, so iterating over the keys rarely makes sense.  But `for..in` does support iterating over the keys of a plain object, which makes it all the more confusing that `for...of` does not.

This is not a bug in any implementation; if it's a bug in anything, it's in the language spec.

The workaround I've taken to using is
```
for( key in var ) {
    value = var[key];
    // ... do stuff with value
}
```

**Comment by fardous80** [comment]
I was having the same problem iterating over FileReader items, finally solved it using Array.from

```
let files = e.target.files || e.dataTransfer.files;

Array.from(files).forEach(file => {
 // do whatever
})

```
