### ISSUE TITLE
Module build failed (from ./node_modules/babel-loader/lib/index.js):

### ISSUE THREAD

**Issue by gabrielsaviank** [babel/babel-loader#847]
Hey, I'm having some error using babel, I tried to lower the versions to 7 no success. 
I tried to add "@babel/preset-env" but is actually present the package.json. 
My index js 
`import React from 'react';
import ReactDOM from 'react-dom';
import App from './App.js';

ReactDOM.render(<App />, document.getElementById('root'));` 

My Webpack.config.js
`const path = require('path');
const webpack = require('webpack');

module.exports = {
    entry: './src/index.js',
    mode: 'development', 
    module: {
        rules: [
            {
                test: /\.(js|js)$/,
                exclude: /(node_modules)/,
                loader: 'babel-loader', 
                options: {presets: ["@babel/env"]}
            },
            {
                test: /\.css$/,
                use: ["style-loader", " css-loader"]
            }
        ]
    },
    resolve: {extensions: ['*', '.js', '.jsx']},
    output: {
        path: path.resolve(__dirname, "dist/"),
        publicPath: '/dist/',
        filename:  'bundle.js'
    },
    devServer: {
        contentBase: path.join(__dirname, 'public/'),
        port: 3000, 
        publicPath: 'http://localhost:3000/dist/',
        hotOnly: true

    }, 
    plugins: [new webpack.HotModuleReplacementPlugin()]
};` 
My package.json 
` "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.9.6",
    "@babel/preset-react": "^7.9.4",
    "babel-loader": "^8.1.0",
    "css-loader": "^3.5.3",
    "style-loader": "^1.2.1",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.11.0"
  },
  "dependencies": {
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  }
}`
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/gabriel/Desktop/React/src/index.js: Unexpected token (5:16) 
I'm getting crazy because I cannot find a solution to this and I tried everything. 
I'm on Linux Ubuntu, Node Version 14.2.0, Npm Version 6.14.4

**Comment by donghainan** [comment]
I have same error with you, how to resolve it?

**Comment by jeroenost** [comment]
Upgrading node.js to >= 13.12.0 fixed it for me

**Comment by JLHwung** [comment]
```diff
{
test: /.(js|js)$/,
exclude: /(node_modules)/,
loader: 'babel-loader',
--- options: {presets: ["@babel/env"]}
+++ options: {presets: ["@babel/env", "@babel/react"]}
},
```

@gabrielsaviank You are using JSX and please install `@babel/preset-react` to enable JSX transforms.
