### ISSUE TITLE
babelrc: false does not work

### ISSUE THREAD

**Issue by budarin** [babel/babel-loader#858]
*Delete what isn't applicable below*
**I'm submitting a bug report**

**Webpack Version:**
4.43

**Babel Core Version**:
7.x

**Babel Loader Version**:
8.1.x

**Please tell us about your environment:**
any

**Current behavior:**
when I use babel loader options in webpack config with `babelrc: false` babel-loader still read babel config from root
It breaks code-splitting chunk name - try to build the [project](https://github.com/budarin/wp-chunk-names-problem-demo.git) - you will see that chunks have numeric file names though it set to `chunkFilename: '[name].js'` in webpack and babel config for loader has no such option .
But root babel config has set `comments: false` and it comes to babel-loader from the root config though babel config has options set to `babelrc: false`
If you remove the option from root babel config and try to build the project again - chunk will have not numerical names.

**Expected/desired behavior:**
babel-loader should not read config from root is babelrc set to false in babel-loader's options

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
Here is the [repo](https://github.com/budarin/wp-chunk-names-problem-demo.git) to reproduce the problem

* **What is the expected behavior?**
Expected babel-loader use set options without reading them from root babel config

* **What is the motivation / use case for changing the behavior?**

**Comment by JLHwung** [comment]
> babelrc: false babel-loader still read babel config from root

https://babel.dev/docs/en/options#configfile

This is expected. `babelrc: false` will prevent babel loading `.babelrc` -- file-relative config -- but _not_ root babel config. If you want to ignore root `babel.config.json`, use
```js
{
  configFile: false
}
```

**Comment by budarin** [comment]
@JLHwung  Thanks!
