### ISSUE TITLE
babel & karma & webpack not working

### ISSUE THREAD

**Issue by yonatanmn** [babel/babel-loader#86]
I'm using babel with webpack, and test with karma and jasmine. In order to use Set() (requires a polyfill), I've added :

loader: 'babel-loader?optional[]=runtime'

to the configuration.

This work's perfectly for the application itself, but the tests are not working, throwing:

TypeError: 'undefined' is not an object (evaluating '_core.Object')

**Comment by frankychung** [comment]
I also use the runtime for our tests. What if you try without the `[]`? The relevant part of my karma config looks like:
```
webpack: {
  module: {
    loaders: [
      {test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader?stage=0&optional=runtime'},
      ...
    ]
  },
  ...
}
```

**Comment by yonatanmn** [comment]
http://stackoverflow.com/questions/31412345/babel-karma-webpack-not-working

**Comment by richburdon** [comment]
Around in circles. The post you link doesn't solve the problem for me. 
There are conflicting suggestions:

1). Add the following to the test file (same error)
    import "babel-polyfill";
2). Add the following to the webpack.config (same error)
    entry: ['babel-polyfill', './webpack.tests.js'], 
3). Add the following to files: [] in the karma.config (this file doesn't exist as of April 2016)
    node_modules/babel-core/browser-polyfill.js',

Any docs or suggestions?

Thanks.
