### ISSUE TITLE
Get ready for webpack@5

### ISSUE THREAD

**Issue by hiroppy** [babel/babel-loader#865]
**Webpack Version:**
v5

* **What is the expected behavior?**

CI has webpack@5 and babel-loader should work with webpack@5.

* **What is the motivation / use case for changing the behavior?**

webpack@5 will be released on the 10th of Oct so we should prepare it. At first, I'll introduce v5 to CI(and maybe migrate to github actions and delete travis and appveyor) and investigate that the current code works or not. If you have already known issues, please tell me.

- [x] CI
  - [x] migrate to github actions
  - [x] add webpack@5 stage
- [ ] make use of InfrastructureLogger
- [x] fix test code

**Comment by fwh1990** [comment]
Congratulations `webpack@5` has been released already.

**Comment by hiroppy** [comment]
yes, now we don't have any problems so I'll close this. thanks.

**Comment by fwh1990** [comment]
Maybe `cacheDirectory` is  unnecessary now due to webpack provide more standard cache

**Comment by fwh1990** [comment]
Maybe `cacheDirectory` is  unnecessary now due to webpack provide more standard cache

**Comment by jahed** [comment]
Relating to `cacheDirectory`, I've created #890.
