### ISSUE TITLE
Module parse failed on optional chaining

### ISSUE THREAD

**Issue by paztis** [babel/babel-loader#871]
## **BEFORE YOU SUBMIT** please read the following:

*Delete what isn't applicable below*
**I'm submitting a bug report**

**Webpack Version:**
4.44.2

**Babel Core Version**:
7.11.6

**Babel Loader Version**:
8.1.0

**Please tell us about your environment:**
OSX 10.15

**Current behavior:**
I just try to remove the @babel/plugin-proposal-optional-chaining plugin from my configuration as it is natively supported (and managed through @babel/preset-env)

Compilation works correctly using pure babel
Compilation is failing with babel-loader
```
ERROR in ./src/pages/design/DesignPage.template.tsx 18:36
Module parse failed: Unexpected token (18:36)
File was processed with these loaders:
 * ../../node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     viewId
|   } = props;
>   const topMessage = props.messages?.[0];
|   const isWarningMessage = topMessage && (topMessage.severity === 'CRITICAL' || topMessage.severity === 'ERROR' || topMessage.severity === 'WARNING');
|   return /*#__PURE__*/React.createElement(Container, {
 @ ./src/pages/design/DesignPage.component.tsx 16:0-55 150:40-58
 @ ./src/application/App.tsx
 @ ./src/index.tsx

```

**Expected/desired behavior:**
As it works natively with browser, it must be supported as non transpiled.
Babel (through @babel/preset-env) and browerslist do their job.
But babel-loader here is blocking

**Comment by paztis** [comment]
ok understand it is a problem of acorn version
Webpack 4.44 still point to 6.x, while optional chaining is only supported in 7.x...
Hope it can be resolved

**Comment by JLHwung** [comment]
This is an upstream webpack issue: https://github.com/webpack/webpack/issues/11186 It is fixed in Webpack 5 however it can not backport to webpack 4 since Acorn 7 introduces new AST for `import()` - webpack relies on the AST to do code splitting.

**Comment by egemon** [comment]
For those who also don't find here the solution - here is good explanation of what is going on 
https://github.com/nuxt/nuxt.js/issues/7722#issuecomment-664745634

**Comment by SarjuHansaliya** [comment]
For those who are using webpack < 5 and nothing is working then try [this](https://github.com/webpack/webpack/issues/10227#issuecomment-706752571) it worked for me
