### ISSUE TITLE
(Requires Babel "^7.0.0-0", but was loaded with "6.26.3)  issue in babel-core with jest  electron

### ISSUE THREAD

**Issue by vrprasanna97** [babel/babel-loader#873]
**I am unable to use npm run dev and npm test together on electron app**

for unit testing, I m using jest  

**In babel rc  plugin "transform-runtime" , works for dev not for jest ,

plugin "@babel/plugin-transform-runtime",works for jest not for dev ,**

I m getting this error:
 **Requires Babel "^7.0.0-0", but was loaded with "6.26.3"**. If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

  "devDependencies": {
....
    "@vue/cli-plugin-unit-jest": "^4.5.7",
    "@vue/test-utils": "^1.0.3",
    "ajv": "^6.5.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.26.0",
    "babili-webpack-plugin": "^0.1.2",
...
]"

  "scripts": {
    "build": "node .electron-vue/build.js && electron-builder",
    "test:unit": "vue-cli-service test:unit",
    "build:clean": "cross-env BUILD_TARGET=clean node .electron-vue/build.js",
    "build:dir": "npm run build:clean && node .electron-vue/build.js && electron-builder --dir",
    "build:player": "cross-env BUILD_TARGET=player node .electron-vue/build.js",

**Comment by JLHwung** [comment]
`"@babel/plugin-transform-runtime"` is for Babel 7, `babel-core` is Babel 6. They are not compatible, please upgrade to Babel 7.
