### ISSUE TITLE
Switch over to Webpack 5's standard cache

### ISSUE THREAD

**Issue by jahed** [babel/babel-loader#890]
**I'm submitting a feature request**

**Webpack Version:**
5.20.2

**Babel Core Version**:
7.12.13

**Babel Loader Version**:
8.2.2

**Please tell us about your environment:**
Linux

**Current behavior:**
babel-loader has its own `cacheDirectory`

**Expected/desired behavior:**
Use Webpack 5's cache implementation.

**What is the motivation / use case for changing the behavior?**

It'd be nice if babel-loader used Webpack 5's cache instead of its own one. I think most popular plugins and loaders have switched over, babel-loader is the only one left in my projects. Though, I'm unsure if Webpack's cache will satisfy babel-loader's requirements.

https://webpack.js.org/configuration/other-options/#cache

**Comment by JLHwung** [comment]
AFAIK the webpack `cache` should be configured in the webpack config. It caches the generated webpack modules. `babel-loader` can not control whether its output will be modified by another loader so we can only cache the `babel-loader` outputs.

I am not sure if there is any we can do on babel-loader side.

**Comment by jahed** [comment]
That makes sense. Looking into it further, loaders can't access `Compilation` so they can't access Webpack's cache (via `getCache`) unlike plugins. So there's not much that can be done.

I'll close this request.
