### ISSUE TITLE
Babel loader printing gibberish on browser web console on error/warning

### ISSUE THREAD

**Issue by neilveil** [babel/babel-loader#893]
**I'm submitting a bug**

**Webpack Version:**
5.24.2

**Babel Core Version**:
7.13.8

**Babel Loader Version**:
8.2.2

**Environment:**
Linux (Linux Mint 20.1 cinnamon)

**Current behavior:**

![web](https://user-images.githubusercontent.com/29909602/109782113-88c6c580-7c2e-11eb-87ad-57da3d4616fc.png)

**Expected/desired behavior:**

![terminal](https://user-images.githubusercontent.com/29909602/109782189-9a0fd200-7c2e-11eb-963e-05ea55c60fce.png)

**What is the expected behavior?**

The same output should be printed on the web console as on the terminal. The colorful part of the error is replaced with some gibberish (Vertical rectangles)

**How I am sure this is because of `babel-loader`?**

You can test & change the code below and try without babel-loader, it works fine. To find the issue I've used a very basic configuration with webpack & babel.

> Not an issue with webpack

> I also have tried with webpack v4 & compatible babel (core, loader) configuration. This issue can also be found in that version too.

**Steps to reproduce**

`package.json`

```json
{
  "name": "webpack-babel-testing",
  "version": "1.0.0",
  "scripts": {
    "start": "webpack serve --port 5000 --mode development",
    "build": "webpack --mode=production"
  },
  "dependencies": {
    "@babel/core": "^7.13.8",
    "@babel/preset-env": "^7.13.9",
    "babel-loader": "^8.2.2",
    "html-webpack-plugin": "^5.2.0",
    "webpack": "^5.24.2",
    "webpack-cli": "^4.5.0",
    "webpack-dev-server": "^3.11.2"
  }
}
```

`webpack.config.js`

```js
module.exports = {
  entry: './index.js',
  output: {
    path: __dirname,
    filename: 'bundle.js',
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
          },
        },
      },
    ],
  },
  devServer: {
    contentBase: __dirname + '/public',
  },
}
```

`index.js`

```js
// Create an error to test on web console & terminal
console.log('Babel with webpack'
```

`public/index.html`

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script src="bundle.js"></script>
  </body>
</html>
```

Project structure:

- index.js
- node_modules/
- package.json
- package-lock.json
- public/
  - index.html
- webpack.config.js

To start the project run

`npm install`
`npm start`

Then open `http://localhost:5000` & check the web console.

**What is the motivation/use case for changing the behavior?**

Errors & warnings should be readable on the web console.

**Comment by korgon** [comment]
This would be awesome to have resolved - as it makes the error quite unclear...

Ex:
![image](https://user-images.githubusercontent.com/5060400/127193333-9f470cea-608d-46fb-825f-eddbf3788e3a.png)

**Comment by JLHwung** [comment]
The gibberish is ASCII escape codes that is supposed to work with a terminal emulator. If you are using browser's console, you can disable it by the [`hightlightCode`](https://babel.dev/docs/en/options#highlightcode) option:

```json
{
  "highlightCode": false
}
```
