### ISSUE TITLE
Trigger webpack re-compilation on Babel config change

### ISSUE THREAD

**Issue by artemirq** [babel/babel-loader#898]
**I'm submitting a feature request**

**Webpack Version:**
5.17.0

**Babel Core Version**:
7.12.3

**Babel Loader Version**:
8.2.2

**Current behavior:**

When user changes babel.config.js/babel.config.json `babel-loader` doesn't trigger re-compilation.

**Expected/desired behavior:**

When user changes babel.config.js/babel.config.json `babel-loader` trigger re-compilation with new actual configuration.

**What is the motivation / use case for changing the behavior?**

It's will be handy to see live changes in watch mode without re-running webpack build.

**Comment by JLHwung** [comment]
I think this issue will be fixed by #887

**Comment by artemirq** [comment]
cc @nicolo-ribaudo. Can we merge this PR?
