### ISSUE TITLE
Syntax error when using .browserslistrc

### ISSUE THREAD

**Issue by codymikol** [babel/babel-loader#902]
**I'm submitting a bug report**

**Webpack Version:**
5.31.0

**Babel Core Version**:
^7.10.2

**Babel Loader Version**:
^8.0.0

**Please tell us about your environment:**
OSX 10.x / Linux / Windows 10

**Current behavior:**
Webpack builds are being transformed in such a way that causes the path within a sourcemap comment to be taken out of the comment block, throwing a syntax error.

There is a whole bunch of information over here: https://github.com/ryanclark/karma-webpack/issues/507

For some reason babel is outputting this when the .browserslistrc file contains certain targets.

```
/***/ "./node_modules/@babel/runtime-corejs2/core-js/date/now.js":
/*!*****************************************************************!*\
  !*** ./node_modules/@babel/runtime-corejs2/core-js/date/now.js ***!
  \*****************************************************************/
```

**Expected/desired behavior:**

I belive that the comment should just be output as

```
/*!*****************************************************************!*\
  !*** ./node_modules/@babel/runtime-corejs2/core-js/date/now.js ***!
  \*****************************************************************/
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

The github repository in the linked issue provides a working example of this failing, if you run the test suite, babel will run and it will fail. If you delete .browserslist.rc it will then pass.

* **What is the expected behavior?**

The tests should pass when a .browserslistrc file is included

* **What is the motivation / use case for changing the behavior?**

Sorry if this isn't a super stripped down reproduction, I don't see this documented anywhere else so I at least wanted to bring attention to the issue. Thanks for all that you do on this project 🙂.

**Comment by nicolo-ribaudo** [comment]
That code is generated by webpack when bundling, not by Babel.

**Comment by peaceful-james** [comment]
> The github repository in the linked issue provides a working example of this failing, if you run the test suite, babel will run and it will fail. If you delete .browserslist.rc it will then pass.

@codymikol The github repo (https://github.com/appzuka/karma-webpackv5-test) in the linked issue (https://github.com/ryanclark/karma-webpack/issues/507) does not have a `.browserslistrc` or `.browserslist.rc` file.
