### ISSUE TITLE
Uncaught TypeError: Cannot read property '__core-js_shared__' of undefined

### ISSUE THREAD

**Issue by miherlosev** [babel/babel-loader#91]
The sample that contains all required files - http://www.screencast.com/t/PTGHgCImI4
## index.js contains the following code:

var obj = {
    property: 1
};
## I has transformed index.js using gulp:

var gulp    = require('gulp');
var webpack = require('gulp-webpack');

gulp.task('webpack', function() {
    gulp.src('./index.js')
        .pipe(webpack({
            output: { filename: 'index.js' },
            module: {
                loaders: [ { loader: 'babel-loader' } ]
            }
        }))
        .pipe(gulp.dest('processed'));
## });

I have included the processed file to the simple html page.
After opening the page I got the error  'Uncaught TypeError: Cannot read property '**core-js_shared**' of undefined.'

**Comment by lsdafjklsd** [comment]
Had the same issue. Solved it by adding https://github.com/pjeby/regenerator-loader and http://facebook.github.io/regenerator/ to my dev-deps, and then adding the `'regenerator'` loader along side babel-loader.

**Comment by halt-hammerzeit** [comment]
I have the same issue and this is something messed up with my webpack project.
Still didn't figure out what's the issue.
I also get "ReactHotAPI is not a function" when using react-hot-loader.

**Comment by halt-hammerzeit** [comment]
So, I resolved the issue.
The issue was that I didn't have `exclude: /node_modules/,` in my javascript loader in webpack configuration.

Now it works
```
			{ 
				test: regular_expressions.javascript,
				exclude: /node_modules/,
				loaders: [babel]
			},
```

**Comment by hzoo** [comment]
Looks like this has been resolved.

Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
