### ISSUE TITLE
how can i set supportsStaticESM in babel-loaders option

### ISSUE THREAD

**Issue by ganshiqingyuan** [babel/babel-loader#913]
## **BEFORE YOU SUBMIT** please read the following:

**Webpack Version:**
5.x

**Babel Core Version**:
7.x

**Babel Loader Version**:
8.x

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
when i set supportsStaticESM in babel-loaders options i get  ".caller is only allowed in root programmatic options"

**Expected/desired behavior:**

i want dynamicImport  keep ```import()``` but ```import xx from 'xx'``` become ```var xx = require()```,,so i want to set supportsStaticESM false and ```modules: auto``` to do this

* **What is the expected behavior?**
i can set this in babel-loader options

**Comment by nicolo-ribaudo** [comment]
When using `babel-loader`, Babel doesn't compile neither `imoprt xx from "xx"` nor `import()`.

Then, webpack compiles `import xx from "xx"` and `import()` to `require()` (or to `__webpack__require__()`).

If you _don't want_ to compile `import()`, I _think_ (but it's a webpack feature, so if it doesn't work I suggest asking there) that you can annotate them like this:
```js
import(/*webpackIgnore: true*/ 'path/to/module.js');
```

**Comment by ganshiqingyuan** [comment]
> When using `babel-loader`, Babel doesn't compile neither `imoprt xx from "xx"` nor `import()`.
> 
> Then, webpack compiles `import xx from "xx"` and `import()` to `require()` (or to `__webpack__require__()`).
> 
> If you _don't want_ to compile `import()`, I _think_ (but it's a webpack feature, so if it doesn't work I suggest asking there) that you can annotate them like this:
> 
> ```js
> import(/*webpackIgnore: true*/ 'path/to/module.js');
> ```
> 
> https://webpack.js.org/api/module-methods/#magic-comments

my origin code is commonjs code,,but babel polify use ```import xx from 'xx'``` to add the usage polify,, i want babel use ```require```,, so i set ```module: commonjs```,, but this make ```import()``` be compiled too.. then it cause webpack cant't judge the platform to generate ```DynamicImport``` code by ```target: node/web ``` option。。。
so i want to set ```supportsStaticESM: false``` to make babel polify ```import``` become ```require ```and ```import()``` keep unchanged to make webpack  can judge platform by ```target ```option

**Comment by nicolo-ribaudo** [comment]
Ok, so the problem is that Babel _thinks_ that your files are ESM (and not CommonJS), so it injects `import` instead of `require`. Try passing `sourceType: "script"` or `sourceType: "unambiguous"` as a Babel option.

**Comment by ganshiqingyuan** [comment]
> Ok, so the problem is that Babel _thinks_ that your files are ESM (and not CommonJS), so it injects `import` instead of `require`. Try passing `sourceType: "script"` or `sourceType: "unambiguous"` as a Babel option.

much thanks your help! it solves my problem ><
