### ISSUE TITLE
Webpack build failing with ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by Reptarsrage** [babel/babel-loader#917]
**I'm submitting a bug report**

**Node Version:**
17.0.0

**Webpack Version:**
5.58.2

**Babel Core Version**:
7.15.8

**Babel Loader Version**:
8.2.2

**Please tell us about your environment:**
Windows 11

**Current behavior:**
Webpack build fails:

```ps
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at filename (node_modules\babel-loader\lib\cache.js:94:23)
    at node_modules\babel-loader\lib\cache.js:120:39
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (node_modules\babel-loader\lib\cache.js:3:103)   
    at _next (node_modules\babel-loader\lib\cache.js:5:194)
    at node_modules\babel-loader\lib\cache.js:5:364
    at new Promise (<anonymous>)
    at node_modules\babel-loader\lib\cache.js:5:97
```

**Expected/desired behavior:**
Webpack build should succeed with no errors

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
This happens after upgrading to latest node version 17.0.0.

* **What is the expected behavior?**
WEbpack build should complete without errors.

* **What is the motivation / use case for changing the behavior?**
The code should work on the latest node version.

**Comment by JLHwung** [comment]
Fixed in #918
