### ISSUE TITLE
Enable es6 polyfills

### ISSUE THREAD

**Issue by voronianski** [babel/babel-loader#92]
I have such webpack config for babel-loader:

```javascript
// ...
module: {
    loaders: [{
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loaders: ['react-hot', 'babel?stage=0&optional=runtime&externalHelpers']
    }
}
```

However running such code `let copy = someArray.copyWithin(0);` returns `Uncaught TypeError: someArray.copyWithin is not a function`, any ideas (it works in [repl](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=true&code=var%20arr%20%3D%20%5B1%2C2%2C3%5D%3B%0Avar%20arr2%20%3D%20arr.copyWithin(0)%3B%0A%0Aarr%20%3D%20%5B0%5D%3B%0A%0Aconsole.log(arr2%2C%20arr)%3B&playground=false))?

Some other methods like `Object.assign` work fine..

**Comment by zloirock** [comment]
Methods of instances not polyfilled with `runtime` transformer.

**Comment by voronianski** [comment]
@zloirock how I could enable them?

**Comment by zloirock** [comment]
Disable `runtime` transformer and use `babel/polyfill` / default version `core-js`.

**Comment by voronianski** [comment]
@zloirock thanks

**Comment by voronianski** [comment]
@zloirock I have another issue now:

webpack config:

```javascript
// ...
module: {
    loaders: [{
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loaders: ['react-hot', 'babel?stage=0&externalHelpers']
    }
}
```

and inside my app.js:

```javascript
// polyfills
import 'babel/polyfill';
```

but got error in console `Uncaught ReferenceError: babelHelpers is not defined`.

**Comment by zloirock** [comment]
Also [include `babel-core/external-helpers`](https://babeljs.io/docs/advanced/external-helpers/#injecting-the-external-helpers).

**Comment by voronianski** [comment]
@zloirock I thought 'babel?stage=0&externalHelpers']'` includes it

**Comment by nlutterman** [comment]
@voronianski I just had this problem and solved it by installing the `babel` package on top of of `babel-core`.  I'm not sure if that's the right, solution though.

I was reading through [an issue on Babel itself](https://github.com/babel/babel/issues/1097#issuecomment-86984995) and it's mentioned:

> ...it's literally the same package with a different package.json...

So it feels weird requiring the both of them... but it works.

@zloirock Can you provide a little more information about how to include the external-helpers?

**Comment by nlutterman** [comment]
Oh, good lord... change

    import 'babel/polyfill';

to

    import 'babel-core/polyfill';

That'll do it.

**Comment by xushao0305** [comment]
@nlutterman yes! I only use babel-load on webpack.config.js and 
import 'babel/polyfill';
or 
 import 'babel-core/polyfill';
It works fine.

So this it babel issue or webpack issue?

**Comment by simon-nguyen** [comment]
@xushao0305 @nlutterman 
I also use `babel-load` and config it inside `webpack.config.js`
All I need to do to put a single import statement inside my `app.module.es6`

```
import 'babel-core/polyfill';
...
angular.module(...);
```
And my app is now generating ES6 Symbol properly. No more `Symbol is undefined` error in IE 11 or Safari.

**Comment by PinkyJie** [comment]
@simon-nguyen Is there a way that make `bable-core/polyfill` a separate entry point, and use conditional comment in index.html to only include this entry point for IE browser?
I tried this in `webpack.config.js`:
```
entry: {
    app: [
        entryJs
    ],
    'ie-polyfill': 'babel-core/polyfill.js'
}
```
and put conditional comments in `index.jade`:
```
// babel polyfill for IE
<!--[if IE]>
<script src="ie-polyfill.{%=o.webpack.hash%}.js"></script>
<![endif]-->
```

But it's not working, I don't want to put this polyfill in for all browsers, I only want to include this for IE.

**Comment by danderu** [comment]
@PinkyJie did you find a solution for your issue? I'm running on the same problem here :\

**Comment by PinkyJie** [comment]
@danderu I have no solution, because conditional comments is not support from IE 10, we must include this shim file for all browsers.

**Comment by danderu** [comment]
@PinkyJie ok! thanks :)

**Comment by d3viant0ne** [comment]
Resolving this as a resolution to the initial question exists in the issue

**Comment by aesinv** [comment]
Just a heads up to those finding this from Google that haven't looked at the site lately (like me), the polyfill is no longer available in `babel-core/polyfill` unless I just really screwed up big time somewhere somehow, but it's now a separate module altogether.

```
npm install --save-dev babel-polyfill
```
Then you can set it as an entry in your webpack config:
```
...
entry: [
  'babel-polyfill',
  './app/index'
],
...
```
or import it:
```
import 'babel-polyfill';
```

Docs: https://babeljs.io/docs/usage/polyfill/
