### ISSUE TITLE
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

### ISSUE THREAD

**Issue by NickOzb** [babel/babel-loader#920]
I have no idea what is wrong

webpack.config.js

```js
const path = require("path");
const webpack = require("webpack");

module.exports = {
  entry: "./src/index.js",
  output: {
    path: path.resolve(__dirname, "./static/frontend"),
    filename: "[name].js",
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: "/node_modules/",
        use: {
            loader: "babel-loader",
        },
      },
    ],
  },
  optimization: {
    minimize: true,
  },
  plugins: [
    new webpack.DefinePlugin({
      "process.env": {
        // This has effect on the react lib size
        NODE_ENV: JSON.stringify("production"),
      },
    }),
  ],
};
```
app.js
```js
import React, { Component } from "react";
import { render } from "react-dom";

export default class App extends Component {
    constructor(props) {
        super(props);

    }

    render() {
        return (<h1>Testing React Code</h1>);
    }
}

const appDiv = document.getElementById("app");
render(<App />, appDiv);
```
Error
```
> frontend@1.0.0 dev C:\Users\Administrator\PycharmProjects\pythonProject2\webProject\frontend
> webpack --mode development --watch

asset main.js 4.71 KiB [compared for emit] (name: main)
runtime modules 937 bytes 4 modules
cacheable modules 370 bytes
  ./src/index.js 37 bytes [built] [code generated]
  ./src/components/App.js 333 bytes [built] [code generated] [1 error]

ERROR in ./src/components/App.js 11:15
Module parse failed: Unexpected token (11:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|     render() {
>         return <h1>Testing React Code</h1>;
|     }
| }
 @ ./src/index.js 1:0-35

webpack 5.64.0 compiled with 1 error in 201 ms
```

**Comment by JLHwung** [comment]
Can you also attach the Babel config?

**Comment by NickOzb** [comment]
> Can you also attach the Babel config?

{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "10"
        }
      }
    ],
    "@babel/preset-react"
  ],
  "plugins": ["@babel/plugin-proposal-class-properties"]
}

**Comment by JLHwung** [comment]
What is the [effective Babel config](https://babeljs.io/docs/en/configuration#print-effective-configs)?

```
BABEL_SHOW_CONFIG_FOR=C:\Users\Administrator\PycharmProjects\pythonProject2\webProject\frontend\src\components\App.js webpack --mode development --watch
```

**Comment by NickOzb** [comment]
> What is the [effective Babel config](https://babeljs.io/docs/en/configuration#print-effective-configs)?
> 
> ```
> BABEL_SHOW_CONFIG_FOR=C:\Users\Administrator\PycharmProjects\pythonProject2\webProject\frontend\src\components\App.js webpack --mode development --watch
> ```

im sorry, i didnt understand the question

**Comment by NickOzb** [comment]
Its in packege,json

{
  "name": "frontend",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "webpack --mode development --watch",
    "build": "webpack --mode production"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.16.0",
    "@babel/preset-env": "^7.16.0",
    "@babel/preset-react": "^7.16.0",
    "babel-loader": "^8.2.3",
    "css-loader": "^6.5.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "style-loader": "^3.3.1",
    "webpack": "^5.64.0",
    "webpack-cli": "^4.9.1",
    "webpack-dev-server": "^4.5.0"
  },
  "dependencies": {
    "@babel/plugin-proposal-class-properties": "^7.16.0",
    "@material-ui/core": "^4.12.3",
    "@material-ui/icons": "^4.11.2",
    "react-router-dom": "^6.0.2"
  }
}

**Comment by NickOzb** [comment]
no solution?

**Comment by JLHwung** [comment]
I don't see a Babel config in `package.json`, can you print the effective config? You can run

```
BABEL_SHOW_CONFIG_FOR=C:\Users\Administrator\PycharmProjects\pythonProject2\webProject\frontend\src\components\App.js webpack --mode development --watch
```

and attach the output.

**Comment by NickOzb** [comment]
I run it and i have this
![image](https://user-images.githubusercontent.com/94305486/141710366-037c68ca-1c89-47d8-9b37-f33327434de3.png)

**Comment by JLHwung** [comment]
When `BABEL_SHOW_CONFIG_FOR` is provided, your terminal should print babel config applied to the file. What is the Babel config?

If you can't see the config, can you provide a reproduction repo?

**Comment by NickOzb** [comment]
i didnt understand eng terms. Can you pls tell me what i need to do?

**Comment by JLHwung** [comment]
Can you share a GitHub repository that can reproduce the errors?

**Comment by NickOzb** [comment]
https://github.com/NickOzb/webProjectBabel.git

**Comment by JLHwung** [comment]
https://github.com/NickOzb/webProjectBabel/blob/main/webProject/frontend/webpack.cofig.js should be renamed to `webpack.config.js`, instead it gets `webpack.cofig.js`, so webpack is running without any config.

**Comment by NickOzb** [comment]
omg such a silly mistake, thanks a lot

**Comment by lexycole** [comment]
**My solution:**
- change app.js to app.jsx
- test: /.(js|jsx)$/
- "@babel/plugin-proposal-class-properties"
