### ISSUE TITLE
Numeric Separators not supported if used with React

### ISSUE THREAD

**Issue by clickwithclark** [babel/babel-loader#922]
**I'm submitting a bug report**

**Webpack Version:**
    4.44.2

**Babel Core Version**:
"7.16.0",

**Babel Loader Version**:
5.4.x/6.2.x

**Please tell us about your environment:**
 Windows 10

**Current behaviour:**
Numeric Separators not working with React
It detects underscores as an identifier

**Expected/desired behaviour:**
     10_000 should be seen as 10000
      instead is seen as 10 and _000

Uncertain of how to get the configuration, 
Building a module works fine on its own with webpack.
but using the module in a React Application throws a failed to compile error

for example :  One of the functions in my module is written as :
```js
export function waitForElement(
  selector,
  checkFrequencyInMs = 500,
  timeoutInMs = 10_000
......
) {
```

When I try to use it in a React App :
![image](https://user-images.githubusercontent.com/20617584/142699729-2fbd16d4-f6e3-44df-8556-1d6718ed10b0.png)

Sorry if the information is not sufficient. If it needs to be placed somewhere else instead please let me know.

Everything works when I removed the underscore.

**Comment by JLHwung** [comment]
The error is thrown from acorn because webpack 4 does not support ES2021. You can upgrade to webpack 5.
