### ISSUE TITLE
Webpack build fails with node 16 and openssl 3 provided by os

### ISSUE THREAD

**Issue by pathmapper** [babel/babel-loader#923]
**I'm submitting a bug report**

ref https://github.com/babel/babel-loader/issues/917, https://github.com/babel/babel-loader/pull/918

**Webpack Version:**
5.65.0

**Babel Core Version**:
7.0.0-bridge.0

**Babel Loader Version**:
8.2.3

**Please tell us about your environment:**
Fedora Rawhide (comes with OpenSSL 3) with node 16 (LTS)

**Current behavior:**
https://github.com/pathmapper/test-landingpage/runs/4675042075?check_suite_focus=true

Build fails with: 
```
ERROR  Failed to compile with 1 error7:33:27 PM
  
  error  in ./src/main.js
  
  Syntax Error: Thread Loader (Worker 0)
  error:0308010C:digital envelope routines::unsupported
      at Generator.next (<anonymous>)
      at new Promise (<anonymous>)
```

because `md4` hashing is used which is deprecated by OpenSSL3.

https://github.com/babel/babel-loader/blob/052c07a0168a24e2bb15fd8890c9e485c5a3fe97/src/cache.js#L66-L70

**Expected/desired behavior:**
Build runs without errors.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
- use Fedora rawhide with node 16 (LTS)
- checkout https://github.com/pathmapper/test-landingpage
- run `yarn install`
- run `yarn build`

* **What is the motivation / use case for changing the behavior?**
Use `babel-loader `with node 16 LTS on operating system with OpenSSL 3.

**Comment by nicolo-ribaudo** [comment]
We can check `process.versions.openssl` other than `process.versions.node` in the code you linked; would you like to open a PR?

**Comment by pathmapper** [comment]
https://github.com/babel/babel-loader/pull/924 is merged
