### ISSUE TITLE
nvm needs to ask for UAC rights

### ISSUE THREAD

**Issue by Pomax** [babel/babel-loader#930]
I installed the latest release (as of today) into D:\nvm because the installer still super-annoyingly tries to install to the UAC admin account's roaming dir, instead of the actual user who ran the installer. However, if I run `nvm use 16.12.0` as regular user I get the follow errors:
```
exit status 5: Access is denied.

exit status 5: Access is denied.
```
which makes sense: a good user account has zero admin rightrs, and this shoudl trigger a windows UAC prompt to allow the program to run with admin rights to make the changes it needs to in the admin-protected `program files` folder.

**Comment by JLHwung** [comment]
🤔 How is this issue related to `babel-loader`?

**Comment by Pomax** [comment]
haha, this is an _excellent_ question, I have no idea why this ended up in the babel-loader repo instead of the nvm-win repo.
