### ISSUE TITLE
Improve performance idea

### ISSUE THREAD

**Issue by rluvaton** [babel/babel-loader#935]
currently we pass the source code between functions, because the source code is string this means that the source code _allocated_ multiple times (primitive so it passed by value and not by reference)

if we pass an array that only contains that value it will reduce the allocated memory by a lot!

https://github.com/babel/babel-loader/blob/052c07a0168a24e2bb15fd8890c9e485c5a3fe97/src/index.js#L48

**Context:**
I found this after failing to building react app because heap out of memory error and used [clinic heap profiler](https://clinicjs.org/heapprofiler/) to diagnose the issue

WDYT?

**Comment by nicolo-ribaudo** [comment]
Strings are passed by reference in all JS engines.

**Comment by rluvaton** [comment]
Oh thanks! Good to know, Just trying to figure out a way to optimize it 😀
