### ISSUE TITLE
yarn always complain babel-loader@8.2.5" has unmet peer dependency "@babel/core@^7.0.0"

### ISSUE THREAD

**Issue by HillLiu** [babel/babel-loader#940]
**Current behavior:**
```bash
warning "reshow-app > babel-loader@8.2.5" has unmet peer dependency "@babel/core@^7.0.0".
```

inside my yarn.lock

```json
"@babel/core@^7.11.1", "@babel/core@^7.7.5", "@babel/core@^7.7.7", "@babel/core@^7.x":
  version "7.17.9"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.17.9.tgz#6bae81a06d95f4d0dec5bb9d74bbc1f58babdcfe"
  integrity sha512-5ug+SfZCpDAkVp9SFIZAzlW18rlzsOcJGaetCjkySnrXXDUw9AR8cDUm1iByTmdWM6yxX6/zycaV76w3YTF2gw==
  dependencies:
    "@ampproject/remapping" "^2.1.0"
    "@babel/code-frame" "^7.16.7"
    "@babel/generator" "^7.17.9"
    "@babel/helper-compilation-targets" "^7.17.7"
    "@babel/helper-module-transforms" "^7.17.7"
    "@babel/helpers" "^7.17.9"
    "@babel/parser" "^7.17.9"
    "@babel/template" "^7.16.7"
    "@babel/traverse" "^7.17.9"
    "@babel/types" "^7.17.0"
    convert-source-map "^1.7.0"
    debug "^4.1.0"
    gensync "^1.0.0-beta.2"
    json5 "^2.2.1"
    semver "^6.3.0"
```

* **What is the expected behavior?**
try dismiss this warning.

* **What is the motivation / use case for changing the behavior?**
Maybe try change peer dependency "@babel/core@^7.0.0" to "@babel/core@^7.x"

**Comment by JLHwung** [comment]
`7.17.9` is included in `@babel/core@^7.0.0`. Do you have `@babel/core` in `package.json`? Does https://www.npmjs.com/package/yarn-deduplicate fixes the problem?

**Comment by HillLiu** [comment]
yup, you could check my yarn.lock section. 

"@babel/core@^7.11.1", "@babel/core@^7.7.5", "@babel/core@^7.7.7", "@babel/core@^7.x":

**Comment by HillLiu** [comment]
I'll close and check this first.

**Comment by HillLiu** [comment]
Check this only happen on my monorepository, no issue for main folder. so it's safe to close.
