### ISSUE TITLE
BUG: webpack5 with @babel/preset-env modules false options does not preserve ES modules.

### ISSUE THREAD

**Issue by whatwg6** [babel/babel-loader#952]
**I'm submitting a bug report**

**Webpack Version:**
 5.74.0

**Babel Core Version**:
7.18.13

**Babel Loader Version**:
8.2.5

**Please tell us about your environment:**
Apple M1 Pro

**Current behavior:**
does not preserve ES modules

**Expected/desired behavior:**
preserve ES module

reproduce: https://stackblitz.com/edit/github-iutjua-twzc7n?file=README.md

* **What is the expected behavior?**

after npm run build, dist/main.js preserve ES module

**Comment by JLHwung** [comment]
In the webpack config,
```js
module.exports = {
...
  output: {
    filename: 'main.js',
    library: {
      type: 'umd',
    },
    path: path.resolve(__dirname, 'dist'),
  },
...
};
```
`library: { type: 'umd' }` instructs webpack to output UMD-style libraries. If you want to use ES modules, you need to specify `module` as the library type and enable the experimental flag:
```js
module.exports = {
...
  output: {
    filename: 'main.js',
    library: {
      type: 'module',
    },
    path: path.resolve(__dirname, 'dist'),
  },
  experiments: {
    outputModule: true,
  },
...
};
```

Closing this issue since this is more related to webpack than Babel.
