### ISSUE TITLE
Error: Cannot find module 'node:fs/promises'

### ISSUE THREAD

**Issue by mendoncanorma** [babel/babel-loader#969]
## **BEFORE YOU SUBMIT** please read the following:

*Delete what isn't applicable below*
**I'm submitting a bug report**

**Webpack Version:**
5.74.0

**Babel Core Version**:
7.19.6

**Babel Loader Version**:
9.0.0

**Please tell us about your environment:**
Windows 11

**Current behavior:**
Receiving the following error with babel-loader 9.0.0

```
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'node:fs/promises
```

No issues observed with babel-loader 8.2.5

**Expected/desired behavior:**

There should not be any build error.

**Comment by JLHwung** [comment]
The `require("node:...")` is supported only in Node.js 14.18+, as a workaround, please upgrade Node to 14.18+. We will release a patch soon.

**Comment by mendoncanorma** [comment]
Thank you! Works now.
~Norma
