### ISSUE TITLE
babel-loader@9.1.0 - C-style commenting in JavaScript function calls is causing compilation errors. babel-loader is treating /* comments */ as unexpected tokens when they appear after => arrow functions operators.

### ISSUE THREAD

**Issue by knuula** [babel/babel-loader#972]
**I'm submitting a bug report**

**Webpack Version:**
5.64.4

**Babel Core Version**:
7.16.0

**Babel Loader Version**:
9.1.0

**Please tell us about your environment:**
Windows 10

**Current behavior:**
during the compiling process, babel-loader is treating /* */ (C-style comment syntax) as unexpected tokens - causing a compiler failure.

![image](https://user-images.githubusercontent.com/48263034/200201380-1c69ae71-2eb5-4f63-8912-890d881b2982.png)

![image](https://user-images.githubusercontent.com/48263034/200201358-e9f89174-eca3-47b2-a2a7-62097cea1f61.png)

**Expected/desired behavior:**
* babel-loader should treat this type of commenting as normal commenting during the compiling process.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
* 
![image](https://user-images.githubusercontent.com/48263034/200201380-1c69ae71-2eb5-4f63-8912-890d881b2982.png)

![image](https://user-images.githubusercontent.com/48263034/200201358-e9f89174-eca3-47b2-a2a7-62097cea1f61.png)

* **What is the expected behavior?**
* babel-loader should treat this type of commenting as normal commenting during the compiling process.

* **What is the motivation / use case for changing the behavior?**
* it is causing compiler failures.

**Comment by jawn-ha** [comment]
same proble

**Comment by eladonline** [comment]
you can see this explained here [https://github.com/diegomura/react-pdf/issues/2072](url)

**Comment by willphamsg** [comment]
same problem

**Comment by nicolo-ribaudo** [comment]
We will release a fix for this today. As a workaround, you can pin your @babel/core version to 7.19

**Comment by hungdev** [comment]
but i dont use @babel/generator in my project @nicolo-ribaudo

**Comment by eladonline** [comment]
> We will release a fix for this today. As a workaround, you can pin your @babel/generator version to 7.19

this is not helping

**Comment by eladonline** [comment]
> We will release a fix for this today. As a workaround, you can pin your @babel/generator version to 7.19

not helping
