### ISSUE TITLE
After upgrade my nodejs version 16.8.0 to 16.9.0, I am getting this error "You may need an additional loader to handle the result of these loaders"

### ISSUE THREAD

**Issue by ugurberkecan** [babel/babel-loader#988]
My project was working before until I upgrade my nodejs 16.8.0 to 16.9.0.

Im getting 'You may need an additional loader to handle the result of these loaders' error in couple fields of my code. Do you know why ? 

**Webpack Version:**
4.43.0

**Babel Core Version**:
7.11.6

**Babel Loader Version**:
5.3.0

**Please tell us about your environment:**
OSX 10.x

**Comment by JLHwung** [comment]
> Babel Loader Version:
> 5.3.0

The last version of babel-loader 5 was published 7 years ago. It is no longer supported, please upgrade to the latest babel-loader.
