### ISSUE TITLE
Bug Error Run npm ci npm ERR! Cannot read property '@babel/cli' of undefined  npm ERR! 

### ISSUE THREAD

**Issue by JawadZein** [babel/babel-loader#989]
## **BEFORE YOU SUBMIT** please read the following:

*Delete what isn't applicable below*
**I'm submitting a bug report**
**I'm submitting a feature request**
**I'm submitting a support request** => Please do not submit support request here, see note at the top of this template.

**Webpack Version:**
1.10.x/2.x

**Babel Core Version**:
6.x

**Babel Loader Version**:
5.4.x/6.2.x

**Please tell us about your environment:**
OSX 10.x / Linux / Windows 10

 System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 19.8.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.4 - C:\scratch\your-own-project\node_modules\.bin\npm.CMD
  npmPackages:
    @babel/cli: ^7.21.0 => 7.21.0
    @babel/core: ^7.21.4 => 7.21.4
    @babel/traverse: ^7.21.4 => 7.21.4
    babel-loader: ^9.1.2 => 9.1.2

**Current behavior:**
unable to run the workflows given this error
npm ERR! Cannot read property '@babel/cli' of undefined

**Expected/desired behavior:**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by JLHwung** [comment]
It seems that you are using Babel 7 with babel-loader 2.0, which is now longer supported. babel-loader 2.0 only works with Babel 6. Please consider upgrade your webpack config or install `babel-core@6`.
