### ISSUE TITLE
semver vulnerable to Regular Expression Denial of Service 

### ISSUE THREAD

**Issue by carma12** [babel/babel-loader#992]
**I'm submitting a feature request**

**Webpack Version:**
"^5.76.2"

**Babel Core Version**:
"^7.18.9"

**Babel Loader Version**:
"^8.2.5"

**Please tell us about your environment:**
Linux (Fedora 37)

**Current behavior:**
I'm working on a React project that uses Webpack and babel-loader ("^8.2.5") as a dependency. Recently, I got an audit dependency error coming from the semver package when executing `npx audit-ci --config audit-ci.json`.

Apparently, versions of the package semver before 7.5.2 are vulnerable to Regular Expression Denial of Service (ReDoS) via the function new Range, when untrusted user data is provided as a range. More information here: https://github.com/advisories/GHSA-c2qf-rxjj-qqgw

As far as I know, babel-loader is using semver as a dependency (https://www.npmjs.com/package/babel-loader?activeTab=dependencies), more specifically version "7.3.2" (https://www.npmjs.com/package/babel-loader?activeTab=code). 

**Desired behavior:**
* Not getting the audit dependency error

**What is the motivation / use case for changing the behavior?**
* Solve the audit dependency error

**Comment by nicolo-ribaudo** [comment]
Hi! `babel-loader` never passes untrusted user data to `semver`, and as such that warning can safely be ignored.

**Comment by carma12** [comment]
Thanks for the quick answer. So in this case I understand it is safe to allowlisting this library from my audit tool, am I right?
